// Package cloudformation_codebuild_template contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package cloudformation_codebuild_template

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// DockerImage - Docker image to use for the build phase
var DockerImage = Param("DockerImage")
