// Package reportingv2 contains CloudFormation resources.
// Main resources
//
// Generated by wetwire-aws import.
package reportingv2

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/serverless"
)

var ReportingAPIV2 = serverless.HttpApi{
	Description: "Reporting API V2",
	DisableExecuteApiEndpoint: true,
}

var GlobalReportingV2 = serverless.Function{
	CodeUri: "src/global-reportingv2",
	Events: Json{
	"GlobalReportingV2": Json{
	"Properties": Json{
	"ApiId": ReportingAPIV2,
	"Method": "GET",
	"Path": "/global",
},
	"Type": "HttpApi",
},
},
}
