// Package template contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package template

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// AggregateAccount - Aggregate account ID
var AggregateAccount = Param("AggregateAccount")

// MainRegion - Main region for the account
var MainRegion = Param("MainRegion")

// SubAccountList - List of sub accounts to be monitored
var SubAccountList = Param("SubAccountList")

var IsAggregateAccountCondition = Equals{AggregateAccount, AWS_ACCOUNT_ID}

var IsMainRegionCondition = Equals{MainRegion, AWS_REGION}
