// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package iotanalytics

// Pipeline_Activity represents AWS::IoTAnalytics::Pipeline.Activity.
type Pipeline_Activity struct {
	AddAttributes        any `json:"AddAttributes,omitempty"`
	Channel              any `json:"Channel,omitempty"`
	Datastore            any `json:"Datastore,omitempty"`
	DeviceRegistryEnrich any `json:"DeviceRegistryEnrich,omitempty"`
	DeviceShadowEnrich   any `json:"DeviceShadowEnrich,omitempty"`
	Filter               any `json:"Filter,omitempty"`
	Lambda               any `json:"Lambda,omitempty"`
	Math                 any `json:"Math,omitempty"`
	RemoveAttributes     any `json:"RemoveAttributes,omitempty"`
	SelectAttributes     any `json:"SelectAttributes,omitempty"`
}

// Pipeline_AddAttributes represents AWS::IoTAnalytics::Pipeline.AddAttributes.
type Pipeline_AddAttributes struct {
	Attributes map[string]any `json:"Attributes,omitempty"`
	Name       any            `json:"Name,omitempty"`
	Next       any            `json:"Next,omitempty"`
}

// Pipeline_Channel represents AWS::IoTAnalytics::Pipeline.Channel.
type Pipeline_Channel struct {
	ChannelName any `json:"ChannelName,omitempty"`
	Name        any `json:"Name,omitempty"`
	Next        any `json:"Next,omitempty"`
}

// Pipeline_Datastore represents AWS::IoTAnalytics::Pipeline.Datastore.
type Pipeline_Datastore struct {
	DatastoreName any `json:"DatastoreName,omitempty"`
	Name          any `json:"Name,omitempty"`
}

// Pipeline_DeviceRegistryEnrich represents AWS::IoTAnalytics::Pipeline.DeviceRegistryEnrich.
type Pipeline_DeviceRegistryEnrich struct {
	Attribute any `json:"Attribute,omitempty"`
	Name      any `json:"Name,omitempty"`
	Next      any `json:"Next,omitempty"`
	RoleArn   any `json:"RoleArn,omitempty"`
	ThingName any `json:"ThingName,omitempty"`
}

// Pipeline_DeviceShadowEnrich represents AWS::IoTAnalytics::Pipeline.DeviceShadowEnrich.
type Pipeline_DeviceShadowEnrich struct {
	Attribute any `json:"Attribute,omitempty"`
	Name      any `json:"Name,omitempty"`
	Next      any `json:"Next,omitempty"`
	RoleArn   any `json:"RoleArn,omitempty"`
	ThingName any `json:"ThingName,omitempty"`
}

// Pipeline_Filter represents AWS::IoTAnalytics::Pipeline.Filter.
type Pipeline_Filter struct {
	Filter any `json:"Filter,omitempty"`
	Name   any `json:"Name,omitempty"`
	Next   any `json:"Next,omitempty"`
}

// Pipeline_Lambda represents AWS::IoTAnalytics::Pipeline.Lambda.
type Pipeline_Lambda struct {
	BatchSize  any `json:"BatchSize,omitempty"`
	LambdaName any `json:"LambdaName,omitempty"`
	Name       any `json:"Name,omitempty"`
	Next       any `json:"Next,omitempty"`
}

// Pipeline_Math represents AWS::IoTAnalytics::Pipeline.Math.
type Pipeline_Math struct {
	Attribute any `json:"Attribute,omitempty"`
	Math      any `json:"Math,omitempty"`
	Name      any `json:"Name,omitempty"`
	Next      any `json:"Next,omitempty"`
}

// Pipeline_RemoveAttributes represents AWS::IoTAnalytics::Pipeline.RemoveAttributes.
type Pipeline_RemoveAttributes struct {
	Attributes []any `json:"Attributes,omitempty"`
	Name       any   `json:"Name,omitempty"`
	Next       any   `json:"Next,omitempty"`
}

// Pipeline_SelectAttributes represents AWS::IoTAnalytics::Pipeline.SelectAttributes.
type Pipeline_SelectAttributes struct {
	Attributes []any `json:"Attributes,omitempty"`
	Name       any   `json:"Name,omitempty"`
	Next       any   `json:"Next,omitempty"`
}
