// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package redshiftserverless

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Workgroup represents AWS::RedshiftServerless::Workgroup.

type Workgroup struct {
	// Attributes for Fn::GetAtt
	Workgroup_BaseCapacity       wetwire.AttrRef `json:"-"`
	Workgroup_CreationDate       wetwire.AttrRef `json:"-"`
	Workgroup_Endpoint_Address   wetwire.AttrRef `json:"-"`
	Workgroup_Endpoint_Port      wetwire.AttrRef `json:"-"`
	Workgroup_EnhancedVpcRouting wetwire.AttrRef `json:"-"`
	Workgroup_MaxCapacity        wetwire.AttrRef `json:"-"`
	Workgroup_NamespaceName      wetwire.AttrRef `json:"-"`
	Workgroup_PubliclyAccessible wetwire.AttrRef `json:"-"`
	Workgroup_SecurityGroupIds   wetwire.AttrRef `json:"-"`
	Workgroup_Status             wetwire.AttrRef `json:"-"`
	Workgroup_SubnetIds          wetwire.AttrRef `json:"-"`
	Workgroup_TrackName          wetwire.AttrRef `json:"-"`
	Workgroup_WorkgroupArn       wetwire.AttrRef `json:"-"`
	Workgroup_WorkgroupId        wetwire.AttrRef `json:"-"`
	Workgroup_WorkgroupName      wetwire.AttrRef `json:"-"`

	// Properties
	BaseCapacity           any                          `json:"BaseCapacity,omitempty"`
	ConfigParameters       []any                        `json:"ConfigParameters,omitempty"`
	EnhancedVpcRouting     any                          `json:"EnhancedVpcRouting,omitempty"`
	MaxCapacity            any                          `json:"MaxCapacity,omitempty"`
	NamespaceName          any                          `json:"NamespaceName,omitempty"`
	Port                   any                          `json:"Port,omitempty"`
	PricePerformanceTarget *Workgroup_PerformanceTarget `json:"PricePerformanceTarget,omitempty"`
	PubliclyAccessible     any                          `json:"PubliclyAccessible,omitempty"`
	RecoveryPointId        any                          `json:"RecoveryPointId,omitempty"`
	SecurityGroupIds       []any                        `json:"SecurityGroupIds,omitempty"`
	SnapshotArn            any                          `json:"SnapshotArn,omitempty"`
	SnapshotName           any                          `json:"SnapshotName,omitempty"`
	SnapshotOwnerAccount   any                          `json:"SnapshotOwnerAccount,omitempty"`
	SubnetIds              []any                        `json:"SubnetIds,omitempty"`
	Tags                   []any                        `json:"Tags,omitempty"`
	TrackName              any                          `json:"TrackName,omitempty"`
	Workgroup              *Workgroup_Workgroup         `json:"Workgroup,omitempty"`
	WorkgroupName          any                          `json:"WorkgroupName,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Workgroup) ResourceType() string {
	return "AWS::RedshiftServerless::Workgroup"
}
