// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package logs

// Transformer_AddKeyEntry represents AWS::Logs::Transformer.AddKeyEntry.
type Transformer_AddKeyEntry struct {
	Key               any `json:"Key,omitempty"`
	OverwriteIfExists any `json:"OverwriteIfExists,omitempty"`
	Value             any `json:"Value,omitempty"`
}

// Transformer_AddKeys represents AWS::Logs::Transformer.AddKeys.
type Transformer_AddKeys struct {
	Entries []Transformer_AddKeyEntry `json:"Entries,omitempty"`
}

// Transformer_CopyValue represents AWS::Logs::Transformer.CopyValue.
type Transformer_CopyValue struct {
	Entries []Transformer_CopyValueEntry `json:"Entries,omitempty"`
}

// Transformer_CopyValueEntry represents AWS::Logs::Transformer.CopyValueEntry.
type Transformer_CopyValueEntry struct {
	OverwriteIfExists any `json:"OverwriteIfExists,omitempty"`
	Source            any `json:"Source,omitempty"`
	Target            any `json:"Target,omitempty"`
}

// Transformer_Csv represents AWS::Logs::Transformer.Csv.
type Transformer_Csv struct {
	Columns        []any `json:"Columns,omitempty"`
	Delimiter      any   `json:"Delimiter,omitempty"`
	QuoteCharacter any   `json:"QuoteCharacter,omitempty"`
	Source         any   `json:"Source,omitempty"`
}

// Transformer_DateTimeConverter represents AWS::Logs::Transformer.DateTimeConverter.
type Transformer_DateTimeConverter struct {
	Locale         any   `json:"Locale,omitempty"`
	MatchPatterns  []any `json:"MatchPatterns,omitempty"`
	Source         any   `json:"Source,omitempty"`
	SourceTimezone any   `json:"SourceTimezone,omitempty"`
	Target         any   `json:"Target,omitempty"`
	TargetFormat   any   `json:"TargetFormat,omitempty"`
	TargetTimezone any   `json:"TargetTimezone,omitempty"`
}

// Transformer_DeleteKeys represents AWS::Logs::Transformer.DeleteKeys.
type Transformer_DeleteKeys struct {
	WithKeys []any `json:"WithKeys,omitempty"`
}

// Transformer_Grok represents AWS::Logs::Transformer.Grok.
type Transformer_Grok struct {
	Match  any `json:"Match,omitempty"`
	Source any `json:"Source,omitempty"`
}

// Transformer_ListToMap represents AWS::Logs::Transformer.ListToMap.
type Transformer_ListToMap struct {
	Flatten          any `json:"Flatten,omitempty"`
	FlattenedElement any `json:"FlattenedElement,omitempty"`
	Key              any `json:"Key,omitempty"`
	Source           any `json:"Source,omitempty"`
	Target           any `json:"Target,omitempty"`
	ValueKey         any `json:"ValueKey,omitempty"`
}

// Transformer_LowerCaseString represents AWS::Logs::Transformer.LowerCaseString.
type Transformer_LowerCaseString struct {
	WithKeys []any `json:"WithKeys,omitempty"`
}

// Transformer_MoveKeyEntry represents AWS::Logs::Transformer.MoveKeyEntry.
type Transformer_MoveKeyEntry struct {
	OverwriteIfExists any `json:"OverwriteIfExists,omitempty"`
	Source            any `json:"Source,omitempty"`
	Target            any `json:"Target,omitempty"`
}

// Transformer_MoveKeys represents AWS::Logs::Transformer.MoveKeys.
type Transformer_MoveKeys struct {
	Entries []Transformer_MoveKeyEntry `json:"Entries,omitempty"`
}

// Transformer_ParseCloudfront represents AWS::Logs::Transformer.ParseCloudfront.
type Transformer_ParseCloudfront struct {
	Source any `json:"Source,omitempty"`
}

// Transformer_ParseJSON represents AWS::Logs::Transformer.ParseJSON.
type Transformer_ParseJSON struct {
	Destination any `json:"Destination,omitempty"`
	Source      any `json:"Source,omitempty"`
}

// Transformer_ParseKeyValue represents AWS::Logs::Transformer.ParseKeyValue.
type Transformer_ParseKeyValue struct {
	Destination       any `json:"Destination,omitempty"`
	FieldDelimiter    any `json:"FieldDelimiter,omitempty"`
	KeyPrefix         any `json:"KeyPrefix,omitempty"`
	KeyValueDelimiter any `json:"KeyValueDelimiter,omitempty"`
	NonMatchValue     any `json:"NonMatchValue,omitempty"`
	OverwriteIfExists any `json:"OverwriteIfExists,omitempty"`
	Source            any `json:"Source,omitempty"`
}

// Transformer_ParsePostgres represents AWS::Logs::Transformer.ParsePostgres.
type Transformer_ParsePostgres struct {
	Source any `json:"Source,omitempty"`
}

// Transformer_ParseRoute53 represents AWS::Logs::Transformer.ParseRoute53.
type Transformer_ParseRoute53 struct {
	Source any `json:"Source,omitempty"`
}

// Transformer_ParseToOCSF represents AWS::Logs::Transformer.ParseToOCSF.
type Transformer_ParseToOCSF struct {
	EventSource    any `json:"EventSource,omitempty"`
	MappingVersion any `json:"MappingVersion,omitempty"`
	OcsfVersion    any `json:"OcsfVersion,omitempty"`
	Source         any `json:"Source,omitempty"`
}

// Transformer_ParseVPC represents AWS::Logs::Transformer.ParseVPC.
type Transformer_ParseVPC struct {
	Source any `json:"Source,omitempty"`
}

// Transformer_ParseWAF represents AWS::Logs::Transformer.ParseWAF.
type Transformer_ParseWAF struct {
	Source any `json:"Source,omitempty"`
}

// Transformer_Processor represents AWS::Logs::Transformer.Processor.
type Transformer_Processor struct {
	AddKeys           *Transformer_AddKeys           `json:"AddKeys,omitempty"`
	CopyValue         *Transformer_CopyValue         `json:"CopyValue,omitempty"`
	Csv               *Transformer_Csv               `json:"Csv,omitempty"`
	DateTimeConverter *Transformer_DateTimeConverter `json:"DateTimeConverter,omitempty"`
	DeleteKeys        *Transformer_DeleteKeys        `json:"DeleteKeys,omitempty"`
	Grok              *Transformer_Grok              `json:"Grok,omitempty"`
	ListToMap         *Transformer_ListToMap         `json:"ListToMap,omitempty"`
	LowerCaseString   *Transformer_LowerCaseString   `json:"LowerCaseString,omitempty"`
	MoveKeys          *Transformer_MoveKeys          `json:"MoveKeys,omitempty"`
	ParseCloudfront   *Transformer_ParseCloudfront   `json:"ParseCloudfront,omitempty"`
	ParseJSON         *Transformer_ParseJSON         `json:"ParseJSON,omitempty"`
	ParseKeyValue     *Transformer_ParseKeyValue     `json:"ParseKeyValue,omitempty"`
	ParsePostgres     *Transformer_ParsePostgres     `json:"ParsePostgres,omitempty"`
	ParseRoute53      *Transformer_ParseRoute53      `json:"ParseRoute53,omitempty"`
	ParseToOCSF       *Transformer_ParseToOCSF       `json:"ParseToOCSF,omitempty"`
	ParseVPC          *Transformer_ParseVPC          `json:"ParseVPC,omitempty"`
	ParseWAF          *Transformer_ParseWAF          `json:"ParseWAF,omitempty"`
	RenameKeys        *Transformer_RenameKeys        `json:"RenameKeys,omitempty"`
	SplitString       *Transformer_SplitString       `json:"SplitString,omitempty"`
	SubstituteString  *Transformer_SubstituteString  `json:"SubstituteString,omitempty"`
	TrimString        *Transformer_TrimString        `json:"TrimString,omitempty"`
	TypeConverter     *Transformer_TypeConverter     `json:"TypeConverter,omitempty"`
	UpperCaseString   *Transformer_UpperCaseString   `json:"UpperCaseString,omitempty"`
}

// Transformer_RenameKeyEntry represents AWS::Logs::Transformer.RenameKeyEntry.
type Transformer_RenameKeyEntry struct {
	Key               any `json:"Key,omitempty"`
	OverwriteIfExists any `json:"OverwriteIfExists,omitempty"`
	RenameTo          any `json:"RenameTo,omitempty"`
}

// Transformer_RenameKeys represents AWS::Logs::Transformer.RenameKeys.
type Transformer_RenameKeys struct {
	Entries []Transformer_RenameKeyEntry `json:"Entries,omitempty"`
}

// Transformer_SplitString represents AWS::Logs::Transformer.SplitString.
type Transformer_SplitString struct {
	Entries []Transformer_SplitStringEntry `json:"Entries,omitempty"`
}

// Transformer_SplitStringEntry represents AWS::Logs::Transformer.SplitStringEntry.
type Transformer_SplitStringEntry struct {
	Delimiter any `json:"Delimiter,omitempty"`
	Source    any `json:"Source,omitempty"`
}

// Transformer_SubstituteString represents AWS::Logs::Transformer.SubstituteString.
type Transformer_SubstituteString struct {
	Entries []Transformer_SubstituteStringEntry `json:"Entries,omitempty"`
}

// Transformer_SubstituteStringEntry represents AWS::Logs::Transformer.SubstituteStringEntry.
type Transformer_SubstituteStringEntry struct {
	From   any `json:"From,omitempty"`
	Source any `json:"Source,omitempty"`
	To     any `json:"To,omitempty"`
}

// Transformer_TrimString represents AWS::Logs::Transformer.TrimString.
type Transformer_TrimString struct {
	WithKeys []any `json:"WithKeys,omitempty"`
}

// Transformer_TypeConverter represents AWS::Logs::Transformer.TypeConverter.
type Transformer_TypeConverter struct {
	Entries []Transformer_TypeConverterEntry `json:"Entries,omitempty"`
}

// Transformer_TypeConverterEntry represents AWS::Logs::Transformer.TypeConverterEntry.
type Transformer_TypeConverterEntry struct {
	Key   any `json:"Key,omitempty"`
	Type_ any `json:"Type,omitempty"`
}

// Transformer_UpperCaseString represents AWS::Logs::Transformer.UpperCaseString.
type Transformer_UpperCaseString struct {
	WithKeys []any `json:"WithKeys,omitempty"`
}
