// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:17-07:00

package backup

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// BackupVault represents AWS::Backup::BackupVault.

type BackupVault struct {
	// Attributes for Fn::GetAtt
	BackupVaultArn wetwire.AttrRef `json:"-"`

	// Properties
	AccessPolicy      any                                 `json:"AccessPolicy,omitempty"`
	BackupVaultName   any                                 `json:"BackupVaultName,omitempty"`
	BackupVaultTags   map[string]any                      `json:"BackupVaultTags,omitempty"`
	EncryptionKeyArn  any                                 `json:"EncryptionKeyArn,omitempty"`
	LockConfiguration *BackupVault_LockConfigurationType  `json:"LockConfiguration,omitempty"`
	Notifications     *BackupVault_NotificationObjectType `json:"Notifications,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r BackupVault) ResourceType() string {
	return "AWS::Backup::BackupVault"
}
