// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package backup

// AggregationPeriod represents valid values for AggregationPeriod.
type AggregationPeriod string

const (
	AggregationPeriodOneDay       AggregationPeriod = "ONE_DAY"
	AggregationPeriodSevenDays    AggregationPeriod = "SEVEN_DAYS"
	AggregationPeriodFourteenDays AggregationPeriod = "FOURTEEN_DAYS"
)

// BackupJobState represents valid values for BackupJobState.
type BackupJobState string

const (
	BackupJobStateCreated   BackupJobState = "CREATED"
	BackupJobStatePending   BackupJobState = "PENDING"
	BackupJobStateRunning   BackupJobState = "RUNNING"
	BackupJobStateAborting  BackupJobState = "ABORTING"
	BackupJobStateAborted   BackupJobState = "ABORTED"
	BackupJobStateCompleted BackupJobState = "COMPLETED"
	BackupJobStateFailed    BackupJobState = "FAILED"
	BackupJobStateExpired   BackupJobState = "EXPIRED"
	BackupJobStatePartial   BackupJobState = "PARTIAL"
)

// BackupJobStatus represents valid values for BackupJobStatus.
type BackupJobStatus string

const (
	BackupJobStatusCreated      BackupJobStatus = "CREATED"
	BackupJobStatusPending      BackupJobStatus = "PENDING"
	BackupJobStatusRunning      BackupJobStatus = "RUNNING"
	BackupJobStatusAborting     BackupJobStatus = "ABORTING"
	BackupJobStatusAborted      BackupJobStatus = "ABORTED"
	BackupJobStatusCompleted    BackupJobStatus = "COMPLETED"
	BackupJobStatusFailed       BackupJobStatus = "FAILED"
	BackupJobStatusExpired      BackupJobStatus = "EXPIRED"
	BackupJobStatusPartial      BackupJobStatus = "PARTIAL"
	BackupJobStatusAggregateAll BackupJobStatus = "AGGREGATE_ALL"
	BackupJobStatusAny          BackupJobStatus = "ANY"
)

// BackupVaultEvent represents valid values for BackupVaultEvent.
type BackupVaultEvent string

const (
	BackupVaultEventBackupJobStarted            BackupVaultEvent = "BACKUP_JOB_STARTED"
	BackupVaultEventBackupJobCompleted          BackupVaultEvent = "BACKUP_JOB_COMPLETED"
	BackupVaultEventBackupJobSuccessful         BackupVaultEvent = "BACKUP_JOB_SUCCESSFUL"
	BackupVaultEventBackupJobFailed             BackupVaultEvent = "BACKUP_JOB_FAILED"
	BackupVaultEventBackupJobExpired            BackupVaultEvent = "BACKUP_JOB_EXPIRED"
	BackupVaultEventRestoreJobStarted           BackupVaultEvent = "RESTORE_JOB_STARTED"
	BackupVaultEventRestoreJobCompleted         BackupVaultEvent = "RESTORE_JOB_COMPLETED"
	BackupVaultEventRestoreJobSuccessful        BackupVaultEvent = "RESTORE_JOB_SUCCESSFUL"
	BackupVaultEventRestoreJobFailed            BackupVaultEvent = "RESTORE_JOB_FAILED"
	BackupVaultEventCopyJobStarted              BackupVaultEvent = "COPY_JOB_STARTED"
	BackupVaultEventCopyJobSuccessful           BackupVaultEvent = "COPY_JOB_SUCCESSFUL"
	BackupVaultEventCopyJobFailed               BackupVaultEvent = "COPY_JOB_FAILED"
	BackupVaultEventRecoveryPointModified       BackupVaultEvent = "RECOVERY_POINT_MODIFIED"
	BackupVaultEventBackupPlanCreated           BackupVaultEvent = "BACKUP_PLAN_CREATED"
	BackupVaultEventBackupPlanModified          BackupVaultEvent = "BACKUP_PLAN_MODIFIED"
	BackupVaultEventS3BackupObjectFailed        BackupVaultEvent = "S3_BACKUP_OBJECT_FAILED"
	BackupVaultEventS3RestoreObjectFailed       BackupVaultEvent = "S3_RESTORE_OBJECT_FAILED"
	BackupVaultEventContinuousBackupInterrupted BackupVaultEvent = "CONTINUOUS_BACKUP_INTERRUPTED"
	BackupVaultEventRecoveryPointIndexCompleted BackupVaultEvent = "RECOVERY_POINT_INDEX_COMPLETED"
	BackupVaultEventRecoveryPointIndexDeleted   BackupVaultEvent = "RECOVERY_POINT_INDEX_DELETED"
	BackupVaultEventRecoveryPointIndexingFailed BackupVaultEvent = "RECOVERY_POINT_INDEXING_FAILED"
)

// ConditionType represents valid values for ConditionType.
type ConditionType string

const (
	ConditionTypeStringequals ConditionType = "STRINGEQUALS"
)

// CopyJobState represents valid values for CopyJobState.
type CopyJobState string

const (
	CopyJobStateCreated   CopyJobState = "CREATED"
	CopyJobStateRunning   CopyJobState = "RUNNING"
	CopyJobStateCompleted CopyJobState = "COMPLETED"
	CopyJobStateFailed    CopyJobState = "FAILED"
	CopyJobStatePartial   CopyJobState = "PARTIAL"
)

// CopyJobStatus represents valid values for CopyJobStatus.
type CopyJobStatus string

const (
	CopyJobStatusCreated      CopyJobStatus = "CREATED"
	CopyJobStatusRunning      CopyJobStatus = "RUNNING"
	CopyJobStatusAborting     CopyJobStatus = "ABORTING"
	CopyJobStatusAborted      CopyJobStatus = "ABORTED"
	CopyJobStatusCompleting   CopyJobStatus = "COMPLETING"
	CopyJobStatusCompleted    CopyJobStatus = "COMPLETED"
	CopyJobStatusFailing      CopyJobStatus = "FAILING"
	CopyJobStatusFailed       CopyJobStatus = "FAILED"
	CopyJobStatusPartial      CopyJobStatus = "PARTIAL"
	CopyJobStatusAggregateAll CopyJobStatus = "AGGREGATE_ALL"
	CopyJobStatusAny          CopyJobStatus = "ANY"
)

// EncryptionKeyType represents valid values for EncryptionKeyType.
type EncryptionKeyType string

const (
	EncryptionKeyTypeAwsOwnedKmsKey        EncryptionKeyType = "AWS_OWNED_KMS_KEY"
	EncryptionKeyTypeCustomerManagedKmsKey EncryptionKeyType = "CUSTOMER_MANAGED_KMS_KEY"
)

// Index represents valid values for Index.
type Index string

const (
	IndexEnabled  Index = "ENABLED"
	IndexDisabled Index = "DISABLED"
)

// IndexStatus represents valid values for IndexStatus.
type IndexStatus string

const (
	IndexStatusPending  IndexStatus = "PENDING"
	IndexStatusActive   IndexStatus = "ACTIVE"
	IndexStatusFailed   IndexStatus = "FAILED"
	IndexStatusDeleting IndexStatus = "DELETING"
)

// LegalHoldStatus represents valid values for LegalHoldStatus.
type LegalHoldStatus string

const (
	LegalHoldStatusCreating  LegalHoldStatus = "CREATING"
	LegalHoldStatusActive    LegalHoldStatus = "ACTIVE"
	LegalHoldStatusCanceling LegalHoldStatus = "CANCELING"
	LegalHoldStatusCanceled  LegalHoldStatus = "CANCELED"
)

// LifecycleDeleteAfterEvent represents valid values for LifecycleDeleteAfterEvent.
type LifecycleDeleteAfterEvent string

const (
	LifecycleDeleteAfterEventDeleteAfterCopy LifecycleDeleteAfterEvent = "DELETE_AFTER_COPY"
)

// MalwareScanner represents valid values for MalwareScanner.
type MalwareScanner string

const (
	MalwareScannerGuardduty MalwareScanner = "GUARDDUTY"
)

// MpaRevokeSessionStatus represents valid values for MpaRevokeSessionStatus.
type MpaRevokeSessionStatus string

const (
	MpaRevokeSessionStatusPending MpaRevokeSessionStatus = "PENDING"
	MpaRevokeSessionStatusFailed  MpaRevokeSessionStatus = "FAILED"
)

// MpaSessionStatus represents valid values for MpaSessionStatus.
type MpaSessionStatus string

const (
	MpaSessionStatusPending  MpaSessionStatus = "PENDING"
	MpaSessionStatusApproved MpaSessionStatus = "APPROVED"
	MpaSessionStatusFailed   MpaSessionStatus = "FAILED"
)

// RecoveryPointStatus represents valid values for RecoveryPointStatus.
type RecoveryPointStatus string

const (
	RecoveryPointStatusCompleted RecoveryPointStatus = "COMPLETED"
	RecoveryPointStatusPartial   RecoveryPointStatus = "PARTIAL"
	RecoveryPointStatusDeleting  RecoveryPointStatus = "DELETING"
	RecoveryPointStatusExpired   RecoveryPointStatus = "EXPIRED"
	RecoveryPointStatusAvailable RecoveryPointStatus = "AVAILABLE"
	RecoveryPointStatusStopped   RecoveryPointStatus = "STOPPED"
	RecoveryPointStatusCreating  RecoveryPointStatus = "CREATING"
)

// RestoreDeletionStatus represents valid values for RestoreDeletionStatus.
type RestoreDeletionStatus string

const (
	RestoreDeletionStatusDeleting   RestoreDeletionStatus = "DELETING"
	RestoreDeletionStatusFailed     RestoreDeletionStatus = "FAILED"
	RestoreDeletionStatusSuccessful RestoreDeletionStatus = "SUCCESSFUL"
)

// RestoreJobState represents valid values for RestoreJobState.
type RestoreJobState string

const (
	RestoreJobStateCreated      RestoreJobState = "CREATED"
	RestoreJobStatePending      RestoreJobState = "PENDING"
	RestoreJobStateRunning      RestoreJobState = "RUNNING"
	RestoreJobStateAborted      RestoreJobState = "ABORTED"
	RestoreJobStateCompleted    RestoreJobState = "COMPLETED"
	RestoreJobStateFailed       RestoreJobState = "FAILED"
	RestoreJobStateAggregateAll RestoreJobState = "AGGREGATE_ALL"
	RestoreJobStateAny          RestoreJobState = "ANY"
)

// RestoreJobStatus represents valid values for RestoreJobStatus.
type RestoreJobStatus string

const (
	RestoreJobStatusPending   RestoreJobStatus = "PENDING"
	RestoreJobStatusRunning   RestoreJobStatus = "RUNNING"
	RestoreJobStatusCompleted RestoreJobStatus = "COMPLETED"
	RestoreJobStatusAborted   RestoreJobStatus = "ABORTED"
	RestoreJobStatusFailed    RestoreJobStatus = "FAILED"
)

// RestoreTestingRecoveryPointSelectionAlgorithm represents valid values for RestoreTestingRecoveryPointSelectionAlgorithm.
type RestoreTestingRecoveryPointSelectionAlgorithm string

const (
	RestoreTestingRecoveryPointSelectionAlgorithmLatestWithinWindow RestoreTestingRecoveryPointSelectionAlgorithm = "LATEST_WITHIN_WINDOW"
	RestoreTestingRecoveryPointSelectionAlgorithmRandomWithinWindow RestoreTestingRecoveryPointSelectionAlgorithm = "RANDOM_WITHIN_WINDOW"
)

// RestoreTestingRecoveryPointType represents valid values for RestoreTestingRecoveryPointType.
type RestoreTestingRecoveryPointType string

const (
	RestoreTestingRecoveryPointTypeContinuous RestoreTestingRecoveryPointType = "CONTINUOUS"
	RestoreTestingRecoveryPointTypeSnapshot   RestoreTestingRecoveryPointType = "SNAPSHOT"
)

// RestoreValidationStatus represents valid values for RestoreValidationStatus.
type RestoreValidationStatus string

const (
	RestoreValidationStatusFailed     RestoreValidationStatus = "FAILED"
	RestoreValidationStatusSuccessful RestoreValidationStatus = "SUCCESSFUL"
	RestoreValidationStatusTimedOut   RestoreValidationStatus = "TIMED_OUT"
	RestoreValidationStatusValidating RestoreValidationStatus = "VALIDATING"
)

// RuleExecutionType represents valid values for RuleExecutionType.
type RuleExecutionType string

const (
	RuleExecutionTypeContinuous             RuleExecutionType = "CONTINUOUS"
	RuleExecutionTypeSnapshots              RuleExecutionType = "SNAPSHOTS"
	RuleExecutionTypeContinuousAndSnapshots RuleExecutionType = "CONTINUOUS_AND_SNAPSHOTS"
)

// ScanFinding represents valid values for ScanFinding.
type ScanFinding string

const (
	ScanFindingMalware ScanFinding = "MALWARE"
)

// ScanJobState represents valid values for ScanJobState.
type ScanJobState string

const (
	ScanJobStateCompleted           ScanJobState = "COMPLETED"
	ScanJobStateCompletedWithIssues ScanJobState = "COMPLETED_WITH_ISSUES"
	ScanJobStateFailed              ScanJobState = "FAILED"
	ScanJobStateCanceled            ScanJobState = "CANCELED"
)

// ScanJobStatus represents valid values for ScanJobStatus.
type ScanJobStatus string

const (
	ScanJobStatusCreated             ScanJobStatus = "CREATED"
	ScanJobStatusCompleted           ScanJobStatus = "COMPLETED"
	ScanJobStatusCompletedWithIssues ScanJobStatus = "COMPLETED_WITH_ISSUES"
	ScanJobStatusRunning             ScanJobStatus = "RUNNING"
	ScanJobStatusFailed              ScanJobStatus = "FAILED"
	ScanJobStatusCanceled            ScanJobStatus = "CANCELED"
	ScanJobStatusAggregateAll        ScanJobStatus = "AGGREGATE_ALL"
	ScanJobStatusAny                 ScanJobStatus = "ANY"
)

// ScanMode represents valid values for ScanMode.
type ScanMode string

const (
	ScanModeFullScan        ScanMode = "FULL_SCAN"
	ScanModeIncrementalScan ScanMode = "INCREMENTAL_SCAN"
)

// ScanResourceType represents valid values for ScanResourceType.
type ScanResourceType string

const (
	ScanResourceTypeEbs ScanResourceType = "EBS"
	ScanResourceTypeEc2 ScanResourceType = "EC2"
	ScanResourceTypeS3  ScanResourceType = "S3"
)

// ScanResultStatus represents valid values for ScanResultStatus.
type ScanResultStatus string

const (
	ScanResultStatusNoThreatsFound ScanResultStatus = "NO_THREATS_FOUND"
	ScanResultStatusThreatsFound   ScanResultStatus = "THREATS_FOUND"
)

// ScanState represents valid values for ScanState.
type ScanState string

const (
	ScanStateCanceled            ScanState = "CANCELED"
	ScanStateCompleted           ScanState = "COMPLETED"
	ScanStateCompletedWithIssues ScanState = "COMPLETED_WITH_ISSUES"
	ScanStateCreated             ScanState = "CREATED"
	ScanStateFailed              ScanState = "FAILED"
	ScanStateRunning             ScanState = "RUNNING"
)

// StorageClass represents valid values for StorageClass.
type StorageClass string

const (
	StorageClassWarm    StorageClass = "WARM"
	StorageClassCold    StorageClass = "COLD"
	StorageClassDeleted StorageClass = "DELETED"
)

// VaultState represents valid values for VaultState.
type VaultState string

const (
	VaultStateCreating  VaultState = "CREATING"
	VaultStateAvailable VaultState = "AVAILABLE"
	VaultStateFailed    VaultState = "FAILED"
)

// VaultType represents valid values for VaultType.
type VaultType string

const (
	VaultTypeBackupVault                   VaultType = "BACKUP_VAULT"
	VaultTypeLogicallyAirGappedBackupVault VaultType = "LOGICALLY_AIR_GAPPED_BACKUP_VAULT"
	VaultTypeRestoreAccessBackupVault      VaultType = "RESTORE_ACCESS_BACKUP_VAULT"
)
