// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package backup

// Framework_ControlInputParameter represents AWS::Backup::Framework.ControlInputParameter.
type Framework_ControlInputParameter struct {
	ParameterName  any `json:"ParameterName,omitempty"`
	ParameterValue any `json:"ParameterValue,omitempty"`
}

// Framework_ControlScope represents AWS::Backup::Framework.ControlScope.
type Framework_ControlScope struct {
	ComplianceResourceIds   []any `json:"ComplianceResourceIds,omitempty"`
	ComplianceResourceTypes []any `json:"ComplianceResourceTypes,omitempty"`
	Tags                    []any `json:"Tags,omitempty"`
}

// Framework_FrameworkControl represents AWS::Backup::Framework.FrameworkControl.
type Framework_FrameworkControl struct {
	ControlInputParameters []any                   `json:"ControlInputParameters,omitempty"`
	ControlName            any                     `json:"ControlName,omitempty"`
	ControlScope           *Framework_ControlScope `json:"ControlScope,omitempty"`
}
