// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package backup

// LogicallyAirGappedBackupVault_NotificationObjectType represents AWS::Backup::LogicallyAirGappedBackupVault.NotificationObjectType.
type LogicallyAirGappedBackupVault_NotificationObjectType struct {
	BackupVaultEvents []any `json:"BackupVaultEvents,omitempty"`
	SNSTopicArn       any   `json:"SNSTopicArn,omitempty"`
}
