// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package config

// ConfigRule_Compliance represents AWS::Config::ConfigRule.Compliance.
type ConfigRule_Compliance struct {
	Type_ any `json:"Type,omitempty"`
}

// ConfigRule_CustomPolicyDetails represents AWS::Config::ConfigRule.CustomPolicyDetails.
type ConfigRule_CustomPolicyDetails struct {
	EnableDebugLogDelivery any `json:"EnableDebugLogDelivery,omitempty"`
	PolicyRuntime          any `json:"PolicyRuntime,omitempty"`
	PolicyText             any `json:"PolicyText,omitempty"`
}

// ConfigRule_EvaluationModeConfiguration represents AWS::Config::ConfigRule.EvaluationModeConfiguration.
type ConfigRule_EvaluationModeConfiguration struct {
	Mode any `json:"Mode,omitempty"`
}

// ConfigRule_Scope represents AWS::Config::ConfigRule.Scope.
type ConfigRule_Scope struct {
	ComplianceResourceId    any   `json:"ComplianceResourceId,omitempty"`
	ComplianceResourceTypes []any `json:"ComplianceResourceTypes,omitempty"`
	TagKey                  any   `json:"TagKey,omitempty"`
	TagValue                any   `json:"TagValue,omitempty"`
}

// ConfigRule_Source represents AWS::Config::ConfigRule.Source.
type ConfigRule_Source struct {
	CustomPolicyDetails *ConfigRule_CustomPolicyDetails `json:"CustomPolicyDetails,omitempty"`
	Owner               any                             `json:"Owner,omitempty"`
	SourceDetails       []ConfigRule_SourceDetail       `json:"SourceDetails,omitempty"`
	SourceIdentifier    any                             `json:"SourceIdentifier,omitempty"`
}

// ConfigRule_SourceDetail represents AWS::Config::ConfigRule.SourceDetail.
type ConfigRule_SourceDetail struct {
	EventSource               any `json:"EventSource,omitempty"`
	MaximumExecutionFrequency any `json:"MaximumExecutionFrequency,omitempty"`
	MessageType               any `json:"MessageType,omitempty"`
}
