// Package apprunnerservicefromecr contains CloudFormation resources.
// Security resources: IAM, Cognito, KMS, etc.
//
// Generated by wetwire-aws import.
package apprunnerservicefromecr

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/iam"
)

var AppRunnerRolePolicyRootPolicyDocument = PolicyDocument{
	Statement: []any{AppRunnerRolePolicyRootPolicyDocumentStatement0},
	Version: "2012-10-17",
}

var AppRunnerRolePolicyRootPolicyDocumentStatement0 = PolicyStatement{
	Action: []any{"ecr:GetDownloadUrlForLayer", "ecr:BatchGetImage", "ecr:DescribeImages", "ecr:GetAuthorizationToken", "ecr:BatchCheckLayerAvailability"},
	Effect: "Allow",
	Resource: "*",
}

var AppRunnerRolePolicyRoot = iam.Role_Policy{
	PolicyDocument: AppRunnerRolePolicyRootPolicyDocument,
	PolicyName: "root",
}

var AppRunnerRoleAssumeRolePolicyDocument = PolicyDocument{
	Statement: []any{AppRunnerRoleAssumeRolePolicyDocumentStatement0},
	Version: "2012-10-17",
}

var AppRunnerRoleAssumeRolePolicyDocumentStatement0 = PolicyStatement{
	Action: []any{"sts:AssumeRole"},
	Effect: "Allow",
	Principal: ServicePrincipal{"build.apprunner.amazonaws.com"},
}

var AppRunnerRole = iam.Role{
	AssumeRolePolicyDocument: AppRunnerRoleAssumeRolePolicyDocument,
	Path: "/",
	Policies: []any{AppRunnerRolePolicyRoot},
}
