// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package lakeformation

// DataCellsFilter represents AWS::LakeFormation::DataCellsFilter.

type DataCellsFilter struct {

	// Properties
	ColumnNames    []any `json:"ColumnNames,omitempty"`
	ColumnWildcard any   `json:"ColumnWildcard,omitempty"`
	DatabaseName   any   `json:"DatabaseName,omitempty"`
	Name           any   `json:"Name,omitempty"`
	RowFilter      any   `json:"RowFilter,omitempty"`
	TableCatalogId any   `json:"TableCatalogId,omitempty"`
	TableName      any   `json:"TableName,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r DataCellsFilter) ResourceType() string {
	return "AWS::LakeFormation::DataCellsFilter"
}
