// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package codedeploy

// DeploymentGroup represents AWS::CodeDeploy::DeploymentGroup.

type DeploymentGroup struct {

	// Properties
	AlarmConfiguration               *DeploymentGroup_AlarmConfiguration               `json:"AlarmConfiguration,omitempty"`
	ApplicationName                  any                                               `json:"ApplicationName,omitempty"`
	AutoRollbackConfiguration        *DeploymentGroup_AutoRollbackConfiguration        `json:"AutoRollbackConfiguration,omitempty"`
	AutoScalingGroups                []any                                             `json:"AutoScalingGroups,omitempty"`
	BlueGreenDeploymentConfiguration *DeploymentGroup_BlueGreenDeploymentConfiguration `json:"BlueGreenDeploymentConfiguration,omitempty"`
	Deployment                       *DeploymentGroup_Deployment                       `json:"Deployment,omitempty"`
	DeploymentConfigName             any                                               `json:"DeploymentConfigName,omitempty"`
	DeploymentGroupName              any                                               `json:"DeploymentGroupName,omitempty"`
	DeploymentStyle                  *DeploymentGroup_DeploymentStyle                  `json:"DeploymentStyle,omitempty"`
	ECSServices                      []any                                             `json:"ECSServices,omitempty"`
	Ec2TagFilters                    []any                                             `json:"Ec2TagFilters,omitempty"`
	Ec2TagSet                        *DeploymentGroup_EC2TagSet                        `json:"Ec2TagSet,omitempty"`
	LoadBalancerInfo                 *DeploymentGroup_LoadBalancerInfo                 `json:"LoadBalancerInfo,omitempty"`
	OnPremisesInstanceTagFilters     []any                                             `json:"OnPremisesInstanceTagFilters,omitempty"`
	OnPremisesTagSet                 *DeploymentGroup_OnPremisesTagSet                 `json:"OnPremisesTagSet,omitempty"`
	OutdatedInstancesStrategy        any                                               `json:"OutdatedInstancesStrategy,omitempty"`
	ServiceRoleArn                   any                                               `json:"ServiceRoleArn,omitempty"`
	Tags                             []any                                             `json:"Tags,omitempty"`
	TerminationHookEnabled           any                                               `json:"TerminationHookEnabled,omitempty"`
	TriggerConfigurations            []any                                             `json:"TriggerConfigurations,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r DeploymentGroup) ResourceType() string {
	return "AWS::CodeDeploy::DeploymentGroup"
}
