// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package mediapackage

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// PackagingGroup represents AWS::MediaPackage::PackagingGroup.

type PackagingGroup struct {
	// Attributes for Fn::GetAtt
	Arn        wetwire.AttrRef `json:"-"`
	DomainName wetwire.AttrRef `json:"-"`

	// Properties
	Authorization    *PackagingGroup_Authorization    `json:"Authorization,omitempty"`
	EgressAccessLogs *PackagingGroup_LogConfiguration `json:"EgressAccessLogs,omitempty"`
	Id               any                              `json:"Id,omitempty"`
	Tags             []any                            `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r PackagingGroup) ResourceType() string {
	return "AWS::MediaPackage::PackagingGroup"
}
