// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package iot

// BillingGroup_BillingGroupProperties represents AWS::IoT::BillingGroup.BillingGroupProperties.
type BillingGroup_BillingGroupProperties struct {
	BillingGroupDescription any `json:"BillingGroupDescription,omitempty"`
}
