// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package iot

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// BillingGroup represents AWS::IoT::BillingGroup.

type BillingGroup struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`
	Id  wetwire.AttrRef `json:"-"`

	// Properties
	BillingGroupName       any                                  `json:"BillingGroupName,omitempty"`
	BillingGroupProperties *BillingGroup_BillingGroupProperties `json:"BillingGroupProperties,omitempty"`
	Tags                   []any                                `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r BillingGroup) ResourceType() string {
	return "AWS::IoT::BillingGroup"
}
