// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package iot

// Command_CommandParameter represents AWS::IoT::Command.CommandParameter.
type Command_CommandParameter struct {
	DefaultValue any `json:"DefaultValue,omitempty"`
	Description  any `json:"Description,omitempty"`
	Name         any `json:"Name,omitempty"`
	Value        any `json:"Value,omitempty"`
}

// Command_CommandParameterValue represents AWS::IoT::Command.CommandParameterValue.
type Command_CommandParameterValue struct {
	B   any `json:"B,omitempty"`
	BIN any `json:"BIN,omitempty"`
	D   any `json:"D,omitempty"`
	I   any `json:"I,omitempty"`
	L   any `json:"L,omitempty"`
	S   any `json:"S,omitempty"`
	UL  any `json:"UL,omitempty"`
}

// Command_CommandPayload represents AWS::IoT::Command.CommandPayload.
type Command_CommandPayload struct {
	Content     any `json:"Content,omitempty"`
	ContentType any `json:"ContentType,omitempty"`
}
