// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package iot

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Dimension represents AWS::IoT::Dimension.

type Dimension struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	Name         any   `json:"Name,omitempty"`
	StringValues []any `json:"StringValues,omitempty"`
	Tags         []any `json:"Tags,omitempty"`
	Type_        any   `json:"Type,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Dimension) ResourceType() string {
	return "AWS::IoT::Dimension"
}
