// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package iot

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// DomainConfiguration represents AWS::IoT::DomainConfiguration.

type DomainConfiguration struct {
	// Attributes for Fn::GetAtt
	Arn                wetwire.AttrRef `json:"-"`
	DomainType         wetwire.AttrRef `json:"-"`
	ServerCertificates wetwire.AttrRef `json:"-"`

	// Properties
	ApplicationProtocol       any   `json:"ApplicationProtocol,omitempty"`
	AuthenticationType        any   `json:"AuthenticationType,omitempty"`
	AuthorizerConfig          any   `json:"AuthorizerConfig,omitempty"`
	ClientCertificateConfig   any   `json:"ClientCertificateConfig,omitempty"`
	DomainConfigurationName   any   `json:"DomainConfigurationName,omitempty"`
	DomainConfigurationStatus any   `json:"DomainConfigurationStatus,omitempty"`
	DomainName                any   `json:"DomainName,omitempty"`
	ServerCertificateArns     []any `json:"ServerCertificateArns,omitempty"`
	ServerCertificateConfig   any   `json:"ServerCertificateConfig,omitempty"`
	ServiceType               any   `json:"ServiceType,omitempty"`
	Tags                      []any `json:"Tags,omitempty"`
	TlsConfig                 any   `json:"TlsConfig,omitempty"`
	ValidationCertificateArn  any   `json:"ValidationCertificateArn,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r DomainConfiguration) ResourceType() string {
	return "AWS::IoT::DomainConfiguration"
}
