// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package iot

// EncryptionConfiguration_ConfigurationDetails represents AWS::IoT::EncryptionConfiguration.ConfigurationDetails.
type EncryptionConfiguration_ConfigurationDetails struct {
	ConfigurationStatus any `json:"ConfigurationStatus,omitempty"`
	ErrorCode           any `json:"ErrorCode,omitempty"`
	ErrorMessage        any `json:"ErrorMessage,omitempty"`
}
