// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package iot

// JobTemplate_AbortConfig represents AWS::IoT::JobTemplate.AbortConfig.
type JobTemplate_AbortConfig struct {
	CriteriaList []JobTemplate_AbortCriteria `json:"CriteriaList,omitempty"`
}

// JobTemplate_AbortCriteria represents AWS::IoT::JobTemplate.AbortCriteria.
type JobTemplate_AbortCriteria struct {
	Action                    any `json:"Action,omitempty"`
	FailureType               any `json:"FailureType,omitempty"`
	MinNumberOfExecutedThings any `json:"MinNumberOfExecutedThings,omitempty"`
	ThresholdPercentage       any `json:"ThresholdPercentage,omitempty"`
}

// JobTemplate_ExponentialRolloutRate represents AWS::IoT::JobTemplate.ExponentialRolloutRate.
type JobTemplate_ExponentialRolloutRate struct {
	BaseRatePerMinute    any                              `json:"BaseRatePerMinute,omitempty"`
	IncrementFactor      any                              `json:"IncrementFactor,omitempty"`
	RateIncreaseCriteria JobTemplate_RateIncreaseCriteria `json:"RateIncreaseCriteria,omitempty"`
}

// JobTemplate_JobExecutionsRetryConfig represents AWS::IoT::JobTemplate.JobExecutionsRetryConfig.
type JobTemplate_JobExecutionsRetryConfig struct {
	RetryCriteriaList []JobTemplate_RetryCriteria `json:"RetryCriteriaList,omitempty"`
}

// JobTemplate_JobExecutionsRolloutConfig represents AWS::IoT::JobTemplate.JobExecutionsRolloutConfig.
type JobTemplate_JobExecutionsRolloutConfig struct {
	ExponentialRolloutRate *JobTemplate_ExponentialRolloutRate `json:"ExponentialRolloutRate,omitempty"`
	MaximumPerMinute       any                                 `json:"MaximumPerMinute,omitempty"`
}

// JobTemplate_MaintenanceWindow represents AWS::IoT::JobTemplate.MaintenanceWindow.
type JobTemplate_MaintenanceWindow struct {
	DurationInMinutes any `json:"DurationInMinutes,omitempty"`
	StartTime         any `json:"StartTime,omitempty"`
}

// JobTemplate_PresignedUrlConfig represents AWS::IoT::JobTemplate.PresignedUrlConfig.
type JobTemplate_PresignedUrlConfig struct {
	ExpiresInSec any `json:"ExpiresInSec,omitempty"`
	RoleArn      any `json:"RoleArn,omitempty"`
}

// JobTemplate_RateIncreaseCriteria represents AWS::IoT::JobTemplate.RateIncreaseCriteria.
type JobTemplate_RateIncreaseCriteria struct {
	NumberOfNotifiedThings  any `json:"NumberOfNotifiedThings,omitempty"`
	NumberOfSucceededThings any `json:"NumberOfSucceededThings,omitempty"`
}

// JobTemplate_RetryCriteria represents AWS::IoT::JobTemplate.RetryCriteria.
type JobTemplate_RetryCriteria struct {
	FailureType     any `json:"FailureType,omitempty"`
	NumberOfRetries any `json:"NumberOfRetries,omitempty"`
}

// JobTemplate_TimeoutConfig represents AWS::IoT::JobTemplate.TimeoutConfig.
type JobTemplate_TimeoutConfig struct {
	InProgressTimeoutInMinutes any `json:"InProgressTimeoutInMinutes,omitempty"`
}
