// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package iot

// Logging represents AWS::IoT::Logging.

type Logging struct {

	// Properties
	AccountId       any `json:"AccountId,omitempty"`
	DefaultLogLevel any `json:"DefaultLogLevel,omitempty"`
	RoleArn         any `json:"RoleArn,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Logging) ResourceType() string {
	return "AWS::IoT::Logging"
}
