// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package iot

// ThingType_Mqtt5Configuration represents AWS::IoT::ThingType.Mqtt5Configuration.
type ThingType_Mqtt5Configuration struct {
	PropagatingAttributes []ThingType_PropagatingAttribute `json:"PropagatingAttributes,omitempty"`
}

// ThingType_PropagatingAttribute represents AWS::IoT::ThingType.PropagatingAttribute.
type ThingType_PropagatingAttribute struct {
	ConnectionAttribute any `json:"ConnectionAttribute,omitempty"`
	ThingAttribute      any `json:"ThingAttribute,omitempty"`
	UserPropertyKey     any `json:"UserPropertyKey,omitempty"`
}

// ThingType_ThingTypeProperties represents AWS::IoT::ThingType.ThingTypeProperties.
type ThingType_ThingTypeProperties struct {
	Mqtt5Configuration   *ThingType_Mqtt5Configuration `json:"Mqtt5Configuration,omitempty"`
	SearchableAttributes []any                         `json:"SearchableAttributes,omitempty"`
	ThingTypeDescription any                           `json:"ThingTypeDescription,omitempty"`
}
