// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package directoryservice

// MicrosoftAD_VpcSettings represents AWS::DirectoryService::MicrosoftAD.VpcSettings.
type MicrosoftAD_VpcSettings struct {
	SubnetIds []any `json:"SubnetIds,omitempty"`
	VpcId     any   `json:"VpcId,omitempty"`
}
