// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ssmincidents

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ReplicationSet represents AWS::SSMIncidents::ReplicationSet.

type ReplicationSet struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	DeletionProtected any                                `json:"DeletionProtected,omitempty"`
	Regions           []ReplicationSet_ReplicationRegion `json:"Regions,omitempty"`
	Tags              []any                              `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ReplicationSet) ResourceType() string {
	return "AWS::SSMIncidents::ReplicationSet"
}
