// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package aps

// ResourcePolicy represents AWS::APS::ResourcePolicy.

type ResourcePolicy struct {

	// Properties
	PolicyDocument any `json:"PolicyDocument,omitempty"`
	WorkspaceArn   any `json:"WorkspaceArn,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ResourcePolicy) ResourceType() string {
	return "AWS::APS::ResourcePolicy"
}
