// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package iotthingsgraph

// DefinitionLanguage represents valid values for DefinitionLanguage.
type DefinitionLanguage string

const (
	DefinitionLanguageGraphql DefinitionLanguage = "GRAPHQL"
)

// DeploymentTarget represents valid values for DeploymentTarget.
type DeploymentTarget string

const (
	DeploymentTargetGreengrass DeploymentTarget = "GREENGRASS"
	DeploymentTargetCloud      DeploymentTarget = "CLOUD"
)

// EntityFilterName represents valid values for EntityFilterName.
type EntityFilterName string

const (
	EntityFilterNameName               EntityFilterName = "NAME"
	EntityFilterNameNamespace          EntityFilterName = "NAMESPACE"
	EntityFilterNameSemanticTypePath   EntityFilterName = "SEMANTIC_TYPE_PATH"
	EntityFilterNameReferencedEntityId EntityFilterName = "REFERENCED_ENTITY_ID"
)

// EntityType represents valid values for EntityType.
type EntityType string

const (
	EntityTypeDevice      EntityType = "DEVICE"
	EntityTypeService     EntityType = "SERVICE"
	EntityTypeDeviceModel EntityType = "DEVICE_MODEL"
	EntityTypeCapability  EntityType = "CAPABILITY"
	EntityTypeState       EntityType = "STATE"
	EntityTypeAction      EntityType = "ACTION"
	EntityTypeEvent       EntityType = "EVENT"
	EntityTypeProperty    EntityType = "PROPERTY"
	EntityTypeMapping     EntityType = "MAPPING"
	EntityTypeEnum        EntityType = "ENUM"
)

// FlowExecutionEventType represents valid values for FlowExecutionEventType.
type FlowExecutionEventType string

const (
	FlowExecutionEventTypeExecutionStarted           FlowExecutionEventType = "EXECUTION_STARTED"
	FlowExecutionEventTypeExecutionFailed            FlowExecutionEventType = "EXECUTION_FAILED"
	FlowExecutionEventTypeExecutionAborted           FlowExecutionEventType = "EXECUTION_ABORTED"
	FlowExecutionEventTypeExecutionSucceeded         FlowExecutionEventType = "EXECUTION_SUCCEEDED"
	FlowExecutionEventTypeStepStarted                FlowExecutionEventType = "STEP_STARTED"
	FlowExecutionEventTypeStepFailed                 FlowExecutionEventType = "STEP_FAILED"
	FlowExecutionEventTypeStepSucceeded              FlowExecutionEventType = "STEP_SUCCEEDED"
	FlowExecutionEventTypeActivityScheduled          FlowExecutionEventType = "ACTIVITY_SCHEDULED"
	FlowExecutionEventTypeActivityStarted            FlowExecutionEventType = "ACTIVITY_STARTED"
	FlowExecutionEventTypeActivityFailed             FlowExecutionEventType = "ACTIVITY_FAILED"
	FlowExecutionEventTypeActivitySucceeded          FlowExecutionEventType = "ACTIVITY_SUCCEEDED"
	FlowExecutionEventTypeStartFlowExecutionTask     FlowExecutionEventType = "START_FLOW_EXECUTION_TASK"
	FlowExecutionEventTypeScheduleNextReadyStepsTask FlowExecutionEventType = "SCHEDULE_NEXT_READY_STEPS_TASK"
	FlowExecutionEventTypeThingActionTask            FlowExecutionEventType = "THING_ACTION_TASK"
	FlowExecutionEventTypeThingActionTaskFailed      FlowExecutionEventType = "THING_ACTION_TASK_FAILED"
	FlowExecutionEventTypeThingActionTaskSucceeded   FlowExecutionEventType = "THING_ACTION_TASK_SUCCEEDED"
	FlowExecutionEventTypeAcknowledgeTaskMessage     FlowExecutionEventType = "ACKNOWLEDGE_TASK_MESSAGE"
)

// FlowExecutionStatus represents valid values for FlowExecutionStatus.
type FlowExecutionStatus string

const (
	FlowExecutionStatusRunning   FlowExecutionStatus = "RUNNING"
	FlowExecutionStatusAborted   FlowExecutionStatus = "ABORTED"
	FlowExecutionStatusSucceeded FlowExecutionStatus = "SUCCEEDED"
	FlowExecutionStatusFailed    FlowExecutionStatus = "FAILED"
)

// FlowTemplateFilterName represents valid values for FlowTemplateFilterName.
type FlowTemplateFilterName string

const (
	FlowTemplateFilterNameDeviceModelId FlowTemplateFilterName = "DEVICE_MODEL_ID"
)

// NamespaceDeletionStatus represents valid values for NamespaceDeletionStatus.
type NamespaceDeletionStatus string

const (
	NamespaceDeletionStatusInProgress NamespaceDeletionStatus = "IN_PROGRESS"
	NamespaceDeletionStatusSucceeded  NamespaceDeletionStatus = "SUCCEEDED"
	NamespaceDeletionStatusFailed     NamespaceDeletionStatus = "FAILED"
)

// NamespaceDeletionStatusErrorCodes represents valid values for NamespaceDeletionStatusErrorCodes.
type NamespaceDeletionStatusErrorCodes string

const (
	NamespaceDeletionStatusErrorCodesValidationFailed NamespaceDeletionStatusErrorCodes = "VALIDATION_FAILED"
)

// SystemInstanceDeploymentStatus represents valid values for SystemInstanceDeploymentStatus.
type SystemInstanceDeploymentStatus string

const (
	SystemInstanceDeploymentStatusNotDeployed        SystemInstanceDeploymentStatus = "NOT_DEPLOYED"
	SystemInstanceDeploymentStatusBootstrap          SystemInstanceDeploymentStatus = "BOOTSTRAP"
	SystemInstanceDeploymentStatusDeployInProgress   SystemInstanceDeploymentStatus = "DEPLOY_IN_PROGRESS"
	SystemInstanceDeploymentStatusDeployedInTarget   SystemInstanceDeploymentStatus = "DEPLOYED_IN_TARGET"
	SystemInstanceDeploymentStatusUndeployInProgress SystemInstanceDeploymentStatus = "UNDEPLOY_IN_PROGRESS"
	SystemInstanceDeploymentStatusFailed             SystemInstanceDeploymentStatus = "FAILED"
	SystemInstanceDeploymentStatusPendingDelete      SystemInstanceDeploymentStatus = "PENDING_DELETE"
	SystemInstanceDeploymentStatusDeletedInTarget    SystemInstanceDeploymentStatus = "DELETED_IN_TARGET"
)

// SystemInstanceFilterName represents valid values for SystemInstanceFilterName.
type SystemInstanceFilterName string

const (
	SystemInstanceFilterNameSystemTemplateId    SystemInstanceFilterName = "SYSTEM_TEMPLATE_ID"
	SystemInstanceFilterNameStatus              SystemInstanceFilterName = "STATUS"
	SystemInstanceFilterNameGreengrassGroupName SystemInstanceFilterName = "GREENGRASS_GROUP_NAME"
)

// SystemTemplateFilterName represents valid values for SystemTemplateFilterName.
type SystemTemplateFilterName string

const (
	SystemTemplateFilterNameFlowTemplateId SystemTemplateFilterName = "FLOW_TEMPLATE_ID"
)

// UploadStatus represents valid values for UploadStatus.
type UploadStatus string

const (
	UploadStatusInProgress UploadStatus = "IN_PROGRESS"
	UploadStatusSucceeded  UploadStatus = "SUCCEEDED"
	UploadStatusFailed     UploadStatus = "FAILED"
)
