// Package cloudfront_stack contains CloudFormation resources.
// Storage resources: S3, EFS, etc.
//
// Generated by wetwire-aws import.
package cloudfront_stack

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/s3"
)

var LoggingBucketPolicyPolicyDocument = PolicyDocument{
	Statement: []any{LoggingBucketPolicyPolicyDocumentStatement0, LoggingBucketPolicyPolicyDocumentStatement1},
	Version: "2012-10-17",
}

var LoggingBucketPolicyPolicyDocumentStatement1 = DenyStatement{
	Action: "s3:*",
	Condition: Json{Bool: Json{"aws:SecureTransport": false}},
	Principal: AWSPrincipal{"*"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${LoggingBucket}/AWSLogs/${AWS::AccountId}/*"}},
}

var LoggingBucketPolicyPolicyDocumentStatement0 = PolicyStatement{
	Action: "s3:PutObject",
	Effect: "Allow",
	Principal: AWSPrincipal{Sub{String: "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"}},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${LoggingBucket}/AWSLogs/${AWS::AccountId}/*"}},
	Sid: "LoggingBucketPermissions",
}

var LoggingBucketPolicy = s3.BucketPolicy{
	Bucket: LoggingBucket,
	PolicyDocument: LoggingBucketPolicyPolicyDocument,
}

var LoggingBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault = s3.Bucket_ServerSideEncryptionByDefault{
	KMSMasterKeyID: LoggingBucketKMSKey.Arn,
	SSEAlgorithm: "aws:kms",
}

var LoggingBucketOwnershipControlsRule1 = s3.Bucket_OwnershipControlsRule{
	ObjectOwnership: "ObjectWriter",
}

var LoggingBucketBucketEncryptionServerSideEncryptionConfiguration1 = s3.Bucket_ServerSideEncryptionRule{
	ServerSideEncryptionByDefault: &LoggingBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault,
}

var LoggingBucketVersioningConfiguration = s3.Bucket_VersioningConfiguration{
	Status: LoggingBucketVersioning,
}

var LoggingBucketPublicAccessBlockConfiguration = s3.Bucket_PublicAccessBlockConfiguration{
	BlockPublicAcls: true,
	BlockPublicPolicy: true,
	IgnorePublicAcls: true,
	RestrictPublicBuckets: true,
}

var LoggingBucketOwnershipControls = s3.Bucket_OwnershipControls{
	Rules: []any{LoggingBucketOwnershipControlsRule1},
}

var LoggingBucketBucketEncryption = s3.Bucket_BucketEncryption{
	ServerSideEncryptionConfiguration: []any{LoggingBucketBucketEncryptionServerSideEncryptionConfiguration1},
}

var LoggingBucket = s3.Bucket{
	AccessControl: "LogDeliveryWrite",
	BucketEncryption: &LoggingBucketBucketEncryption,
	BucketName: Sub{String: "${AppName}-logging-${Environment}-${AWS::AccountId}-${AWS::Region}"},
	OwnershipControls: &LoggingBucketOwnershipControls,
	PublicAccessBlockConfiguration: &LoggingBucketPublicAccessBlockConfiguration,
	VersioningConfiguration: &LoggingBucketVersioningConfiguration,
}
