// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package apprunner

// AutoScalingConfigurationStatus represents valid values for AutoScalingConfigurationStatus.
type AutoScalingConfigurationStatus string

const (
	AutoScalingConfigurationStatusActive   AutoScalingConfigurationStatus = "ACTIVE"
	AutoScalingConfigurationStatusInactive AutoScalingConfigurationStatus = "INACTIVE"
)

// CertificateValidationRecordStatus represents valid values for CertificateValidationRecordStatus.
type CertificateValidationRecordStatus string

const (
	CertificateValidationRecordStatusPendingValidation CertificateValidationRecordStatus = "PENDING_VALIDATION"
	CertificateValidationRecordStatusSuccess           CertificateValidationRecordStatus = "SUCCESS"
	CertificateValidationRecordStatusFailed            CertificateValidationRecordStatus = "FAILED"
)

// ConfigurationSource represents valid values for ConfigurationSource.
type ConfigurationSource string

const (
	ConfigurationSourceRepository ConfigurationSource = "REPOSITORY"
	ConfigurationSourceApi        ConfigurationSource = "API"
)

// ConnectionStatus represents valid values for ConnectionStatus.
type ConnectionStatus string

const (
	ConnectionStatusPendingHandshake ConnectionStatus = "PENDING_HANDSHAKE"
	ConnectionStatusAvailable        ConnectionStatus = "AVAILABLE"
	ConnectionStatusError            ConnectionStatus = "ERROR"
	ConnectionStatusDeleted          ConnectionStatus = "DELETED"
)

// CustomDomainAssociationStatus represents valid values for CustomDomainAssociationStatus.
type CustomDomainAssociationStatus string

const (
	CustomDomainAssociationStatusCreating                        CustomDomainAssociationStatus = "CREATING"
	CustomDomainAssociationStatusCreateFailed                    CustomDomainAssociationStatus = "CREATE_FAILED"
	CustomDomainAssociationStatusActive                          CustomDomainAssociationStatus = "ACTIVE"
	CustomDomainAssociationStatusDeleting                        CustomDomainAssociationStatus = "DELETING"
	CustomDomainAssociationStatusDeleteFailed                    CustomDomainAssociationStatus = "DELETE_FAILED"
	CustomDomainAssociationStatusPendingCertificateDnsValidation CustomDomainAssociationStatus = "PENDING_CERTIFICATE_DNS_VALIDATION"
	CustomDomainAssociationStatusBindingCertificate              CustomDomainAssociationStatus = "BINDING_CERTIFICATE"
)

// EgressType represents valid values for EgressType.
type EgressType string

const (
	EgressTypeDefault EgressType = "DEFAULT"
	EgressTypeVpc     EgressType = "VPC"
)

// HealthCheckProtocol represents valid values for HealthCheckProtocol.
type HealthCheckProtocol string

const (
	HealthCheckProtocolTcp  HealthCheckProtocol = "TCP"
	HealthCheckProtocolHttp HealthCheckProtocol = "HTTP"
)

// ImageRepositoryType represents valid values for ImageRepositoryType.
type ImageRepositoryType string

const (
	ImageRepositoryTypeEcr       ImageRepositoryType = "ECR"
	ImageRepositoryTypeEcrPublic ImageRepositoryType = "ECR_PUBLIC"
)

// IpAddressType represents valid values for IpAddressType.
type IpAddressType string

const (
	IpAddressTypeIpv4      IpAddressType = "IPV4"
	IpAddressTypeDualStack IpAddressType = "DUAL_STACK"
)

// ObservabilityConfigurationStatus represents valid values for ObservabilityConfigurationStatus.
type ObservabilityConfigurationStatus string

const (
	ObservabilityConfigurationStatusActive   ObservabilityConfigurationStatus = "ACTIVE"
	ObservabilityConfigurationStatusInactive ObservabilityConfigurationStatus = "INACTIVE"
)

// OperationStatus represents valid values for OperationStatus.
type OperationStatus string

const (
	OperationStatusPending            OperationStatus = "PENDING"
	OperationStatusInProgress         OperationStatus = "IN_PROGRESS"
	OperationStatusFailed             OperationStatus = "FAILED"
	OperationStatusSucceeded          OperationStatus = "SUCCEEDED"
	OperationStatusRollbackInProgress OperationStatus = "ROLLBACK_IN_PROGRESS"
	OperationStatusRollbackFailed     OperationStatus = "ROLLBACK_FAILED"
	OperationStatusRollbackSucceeded  OperationStatus = "ROLLBACK_SUCCEEDED"
)

// OperationType represents valid values for OperationType.
type OperationType string

const (
	OperationTypeStartDeployment OperationType = "START_DEPLOYMENT"
	OperationTypeCreateService   OperationType = "CREATE_SERVICE"
	OperationTypePauseService    OperationType = "PAUSE_SERVICE"
	OperationTypeResumeService   OperationType = "RESUME_SERVICE"
	OperationTypeDeleteService   OperationType = "DELETE_SERVICE"
	OperationTypeUpdateService   OperationType = "UPDATE_SERVICE"
)

// ProviderType represents valid values for ProviderType.
type ProviderType string

const (
	ProviderTypeGithub    ProviderType = "GITHUB"
	ProviderTypeBitbucket ProviderType = "BITBUCKET"
)

// Runtime represents valid values for Runtime.
type Runtime string

const (
	RuntimePython3    Runtime = "PYTHON_3"
	RuntimeNodejs12   Runtime = "NODEJS_12"
	RuntimeNodejs14   Runtime = "NODEJS_14"
	RuntimeCorretto8  Runtime = "CORRETTO_8"
	RuntimeCorretto11 Runtime = "CORRETTO_11"
	RuntimeNodejs16   Runtime = "NODEJS_16"
	RuntimeGo1        Runtime = "GO_1"
	RuntimeDotnet6    Runtime = "DOTNET_6"
	RuntimePhp81      Runtime = "PHP_81"
	RuntimeRuby31     Runtime = "RUBY_31"
	RuntimePython311  Runtime = "PYTHON_311"
	RuntimeNodejs18   Runtime = "NODEJS_18"
	RuntimeNodejs22   Runtime = "NODEJS_22"
)

// ServiceStatus represents valid values for ServiceStatus.
type ServiceStatus string

const (
	ServiceStatusCreateFailed        ServiceStatus = "CREATE_FAILED"
	ServiceStatusRunning             ServiceStatus = "RUNNING"
	ServiceStatusDeleted             ServiceStatus = "DELETED"
	ServiceStatusDeleteFailed        ServiceStatus = "DELETE_FAILED"
	ServiceStatusPaused              ServiceStatus = "PAUSED"
	ServiceStatusOperationInProgress ServiceStatus = "OPERATION_IN_PROGRESS"
)

// SourceCodeVersionType represents valid values for SourceCodeVersionType.
type SourceCodeVersionType string

const (
	SourceCodeVersionTypeBranch SourceCodeVersionType = "BRANCH"
)

// TracingVendor represents valid values for TracingVendor.
type TracingVendor string

const (
	TracingVendorAwsxray TracingVendor = "AWSXRAY"
)

// VpcConnectorStatus represents valid values for VpcConnectorStatus.
type VpcConnectorStatus string

const (
	VpcConnectorStatusActive   VpcConnectorStatus = "ACTIVE"
	VpcConnectorStatusInactive VpcConnectorStatus = "INACTIVE"
)

// VpcIngressConnectionStatus represents valid values for VpcIngressConnectionStatus.
type VpcIngressConnectionStatus string

const (
	VpcIngressConnectionStatusAvailable       VpcIngressConnectionStatus = "AVAILABLE"
	VpcIngressConnectionStatusPendingCreation VpcIngressConnectionStatus = "PENDING_CREATION"
	VpcIngressConnectionStatusPendingUpdate   VpcIngressConnectionStatus = "PENDING_UPDATE"
	VpcIngressConnectionStatusPendingDeletion VpcIngressConnectionStatus = "PENDING_DELETION"
	VpcIngressConnectionStatusFailedCreation  VpcIngressConnectionStatus = "FAILED_CREATION"
	VpcIngressConnectionStatusFailedUpdate    VpcIngressConnectionStatus = "FAILED_UPDATE"
	VpcIngressConnectionStatusFailedDeletion  VpcIngressConnectionStatus = "FAILED_DELETION"
	VpcIngressConnectionStatusDeleted         VpcIngressConnectionStatus = "DELETED"
)
