// Package emrclustergangliawithsparkors3backedhbase contains CloudFormation resources.
// Security resources: IAM, Cognito, KMS, etc.
//
// Generated by wetwire-aws import.
package emrclustergangliawithsparkors3backedhbase

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/iam"
)

var EMRClusterServiceRoleAssumeRolePolicyDocument = PolicyDocument{
	Statement: []any{EMRClusterServiceRoleAssumeRolePolicyDocumentStatement0},
	Version: "2012-10-17",
}

var EMRClusterServiceRoleAssumeRolePolicyDocumentStatement0 = PolicyStatement{
	Action: []any{"sts:AssumeRole"},
	Effect: "Allow",
	Principal: ServicePrincipal{"elasticmapreduce.amazonaws.com"},
}

var EMRClusterServiceRole = iam.Role{
	AssumeRolePolicyDocument: EMRClusterServiceRoleAssumeRolePolicyDocument,
	ManagedPolicyArns: []any{"arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole"},
	Path: "/",
}

var EMRClusterinstanceProfileRoleAssumeRolePolicyDocument = PolicyDocument{
	Statement: []any{EMRClusterinstanceProfileRoleAssumeRolePolicyDocumentStatement0},
	Version: "2012-10-17",
}

var EMRClusterinstanceProfileRoleAssumeRolePolicyDocumentStatement0 = PolicyStatement{
	Action: []any{"sts:AssumeRole"},
	Effect: "Allow",
	Principal: ServicePrincipal{"ec2.amazonaws.com"},
}

var EMRClusterinstanceProfileRole = iam.Role{
	AssumeRolePolicyDocument: EMRClusterinstanceProfileRoleAssumeRolePolicyDocument,
	ManagedPolicyArns: []any{"arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role"},
	Path: "/",
}

var EMRClusterinstanceProfile = iam.InstanceProfile{
	Path: "/",
	Roles: []any{EMRClusterinstanceProfileRole},
}
