// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package route53recoveryreadiness

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Cell represents AWS::Route53RecoveryReadiness::Cell.

type Cell struct {
	// Attributes for Fn::GetAtt
	CellArn               wetwire.AttrRef `json:"-"`
	ParentReadinessScopes wetwire.AttrRef `json:"-"`

	// Properties
	CellName any   `json:"CellName,omitempty"`
	Cells    []any `json:"Cells,omitempty"`
	Tags     []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Cell) ResourceType() string {
	return "AWS::Route53RecoveryReadiness::Cell"
}
