// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package datazone

// Environment_EnvironmentParameter represents AWS::DataZone::Environment.EnvironmentParameter.
type Environment_EnvironmentParameter struct {
	Name  any `json:"Name,omitempty"`
	Value any `json:"Value,omitempty"`
}
