// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package datazone

// FormType_Model represents AWS::DataZone::FormType.Model.
type FormType_Model struct {
	Smithy any `json:"Smithy,omitempty"`
}
