// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package datazone

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Owner represents AWS::DataZone::Owner.

type Owner struct {
	// Attributes for Fn::GetAtt
	OwnerIdentifier wetwire.AttrRef `json:"-"`
	OwnerType       wetwire.AttrRef `json:"-"`

	// Properties
	DomainIdentifier any                   `json:"DomainIdentifier,omitempty"`
	EntityIdentifier any                   `json:"EntityIdentifier,omitempty"`
	EntityType       any                   `json:"EntityType,omitempty"`
	Owner            Owner_OwnerProperties `json:"Owner,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Owner) ResourceType() string {
	return "AWS::DataZone::Owner"
}
