// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package quicksight

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// CustomPermissions represents AWS::QuickSight::CustomPermissions.

type CustomPermissions struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	AwsAccountId          any   `json:"AwsAccountId,omitempty"`
	Capabilities          any   `json:"Capabilities,omitempty"`
	CustomPermissionsName any   `json:"CustomPermissionsName,omitempty"`
	Tags                  []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r CustomPermissions) ResourceType() string {
	return "AWS::QuickSight::CustomPermissions"
}
