// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package quicksight

// Theme_BorderStyle represents AWS::QuickSight::Theme.BorderStyle.
type Theme_BorderStyle struct {
	Show any `json:"Show,omitempty"`
}

// Theme_DataColorPalette represents AWS::QuickSight::Theme.DataColorPalette.
type Theme_DataColorPalette struct {
	Colors         []any `json:"Colors,omitempty"`
	EmptyFillColor any   `json:"EmptyFillColor,omitempty"`
	MinMaxGradient []any `json:"MinMaxGradient,omitempty"`
}

// Theme_Font represents AWS::QuickSight::Theme.Font.
type Theme_Font struct {
	FontFamily any `json:"FontFamily,omitempty"`
}

// Theme_GutterStyle represents AWS::QuickSight::Theme.GutterStyle.
type Theme_GutterStyle struct {
	Show any `json:"Show,omitempty"`
}

// Theme_MarginStyle represents AWS::QuickSight::Theme.MarginStyle.
type Theme_MarginStyle struct {
	Show any `json:"Show,omitempty"`
}

// Theme_ResourcePermission represents AWS::QuickSight::Theme.ResourcePermission.
type Theme_ResourcePermission struct {
	Actions   []any `json:"Actions,omitempty"`
	Principal any   `json:"Principal,omitempty"`
}

// Theme_SheetStyle represents AWS::QuickSight::Theme.SheetStyle.
type Theme_SheetStyle struct {
	Tile       any `json:"Tile,omitempty"`
	TileLayout any `json:"TileLayout,omitempty"`
}

// Theme_ThemeConfiguration represents AWS::QuickSight::Theme.ThemeConfiguration.
type Theme_ThemeConfiguration struct {
	DataColorPalette any `json:"DataColorPalette,omitempty"`
	Sheet            any `json:"Sheet,omitempty"`
	Typography       any `json:"Typography,omitempty"`
	UIColorPalette   any `json:"UIColorPalette,omitempty"`
}

// Theme_ThemeError represents AWS::QuickSight::Theme.ThemeError.
type Theme_ThemeError struct {
	Message any `json:"Message,omitempty"`
	Type_   any `json:"Type,omitempty"`
}

// Theme_ThemeVersion represents AWS::QuickSight::Theme.ThemeVersion.
type Theme_ThemeVersion struct {
	Arn           any   `json:"Arn,omitempty"`
	BaseThemeId   any   `json:"BaseThemeId,omitempty"`
	Configuration any   `json:"Configuration,omitempty"`
	CreatedTime   any   `json:"CreatedTime,omitempty"`
	Description   any   `json:"Description,omitempty"`
	Errors        []any `json:"Errors,omitempty"`
	Status        any   `json:"Status,omitempty"`
	VersionNumber any   `json:"VersionNumber,omitempty"`
}

// Theme_TileLayoutStyle represents AWS::QuickSight::Theme.TileLayoutStyle.
type Theme_TileLayoutStyle struct {
	Gutter any `json:"Gutter,omitempty"`
	Margin any `json:"Margin,omitempty"`
}

// Theme_TileStyle represents AWS::QuickSight::Theme.TileStyle.
type Theme_TileStyle struct {
	Border any `json:"Border,omitempty"`
}

// Theme_Typography represents AWS::QuickSight::Theme.Typography.
type Theme_Typography struct {
	FontFamilies []any `json:"FontFamilies,omitempty"`
}

// Theme_UIColorPalette represents AWS::QuickSight::Theme.UIColorPalette.
type Theme_UIColorPalette struct {
	Accent              any `json:"Accent,omitempty"`
	AccentForeground    any `json:"AccentForeground,omitempty"`
	Danger              any `json:"Danger,omitempty"`
	DangerForeground    any `json:"DangerForeground,omitempty"`
	Dimension           any `json:"Dimension,omitempty"`
	DimensionForeground any `json:"DimensionForeground,omitempty"`
	Measure             any `json:"Measure,omitempty"`
	MeasureForeground   any `json:"MeasureForeground,omitempty"`
	PrimaryBackground   any `json:"PrimaryBackground,omitempty"`
	PrimaryForeground   any `json:"PrimaryForeground,omitempty"`
	SecondaryBackground any `json:"SecondaryBackground,omitempty"`
	SecondaryForeground any `json:"SecondaryForeground,omitempty"`
	Success             any `json:"Success,omitempty"`
	SuccessForeground   any `json:"SuccessForeground,omitempty"`
	Warning             any `json:"Warning,omitempty"`
	WarningForeground   any `json:"WarningForeground,omitempty"`
}
