// Package ec2_domain_join contains CloudFormation resources.
// Network resources: VPC, Subnets, Load Balancers, CloudFront, etc.
//
// Generated by wetwire-aws import.
package ec2_domain_join

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/ec2"
)

var InstanceSecurityGroupSecurityGroupIngressPort3389 = ec2.SecurityGroup_Ingress{
	CidrIp: "0.0.0.0/0",
	FromPort: "3389",
	IpProtocol: "tcp",
	ToPort: "3389",
}

var InstanceSecurityGroup = ec2.SecurityGroup{
	GroupDescription: "Allow http to client host",
	SecurityGroupIngress: List(InstanceSecurityGroupSecurityGroupIngressPort3389),
	VpcId: VPC,
}
