// Package vpcpeering_accepter_tag_cfn contains CloudFormation resources.
// Main resources
//
// Generated by wetwire-aws import.
package vpcpeering_accepter_tag_cfn

// TagVpcPeeringConnectionsResource is a placeholder for unknown resource type: Custom::TagVpcPeeringConnection
// This allows references from outputs and other resources to compile.
var TagVpcPeeringConnectionsResource any = nil
