// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package customerprofiles

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Domain represents AWS::CustomerProfiles::Domain.

type Domain struct {
	// Attributes for Fn::GetAtt
	CreatedAt                              wetwire.AttrRef `json:"-"`
	DataStore_Readiness                    wetwire.AttrRef `json:"-"`
	DataStore_Readiness_Message            wetwire.AttrRef `json:"-"`
	DataStore_Readiness_ProgressPercentage wetwire.AttrRef `json:"-"`
	LastUpdatedAt                          wetwire.AttrRef `json:"-"`
	RuleBasedMatching_Status               wetwire.AttrRef `json:"-"`
	Stats                                  wetwire.AttrRef `json:"-"`
	Stats_MeteringProfileCount             wetwire.AttrRef `json:"-"`
	Stats_ObjectCount                      wetwire.AttrRef `json:"-"`
	Stats_ProfileCount                     wetwire.AttrRef `json:"-"`
	Stats_TotalSize                        wetwire.AttrRef `json:"-"`

	// Properties
	DataStore             any   `json:"DataStore,omitempty"`
	DeadLetterQueueUrl    any   `json:"DeadLetterQueueUrl,omitempty"`
	DefaultEncryptionKey  any   `json:"DefaultEncryptionKey,omitempty"`
	DefaultExpirationDays any   `json:"DefaultExpirationDays,omitempty"`
	DomainName            any   `json:"DomainName,omitempty"`
	Matching              any   `json:"Matching,omitempty"`
	RuleBasedMatching     any   `json:"RuleBasedMatching,omitempty"`
	Tags                  []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Domain) ResourceType() string {
	return "AWS::CustomerProfiles::Domain"
}
