// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package customerprofiles

// Domain_AttributeTypesSelector represents AWS::CustomerProfiles::Domain.AttributeTypesSelector.
type Domain_AttributeTypesSelector struct {
	Address                []any `json:"Address,omitempty"`
	AttributeMatchingModel any   `json:"AttributeMatchingModel,omitempty"`
	EmailAddress           []any `json:"EmailAddress,omitempty"`
	PhoneNumber            []any `json:"PhoneNumber,omitempty"`
}

// Domain_AutoMerging represents AWS::CustomerProfiles::Domain.AutoMerging.
type Domain_AutoMerging struct {
	ConflictResolution                  *Domain_ConflictResolution `json:"ConflictResolution,omitempty"`
	Consolidation                       *Domain_Consolidation      `json:"Consolidation,omitempty"`
	Enabled                             any                        `json:"Enabled,omitempty"`
	MinAllowedConfidenceScoreForMerging any                        `json:"MinAllowedConfidenceScoreForMerging,omitempty"`
}

// Domain_ConflictResolution represents AWS::CustomerProfiles::Domain.ConflictResolution.
type Domain_ConflictResolution struct {
	ConflictResolvingModel any `json:"ConflictResolvingModel,omitempty"`
	SourceName             any `json:"SourceName,omitempty"`
}

// Domain_Consolidation represents AWS::CustomerProfiles::Domain.Consolidation.
type Domain_Consolidation struct {
	MatchingAttributesList any `json:"MatchingAttributesList,omitempty"`
}

// Domain_DataStore represents AWS::CustomerProfiles::Domain.DataStore.
type Domain_DataStore struct {
	Enabled   any                                      `json:"Enabled,omitempty"`
	Readiness *CalculatedAttributeDefinition_Readiness `json:"Readiness,omitempty"`
}

// Domain_DomainStats represents AWS::CustomerProfiles::Domain.DomainStats.
type Domain_DomainStats struct {
	MeteringProfileCount any `json:"MeteringProfileCount,omitempty"`
	ObjectCount          any `json:"ObjectCount,omitempty"`
	ProfileCount         any `json:"ProfileCount,omitempty"`
	TotalSize            any `json:"TotalSize,omitempty"`
}

// Domain_ExportingConfig represents AWS::CustomerProfiles::Domain.ExportingConfig.
type Domain_ExportingConfig struct {
	S3Exporting *Domain_S3ExportingConfig `json:"S3Exporting,omitempty"`
}

// Domain_JobSchedule represents AWS::CustomerProfiles::Domain.JobSchedule.
type Domain_JobSchedule struct {
	DayOfTheWeek any `json:"DayOfTheWeek,omitempty"`
	Time         any `json:"Time,omitempty"`
}

// Domain_Matching represents AWS::CustomerProfiles::Domain.Matching.
type Domain_Matching struct {
	AutoMerging     *Domain_AutoMerging     `json:"AutoMerging,omitempty"`
	Enabled         any                     `json:"Enabled,omitempty"`
	ExportingConfig *Domain_ExportingConfig `json:"ExportingConfig,omitempty"`
	JobSchedule     *Domain_JobSchedule     `json:"JobSchedule,omitempty"`
}

// Domain_MatchingRule represents AWS::CustomerProfiles::Domain.MatchingRule.
type Domain_MatchingRule struct {
	Rule []any `json:"Rule,omitempty"`
}

// Domain_Readiness represents AWS::CustomerProfiles::Domain.Readiness.
type Domain_Readiness struct {
	Message            any `json:"Message,omitempty"`
	ProgressPercentage any `json:"ProgressPercentage,omitempty"`
}

// Domain_RuleBasedMatching represents AWS::CustomerProfiles::Domain.RuleBasedMatching.
type Domain_RuleBasedMatching struct {
	AttributeTypesSelector         *Domain_AttributeTypesSelector `json:"AttributeTypesSelector,omitempty"`
	ConflictResolution             *Domain_ConflictResolution     `json:"ConflictResolution,omitempty"`
	Enabled                        any                            `json:"Enabled,omitempty"`
	ExportingConfig                *Domain_ExportingConfig        `json:"ExportingConfig,omitempty"`
	MatchingRules                  []Domain_MatchingRule          `json:"MatchingRules,omitempty"`
	MaxAllowedRuleLevelForMatching any                            `json:"MaxAllowedRuleLevelForMatching,omitempty"`
	MaxAllowedRuleLevelForMerging  any                            `json:"MaxAllowedRuleLevelForMerging,omitempty"`
	Status                         any                            `json:"Status,omitempty"`
}

// Domain_S3ExportingConfig represents AWS::CustomerProfiles::Domain.S3ExportingConfig.
type Domain_S3ExportingConfig struct {
	S3BucketName any `json:"S3BucketName,omitempty"`
	S3KeyName    any `json:"S3KeyName,omitempty"`
}
