// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package secretsmanager

// RotationSchedule_ExternalSecretRotationMetadataItem represents AWS::SecretsManager::RotationSchedule.ExternalSecretRotationMetadataItem.
type RotationSchedule_ExternalSecretRotationMetadataItem struct {
	Key   any `json:"Key,omitempty"`
	Value any `json:"Value,omitempty"`
}

// RotationSchedule_HostedRotationLambda represents AWS::SecretsManager::RotationSchedule.HostedRotationLambda.
type RotationSchedule_HostedRotationLambda struct {
	ExcludeCharacters        any `json:"ExcludeCharacters,omitempty"`
	KmsKeyArn                any `json:"KmsKeyArn,omitempty"`
	MasterSecretArn          any `json:"MasterSecretArn,omitempty"`
	MasterSecretKmsKeyArn    any `json:"MasterSecretKmsKeyArn,omitempty"`
	RotationLambdaName       any `json:"RotationLambdaName,omitempty"`
	RotationType             any `json:"RotationType,omitempty"`
	Runtime                  any `json:"Runtime,omitempty"`
	SuperuserSecretArn       any `json:"SuperuserSecretArn,omitempty"`
	SuperuserSecretKmsKeyArn any `json:"SuperuserSecretKmsKeyArn,omitempty"`
	VpcSecurityGroupIds      any `json:"VpcSecurityGroupIds,omitempty"`
	VpcSubnetIds             any `json:"VpcSubnetIds,omitempty"`
}

// RotationSchedule_RotationRules represents AWS::SecretsManager::RotationSchedule.RotationRules.
type RotationSchedule_RotationRules struct {
	AutomaticallyAfterDays any `json:"AutomaticallyAfterDays,omitempty"`
	Duration               any `json:"Duration,omitempty"`
	ScheduleExpression     any `json:"ScheduleExpression,omitempty"`
}
