// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package cloudwatch

// AnomalyDetector represents AWS::CloudWatch::AnomalyDetector.

type AnomalyDetector struct {

	// Properties
	Configuration               any   `json:"Configuration,omitempty"`
	Dimensions                  []any `json:"Dimensions,omitempty"`
	MetricCharacteristics       any   `json:"MetricCharacteristics,omitempty"`
	MetricMathAnomalyDetector   any   `json:"MetricMathAnomalyDetector,omitempty"`
	MetricName                  any   `json:"MetricName,omitempty"`
	Namespace                   any   `json:"Namespace,omitempty"`
	SingleMetricAnomalyDetector any   `json:"SingleMetricAnomalyDetector,omitempty"`
	Stat                        any   `json:"Stat,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r AnomalyDetector) ResourceType() string {
	return "AWS::CloudWatch::AnomalyDetector"
}
