// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cloudwatch

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// MetricStream represents AWS::CloudWatch::MetricStream.

type MetricStream struct {
	// Attributes for Fn::GetAtt
	Arn            wetwire.AttrRef `json:"-"`
	CreationDate   wetwire.AttrRef `json:"-"`
	LastUpdateDate wetwire.AttrRef `json:"-"`
	State          wetwire.AttrRef `json:"-"`

	// Properties
	ExcludeFilters               []MetricStream_MetricStreamFilter                  `json:"ExcludeFilters,omitempty"`
	FirehoseArn                  any                                                `json:"FirehoseArn,omitempty"`
	IncludeFilters               []MetricStream_MetricStreamFilter                  `json:"IncludeFilters,omitempty"`
	IncludeLinkedAccountsMetrics any                                                `json:"IncludeLinkedAccountsMetrics,omitempty"`
	Name                         any                                                `json:"Name,omitempty"`
	OutputFormat                 any                                                `json:"OutputFormat,omitempty"`
	RoleArn                      any                                                `json:"RoleArn,omitempty"`
	StatisticsConfigurations     []MetricStream_MetricStreamStatisticsConfiguration `json:"StatisticsConfigurations,omitempty"`
	Tags                         []any                                              `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r MetricStream) ResourceType() string {
	return "AWS::CloudWatch::MetricStream"
}
