// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package emr

// InstanceFleetConfig_Configuration represents AWS::EMR::InstanceFleetConfig.Configuration.
type InstanceFleetConfig_Configuration struct {
	Classification          any                     `json:"Classification,omitempty"`
	ConfigurationProperties map[string]any          `json:"ConfigurationProperties,omitempty"`
	Configurations          []Cluster_Configuration `json:"Configurations,omitempty"`
}

// InstanceFleetConfig_EbsBlockDeviceConfig represents AWS::EMR::InstanceFleetConfig.EbsBlockDeviceConfig.
type InstanceFleetConfig_EbsBlockDeviceConfig struct {
	VolumeSpecification Cluster_VolumeSpecification `json:"VolumeSpecification,omitempty"`
	VolumesPerInstance  any                         `json:"VolumesPerInstance,omitempty"`
}

// InstanceFleetConfig_EbsConfiguration represents AWS::EMR::InstanceFleetConfig.EbsConfiguration.
type InstanceFleetConfig_EbsConfiguration struct {
	EbsBlockDeviceConfigs []Cluster_EbsBlockDeviceConfig `json:"EbsBlockDeviceConfigs,omitempty"`
	EbsOptimized          any                            `json:"EbsOptimized,omitempty"`
}

// InstanceFleetConfig_InstanceFleetProvisioningSpecifications represents AWS::EMR::InstanceFleetConfig.InstanceFleetProvisioningSpecifications.
type InstanceFleetConfig_InstanceFleetProvisioningSpecifications struct {
	OnDemandSpecification *Cluster_OnDemandProvisioningSpecification `json:"OnDemandSpecification,omitempty"`
	SpotSpecification     *Cluster_SpotProvisioningSpecification     `json:"SpotSpecification,omitempty"`
}

// InstanceFleetConfig_InstanceFleetResizingSpecifications represents AWS::EMR::InstanceFleetConfig.InstanceFleetResizingSpecifications.
type InstanceFleetConfig_InstanceFleetResizingSpecifications struct {
	OnDemandResizeSpecification *Cluster_OnDemandResizingSpecification `json:"OnDemandResizeSpecification,omitempty"`
	SpotResizeSpecification     *Cluster_SpotResizingSpecification     `json:"SpotResizeSpecification,omitempty"`
}

// InstanceFleetConfig_InstanceTypeConfig represents AWS::EMR::InstanceFleetConfig.InstanceTypeConfig.
type InstanceFleetConfig_InstanceTypeConfig struct {
	BidPrice                            any                       `json:"BidPrice,omitempty"`
	BidPriceAsPercentageOfOnDemandPrice any                       `json:"BidPriceAsPercentageOfOnDemandPrice,omitempty"`
	Configurations                      []Cluster_Configuration   `json:"Configurations,omitempty"`
	CustomAmiId                         any                       `json:"CustomAmiId,omitempty"`
	EbsConfiguration                    *Cluster_EbsConfiguration `json:"EbsConfiguration,omitempty"`
	InstanceType                        any                       `json:"InstanceType,omitempty"`
	Priority                            any                       `json:"Priority,omitempty"`
	WeightedCapacity                    any                       `json:"WeightedCapacity,omitempty"`
}

// InstanceFleetConfig_OnDemandCapacityReservationOptions represents AWS::EMR::InstanceFleetConfig.OnDemandCapacityReservationOptions.
type InstanceFleetConfig_OnDemandCapacityReservationOptions struct {
	CapacityReservationPreference       any `json:"CapacityReservationPreference,omitempty"`
	CapacityReservationResourceGroupArn any `json:"CapacityReservationResourceGroupArn,omitempty"`
	UsageStrategy                       any `json:"UsageStrategy,omitempty"`
}

// InstanceFleetConfig_OnDemandProvisioningSpecification represents AWS::EMR::InstanceFleetConfig.OnDemandProvisioningSpecification.
type InstanceFleetConfig_OnDemandProvisioningSpecification struct {
	AllocationStrategy         any                                         `json:"AllocationStrategy,omitempty"`
	CapacityReservationOptions *Cluster_OnDemandCapacityReservationOptions `json:"CapacityReservationOptions,omitempty"`
}

// InstanceFleetConfig_OnDemandResizingSpecification represents AWS::EMR::InstanceFleetConfig.OnDemandResizingSpecification.
type InstanceFleetConfig_OnDemandResizingSpecification struct {
	AllocationStrategy         any                                         `json:"AllocationStrategy,omitempty"`
	CapacityReservationOptions *Cluster_OnDemandCapacityReservationOptions `json:"CapacityReservationOptions,omitempty"`
	TimeoutDurationMinutes     any                                         `json:"TimeoutDurationMinutes,omitempty"`
}

// InstanceFleetConfig_SpotProvisioningSpecification represents AWS::EMR::InstanceFleetConfig.SpotProvisioningSpecification.
type InstanceFleetConfig_SpotProvisioningSpecification struct {
	AllocationStrategy     any `json:"AllocationStrategy,omitempty"`
	BlockDurationMinutes   any `json:"BlockDurationMinutes,omitempty"`
	TimeoutAction          any `json:"TimeoutAction,omitempty"`
	TimeoutDurationMinutes any `json:"TimeoutDurationMinutes,omitempty"`
}

// InstanceFleetConfig_SpotResizingSpecification represents AWS::EMR::InstanceFleetConfig.SpotResizingSpecification.
type InstanceFleetConfig_SpotResizingSpecification struct {
	AllocationStrategy     any `json:"AllocationStrategy,omitempty"`
	TimeoutDurationMinutes any `json:"TimeoutDurationMinutes,omitempty"`
}

// InstanceFleetConfig_VolumeSpecification represents AWS::EMR::InstanceFleetConfig.VolumeSpecification.
type InstanceFleetConfig_VolumeSpecification struct {
	Iops       any `json:"Iops,omitempty"`
	SizeInGB   any `json:"SizeInGB,omitempty"`
	Throughput any `json:"Throughput,omitempty"`
	VolumeType any `json:"VolumeType,omitempty"`
}
