// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package emr

// InstanceGroupConfig represents AWS::EMR::InstanceGroupConfig.

type InstanceGroupConfig struct {

	// Properties
	AutoScalingPolicy *InstanceGroupConfig_AutoScalingPolicy `json:"AutoScalingPolicy,omitempty"`
	BidPrice          any                                    `json:"BidPrice,omitempty"`
	Configurations    []any                                  `json:"Configurations,omitempty"`
	CustomAmiId       any                                    `json:"CustomAmiId,omitempty"`
	EbsConfiguration  *InstanceGroupConfig_EbsConfiguration  `json:"EbsConfiguration,omitempty"`
	InstanceCount     any                                    `json:"InstanceCount,omitempty"`
	InstanceRole      any                                    `json:"InstanceRole,omitempty"`
	InstanceType      any                                    `json:"InstanceType,omitempty"`
	JobFlowId         any                                    `json:"JobFlowId,omitempty"`
	Market            any                                    `json:"Market,omitempty"`
	Name              any                                    `json:"Name,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r InstanceGroupConfig) ResourceType() string {
	return "AWS::EMR::InstanceGroupConfig"
}
