// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package emr

// WALWorkspace represents AWS::EMR::WALWorkspace.

type WALWorkspace struct {

	// Properties
	Tags             []any `json:"Tags,omitempty"`
	WALWorkspaceName any   `json:"WALWorkspaceName,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r WALWorkspace) ResourceType() string {
	return "AWS::EMR::WALWorkspace"
}
