// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package stepfunctions

// EncryptionType represents valid values for EncryptionType.
type EncryptionType string

const (
	EncryptionTypeAwsOwnedKey           EncryptionType = "AWS_OWNED_KEY"
	EncryptionTypeCustomerManagedKmsKey EncryptionType = "CUSTOMER_MANAGED_KMS_KEY"
)

// ExecutionRedriveFilter represents valid values for ExecutionRedriveFilter.
type ExecutionRedriveFilter string

const (
	ExecutionRedriveFilterRedriven    ExecutionRedriveFilter = "REDRIVEN"
	ExecutionRedriveFilterNotRedriven ExecutionRedriveFilter = "NOT_REDRIVEN"
)

// ExecutionRedriveStatus represents valid values for ExecutionRedriveStatus.
type ExecutionRedriveStatus string

const (
	ExecutionRedriveStatusRedrivable         ExecutionRedriveStatus = "REDRIVABLE"
	ExecutionRedriveStatusNotRedrivable      ExecutionRedriveStatus = "NOT_REDRIVABLE"
	ExecutionRedriveStatusRedrivableByMapRun ExecutionRedriveStatus = "REDRIVABLE_BY_MAP_RUN"
)

// ExecutionStatus represents valid values for ExecutionStatus.
type ExecutionStatus string

const (
	ExecutionStatusRunning        ExecutionStatus = "RUNNING"
	ExecutionStatusSucceeded      ExecutionStatus = "SUCCEEDED"
	ExecutionStatusFailed         ExecutionStatus = "FAILED"
	ExecutionStatusTimedOut       ExecutionStatus = "TIMED_OUT"
	ExecutionStatusAborted        ExecutionStatus = "ABORTED"
	ExecutionStatusPendingRedrive ExecutionStatus = "PENDING_REDRIVE"
)

// HistoryEventType represents valid values for HistoryEventType.
type HistoryEventType string

const (
	HistoryEventTypeActivityfailed               HistoryEventType = "ActivityFailed"
	HistoryEventTypeActivityscheduled            HistoryEventType = "ActivityScheduled"
	HistoryEventTypeActivityschedulefailed       HistoryEventType = "ActivityScheduleFailed"
	HistoryEventTypeActivitystarted              HistoryEventType = "ActivityStarted"
	HistoryEventTypeActivitysucceeded            HistoryEventType = "ActivitySucceeded"
	HistoryEventTypeActivitytimedout             HistoryEventType = "ActivityTimedOut"
	HistoryEventTypeChoicestateentered           HistoryEventType = "ChoiceStateEntered"
	HistoryEventTypeChoicestateexited            HistoryEventType = "ChoiceStateExited"
	HistoryEventTypeExecutionaborted             HistoryEventType = "ExecutionAborted"
	HistoryEventTypeExecutionfailed              HistoryEventType = "ExecutionFailed"
	HistoryEventTypeExecutionstarted             HistoryEventType = "ExecutionStarted"
	HistoryEventTypeExecutionsucceeded           HistoryEventType = "ExecutionSucceeded"
	HistoryEventTypeExecutiontimedout            HistoryEventType = "ExecutionTimedOut"
	HistoryEventTypeFailstateentered             HistoryEventType = "FailStateEntered"
	HistoryEventTypeLambdafunctionfailed         HistoryEventType = "LambdaFunctionFailed"
	HistoryEventTypeLambdafunctionscheduled      HistoryEventType = "LambdaFunctionScheduled"
	HistoryEventTypeLambdafunctionschedulefailed HistoryEventType = "LambdaFunctionScheduleFailed"
	HistoryEventTypeLambdafunctionstarted        HistoryEventType = "LambdaFunctionStarted"
	HistoryEventTypeLambdafunctionstartfailed    HistoryEventType = "LambdaFunctionStartFailed"
	HistoryEventTypeLambdafunctionsucceeded      HistoryEventType = "LambdaFunctionSucceeded"
	HistoryEventTypeLambdafunctiontimedout       HistoryEventType = "LambdaFunctionTimedOut"
	HistoryEventTypeMapiterationaborted          HistoryEventType = "MapIterationAborted"
	HistoryEventTypeMapiterationfailed           HistoryEventType = "MapIterationFailed"
	HistoryEventTypeMapiterationstarted          HistoryEventType = "MapIterationStarted"
	HistoryEventTypeMapiterationsucceeded        HistoryEventType = "MapIterationSucceeded"
	HistoryEventTypeMapstateaborted              HistoryEventType = "MapStateAborted"
	HistoryEventTypeMapstateentered              HistoryEventType = "MapStateEntered"
	HistoryEventTypeMapstateexited               HistoryEventType = "MapStateExited"
	HistoryEventTypeMapstatefailed               HistoryEventType = "MapStateFailed"
	HistoryEventTypeMapstatestarted              HistoryEventType = "MapStateStarted"
	HistoryEventTypeMapstatesucceeded            HistoryEventType = "MapStateSucceeded"
	HistoryEventTypeParallelstateaborted         HistoryEventType = "ParallelStateAborted"
	HistoryEventTypeParallelstateentered         HistoryEventType = "ParallelStateEntered"
	HistoryEventTypeParallelstateexited          HistoryEventType = "ParallelStateExited"
	HistoryEventTypeParallelstatefailed          HistoryEventType = "ParallelStateFailed"
	HistoryEventTypeParallelstatestarted         HistoryEventType = "ParallelStateStarted"
	HistoryEventTypeParallelstatesucceeded       HistoryEventType = "ParallelStateSucceeded"
	HistoryEventTypePassstateentered             HistoryEventType = "PassStateEntered"
	HistoryEventTypePassstateexited              HistoryEventType = "PassStateExited"
	HistoryEventTypeSucceedstateentered          HistoryEventType = "SucceedStateEntered"
	HistoryEventTypeSucceedstateexited           HistoryEventType = "SucceedStateExited"
	HistoryEventTypeTaskfailed                   HistoryEventType = "TaskFailed"
	HistoryEventTypeTaskscheduled                HistoryEventType = "TaskScheduled"
	HistoryEventTypeTaskstarted                  HistoryEventType = "TaskStarted"
	HistoryEventTypeTaskstartfailed              HistoryEventType = "TaskStartFailed"
	HistoryEventTypeTaskstateaborted             HistoryEventType = "TaskStateAborted"
	HistoryEventTypeTaskstateentered             HistoryEventType = "TaskStateEntered"
	HistoryEventTypeTaskstateexited              HistoryEventType = "TaskStateExited"
	HistoryEventTypeTasksubmitfailed             HistoryEventType = "TaskSubmitFailed"
	HistoryEventTypeTasksubmitted                HistoryEventType = "TaskSubmitted"
	HistoryEventTypeTasksucceeded                HistoryEventType = "TaskSucceeded"
	HistoryEventTypeTasktimedout                 HistoryEventType = "TaskTimedOut"
	HistoryEventTypeWaitstateaborted             HistoryEventType = "WaitStateAborted"
	HistoryEventTypeWaitstateentered             HistoryEventType = "WaitStateEntered"
	HistoryEventTypeWaitstateexited              HistoryEventType = "WaitStateExited"
	HistoryEventTypeMaprunaborted                HistoryEventType = "MapRunAborted"
	HistoryEventTypeMaprunfailed                 HistoryEventType = "MapRunFailed"
	HistoryEventTypeMaprunstarted                HistoryEventType = "MapRunStarted"
	HistoryEventTypeMaprunsucceeded              HistoryEventType = "MapRunSucceeded"
	HistoryEventTypeExecutionredriven            HistoryEventType = "ExecutionRedriven"
	HistoryEventTypeMaprunredriven               HistoryEventType = "MapRunRedriven"
	HistoryEventTypeEvaluationfailed             HistoryEventType = "EvaluationFailed"
)

// IncludedData represents valid values for IncludedData.
type IncludedData string

const (
	IncludedDataAllData      IncludedData = "ALL_DATA"
	IncludedDataMetadataOnly IncludedData = "METADATA_ONLY"
)

// InspectionLevel represents valid values for InspectionLevel.
type InspectionLevel string

const (
	InspectionLevelInfo  InspectionLevel = "INFO"
	InspectionLevelDebug InspectionLevel = "DEBUG"
	InspectionLevelTrace InspectionLevel = "TRACE"
)

// KmsKeyState represents valid values for KmsKeyState.
type KmsKeyState string

const (
	KmsKeyStateDisabled        KmsKeyState = "DISABLED"
	KmsKeyStatePendingDeletion KmsKeyState = "PENDING_DELETION"
	KmsKeyStatePendingImport   KmsKeyState = "PENDING_IMPORT"
	KmsKeyStateUnavailable     KmsKeyState = "UNAVAILABLE"
	KmsKeyStateCreating        KmsKeyState = "CREATING"
)

// LogLevel represents valid values for LogLevel.
type LogLevel string

const (
	LogLevelAll   LogLevel = "ALL"
	LogLevelError LogLevel = "ERROR"
	LogLevelFatal LogLevel = "FATAL"
	LogLevelOff   LogLevel = "OFF"
)

// MapRunStatus represents valid values for MapRunStatus.
type MapRunStatus string

const (
	MapRunStatusRunning   MapRunStatus = "RUNNING"
	MapRunStatusSucceeded MapRunStatus = "SUCCEEDED"
	MapRunStatusFailed    MapRunStatus = "FAILED"
	MapRunStatusAborted   MapRunStatus = "ABORTED"
)

// MockResponseValidationMode represents valid values for MockResponseValidationMode.
type MockResponseValidationMode string

const (
	MockResponseValidationModeStrict  MockResponseValidationMode = "STRICT"
	MockResponseValidationModePresent MockResponseValidationMode = "PRESENT"
	MockResponseValidationModeNone    MockResponseValidationMode = "NONE"
)

// StateMachineStatus represents valid values for StateMachineStatus.
type StateMachineStatus string

const (
	StateMachineStatusActive   StateMachineStatus = "ACTIVE"
	StateMachineStatusDeleting StateMachineStatus = "DELETING"
)

// StateMachineType represents valid values for StateMachineType.
type StateMachineType string

const (
	StateMachineTypeStandard StateMachineType = "STANDARD"
	StateMachineTypeExpress  StateMachineType = "EXPRESS"
)

// SyncExecutionStatus represents valid values for SyncExecutionStatus.
type SyncExecutionStatus string

const (
	SyncExecutionStatusSucceeded SyncExecutionStatus = "SUCCEEDED"
	SyncExecutionStatusFailed    SyncExecutionStatus = "FAILED"
	SyncExecutionStatusTimedOut  SyncExecutionStatus = "TIMED_OUT"
)

// TestExecutionStatus represents valid values for TestExecutionStatus.
type TestExecutionStatus string

const (
	TestExecutionStatusSucceeded   TestExecutionStatus = "SUCCEEDED"
	TestExecutionStatusFailed      TestExecutionStatus = "FAILED"
	TestExecutionStatusRetriable   TestExecutionStatus = "RETRIABLE"
	TestExecutionStatusCaughtError TestExecutionStatus = "CAUGHT_ERROR"
)

// ValidateStateMachineDefinitionResultCode represents valid values for ValidateStateMachineDefinitionResultCode.
type ValidateStateMachineDefinitionResultCode string

const (
	ValidateStateMachineDefinitionResultCodeOk   ValidateStateMachineDefinitionResultCode = "OK"
	ValidateStateMachineDefinitionResultCodeFail ValidateStateMachineDefinitionResultCode = "FAIL"
)

// ValidateStateMachineDefinitionSeverity represents valid values for ValidateStateMachineDefinitionSeverity.
type ValidateStateMachineDefinitionSeverity string

const (
	ValidateStateMachineDefinitionSeverityError   ValidateStateMachineDefinitionSeverity = "ERROR"
	ValidateStateMachineDefinitionSeverityWarning ValidateStateMachineDefinitionSeverity = "WARNING"
)

// ValidationExceptionReason represents valid values for ValidationExceptionReason.
type ValidationExceptionReason string

const (
	ValidationExceptionReasonApiDoesNotSupportLabeledArns ValidationExceptionReason = "API_DOES_NOT_SUPPORT_LABELED_ARNS"
	ValidationExceptionReasonMissingRequiredParameter     ValidationExceptionReason = "MISSING_REQUIRED_PARAMETER"
	ValidationExceptionReasonCannotUpdateCompletedMapRun  ValidationExceptionReason = "CANNOT_UPDATE_COMPLETED_MAP_RUN"
	ValidationExceptionReasonInvalidRoutingConfiguration  ValidationExceptionReason = "INVALID_ROUTING_CONFIGURATION"
)
