// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package stepfunctions

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// StateMachine represents AWS::StepFunctions::StateMachine.

type StateMachine struct {
	// Attributes for Fn::GetAtt
	Arn                    wetwire.AttrRef `json:"-"`
	Name                   wetwire.AttrRef `json:"-"`
	StateMachineRevisionId wetwire.AttrRef `json:"-"`

	// Properties
	Definition              any                                   `json:"Definition,omitempty"`
	DefinitionS3Location    *StateMachine_S3Location              `json:"DefinitionS3Location,omitempty"`
	DefinitionString        any                                   `json:"DefinitionString,omitempty"`
	DefinitionSubstitutions map[string]any                        `json:"DefinitionSubstitutions,omitempty"`
	EncryptionConfiguration *StateMachine_EncryptionConfiguration `json:"EncryptionConfiguration,omitempty"`
	LoggingConfiguration    *StateMachine_LoggingConfiguration    `json:"LoggingConfiguration,omitempty"`
	RoleArn                 any                                   `json:"RoleArn,omitempty"`
	StateMachineName        any                                   `json:"StateMachineName,omitempty"`
	StateMachineType        any                                   `json:"StateMachineType,omitempty"`
	Tags                    []any                                 `json:"Tags,omitempty"`
	TracingConfiguration    *StateMachine_TracingConfiguration    `json:"TracingConfiguration,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r StateMachine) ResourceType() string {
	return "AWS::StepFunctions::StateMachine"
}
