// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package connectcampaignsv2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Campaign represents AWS::ConnectCampaignsV2::Campaign.

type Campaign struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	ChannelSubtypeConfig        *Campaign_ChannelSubtypeConfig      `json:"ChannelSubtypeConfig,omitempty"`
	CommunicationLimitsOverride *Campaign_CommunicationLimitsConfig `json:"CommunicationLimitsOverride,omitempty"`
	CommunicationTimeConfig     *Campaign_CommunicationTimeConfig   `json:"CommunicationTimeConfig,omitempty"`
	ConnectCampaignFlowArn      any                                 `json:"ConnectCampaignFlowArn,omitempty"`
	ConnectInstanceId           any                                 `json:"ConnectInstanceId,omitempty"`
	Name                        any                                 `json:"Name,omitempty"`
	Schedule                    *Campaign_Schedule                  `json:"Schedule,omitempty"`
	Source                      *Campaign_Source                    `json:"Source,omitempty"`
	Tags                        []any                               `json:"Tags,omitempty"`
	Type_                       any                                 `json:"Type,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Campaign) ResourceType() string {
	return "AWS::ConnectCampaignsV2::Campaign"
}
