// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package sagemaker

// ModelCard_AdditionalInformation represents AWS::SageMaker::ModelCard.AdditionalInformation.
type ModelCard_AdditionalInformation struct {
	CaveatsAndRecommendations any            `json:"CaveatsAndRecommendations,omitempty"`
	CustomDetails             map[string]any `json:"CustomDetails,omitempty"`
	EthicalConsiderations     any            `json:"EthicalConsiderations,omitempty"`
}

// ModelCard_BusinessDetails represents AWS::SageMaker::ModelCard.BusinessDetails.
type ModelCard_BusinessDetails struct {
	BusinessProblem      any `json:"BusinessProblem,omitempty"`
	BusinessStakeholders any `json:"BusinessStakeholders,omitempty"`
	LineOfBusiness       any `json:"LineOfBusiness,omitempty"`
}

// ModelCard_Container represents AWS::SageMaker::ModelCard.Container.
type ModelCard_Container struct {
	Image            any `json:"Image,omitempty"`
	ModelDataUrl     any `json:"ModelDataUrl,omitempty"`
	NearestModelName any `json:"NearestModelName,omitempty"`
}

// ModelCard_Content represents AWS::SageMaker::ModelCard.Content.
type ModelCard_Content struct {
	AdditionalInformation *ModelCard_AdditionalInformation `json:"AdditionalInformation,omitempty"`
	BusinessDetails       *ModelCard_BusinessDetails       `json:"BusinessDetails,omitempty"`
	EvaluationDetails     []ModelCard_EvaluationDetail     `json:"EvaluationDetails,omitempty"`
	IntendedUses          *ModelCard_IntendedUses          `json:"IntendedUses,omitempty"`
	ModelOverview         *ModelCard_ModelOverview         `json:"ModelOverview,omitempty"`
	ModelPackageDetails   *ModelCard_ModelPackageDetails   `json:"ModelPackageDetails,omitempty"`
	TrainingDetails       *ModelCard_TrainingDetails       `json:"TrainingDetails,omitempty"`
}

// ModelCard_EvaluationDetail represents AWS::SageMaker::ModelCard.EvaluationDetail.
type ModelCard_EvaluationDetail struct {
	Datasets              []any                   `json:"Datasets,omitempty"`
	EvaluationJobArn      any                     `json:"EvaluationJobArn,omitempty"`
	EvaluationObservation any                     `json:"EvaluationObservation,omitempty"`
	Metadata              map[string]any          `json:"Metadata,omitempty"`
	MetricGroups          []ModelCard_MetricGroup `json:"MetricGroups,omitempty"`
	Name                  any                     `json:"Name,omitempty"`
}

// ModelCard_Function represents AWS::SageMaker::ModelCard.Function.
type ModelCard_Function struct {
	Condition any `json:"Condition,omitempty"`
	Facet     any `json:"Facet,omitempty"`
	Function  any `json:"Function,omitempty"`
}

// ModelCard_InferenceEnvironment represents AWS::SageMaker::ModelCard.InferenceEnvironment.
type ModelCard_InferenceEnvironment struct {
	ContainerImage []any `json:"ContainerImage,omitempty"`
}

// ModelCard_InferenceSpecification represents AWS::SageMaker::ModelCard.InferenceSpecification.
type ModelCard_InferenceSpecification struct {
	Containers []ModelCard_Container `json:"Containers,omitempty"`
}

// ModelCard_IntendedUses represents AWS::SageMaker::ModelCard.IntendedUses.
type ModelCard_IntendedUses struct {
	ExplanationsForRiskRating       any `json:"ExplanationsForRiskRating,omitempty"`
	FactorsAffectingModelEfficiency any `json:"FactorsAffectingModelEfficiency,omitempty"`
	IntendedUses                    any `json:"IntendedUses,omitempty"`
	PurposeOfModel                  any `json:"PurposeOfModel,omitempty"`
	RiskRating                      any `json:"RiskRating,omitempty"`
}

// ModelCard_MetricDataItems represents AWS::SageMaker::ModelCard.MetricDataItems.
type ModelCard_MetricDataItems struct {
	Name      any   `json:"Name,omitempty"`
	Notes     any   `json:"Notes,omitempty"`
	Type_     any   `json:"Type,omitempty"`
	Value     any   `json:"Value,omitempty"`
	XAxisName []any `json:"XAxisName,omitempty"`
	YAxisName []any `json:"YAxisName,omitempty"`
}

// ModelCard_MetricGroup represents AWS::SageMaker::ModelCard.MetricGroup.
type ModelCard_MetricGroup struct {
	MetricData []ModelCard_MetricDataItems `json:"MetricData,omitempty"`
	Name       any                         `json:"Name,omitempty"`
}

// ModelCard_ModelOverview represents AWS::SageMaker::ModelCard.ModelOverview.
type ModelCard_ModelOverview struct {
	AlgorithmType        any                             `json:"AlgorithmType,omitempty"`
	InferenceEnvironment *ModelCard_InferenceEnvironment `json:"InferenceEnvironment,omitempty"`
	ModelArtifact        []any                           `json:"ModelArtifact,omitempty"`
	ModelCreator         any                             `json:"ModelCreator,omitempty"`
	ModelDescription     any                             `json:"ModelDescription,omitempty"`
	ModelId              any                             `json:"ModelId,omitempty"`
	ModelName            any                             `json:"ModelName,omitempty"`
	ModelOwner           any                             `json:"ModelOwner,omitempty"`
	ModelVersion         any                             `json:"ModelVersion,omitempty"`
	ProblemType          any                             `json:"ProblemType,omitempty"`
}

// ModelCard_ModelPackageCreator represents AWS::SageMaker::ModelCard.ModelPackageCreator.
type ModelCard_ModelPackageCreator struct {
	UserProfileName any `json:"UserProfileName,omitempty"`
}

// ModelCard_ModelPackageDetails represents AWS::SageMaker::ModelCard.ModelPackageDetails.
type ModelCard_ModelPackageDetails struct {
	ApprovalDescription     any                               `json:"ApprovalDescription,omitempty"`
	CreatedBy               *ModelCard_ModelPackageCreator    `json:"CreatedBy,omitempty"`
	Domain                  any                               `json:"Domain,omitempty"`
	InferenceSpecification  *ModelCard_InferenceSpecification `json:"InferenceSpecification,omitempty"`
	ModelApprovalStatus     any                               `json:"ModelApprovalStatus,omitempty"`
	ModelPackageArn         any                               `json:"ModelPackageArn,omitempty"`
	ModelPackageDescription any                               `json:"ModelPackageDescription,omitempty"`
	ModelPackageGroupName   any                               `json:"ModelPackageGroupName,omitempty"`
	ModelPackageName        any                               `json:"ModelPackageName,omitempty"`
	ModelPackageStatus      any                               `json:"ModelPackageStatus,omitempty"`
	ModelPackageVersion     any                               `json:"ModelPackageVersion,omitempty"`
	SourceAlgorithms        []ModelCard_SourceAlgorithm       `json:"SourceAlgorithms,omitempty"`
	Task                    any                               `json:"Task,omitempty"`
}

// ModelCard_ObjectiveFunction represents AWS::SageMaker::ModelCard.ObjectiveFunction.
type ModelCard_ObjectiveFunction struct {
	Function *ModelCard_Function `json:"Function,omitempty"`
	Notes    any                 `json:"Notes,omitempty"`
}

// ModelCard_SecurityConfig represents AWS::SageMaker::ModelCard.SecurityConfig.
type ModelCard_SecurityConfig struct {
	KmsKeyId any `json:"KmsKeyId,omitempty"`
}

// ModelCard_SourceAlgorithm represents AWS::SageMaker::ModelCard.SourceAlgorithm.
type ModelCard_SourceAlgorithm struct {
	AlgorithmName any `json:"AlgorithmName,omitempty"`
	ModelDataUrl  any `json:"ModelDataUrl,omitempty"`
}

// ModelCard_TrainingDetails represents AWS::SageMaker::ModelCard.TrainingDetails.
type ModelCard_TrainingDetails struct {
	ObjectiveFunction    *ModelCard_ObjectiveFunction  `json:"ObjectiveFunction,omitempty"`
	TrainingJobDetails   *ModelCard_TrainingJobDetails `json:"TrainingJobDetails,omitempty"`
	TrainingObservations any                           `json:"TrainingObservations,omitempty"`
}

// ModelCard_TrainingEnvironment represents AWS::SageMaker::ModelCard.TrainingEnvironment.
type ModelCard_TrainingEnvironment struct {
	ContainerImage []any `json:"ContainerImage,omitempty"`
}

// ModelCard_TrainingHyperParameter represents AWS::SageMaker::ModelCard.TrainingHyperParameter.
type ModelCard_TrainingHyperParameter struct {
	Name  any `json:"Name,omitempty"`
	Value any `json:"Value,omitempty"`
}

// ModelCard_TrainingJobDetails represents AWS::SageMaker::ModelCard.TrainingJobDetails.
type ModelCard_TrainingJobDetails struct {
	HyperParameters             []ModelCard_TrainingHyperParameter `json:"HyperParameters,omitempty"`
	TrainingArn                 any                                `json:"TrainingArn,omitempty"`
	TrainingDatasets            []any                              `json:"TrainingDatasets,omitempty"`
	TrainingEnvironment         *ModelCard_TrainingEnvironment     `json:"TrainingEnvironment,omitempty"`
	TrainingMetrics             []ModelCard_TrainingMetric         `json:"TrainingMetrics,omitempty"`
	UserProvidedHyperParameters []ModelCard_TrainingHyperParameter `json:"UserProvidedHyperParameters,omitempty"`
	UserProvidedTrainingMetrics []ModelCard_TrainingMetric         `json:"UserProvidedTrainingMetrics,omitempty"`
}

// ModelCard_TrainingMetric represents AWS::SageMaker::ModelCard.TrainingMetric.
type ModelCard_TrainingMetric struct {
	Name  any `json:"Name,omitempty"`
	Notes any `json:"Notes,omitempty"`
	Value any `json:"Value,omitempty"`
}

// ModelCard_UserContext represents AWS::SageMaker::ModelCard.UserContext.
type ModelCard_UserContext struct {
	DomainId        any `json:"DomainId,omitempty"`
	UserProfileArn  any `json:"UserProfileArn,omitempty"`
	UserProfileName any `json:"UserProfileName,omitempty"`
}
