// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package sagemaker

// Workteam_CognitoMemberDefinition represents AWS::SageMaker::Workteam.CognitoMemberDefinition.
type Workteam_CognitoMemberDefinition struct {
	CognitoClientId  any `json:"CognitoClientId,omitempty"`
	CognitoUserGroup any `json:"CognitoUserGroup,omitempty"`
	CognitoUserPool  any `json:"CognitoUserPool,omitempty"`
}

// Workteam_MemberDefinition represents AWS::SageMaker::Workteam.MemberDefinition.
type Workteam_MemberDefinition struct {
	CognitoMemberDefinition *Workteam_CognitoMemberDefinition `json:"CognitoMemberDefinition,omitempty"`
	OidcMemberDefinition    *Workteam_OidcMemberDefinition    `json:"OidcMemberDefinition,omitempty"`
}

// Workteam_NotificationConfiguration represents AWS::SageMaker::Workteam.NotificationConfiguration.
type Workteam_NotificationConfiguration struct {
	NotificationTopicArn any `json:"NotificationTopicArn,omitempty"`
}

// Workteam_OidcMemberDefinition represents AWS::SageMaker::Workteam.OidcMemberDefinition.
type Workteam_OidcMemberDefinition struct {
	OidcGroups []any `json:"OidcGroups,omitempty"`
}
