// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package aiops

// InvestigationGroup_ChatbotNotificationChannel represents AWS::AIOps::InvestigationGroup.ChatbotNotificationChannel.
type InvestigationGroup_ChatbotNotificationChannel struct {
	ChatConfigurationArns []any `json:"ChatConfigurationArns,omitempty"`
	SNSTopicArn           any   `json:"SNSTopicArn,omitempty"`
}

// InvestigationGroup_CrossAccountConfiguration represents AWS::AIOps::InvestigationGroup.CrossAccountConfiguration.
type InvestigationGroup_CrossAccountConfiguration struct {
	SourceRoleArn any `json:"SourceRoleArn,omitempty"`
}

// InvestigationGroup_EncryptionConfigMap represents AWS::AIOps::InvestigationGroup.EncryptionConfigMap.
type InvestigationGroup_EncryptionConfigMap struct {
	EncryptionConfigurationType any `json:"EncryptionConfigurationType,omitempty"`
	KmsKeyId                    any `json:"KmsKeyId,omitempty"`
}
