// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package observabilityadmin

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// OrganizationTelemetryRule represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.

type OrganizationTelemetryRule struct {
	// Attributes for Fn::GetAtt
	RuleArn wetwire.AttrRef `json:"-"`

	// Properties
	Rule     OrganizationTelemetryRule_TelemetryRule `json:"Rule,omitempty"`
	RuleName any                                     `json:"RuleName,omitempty"`
	Tags     []any                                   `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r OrganizationTelemetryRule) ResourceType() string {
	return "AWS::ObservabilityAdmin::OrganizationTelemetryRule"
}
