// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package observabilityadmin

// OrganizationTelemetryRule_ActionCondition represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.ActionCondition.
type OrganizationTelemetryRule_ActionCondition struct {
	Action any `json:"Action,omitempty"`
}

// OrganizationTelemetryRule_AdvancedEventSelector represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.AdvancedEventSelector.
type OrganizationTelemetryRule_AdvancedEventSelector struct {
	FieldSelectors []OrganizationTelemetryRule_AdvancedFieldSelector `json:"FieldSelectors,omitempty"`
	Name           any                                               `json:"Name,omitempty"`
}

// OrganizationTelemetryRule_AdvancedFieldSelector represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.AdvancedFieldSelector.
type OrganizationTelemetryRule_AdvancedFieldSelector struct {
	EndsWith      []any `json:"EndsWith,omitempty"`
	Equals        []any `json:"Equals,omitempty"`
	Field         any   `json:"Field,omitempty"`
	NotEndsWith   []any `json:"NotEndsWith,omitempty"`
	NotEquals     []any `json:"NotEquals,omitempty"`
	NotStartsWith []any `json:"NotStartsWith,omitempty"`
	StartsWith    []any `json:"StartsWith,omitempty"`
}

// OrganizationTelemetryRule_CloudtrailParameters represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.CloudtrailParameters.
type OrganizationTelemetryRule_CloudtrailParameters struct {
	AdvancedEventSelectors []OrganizationTelemetryRule_AdvancedEventSelector `json:"AdvancedEventSelectors,omitempty"`
}

// OrganizationTelemetryRule_Condition represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.Condition.
type OrganizationTelemetryRule_Condition struct {
	ActionCondition    *OrganizationTelemetryRule_ActionCondition    `json:"ActionCondition,omitempty"`
	LabelNameCondition *OrganizationTelemetryRule_LabelNameCondition `json:"LabelNameCondition,omitempty"`
}

// OrganizationTelemetryRule_ELBLoadBalancerLoggingParameters represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.ELBLoadBalancerLoggingParameters.
type OrganizationTelemetryRule_ELBLoadBalancerLoggingParameters struct {
	FieldDelimiter any `json:"FieldDelimiter,omitempty"`
	OutputFormat   any `json:"OutputFormat,omitempty"`
}

// OrganizationTelemetryRule_FieldToMatch represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.FieldToMatch.
type OrganizationTelemetryRule_FieldToMatch struct {
	Method       any                                     `json:"Method,omitempty"`
	QueryString  any                                     `json:"QueryString,omitempty"`
	SingleHeader *OrganizationTelemetryRule_SingleHeader `json:"SingleHeader,omitempty"`
	UriPath      any                                     `json:"UriPath,omitempty"`
}

// OrganizationTelemetryRule_Filter represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.Filter.
type OrganizationTelemetryRule_Filter struct {
	Behavior    any                                   `json:"Behavior,omitempty"`
	Conditions  []OrganizationTelemetryRule_Condition `json:"Conditions,omitempty"`
	Requirement any                                   `json:"Requirement,omitempty"`
}

// OrganizationTelemetryRule_LabelNameCondition represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.LabelNameCondition.
type OrganizationTelemetryRule_LabelNameCondition struct {
	LabelName any `json:"LabelName,omitempty"`
}

// OrganizationTelemetryRule_LoggingFilter represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.LoggingFilter.
type OrganizationTelemetryRule_LoggingFilter struct {
	DefaultBehavior any                                `json:"DefaultBehavior,omitempty"`
	Filters         []OrganizationTelemetryRule_Filter `json:"Filters,omitempty"`
}

// OrganizationTelemetryRule_SingleHeader represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.SingleHeader.
type OrganizationTelemetryRule_SingleHeader struct {
	Name any `json:"Name,omitempty"`
}

// OrganizationTelemetryRule_TelemetryDestinationConfiguration represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.TelemetryDestinationConfiguration.
type OrganizationTelemetryRule_TelemetryDestinationConfiguration struct {
	CloudtrailParameters             *OrganizationTelemetryRule_CloudtrailParameters             `json:"CloudtrailParameters,omitempty"`
	DestinationPattern               any                                                         `json:"DestinationPattern,omitempty"`
	DestinationType                  any                                                         `json:"DestinationType,omitempty"`
	ELBLoadBalancerLoggingParameters *OrganizationTelemetryRule_ELBLoadBalancerLoggingParameters `json:"ELBLoadBalancerLoggingParameters,omitempty"`
	RetentionInDays                  any                                                         `json:"RetentionInDays,omitempty"`
	VPCFlowLogParameters             *OrganizationTelemetryRule_VPCFlowLogParameters             `json:"VPCFlowLogParameters,omitempty"`
	WAFLoggingParameters             *OrganizationTelemetryRule_WAFLoggingParameters             `json:"WAFLoggingParameters,omitempty"`
}

// OrganizationTelemetryRule_TelemetryRule represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.TelemetryRule.
type OrganizationTelemetryRule_TelemetryRule struct {
	DestinationConfiguration *OrganizationTelemetryRule_TelemetryDestinationConfiguration `json:"DestinationConfiguration,omitempty"`
	ResourceType             any                                                          `json:"ResourceType,omitempty"`
	Scope                    any                                                          `json:"Scope,omitempty"`
	SelectionCriteria        any                                                          `json:"SelectionCriteria,omitempty"`
	TelemetrySourceTypes     []any                                                        `json:"TelemetrySourceTypes,omitempty"`
	TelemetryType            any                                                          `json:"TelemetryType,omitempty"`
}

// OrganizationTelemetryRule_VPCFlowLogParameters represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.VPCFlowLogParameters.
type OrganizationTelemetryRule_VPCFlowLogParameters struct {
	LogFormat              any `json:"LogFormat,omitempty"`
	MaxAggregationInterval any `json:"MaxAggregationInterval,omitempty"`
	TrafficType            any `json:"TrafficType,omitempty"`
}

// OrganizationTelemetryRule_WAFLoggingParameters represents AWS::ObservabilityAdmin::OrganizationTelemetryRule.WAFLoggingParameters.
type OrganizationTelemetryRule_WAFLoggingParameters struct {
	LogType        any                                      `json:"LogType,omitempty"`
	LoggingFilter  *OrganizationTelemetryRule_LoggingFilter `json:"LoggingFilter,omitempty"`
	RedactedFields []OrganizationTelemetryRule_FieldToMatch `json:"RedactedFields,omitempty"`
}
