// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package observabilityadmin

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// TelemetryPipelines represents AWS::ObservabilityAdmin::TelemetryPipelines.

type TelemetryPipelines struct {
	// Attributes for Fn::GetAtt
	Arn                               wetwire.AttrRef `json:"-"`
	Pipeline                          wetwire.AttrRef `json:"-"`
	Pipeline_Arn                      wetwire.AttrRef `json:"-"`
	Pipeline_Configuration            wetwire.AttrRef `json:"-"`
	Pipeline_Configuration_Body       wetwire.AttrRef `json:"-"`
	Pipeline_CreatedTimeStamp         wetwire.AttrRef `json:"-"`
	Pipeline_LastUpdateTimeStamp      wetwire.AttrRef `json:"-"`
	Pipeline_Name                     wetwire.AttrRef `json:"-"`
	Pipeline_Status                   wetwire.AttrRef `json:"-"`
	Pipeline_StatusReason             wetwire.AttrRef `json:"-"`
	Pipeline_StatusReason_Description wetwire.AttrRef `json:"-"`
	Pipeline_Tags                     wetwire.AttrRef `json:"-"`
	PipelineIdentifier                wetwire.AttrRef `json:"-"`
	Status                            wetwire.AttrRef `json:"-"`
	StatusReason                      wetwire.AttrRef `json:"-"`
	StatusReason_Description          wetwire.AttrRef `json:"-"`

	// Properties
	Configuration TelemetryPipelines_TelemetryPipelineConfiguration `json:"Configuration,omitempty"`
	Name          any                                               `json:"Name,omitempty"`
	Tags          []any                                             `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r TelemetryPipelines) ResourceType() string {
	return "AWS::ObservabilityAdmin::TelemetryPipelines"
}
