// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package iotsitewise

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// AccessPolicy represents AWS::IoTSiteWise::AccessPolicy.

type AccessPolicy struct {
	// Attributes for Fn::GetAtt
	AccessPolicyArn wetwire.AttrRef `json:"-"`
	AccessPolicyId  wetwire.AttrRef `json:"-"`

	// Properties
	AccessPolicyIdentity   AccessPolicy_AccessPolicyIdentity `json:"AccessPolicyIdentity,omitempty"`
	AccessPolicyPermission any                               `json:"AccessPolicyPermission,omitempty"`
	AccessPolicyResource   AccessPolicy_AccessPolicyResource `json:"AccessPolicyResource,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r AccessPolicy) ResourceType() string {
	return "AWS::IoTSiteWise::AccessPolicy"
}
