// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package iotsitewise

// ComputationModel_AnomalyDetectionComputationModelConfiguration represents AWS::IoTSiteWise::ComputationModel.AnomalyDetectionComputationModelConfiguration.
type ComputationModel_AnomalyDetectionComputationModelConfiguration struct {
	InputProperties any `json:"InputProperties,omitempty"`
	ResultProperty  any `json:"ResultProperty,omitempty"`
}

// ComputationModel_AssetModelPropertyBindingValue represents AWS::IoTSiteWise::ComputationModel.AssetModelPropertyBindingValue.
type ComputationModel_AssetModelPropertyBindingValue struct {
	AssetModelId any `json:"AssetModelId,omitempty"`
	PropertyId   any `json:"PropertyId,omitempty"`
}

// ComputationModel_AssetPropertyBindingValue represents AWS::IoTSiteWise::ComputationModel.AssetPropertyBindingValue.
type ComputationModel_AssetPropertyBindingValue struct {
	AssetId    any `json:"AssetId,omitempty"`
	PropertyId any `json:"PropertyId,omitempty"`
}

// ComputationModel_ComputationModelConfiguration represents AWS::IoTSiteWise::ComputationModel.ComputationModelConfiguration.
type ComputationModel_ComputationModelConfiguration struct {
	AnomalyDetection *ComputationModel_AnomalyDetectionComputationModelConfiguration `json:"AnomalyDetection,omitempty"`
}

// ComputationModel_ComputationModelDataBindingValue represents AWS::IoTSiteWise::ComputationModel.ComputationModelDataBindingValue.
type ComputationModel_ComputationModelDataBindingValue struct {
	AssetModelProperty *ComputationModel_AssetModelPropertyBindingValue    `json:"AssetModelProperty,omitempty"`
	AssetProperty      *ComputationModel_AssetPropertyBindingValue         `json:"AssetProperty,omitempty"`
	List               []ComputationModel_ComputationModelDataBindingValue `json:"List,omitempty"`
}
