// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package fsx

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// FileSystem represents AWS::FSx::FileSystem.

type FileSystem struct {
	// Attributes for Fn::GetAtt
	DNSName         wetwire.AttrRef `json:"-"`
	LustreMountName wetwire.AttrRef `json:"-"`
	ResourceARN     wetwire.AttrRef `json:"-"`
	RootVolumeId    wetwire.AttrRef `json:"-"`

	// Properties
	BackupId              any                              `json:"BackupId,omitempty"`
	FileSystemType        any                              `json:"FileSystemType,omitempty"`
	FileSystemTypeVersion any                              `json:"FileSystemTypeVersion,omitempty"`
	KmsKeyId              any                              `json:"KmsKeyId,omitempty"`
	LustreConfiguration   *FileSystem_LustreConfiguration  `json:"LustreConfiguration,omitempty"`
	NetworkType           any                              `json:"NetworkType,omitempty"`
	OntapConfiguration    *FileSystem_OntapConfiguration   `json:"OntapConfiguration,omitempty"`
	OpenZFSConfiguration  *FileSystem_OpenZFSConfiguration `json:"OpenZFSConfiguration,omitempty"`
	SecurityGroupIds      []any                            `json:"SecurityGroupIds,omitempty"`
	StorageCapacity       any                              `json:"StorageCapacity,omitempty"`
	StorageType           any                              `json:"StorageType,omitempty"`
	SubnetIds             []any                            `json:"SubnetIds,omitempty"`
	Tags                  []any                            `json:"Tags,omitempty"`
	WindowsConfiguration  *FileSystem_WindowsConfiguration `json:"WindowsConfiguration,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r FileSystem) ResourceType() string {
	return "AWS::FSx::FileSystem"
}
