// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package deadline

// Fleet_AcceleratorCapabilities represents AWS::Deadline::Fleet.AcceleratorCapabilities.
type Fleet_AcceleratorCapabilities struct {
	Count      *Fleet_AcceleratorCountRange `json:"Count,omitempty"`
	Selections []Fleet_AcceleratorSelection `json:"Selections,omitempty"`
}

// Fleet_AcceleratorCountRange represents AWS::Deadline::Fleet.AcceleratorCountRange.
type Fleet_AcceleratorCountRange struct {
	Max any `json:"Max,omitempty"`
	Min any `json:"Min,omitempty"`
}

// Fleet_AcceleratorSelection represents AWS::Deadline::Fleet.AcceleratorSelection.
type Fleet_AcceleratorSelection struct {
	Name    any `json:"Name,omitempty"`
	Runtime any `json:"Runtime,omitempty"`
}

// Fleet_AcceleratorTotalMemoryMiBRange represents AWS::Deadline::Fleet.AcceleratorTotalMemoryMiBRange.
type Fleet_AcceleratorTotalMemoryMiBRange struct {
	Max any `json:"Max,omitempty"`
	Min any `json:"Min,omitempty"`
}

// Fleet_CustomerManagedFleetConfiguration represents AWS::Deadline::Fleet.CustomerManagedFleetConfiguration.
type Fleet_CustomerManagedFleetConfiguration struct {
	Mode               any                                     `json:"Mode,omitempty"`
	StorageProfileId   any                                     `json:"StorageProfileId,omitempty"`
	TagPropagationMode any                                     `json:"TagPropagationMode,omitempty"`
	WorkerCapabilities Fleet_CustomerManagedWorkerCapabilities `json:"WorkerCapabilities,omitempty"`
}

// Fleet_CustomerManagedWorkerCapabilities represents AWS::Deadline::Fleet.CustomerManagedWorkerCapabilities.
type Fleet_CustomerManagedWorkerCapabilities struct {
	AcceleratorCount          *Fleet_AcceleratorCountRange          `json:"AcceleratorCount,omitempty"`
	AcceleratorTotalMemoryMiB *Fleet_AcceleratorTotalMemoryMiBRange `json:"AcceleratorTotalMemoryMiB,omitempty"`
	AcceleratorTypes          []any                                 `json:"AcceleratorTypes,omitempty"`
	CpuArchitectureType       any                                   `json:"CpuArchitectureType,omitempty"`
	CustomAmounts             []Fleet_FleetAmountCapability         `json:"CustomAmounts,omitempty"`
	CustomAttributes          []Fleet_FleetAttributeCapability      `json:"CustomAttributes,omitempty"`
	MemoryMiB                 Fleet_MemoryMiBRange                  `json:"MemoryMiB,omitempty"`
	OsFamily                  any                                   `json:"OsFamily,omitempty"`
	VCpuCount                 Fleet_VCpuCountRange                  `json:"VCpuCount,omitempty"`
}

// Fleet_Ec2EbsVolume represents AWS::Deadline::Fleet.Ec2EbsVolume.
type Fleet_Ec2EbsVolume struct {
	Iops          any `json:"Iops,omitempty"`
	SizeGiB       any `json:"SizeGiB,omitempty"`
	ThroughputMiB any `json:"ThroughputMiB,omitempty"`
}

// Fleet_FleetAmountCapability represents AWS::Deadline::Fleet.FleetAmountCapability.
type Fleet_FleetAmountCapability struct {
	Max  any `json:"Max,omitempty"`
	Min  any `json:"Min,omitempty"`
	Name any `json:"Name,omitempty"`
}

// Fleet_FleetAttributeCapability represents AWS::Deadline::Fleet.FleetAttributeCapability.
type Fleet_FleetAttributeCapability struct {
	Name   any   `json:"Name,omitempty"`
	Values []any `json:"Values,omitempty"`
}

// Fleet_FleetCapabilities represents AWS::Deadline::Fleet.FleetCapabilities.
type Fleet_FleetCapabilities struct {
	Amounts    []Fleet_FleetAmountCapability    `json:"Amounts,omitempty"`
	Attributes []Fleet_FleetAttributeCapability `json:"Attributes,omitempty"`
}

// Fleet_FleetConfiguration represents AWS::Deadline::Fleet.FleetConfiguration.
type Fleet_FleetConfiguration struct {
	CustomerManaged   *Fleet_CustomerManagedFleetConfiguration   `json:"CustomerManaged,omitempty"`
	ServiceManagedEc2 *Fleet_ServiceManagedEc2FleetConfiguration `json:"ServiceManagedEc2,omitempty"`
}

// Fleet_HostConfiguration represents AWS::Deadline::Fleet.HostConfiguration.
type Fleet_HostConfiguration struct {
	ScriptBody           any `json:"ScriptBody,omitempty"`
	ScriptTimeoutSeconds any `json:"ScriptTimeoutSeconds,omitempty"`
}

// Fleet_MemoryMiBRange represents AWS::Deadline::Fleet.MemoryMiBRange.
type Fleet_MemoryMiBRange struct {
	Max any `json:"Max,omitempty"`
	Min any `json:"Min,omitempty"`
}

// Fleet_ServiceManagedEc2FleetConfiguration represents AWS::Deadline::Fleet.ServiceManagedEc2FleetConfiguration.
type Fleet_ServiceManagedEc2FleetConfiguration struct {
	InstanceCapabilities  Fleet_ServiceManagedEc2InstanceCapabilities  `json:"InstanceCapabilities,omitempty"`
	InstanceMarketOptions Fleet_ServiceManagedEc2InstanceMarketOptions `json:"InstanceMarketOptions,omitempty"`
	StorageProfileId      any                                          `json:"StorageProfileId,omitempty"`
	VpcConfiguration      *Fleet_VpcConfiguration                      `json:"VpcConfiguration,omitempty"`
}

// Fleet_ServiceManagedEc2InstanceCapabilities represents AWS::Deadline::Fleet.ServiceManagedEc2InstanceCapabilities.
type Fleet_ServiceManagedEc2InstanceCapabilities struct {
	AcceleratorCapabilities *Fleet_AcceleratorCapabilities   `json:"AcceleratorCapabilities,omitempty"`
	AllowedInstanceTypes    []any                            `json:"AllowedInstanceTypes,omitempty"`
	CpuArchitectureType     any                              `json:"CpuArchitectureType,omitempty"`
	CustomAmounts           []Fleet_FleetAmountCapability    `json:"CustomAmounts,omitempty"`
	CustomAttributes        []Fleet_FleetAttributeCapability `json:"CustomAttributes,omitempty"`
	ExcludedInstanceTypes   []any                            `json:"ExcludedInstanceTypes,omitempty"`
	MemoryMiB               Fleet_MemoryMiBRange             `json:"MemoryMiB,omitempty"`
	OsFamily                any                              `json:"OsFamily,omitempty"`
	RootEbsVolume           *Fleet_Ec2EbsVolume              `json:"RootEbsVolume,omitempty"`
	VCpuCount               Fleet_VCpuCountRange             `json:"VCpuCount,omitempty"`
}

// Fleet_ServiceManagedEc2InstanceMarketOptions represents AWS::Deadline::Fleet.ServiceManagedEc2InstanceMarketOptions.
type Fleet_ServiceManagedEc2InstanceMarketOptions struct {
	Type_ any `json:"Type,omitempty"`
}

// Fleet_VCpuCountRange represents AWS::Deadline::Fleet.VCpuCountRange.
type Fleet_VCpuCountRange struct {
	Max any `json:"Max,omitempty"`
	Min any `json:"Min,omitempty"`
}

// Fleet_VpcConfiguration represents AWS::Deadline::Fleet.VpcConfiguration.
type Fleet_VpcConfiguration struct {
	ResourceConfigurationArns []any `json:"ResourceConfigurationArns,omitempty"`
}
