// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package deadline

// QueueLimitAssociation represents AWS::Deadline::QueueLimitAssociation.

type QueueLimitAssociation struct {

	// Properties
	FarmId  any `json:"FarmId,omitempty"`
	LimitId any `json:"LimitId,omitempty"`
	QueueId any `json:"QueueId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r QueueLimitAssociation) ResourceType() string {
	return "AWS::Deadline::QueueLimitAssociation"
}
