// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package deadline

// Queue_JobAttachmentSettings represents AWS::Deadline::Queue.JobAttachmentSettings.
type Queue_JobAttachmentSettings struct {
	RootPrefix   any `json:"RootPrefix,omitempty"`
	S3BucketName any `json:"S3BucketName,omitempty"`
}

// Queue_JobRunAsUser represents AWS::Deadline::Queue.JobRunAsUser.
type Queue_JobRunAsUser struct {
	Posix   *Queue_PosixUser   `json:"Posix,omitempty"`
	RunAs   any                `json:"RunAs,omitempty"`
	Windows *Queue_WindowsUser `json:"Windows,omitempty"`
}

// Queue_PosixUser represents AWS::Deadline::Queue.PosixUser.
type Queue_PosixUser struct {
	Group any `json:"Group,omitempty"`
	User  any `json:"User,omitempty"`
}

// Queue_WindowsUser represents AWS::Deadline::Queue.WindowsUser.
type Queue_WindowsUser struct {
	PasswordArn any `json:"PasswordArn,omitempty"`
	User        any `json:"User,omitempty"`
}
