// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package deadline

// QueueFleetAssociation represents AWS::Deadline::QueueFleetAssociation.

type QueueFleetAssociation struct {

	// Properties
	FarmId  any `json:"FarmId,omitempty"`
	FleetId any `json:"FleetId,omitempty"`
	QueueId any `json:"QueueId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r QueueFleetAssociation) ResourceType() string {
	return "AWS::Deadline::QueueFleetAssociation"
}
