// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:00:14-07:00

package serverless

// Connector represents AWS::Serverless::Connector.
// Creates permissions between two resources.

type Connector struct {

	// Properties
	// Destination resource reference.
	Destination any `json:"Destination,omitempty"`
	// Permission types (Read, Write).
	Permissions []any `json:"Permissions,omitempty"`
	// Source resource reference.
	Source any `json:"Source,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Connector) ResourceType() string {
	return "AWS::Serverless::Connector"
}
