// Package webapp contains CloudFormation resources.
// Storage resources: S3, EFS, etc.
//
// Generated by wetwire-aws import.
package webapp

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/s3"
)

var SiteCloudFrontLogsBucketAccessPolicyPolicyDocument = PolicyDocument{
	Statement: []any{SiteCloudFrontLogsBucketAccessPolicyPolicyDocumentStatement0, SiteCloudFrontLogsBucketAccessPolicyPolicyDocumentStatement1},
	Version: "2012-10-17",
}

var SiteCloudFrontLogsBucketAccessPolicyPolicyDocumentStatement1 = PolicyStatement{
	Action: "s3:PutObject",
	Condition: Json{ArnLike: Json{"aws:SourceArn": Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-${AWS::Region}-${AWS::AccountId}"}}, StringEquals: Json{"aws:SourceAccount": AWS_ACCOUNT_ID}},
	Effect: "Allow",
	Principal: ServicePrincipal{"logging.s3.amazonaws.com"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteCloudFrontLogsBucketAccessPolicyPolicyDocumentStatement0 = DenyStatement{
	Action: "s3:*",
	Condition: Json{Bool: Json{"aws:SecureTransport": false}},
	Principal: AWSPrincipal{"*"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-${AWS::Region}-${AWS::AccountId}"}, Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteCloudFrontLogsBucketAccessPolicy = s3.BucketPolicy{
	Bucket: Sub{String: "${AppName}-cflogs-${AWS::Region}-${AWS::AccountId}"},
	PolicyDocument: SiteCloudFrontLogsBucketAccessPolicyPolicyDocument,
}

var SiteCloudFrontLogsLogBucketObjectLockConfigurationRuleDefaultRetention = s3.Bucket_DefaultRetention{
	Mode: "COMPLIANCE",
	Years: 1,
}

var SiteCloudFrontLogsLogBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault = s3.Bucket_ServerSideEncryptionByDefault{
	SSEAlgorithm: "AES256",
}

var SiteCloudFrontLogsLogBucketObjectLockConfigurationRule = s3.Bucket_ObjectLockRule{
	DefaultRetention: SiteCloudFrontLogsLogBucketObjectLockConfigurationRuleDefaultRetention,
}

var SiteCloudFrontLogsLogBucketBucketEncryptionServerSideEncryptionConfiguration1 = s3.Bucket_ServerSideEncryptionRule{
	ServerSideEncryptionByDefault: SiteCloudFrontLogsLogBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault,
}

var SiteCloudFrontLogsLogBucketVersioningConfiguration = s3.Bucket_VersioningConfiguration{
	Status: "Enabled",
}

var SiteCloudFrontLogsLogBucketPublicAccessBlockConfiguration = s3.Bucket_PublicAccessBlockConfiguration{
	BlockPublicAcls: true,
	BlockPublicPolicy: true,
	IgnorePublicAcls: true,
	RestrictPublicBuckets: true,
}

var SiteCloudFrontLogsLogBucketObjectLockConfiguration = s3.Bucket_ObjectLockConfiguration{
	ObjectLockEnabled: "Enabled",
	Rule: SiteCloudFrontLogsLogBucketObjectLockConfigurationRule,
}

var SiteCloudFrontLogsLogBucketBucketEncryption = s3.Bucket_BucketEncryption{
	ServerSideEncryptionConfiguration: []any{SiteCloudFrontLogsLogBucketBucketEncryptionServerSideEncryptionConfiguration1},
}

var SiteCloudFrontLogsLogBucket = s3.Bucket{
	BucketEncryption: SiteCloudFrontLogsLogBucketBucketEncryption,
	BucketName: Sub{String: "${AppName}-cflogs-logs-${AWS::Region}-${AWS::AccountId}"},
	ObjectLockConfiguration: SiteCloudFrontLogsLogBucketObjectLockConfiguration,
	ObjectLockEnabled: true,
	PublicAccessBlockConfiguration: SiteCloudFrontLogsLogBucketPublicAccessBlockConfiguration,
	VersioningConfiguration: SiteCloudFrontLogsLogBucketVersioningConfiguration,
}

var SiteCloudFrontLogsLogBucketAccessPolicyPolicyDocument = PolicyDocument{
	Statement: []any{SiteCloudFrontLogsLogBucketAccessPolicyPolicyDocumentStatement0, SiteCloudFrontLogsLogBucketAccessPolicyPolicyDocumentStatement1},
	Version: "2012-10-17",
}

var SiteCloudFrontLogsLogBucketAccessPolicyPolicyDocumentStatement1 = PolicyStatement{
	Action: "s3:PutObject",
	Condition: Json{ArnLike: Json{"aws:SourceArn": Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-logs-${AWS::Region}-${AWS::AccountId}"}}, StringEquals: Json{"aws:SourceAccount": AWS_ACCOUNT_ID}},
	Effect: "Allow",
	Principal: ServicePrincipal{"logging.s3.amazonaws.com"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-logs-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteCloudFrontLogsLogBucketAccessPolicyPolicyDocumentStatement0 = DenyStatement{
	Action: "s3:*",
	Condition: Json{Bool: Json{"aws:SecureTransport": false}},
	Principal: AWSPrincipal{"*"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-logs-${AWS::Region}-${AWS::AccountId}"}, Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-logs-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteCloudFrontLogsLogBucketAccessPolicy = s3.BucketPolicy{
	Bucket: Sub{String: "${AppName}-cflogs-logs-${AWS::Region}-${AWS::AccountId}"},
	PolicyDocument: SiteCloudFrontLogsLogBucketAccessPolicyPolicyDocument,
}

var SiteCloudFrontLogsReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault = s3.Bucket_ServerSideEncryptionByDefault{
	SSEAlgorithm: "AES256",
}

var SiteCloudFrontLogsReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1 = s3.Bucket_ServerSideEncryptionRule{
	ServerSideEncryptionByDefault: SiteCloudFrontLogsReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault,
}

var SiteCloudFrontLogsReplicaBucketVersioningConfiguration = s3.Bucket_VersioningConfiguration{
	Status: "Enabled",
}

var SiteCloudFrontLogsReplicaBucketPublicAccessBlockConfiguration = s3.Bucket_PublicAccessBlockConfiguration{
	BlockPublicAcls: true,
	BlockPublicPolicy: true,
	IgnorePublicAcls: true,
	RestrictPublicBuckets: true,
}

var SiteCloudFrontLogsReplicaBucketBucketEncryption = s3.Bucket_BucketEncryption{
	ServerSideEncryptionConfiguration: []any{SiteCloudFrontLogsReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1},
}

var SiteCloudFrontLogsReplicaBucket = s3.Bucket{
	BucketEncryption: SiteCloudFrontLogsReplicaBucketBucketEncryption,
	BucketName: Sub{String: "${AppName}-cflogs-replicas-${AWS::Region}-${AWS::AccountId}"},
	ObjectLockEnabled: false,
	PublicAccessBlockConfiguration: SiteCloudFrontLogsReplicaBucketPublicAccessBlockConfiguration,
	VersioningConfiguration: SiteCloudFrontLogsReplicaBucketVersioningConfiguration,
}

var SiteCloudFrontLogsReplicaBucketAccessPolicyPolicyDocument = PolicyDocument{
	Statement: []any{SiteCloudFrontLogsReplicaBucketAccessPolicyPolicyDocumentStatement0, SiteCloudFrontLogsReplicaBucketAccessPolicyPolicyDocumentStatement1},
	Version: "2012-10-17",
}

var SiteCloudFrontLogsReplicaBucketAccessPolicyPolicyDocumentStatement1 = PolicyStatement{
	Action: "s3:PutObject",
	Condition: Json{ArnLike: Json{"aws:SourceArn": Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-replicas-${AWS::Region}-${AWS::AccountId}"}}, StringEquals: Json{"aws:SourceAccount": AWS_ACCOUNT_ID}},
	Effect: "Allow",
	Principal: ServicePrincipal{"logging.s3.amazonaws.com"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-replicas-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteCloudFrontLogsReplicaBucketAccessPolicyPolicyDocumentStatement0 = DenyStatement{
	Action: "s3:*",
	Condition: Json{Bool: Json{"aws:SecureTransport": false}},
	Principal: AWSPrincipal{"*"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-replicas-${AWS::Region}-${AWS::AccountId}"}, Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-cflogs-replicas-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteCloudFrontLogsReplicaBucketAccessPolicy = s3.BucketPolicy{
	Bucket: Sub{String: "${AppName}-cflogs-replicas-${AWS::Region}-${AWS::AccountId}"},
	PolicyDocument: SiteCloudFrontLogsReplicaBucketAccessPolicyPolicyDocument,
}

var SiteCloudFrontLogsBucketReplicationConfigurationRuleEnabledDestination = s3.Bucket_ReplicationDestination{
	Bucket: SiteCloudFrontLogsReplicaBucket.Arn,
}

var SiteCloudFrontLogsBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault = s3.Bucket_ServerSideEncryptionByDefault{
	SSEAlgorithm: "AES256",
}

var SiteCloudFrontLogsBucketReplicationConfigurationRuleEnabled = s3.Bucket_ReplicationRule{
	Destination: SiteCloudFrontLogsBucketReplicationConfigurationRuleEnabledDestination,
	Status: "Enabled",
}

var SiteCloudFrontLogsBucketOwnershipControlsRule1 = s3.Bucket_OwnershipControlsRule{
	ObjectOwnership: "BucketOwnerPreferred",
}

var SiteCloudFrontLogsBucketBucketEncryptionServerSideEncryptionConfiguration1 = s3.Bucket_ServerSideEncryptionRule{
	ServerSideEncryptionByDefault: SiteCloudFrontLogsBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault,
}

var SiteCloudFrontLogsBucketVersioningConfiguration = s3.Bucket_VersioningConfiguration{
	Status: "Enabled",
}

var SiteCloudFrontLogsBucketReplicationConfiguration = s3.Bucket_ReplicationConfiguration{
	Role: SiteCloudFrontLogsReplicationRole.Arn,
	Rules: []any{SiteCloudFrontLogsBucketReplicationConfigurationRuleEnabled},
}

var SiteCloudFrontLogsBucketPublicAccessBlockConfiguration = s3.Bucket_PublicAccessBlockConfiguration{
	BlockPublicAcls: true,
	BlockPublicPolicy: true,
	IgnorePublicAcls: true,
	RestrictPublicBuckets: true,
}

var SiteCloudFrontLogsBucketOwnershipControls = s3.Bucket_OwnershipControls{
	Rules: []any{SiteCloudFrontLogsBucketOwnershipControlsRule1},
}

var SiteCloudFrontLogsBucketLoggingConfiguration = s3.Bucket_LoggingConfiguration{
	DestinationBucketName: SiteCloudFrontLogsLogBucket,
}

var SiteCloudFrontLogsBucketBucketEncryption = s3.Bucket_BucketEncryption{
	ServerSideEncryptionConfiguration: []any{SiteCloudFrontLogsBucketBucketEncryptionServerSideEncryptionConfiguration1},
}

var SiteCloudFrontLogsBucket = s3.Bucket{
	BucketEncryption: SiteCloudFrontLogsBucketBucketEncryption,
	BucketName: Sub{String: "${AppName}-cflogs-${AWS::Region}-${AWS::AccountId}"},
	LoggingConfiguration: SiteCloudFrontLogsBucketLoggingConfiguration,
	ObjectLockEnabled: false,
	OwnershipControls: SiteCloudFrontLogsBucketOwnershipControls,
	PublicAccessBlockConfiguration: SiteCloudFrontLogsBucketPublicAccessBlockConfiguration,
	ReplicationConfiguration: SiteCloudFrontLogsBucketReplicationConfiguration,
	VersioningConfiguration: SiteCloudFrontLogsBucketVersioningConfiguration,
}

var SiteContentLogBucketObjectLockConfigurationRuleDefaultRetention = s3.Bucket_DefaultRetention{
	Mode: "COMPLIANCE",
	Years: 1,
}

var SiteContentLogBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault = s3.Bucket_ServerSideEncryptionByDefault{
	SSEAlgorithm: "AES256",
}

var SiteContentLogBucketObjectLockConfigurationRule = s3.Bucket_ObjectLockRule{
	DefaultRetention: SiteContentLogBucketObjectLockConfigurationRuleDefaultRetention,
}

var SiteContentLogBucketBucketEncryptionServerSideEncryptionConfiguration1 = s3.Bucket_ServerSideEncryptionRule{
	ServerSideEncryptionByDefault: SiteContentLogBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault,
}

var SiteContentLogBucketVersioningConfiguration = s3.Bucket_VersioningConfiguration{
	Status: "Enabled",
}

var SiteContentLogBucketPublicAccessBlockConfiguration = s3.Bucket_PublicAccessBlockConfiguration{
	BlockPublicAcls: true,
	BlockPublicPolicy: true,
	IgnorePublicAcls: true,
	RestrictPublicBuckets: true,
}

var SiteContentLogBucketObjectLockConfiguration = s3.Bucket_ObjectLockConfiguration{
	ObjectLockEnabled: "Enabled",
	Rule: SiteContentLogBucketObjectLockConfigurationRule,
}

var SiteContentLogBucketBucketEncryption = s3.Bucket_BucketEncryption{
	ServerSideEncryptionConfiguration: []any{SiteContentLogBucketBucketEncryptionServerSideEncryptionConfiguration1},
}

var SiteContentLogBucket = s3.Bucket{
	BucketEncryption: SiteContentLogBucketBucketEncryption,
	BucketName: Sub{String: "${AppName}-content-logs-${AWS::Region}-${AWS::AccountId}"},
	ObjectLockConfiguration: SiteContentLogBucketObjectLockConfiguration,
	ObjectLockEnabled: true,
	PublicAccessBlockConfiguration: SiteContentLogBucketPublicAccessBlockConfiguration,
	VersioningConfiguration: SiteContentLogBucketVersioningConfiguration,
}

var SiteContentLogBucketAccessPolicyPolicyDocument = PolicyDocument{
	Statement: []any{SiteContentLogBucketAccessPolicyPolicyDocumentStatement0, SiteContentLogBucketAccessPolicyPolicyDocumentStatement1},
	Version: "2012-10-17",
}

var SiteContentLogBucketAccessPolicyPolicyDocumentStatement1 = PolicyStatement{
	Action: "s3:PutObject",
	Condition: Json{ArnLike: Json{"aws:SourceArn": Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-logs-${AWS::Region}-${AWS::AccountId}"}}, StringEquals: Json{"aws:SourceAccount": AWS_ACCOUNT_ID}},
	Effect: "Allow",
	Principal: ServicePrincipal{"logging.s3.amazonaws.com"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-logs-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteContentLogBucketAccessPolicyPolicyDocumentStatement0 = DenyStatement{
	Action: "s3:*",
	Condition: Json{Bool: Json{"aws:SecureTransport": false}},
	Principal: AWSPrincipal{"*"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-logs-${AWS::Region}-${AWS::AccountId}"}, Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-logs-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteContentLogBucketAccessPolicy = s3.BucketPolicy{
	Bucket: Sub{String: "${AppName}-content-logs-${AWS::Region}-${AWS::AccountId}"},
	PolicyDocument: SiteContentLogBucketAccessPolicyPolicyDocument,
}

var SiteContentReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault = s3.Bucket_ServerSideEncryptionByDefault{
	SSEAlgorithm: "AES256",
}

var SiteContentReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1 = s3.Bucket_ServerSideEncryptionRule{
	ServerSideEncryptionByDefault: SiteContentReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault,
}

var SiteContentReplicaBucketVersioningConfiguration = s3.Bucket_VersioningConfiguration{
	Status: "Enabled",
}

var SiteContentReplicaBucketPublicAccessBlockConfiguration = s3.Bucket_PublicAccessBlockConfiguration{
	BlockPublicAcls: true,
	BlockPublicPolicy: true,
	IgnorePublicAcls: true,
	RestrictPublicBuckets: true,
}

var SiteContentReplicaBucketBucketEncryption = s3.Bucket_BucketEncryption{
	ServerSideEncryptionConfiguration: []any{SiteContentReplicaBucketBucketEncryptionServerSideEncryptionConfiguration1},
}

var SiteContentReplicaBucket = s3.Bucket{
	BucketEncryption: SiteContentReplicaBucketBucketEncryption,
	BucketName: Sub{String: "${AppName}-content-replicas-${AWS::Region}-${AWS::AccountId}"},
	ObjectLockEnabled: false,
	PublicAccessBlockConfiguration: SiteContentReplicaBucketPublicAccessBlockConfiguration,
	VersioningConfiguration: SiteContentReplicaBucketVersioningConfiguration,
}

var SiteContentReplicaBucketAccessPolicyPolicyDocument = PolicyDocument{
	Statement: []any{SiteContentReplicaBucketAccessPolicyPolicyDocumentStatement0, SiteContentReplicaBucketAccessPolicyPolicyDocumentStatement1},
	Version: "2012-10-17",
}

var SiteContentReplicaBucketAccessPolicyPolicyDocumentStatement1 = PolicyStatement{
	Action: "s3:PutObject",
	Condition: Json{ArnLike: Json{"aws:SourceArn": Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-replicas-${AWS::Region}-${AWS::AccountId}"}}, StringEquals: Json{"aws:SourceAccount": AWS_ACCOUNT_ID}},
	Effect: "Allow",
	Principal: ServicePrincipal{"logging.s3.amazonaws.com"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-replicas-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteContentReplicaBucketAccessPolicyPolicyDocumentStatement0 = DenyStatement{
	Action: "s3:*",
	Condition: Json{Bool: Json{"aws:SecureTransport": false}},
	Principal: AWSPrincipal{"*"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-replicas-${AWS::Region}-${AWS::AccountId}"}, Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-replicas-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteContentReplicaBucketAccessPolicy = s3.BucketPolicy{
	Bucket: Sub{String: "${AppName}-content-replicas-${AWS::Region}-${AWS::AccountId}"},
	PolicyDocument: SiteContentReplicaBucketAccessPolicyPolicyDocument,
}

var SiteContentBucketReplicationConfigurationRuleEnabledDestination = s3.Bucket_ReplicationDestination{
	Bucket: SiteContentReplicaBucket.Arn,
}

var SiteContentBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault = s3.Bucket_ServerSideEncryptionByDefault{
	SSEAlgorithm: "AES256",
}

var SiteContentBucketReplicationConfigurationRuleEnabled = s3.Bucket_ReplicationRule{
	Destination: SiteContentBucketReplicationConfigurationRuleEnabledDestination,
	Status: "Enabled",
}

var SiteContentBucketBucketEncryptionServerSideEncryptionConfiguration1 = s3.Bucket_ServerSideEncryptionRule{
	ServerSideEncryptionByDefault: SiteContentBucketBucketEncryptionServerSideEncryptionConfiguration1ServerSideEncryptionByDefault,
}

var SiteContentBucketVersioningConfiguration = s3.Bucket_VersioningConfiguration{
	Status: "Enabled",
}

var SiteContentBucketReplicationConfiguration = s3.Bucket_ReplicationConfiguration{
	Role: SiteContentReplicationRole.Arn,
	Rules: []any{SiteContentBucketReplicationConfigurationRuleEnabled},
}

var SiteContentBucketPublicAccessBlockConfiguration = s3.Bucket_PublicAccessBlockConfiguration{
	BlockPublicAcls: true,
	BlockPublicPolicy: true,
	IgnorePublicAcls: true,
	RestrictPublicBuckets: true,
}

var SiteContentBucketLoggingConfiguration = s3.Bucket_LoggingConfiguration{
	DestinationBucketName: SiteContentLogBucket,
}

var SiteContentBucketBucketEncryption = s3.Bucket_BucketEncryption{
	ServerSideEncryptionConfiguration: []any{SiteContentBucketBucketEncryptionServerSideEncryptionConfiguration1},
}

var SiteContentBucket = s3.Bucket{
	BucketEncryption: SiteContentBucketBucketEncryption,
	BucketName: Sub{String: "${AppName}-content-${AWS::Region}-${AWS::AccountId}"},
	LoggingConfiguration: SiteContentBucketLoggingConfiguration,
	ObjectLockEnabled: false,
	PublicAccessBlockConfiguration: SiteContentBucketPublicAccessBlockConfiguration,
	ReplicationConfiguration: SiteContentBucketReplicationConfiguration,
	VersioningConfiguration: SiteContentBucketVersioningConfiguration,
}

var SiteContentBucketAccessPolicyPolicyDocument = PolicyDocument{
	Statement: []any{SiteContentBucketAccessPolicyPolicyDocumentStatement0, SiteContentBucketAccessPolicyPolicyDocumentStatement1, SiteContentBucketAccessPolicyPolicyDocumentStatement2},
	Version: "2012-10-17",
}

var SiteContentBucketAccessPolicyPolicyDocumentStatement2 = PolicyStatement{
	Action: "s3:PutObject",
	Condition: Json{ArnLike: Json{"aws:SourceArn": Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-${AWS::Region}-${AWS::AccountId}"}}, StringEquals: Json{"aws:SourceAccount": AWS_ACCOUNT_ID}},
	Effect: "Allow",
	Principal: ServicePrincipal{"logging.s3.amazonaws.com"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteContentBucketAccessPolicyPolicyDocumentStatement1 = DenyStatement{
	Action: "s3:*",
	Condition: Json{Bool: Json{"aws:SecureTransport": false}},
	Principal: AWSPrincipal{"*"},
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-${AWS::Region}-${AWS::AccountId}"}, Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-${AWS::Region}-${AWS::AccountId}/*"}},
}

var SiteContentBucketAccessPolicyPolicyDocumentStatement0 = PolicyStatement{
	Action: "s3:GetObject",
	Condition: Json{StringEquals: Json{"AWS:SourceArn": Sub{String: "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${SiteDistribution.Id}"}}},
	Effect: "Allow",
	Principal: ServicePrincipal{"cloudfront.amazonaws.com"},
	Resource: Sub{String: "arn:${AWS::Partition}:s3:::${AppName}-content-${AWS::Region}-${AWS::AccountId}/*"},
}

var SiteContentBucketAccessPolicy = s3.BucketPolicy{
	Bucket: Sub{String: "${AppName}-content-${AWS::Region}-${AWS::AccountId}"},
	PolicyDocument: SiteContentBucketAccessPolicyPolicyDocument,
}
