// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package wisdom

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// AIGuardrailVersion represents AWS::Wisdom::AIGuardrailVersion.

type AIGuardrailVersion struct {
	// Attributes for Fn::GetAtt
	AIGuardrailArn       wetwire.AttrRef `json:"-"`
	AIGuardrailVersionId wetwire.AttrRef `json:"-"`
	AssistantArn         wetwire.AttrRef `json:"-"`
	VersionNumber        wetwire.AttrRef `json:"-"`

	// Properties
	AIGuardrailId       any `json:"AIGuardrailId,omitempty"`
	AssistantId         any `json:"AssistantId,omitempty"`
	ModifiedTimeSeconds any `json:"ModifiedTimeSeconds,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r AIGuardrailVersion) ResourceType() string {
	return "AWS::Wisdom::AIGuardrailVersion"
}
