// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package wisdom

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// KnowledgeBase represents AWS::Wisdom::KnowledgeBase.

type KnowledgeBase struct {
	// Attributes for Fn::GetAtt
	KnowledgeBaseArn wetwire.AttrRef `json:"-"`
	KnowledgeBaseId  wetwire.AttrRef `json:"-"`

	// Properties
	Description                       any                                              `json:"Description,omitempty"`
	KnowledgeBaseType                 any                                              `json:"KnowledgeBaseType,omitempty"`
	Name                              any                                              `json:"Name,omitempty"`
	RenderingConfiguration            *KnowledgeBase_RenderingConfiguration            `json:"RenderingConfiguration,omitempty"`
	ServerSideEncryptionConfiguration *KnowledgeBase_ServerSideEncryptionConfiguration `json:"ServerSideEncryptionConfiguration,omitempty"`
	SourceConfiguration               *KnowledgeBase_SourceConfiguration               `json:"SourceConfiguration,omitempty"`
	Tags                              []any                                            `json:"Tags,omitempty"`
	VectorIngestionConfiguration      *KnowledgeBase_VectorIngestionConfiguration      `json:"VectorIngestionConfiguration,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r KnowledgeBase) ResourceType() string {
	return "AWS::Wisdom::KnowledgeBase"
}
