// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:23-07:00

package wisdom

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// MessageTemplate represents AWS::Wisdom::MessageTemplate.

type MessageTemplate struct {
	// Attributes for Fn::GetAtt
	MessageTemplateArn           wetwire.AttrRef `json:"-"`
	MessageTemplateContentSha256 wetwire.AttrRef `json:"-"`
	MessageTemplateId            wetwire.AttrRef `json:"-"`

	// Properties
	ChannelSubtype             any                     `json:"ChannelSubtype,omitempty"`
	Content                    MessageTemplate_Content `json:"Content,omitempty"`
	DefaultAttributes          any                     `json:"DefaultAttributes,omitempty"`
	Description                any                     `json:"Description,omitempty"`
	GroupingConfiguration      any                     `json:"GroupingConfiguration,omitempty"`
	KnowledgeBaseArn           any                     `json:"KnowledgeBaseArn,omitempty"`
	Language                   any                     `json:"Language,omitempty"`
	MessageTemplateAttachments []any                   `json:"MessageTemplateAttachments,omitempty"`
	Name                       any                     `json:"Name,omitempty"`
	Tags                       []any                   `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r MessageTemplate) ResourceType() string {
	return "AWS::Wisdom::MessageTemplate"
}
