// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package wisdom

// MessageTemplate_AgentAttributes represents AWS::Wisdom::MessageTemplate.AgentAttributes.
type MessageTemplate_AgentAttributes struct {
	FirstName any `json:"FirstName,omitempty"`
	LastName  any `json:"LastName,omitempty"`
}

// MessageTemplate_Content represents AWS::Wisdom::MessageTemplate.Content.
type MessageTemplate_Content struct {
	EmailMessageTemplateContent *MessageTemplate_EmailMessageTemplateContent `json:"EmailMessageTemplateContent,omitempty"`
	SmsMessageTemplateContent   *MessageTemplate_SmsMessageTemplateContent   `json:"SmsMessageTemplateContent,omitempty"`
}

// MessageTemplate_CustomerProfileAttributes represents AWS::Wisdom::MessageTemplate.CustomerProfileAttributes.
type MessageTemplate_CustomerProfileAttributes struct {
	AccountNumber         any            `json:"AccountNumber,omitempty"`
	AdditionalInformation any            `json:"AdditionalInformation,omitempty"`
	Address1              any            `json:"Address1,omitempty"`
	Address2              any            `json:"Address2,omitempty"`
	Address3              any            `json:"Address3,omitempty"`
	Address4              any            `json:"Address4,omitempty"`
	BillingAddress1       any            `json:"BillingAddress1,omitempty"`
	BillingAddress2       any            `json:"BillingAddress2,omitempty"`
	BillingAddress3       any            `json:"BillingAddress3,omitempty"`
	BillingAddress4       any            `json:"BillingAddress4,omitempty"`
	BillingCity           any            `json:"BillingCity,omitempty"`
	BillingCountry        any            `json:"BillingCountry,omitempty"`
	BillingCounty         any            `json:"BillingCounty,omitempty"`
	BillingPostalCode     any            `json:"BillingPostalCode,omitempty"`
	BillingProvince       any            `json:"BillingProvince,omitempty"`
	BillingState          any            `json:"BillingState,omitempty"`
	BirthDate             any            `json:"BirthDate,omitempty"`
	BusinessEmailAddress  any            `json:"BusinessEmailAddress,omitempty"`
	BusinessName          any            `json:"BusinessName,omitempty"`
	BusinessPhoneNumber   any            `json:"BusinessPhoneNumber,omitempty"`
	City                  any            `json:"City,omitempty"`
	Country               any            `json:"Country,omitempty"`
	County                any            `json:"County,omitempty"`
	Custom                map[string]any `json:"Custom,omitempty"`
	EmailAddress          any            `json:"EmailAddress,omitempty"`
	FirstName             any            `json:"FirstName,omitempty"`
	Gender                any            `json:"Gender,omitempty"`
	HomePhoneNumber       any            `json:"HomePhoneNumber,omitempty"`
	LastName              any            `json:"LastName,omitempty"`
	MailingAddress1       any            `json:"MailingAddress1,omitempty"`
	MailingAddress2       any            `json:"MailingAddress2,omitempty"`
	MailingAddress3       any            `json:"MailingAddress3,omitempty"`
	MailingAddress4       any            `json:"MailingAddress4,omitempty"`
	MailingCity           any            `json:"MailingCity,omitempty"`
	MailingCountry        any            `json:"MailingCountry,omitempty"`
	MailingCounty         any            `json:"MailingCounty,omitempty"`
	MailingPostalCode     any            `json:"MailingPostalCode,omitempty"`
	MailingProvince       any            `json:"MailingProvince,omitempty"`
	MailingState          any            `json:"MailingState,omitempty"`
	MiddleName            any            `json:"MiddleName,omitempty"`
	MobilePhoneNumber     any            `json:"MobilePhoneNumber,omitempty"`
	PartyType             any            `json:"PartyType,omitempty"`
	PhoneNumber           any            `json:"PhoneNumber,omitempty"`
	PostalCode            any            `json:"PostalCode,omitempty"`
	ProfileARN            any            `json:"ProfileARN,omitempty"`
	ProfileId             any            `json:"ProfileId,omitempty"`
	Province              any            `json:"Province,omitempty"`
	ShippingAddress1      any            `json:"ShippingAddress1,omitempty"`
	ShippingAddress2      any            `json:"ShippingAddress2,omitempty"`
	ShippingAddress3      any            `json:"ShippingAddress3,omitempty"`
	ShippingAddress4      any            `json:"ShippingAddress4,omitempty"`
	ShippingCity          any            `json:"ShippingCity,omitempty"`
	ShippingCountry       any            `json:"ShippingCountry,omitempty"`
	ShippingCounty        any            `json:"ShippingCounty,omitempty"`
	ShippingPostalCode    any            `json:"ShippingPostalCode,omitempty"`
	ShippingProvince      any            `json:"ShippingProvince,omitempty"`
	ShippingState         any            `json:"ShippingState,omitempty"`
	State                 any            `json:"State,omitempty"`
}

// MessageTemplate_EmailMessageTemplateContent represents AWS::Wisdom::MessageTemplate.EmailMessageTemplateContent.
type MessageTemplate_EmailMessageTemplateContent struct {
	Body    MessageTemplate_EmailMessageTemplateContentBody `json:"Body,omitempty"`
	Headers []MessageTemplate_EmailMessageTemplateHeader    `json:"Headers,omitempty"`
	Subject any                                             `json:"Subject,omitempty"`
}

// MessageTemplate_EmailMessageTemplateContentBody represents AWS::Wisdom::MessageTemplate.EmailMessageTemplateContentBody.
type MessageTemplate_EmailMessageTemplateContentBody struct {
	Html      *MessageTemplate_MessageTemplateBodyContentProvider `json:"Html,omitempty"`
	PlainText *MessageTemplate_MessageTemplateBodyContentProvider `json:"PlainText,omitempty"`
}

// MessageTemplate_EmailMessageTemplateHeader represents AWS::Wisdom::MessageTemplate.EmailMessageTemplateHeader.
type MessageTemplate_EmailMessageTemplateHeader struct {
	Name  any `json:"Name,omitempty"`
	Value any `json:"Value,omitempty"`
}

// MessageTemplate_GroupingConfiguration represents AWS::Wisdom::MessageTemplate.GroupingConfiguration.
type MessageTemplate_GroupingConfiguration struct {
	Criteria any   `json:"Criteria,omitempty"`
	Values   []any `json:"Values,omitempty"`
}

// MessageTemplate_MessageTemplateAttachment represents AWS::Wisdom::MessageTemplate.MessageTemplateAttachment.
type MessageTemplate_MessageTemplateAttachment struct {
	AttachmentId   any `json:"AttachmentId,omitempty"`
	AttachmentName any `json:"AttachmentName,omitempty"`
	S3PresignedUrl any `json:"S3PresignedUrl,omitempty"`
}

// MessageTemplate_MessageTemplateAttributes represents AWS::Wisdom::MessageTemplate.MessageTemplateAttributes.
type MessageTemplate_MessageTemplateAttributes struct {
	AgentAttributes           *MessageTemplate_AgentAttributes           `json:"AgentAttributes,omitempty"`
	CustomAttributes          map[string]any                             `json:"CustomAttributes,omitempty"`
	CustomerProfileAttributes *MessageTemplate_CustomerProfileAttributes `json:"CustomerProfileAttributes,omitempty"`
	SystemAttributes          *MessageTemplate_SystemAttributes          `json:"SystemAttributes,omitempty"`
}

// MessageTemplate_MessageTemplateBodyContentProvider represents AWS::Wisdom::MessageTemplate.MessageTemplateBodyContentProvider.
type MessageTemplate_MessageTemplateBodyContentProvider struct {
	Content any `json:"Content,omitempty"`
}

// MessageTemplate_SmsMessageTemplateContent represents AWS::Wisdom::MessageTemplate.SmsMessageTemplateContent.
type MessageTemplate_SmsMessageTemplateContent struct {
	Body MessageTemplate_SmsMessageTemplateContentBody `json:"Body,omitempty"`
}

// MessageTemplate_SmsMessageTemplateContentBody represents AWS::Wisdom::MessageTemplate.SmsMessageTemplateContentBody.
type MessageTemplate_SmsMessageTemplateContentBody struct {
	PlainText *MessageTemplate_MessageTemplateBodyContentProvider `json:"PlainText,omitempty"`
}

// MessageTemplate_SystemAttributes represents AWS::Wisdom::MessageTemplate.SystemAttributes.
type MessageTemplate_SystemAttributes struct {
	CustomerEndpoint *MessageTemplate_SystemEndpointAttributes `json:"CustomerEndpoint,omitempty"`
	Name             any                                       `json:"Name,omitempty"`
	SystemEndpoint   *MessageTemplate_SystemEndpointAttributes `json:"SystemEndpoint,omitempty"`
}

// MessageTemplate_SystemEndpointAttributes represents AWS::Wisdom::MessageTemplate.SystemEndpointAttributes.
type MessageTemplate_SystemEndpointAttributes struct {
	Address any `json:"Address,omitempty"`
}
