// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package resourceexplorer2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Index represents AWS::ResourceExplorer2::Index.

type Index struct {
	// Attributes for Fn::GetAtt
	Arn        wetwire.AttrRef `json:"-"`
	IndexState wetwire.AttrRef `json:"-"`

	// Properties
	Tags  map[string]any `json:"Tags,omitempty"`
	Type_ any            `json:"Type,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Index) ResourceType() string {
	return "AWS::ResourceExplorer2::Index"
}
