// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package resourceexplorer2

// View_IncludedProperty represents AWS::ResourceExplorer2::View.IncludedProperty.
type View_IncludedProperty struct {
	Name any `json:"Name,omitempty"`
}

// View_SearchFilter represents AWS::ResourceExplorer2::View.SearchFilter.
type View_SearchFilter struct {
	FilterString any `json:"FilterString,omitempty"`
}
