// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package arcregionswitch

// Plan_ArcRoutingControlConfiguration represents AWS::ARCRegionSwitch::Plan.ArcRoutingControlConfiguration.
type Plan_ArcRoutingControlConfiguration struct {
	CrossAccountRole         any `json:"CrossAccountRole,omitempty"`
	ExternalId               any `json:"ExternalId,omitempty"`
	RegionAndRoutingControls any `json:"RegionAndRoutingControls,omitempty"`
	TimeoutMinutes           any `json:"TimeoutMinutes,omitempty"`
}

// Plan_Asg represents AWS::ARCRegionSwitch::Plan.Asg.
type Plan_Asg struct {
	Arn              any `json:"Arn,omitempty"`
	CrossAccountRole any `json:"CrossAccountRole,omitempty"`
	ExternalId       any `json:"ExternalId,omitempty"`
}

// Plan_AssociatedAlarm represents AWS::ARCRegionSwitch::Plan.AssociatedAlarm.
type Plan_AssociatedAlarm struct {
	AlarmType          any `json:"AlarmType,omitempty"`
	CrossAccountRole   any `json:"CrossAccountRole,omitempty"`
	ExternalId         any `json:"ExternalId,omitempty"`
	ResourceIdentifier any `json:"ResourceIdentifier,omitempty"`
}

// Plan_CustomActionLambdaConfiguration represents AWS::ARCRegionSwitch::Plan.CustomActionLambdaConfiguration.
type Plan_CustomActionLambdaConfiguration struct {
	Lambdas              []Plan_Lambdas         `json:"Lambdas,omitempty"`
	RegionToRun          any                    `json:"RegionToRun,omitempty"`
	RetryIntervalMinutes any                    `json:"RetryIntervalMinutes,omitempty"`
	TimeoutMinutes       any                    `json:"TimeoutMinutes,omitempty"`
	Ungraceful           *Plan_LambdaUngraceful `json:"Ungraceful,omitempty"`
}

// Plan_Ec2AsgCapacityIncreaseConfiguration represents AWS::ARCRegionSwitch::Plan.Ec2AsgCapacityIncreaseConfiguration.
type Plan_Ec2AsgCapacityIncreaseConfiguration struct {
	Asgs                       []Plan_Asg          `json:"Asgs,omitempty"`
	CapacityMonitoringApproach any                 `json:"CapacityMonitoringApproach,omitempty"`
	TargetPercent              any                 `json:"TargetPercent,omitempty"`
	TimeoutMinutes             any                 `json:"TimeoutMinutes,omitempty"`
	Ungraceful                 *Plan_Ec2Ungraceful `json:"Ungraceful,omitempty"`
}

// Plan_Ec2Ungraceful represents AWS::ARCRegionSwitch::Plan.Ec2Ungraceful.
type Plan_Ec2Ungraceful struct {
	MinimumSuccessPercentage any `json:"MinimumSuccessPercentage,omitempty"`
}

// Plan_EcsCapacityIncreaseConfiguration represents AWS::ARCRegionSwitch::Plan.EcsCapacityIncreaseConfiguration.
type Plan_EcsCapacityIncreaseConfiguration struct {
	CapacityMonitoringApproach any                 `json:"CapacityMonitoringApproach,omitempty"`
	Services                   []Plan_Service      `json:"Services,omitempty"`
	TargetPercent              any                 `json:"TargetPercent,omitempty"`
	TimeoutMinutes             any                 `json:"TimeoutMinutes,omitempty"`
	Ungraceful                 *Plan_EcsUngraceful `json:"Ungraceful,omitempty"`
}

// Plan_EcsUngraceful represents AWS::ARCRegionSwitch::Plan.EcsUngraceful.
type Plan_EcsUngraceful struct {
	MinimumSuccessPercentage any `json:"MinimumSuccessPercentage,omitempty"`
}

// Plan_EksCluster represents AWS::ARCRegionSwitch::Plan.EksCluster.
type Plan_EksCluster struct {
	ClusterArn       any `json:"ClusterArn,omitempty"`
	CrossAccountRole any `json:"CrossAccountRole,omitempty"`
	ExternalId       any `json:"ExternalId,omitempty"`
}

// Plan_EksResourceScalingConfiguration represents AWS::ARCRegionSwitch::Plan.EksResourceScalingConfiguration.
type Plan_EksResourceScalingConfiguration struct {
	CapacityMonitoringApproach any                                `json:"CapacityMonitoringApproach,omitempty"`
	EksClusters                []Plan_EksCluster                  `json:"EksClusters,omitempty"`
	KubernetesResourceType     Plan_KubernetesResourceType        `json:"KubernetesResourceType,omitempty"`
	ScalingResources           any                                `json:"ScalingResources,omitempty"`
	TargetPercent              any                                `json:"TargetPercent,omitempty"`
	TimeoutMinutes             any                                `json:"TimeoutMinutes,omitempty"`
	Ungraceful                 *Plan_EksResourceScalingUngraceful `json:"Ungraceful,omitempty"`
}

// Plan_EksResourceScalingUngraceful represents AWS::ARCRegionSwitch::Plan.EksResourceScalingUngraceful.
type Plan_EksResourceScalingUngraceful struct {
	MinimumSuccessPercentage any `json:"MinimumSuccessPercentage,omitempty"`
}

// Plan_ExecutionApprovalConfiguration represents AWS::ARCRegionSwitch::Plan.ExecutionApprovalConfiguration.
type Plan_ExecutionApprovalConfiguration struct {
	ApprovalRole   any `json:"ApprovalRole,omitempty"`
	TimeoutMinutes any `json:"TimeoutMinutes,omitempty"`
}

// Plan_ExecutionBlockConfiguration represents AWS::ARCRegionSwitch::Plan.ExecutionBlockConfiguration.
type Plan_ExecutionBlockConfiguration struct {
	ArcRoutingControlConfig      *Plan_ArcRoutingControlConfiguration      `json:"ArcRoutingControlConfig,omitempty"`
	CustomActionLambdaConfig     *Plan_CustomActionLambdaConfiguration     `json:"CustomActionLambdaConfig,omitempty"`
	Ec2AsgCapacityIncreaseConfig *Plan_Ec2AsgCapacityIncreaseConfiguration `json:"Ec2AsgCapacityIncreaseConfig,omitempty"`
	EcsCapacityIncreaseConfig    *Plan_EcsCapacityIncreaseConfiguration    `json:"EcsCapacityIncreaseConfig,omitempty"`
	EksResourceScalingConfig     *Plan_EksResourceScalingConfiguration     `json:"EksResourceScalingConfig,omitempty"`
	ExecutionApprovalConfig      *Plan_ExecutionApprovalConfiguration      `json:"ExecutionApprovalConfig,omitempty"`
	GlobalAuroraConfig           *Plan_GlobalAuroraConfiguration           `json:"GlobalAuroraConfig,omitempty"`
	ParallelConfig               *Plan_ParallelExecutionBlockConfiguration `json:"ParallelConfig,omitempty"`
	RegionSwitchPlanConfig       *Plan_RegionSwitchPlanConfiguration       `json:"RegionSwitchPlanConfig,omitempty"`
	Route53HealthCheckConfig     *Plan_Route53HealthCheckConfiguration     `json:"Route53HealthCheckConfig,omitempty"`
}

// Plan_GlobalAuroraConfiguration represents AWS::ARCRegionSwitch::Plan.GlobalAuroraConfiguration.
type Plan_GlobalAuroraConfiguration struct {
	Behavior                any                          `json:"Behavior,omitempty"`
	CrossAccountRole        any                          `json:"CrossAccountRole,omitempty"`
	DatabaseClusterArns     []any                        `json:"DatabaseClusterArns,omitempty"`
	ExternalId              any                          `json:"ExternalId,omitempty"`
	GlobalClusterIdentifier any                          `json:"GlobalClusterIdentifier,omitempty"`
	TimeoutMinutes          any                          `json:"TimeoutMinutes,omitempty"`
	Ungraceful              *Plan_GlobalAuroraUngraceful `json:"Ungraceful,omitempty"`
}

// Plan_GlobalAuroraUngraceful represents AWS::ARCRegionSwitch::Plan.GlobalAuroraUngraceful.
type Plan_GlobalAuroraUngraceful struct {
	Ungraceful any `json:"Ungraceful,omitempty"`
}

// Plan_KubernetesResourceType represents AWS::ARCRegionSwitch::Plan.KubernetesResourceType.
type Plan_KubernetesResourceType struct {
	ApiVersion any `json:"ApiVersion,omitempty"`
	Kind       any `json:"Kind,omitempty"`
}

// Plan_LambdaUngraceful represents AWS::ARCRegionSwitch::Plan.LambdaUngraceful.
type Plan_LambdaUngraceful struct {
	Behavior any `json:"Behavior,omitempty"`
}

// Plan_Lambdas represents AWS::ARCRegionSwitch::Plan.Lambdas.
type Plan_Lambdas struct {
	Arn              any `json:"Arn,omitempty"`
	CrossAccountRole any `json:"CrossAccountRole,omitempty"`
	ExternalId       any `json:"ExternalId,omitempty"`
}

// Plan_ParallelExecutionBlockConfiguration represents AWS::ARCRegionSwitch::Plan.ParallelExecutionBlockConfiguration.
type Plan_ParallelExecutionBlockConfiguration struct {
	Steps []Plan_Step `json:"Steps,omitempty"`
}

// Plan_RegionSwitchPlanConfiguration represents AWS::ARCRegionSwitch::Plan.RegionSwitchPlanConfiguration.
type Plan_RegionSwitchPlanConfiguration struct {
	Arn              any `json:"Arn,omitempty"`
	CrossAccountRole any `json:"CrossAccountRole,omitempty"`
	ExternalId       any `json:"ExternalId,omitempty"`
}

// Plan_Route53HealthCheckConfiguration represents AWS::ARCRegionSwitch::Plan.Route53HealthCheckConfiguration.
type Plan_Route53HealthCheckConfiguration struct {
	CrossAccountRole any                             `json:"CrossAccountRole,omitempty"`
	ExternalId       any                             `json:"ExternalId,omitempty"`
	HostedZoneId     any                             `json:"HostedZoneId,omitempty"`
	RecordName       any                             `json:"RecordName,omitempty"`
	RecordSets       []Plan_Route53ResourceRecordSet `json:"RecordSets,omitempty"`
	TimeoutMinutes   any                             `json:"TimeoutMinutes,omitempty"`
}

// Plan_Route53ResourceRecordSet represents AWS::ARCRegionSwitch::Plan.Route53ResourceRecordSet.
type Plan_Route53ResourceRecordSet struct {
	RecordSetIdentifier any `json:"RecordSetIdentifier,omitempty"`
	Region              any `json:"Region,omitempty"`
}

// Plan_Service represents AWS::ARCRegionSwitch::Plan.Service.
type Plan_Service struct {
	ClusterArn       any `json:"ClusterArn,omitempty"`
	CrossAccountRole any `json:"CrossAccountRole,omitempty"`
	ExternalId       any `json:"ExternalId,omitempty"`
	ServiceArn       any `json:"ServiceArn,omitempty"`
}

// Plan_Step represents AWS::ARCRegionSwitch::Plan.Step.
type Plan_Step struct {
	Description                 any                              `json:"Description,omitempty"`
	ExecutionBlockConfiguration Plan_ExecutionBlockConfiguration `json:"ExecutionBlockConfiguration,omitempty"`
	ExecutionBlockType          any                              `json:"ExecutionBlockType,omitempty"`
	Name                        any                              `json:"Name,omitempty"`
}

// Plan_Trigger represents AWS::ARCRegionSwitch::Plan.Trigger.
type Plan_Trigger struct {
	Action                           any                     `json:"Action,omitempty"`
	Conditions                       []Plan_TriggerCondition `json:"Conditions,omitempty"`
	Description                      any                     `json:"Description,omitempty"`
	MinDelayMinutesBetweenExecutions any                     `json:"MinDelayMinutesBetweenExecutions,omitempty"`
	TargetRegion                     any                     `json:"TargetRegion,omitempty"`
}

// Plan_TriggerCondition represents AWS::ARCRegionSwitch::Plan.TriggerCondition.
type Plan_TriggerCondition struct {
	AssociatedAlarmName any `json:"AssociatedAlarmName,omitempty"`
	Condition           any `json:"Condition,omitempty"`
}

// Plan_Workflow represents AWS::ARCRegionSwitch::Plan.Workflow.
type Plan_Workflow struct {
	Steps                []Plan_Step `json:"Steps,omitempty"`
	WorkflowDescription  any         `json:"WorkflowDescription,omitempty"`
	WorkflowTargetAction any         `json:"WorkflowTargetAction,omitempty"`
	WorkflowTargetRegion any         `json:"WorkflowTargetRegion,omitempty"`
}
