// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package servicecatalog

// ServiceAction_DefinitionParameter represents AWS::ServiceCatalog::ServiceAction.DefinitionParameter.
type ServiceAction_DefinitionParameter struct {
	Key   any `json:"Key,omitempty"`
	Value any `json:"Value,omitempty"`
}
