// Package string_example contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package string_example

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

var InputString = Param("InputString")
