// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package efs

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// AccessPoint represents AWS::EFS::AccessPoint.

type AccessPoint struct {
	// Attributes for Fn::GetAtt
	AccessPointId wetwire.AttrRef `json:"-"`
	Arn           wetwire.AttrRef `json:"-"`

	// Properties
	AccessPointTags []any `json:"AccessPointTags,omitempty"`
	ClientToken     any   `json:"ClientToken,omitempty"`
	FileSystemId    any   `json:"FileSystemId,omitempty"`
	PosixUser       any   `json:"PosixUser,omitempty"`
	RootDirectory   any   `json:"RootDirectory,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r AccessPoint) ResourceType() string {
	return "AWS::EFS::AccessPoint"
}
