// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package mwaa

// EndpointManagement represents valid values for EndpointManagement.
type EndpointManagement string

const (
	EndpointManagementCustomer EndpointManagement = "CUSTOMER"
	EndpointManagementService  EndpointManagement = "SERVICE"
)

// EnvironmentStatus represents valid values for EnvironmentStatus.
type EnvironmentStatus string

const (
	EnvironmentStatusCreating         EnvironmentStatus = "CREATING"
	EnvironmentStatusCreateFailed     EnvironmentStatus = "CREATE_FAILED"
	EnvironmentStatusAvailable        EnvironmentStatus = "AVAILABLE"
	EnvironmentStatusUpdating         EnvironmentStatus = "UPDATING"
	EnvironmentStatusDeleting         EnvironmentStatus = "DELETING"
	EnvironmentStatusDeleted          EnvironmentStatus = "DELETED"
	EnvironmentStatusUnavailable      EnvironmentStatus = "UNAVAILABLE"
	EnvironmentStatusUpdateFailed     EnvironmentStatus = "UPDATE_FAILED"
	EnvironmentStatusRollingBack      EnvironmentStatus = "ROLLING_BACK"
	EnvironmentStatusCreatingSnapshot EnvironmentStatus = "CREATING_SNAPSHOT"
	EnvironmentStatusPending          EnvironmentStatus = "PENDING"
	EnvironmentStatusMaintenance      EnvironmentStatus = "MAINTENANCE"
)

// LoggingLevel represents valid values for LoggingLevel.
type LoggingLevel string

const (
	LoggingLevelCritical LoggingLevel = "CRITICAL"
	LoggingLevelError    LoggingLevel = "ERROR"
	LoggingLevelWarning  LoggingLevel = "WARNING"
	LoggingLevelInfo     LoggingLevel = "INFO"
	LoggingLevelDebug    LoggingLevel = "DEBUG"
)

// RestApiMethod represents valid values for RestApiMethod.
type RestApiMethod string

const (
	RestApiMethodGet    RestApiMethod = "GET"
	RestApiMethodPut    RestApiMethod = "PUT"
	RestApiMethodPost   RestApiMethod = "POST"
	RestApiMethodPatch  RestApiMethod = "PATCH"
	RestApiMethodDelete RestApiMethod = "DELETE"
)

// Unit represents valid values for Unit.
type Unit string

const (
	UnitSeconds            Unit = "Seconds"
	UnitMicroseconds       Unit = "Microseconds"
	UnitMilliseconds       Unit = "Milliseconds"
	UnitBytes              Unit = "Bytes"
	UnitKilobytes          Unit = "Kilobytes"
	UnitMegabytes          Unit = "Megabytes"
	UnitGigabytes          Unit = "Gigabytes"
	UnitTerabytes          Unit = "Terabytes"
	UnitBits               Unit = "Bits"
	UnitKilobits           Unit = "Kilobits"
	UnitMegabits           Unit = "Megabits"
	UnitGigabits           Unit = "Gigabits"
	UnitTerabits           Unit = "Terabits"
	UnitPercent            Unit = "Percent"
	UnitCount              Unit = "Count"
	UnitBytespersecond     Unit = "Bytes/Second"
	UnitKilobytespersecond Unit = "Kilobytes/Second"
	UnitMegabytespersecond Unit = "Megabytes/Second"
	UnitGigabytespersecond Unit = "Gigabytes/Second"
	UnitTerabytespersecond Unit = "Terabytes/Second"
	UnitBitspersecond      Unit = "Bits/Second"
	UnitKilobitspersecond  Unit = "Kilobits/Second"
	UnitMegabitspersecond  Unit = "Megabits/Second"
	UnitGigabitspersecond  Unit = "Gigabits/Second"
	UnitTerabitspersecond  Unit = "Terabits/Second"
	UnitCountpersecond     Unit = "Count/Second"
	UnitNone               Unit = "None"
)

// UpdateStatus represents valid values for UpdateStatus.
type UpdateStatus string

const (
	UpdateStatusSuccess UpdateStatus = "SUCCESS"
	UpdateStatusPending UpdateStatus = "PENDING"
	UpdateStatusFailed  UpdateStatus = "FAILED"
)

// WebserverAccessMode represents valid values for WebserverAccessMode.
type WebserverAccessMode string

const (
	WebserverAccessModePrivateOnly WebserverAccessMode = "PRIVATE_ONLY"
	WebserverAccessModePublicOnly  WebserverAccessMode = "PUBLIC_ONLY"
)

// WorkerReplacementStrategy represents valid values for WorkerReplacementStrategy.
type WorkerReplacementStrategy string

const (
	WorkerReplacementStrategyForced   WorkerReplacementStrategy = "FORCED"
	WorkerReplacementStrategyGraceful WorkerReplacementStrategy = "GRACEFUL"
)
