// Package template contains CloudFormation resources.
// Database resources: RDS, DynamoDB, etc.
//
// Generated by wetwire-aws import.
package template

import (
	"github.com/lex00/cloudformation-schema-go/enums"
	"github.com/lex00/wetwire-aws-go/resources/dynamodb"
)

var urlTableTimeToLiveSpecification = dynamodb.Table_TimeToLiveSpecification{
	AttributeName: "TTL",
	Enabled: true,
}

var urlTableKeySchema1 = dynamodb.Table_KeySchema{
	AttributeName: "id",
	KeyType: "HASH",
}

var urlTableAttributeDefinition1 = dynamodb.Table_AttributeDefinition{
	AttributeName: "id",
	AttributeType: "S",
}

var UrlTable = dynamodb.Table{
	AttributeDefinitions: []any{urlTableAttributeDefinition1},
	BillingMode: enums.DynamodbBillingModePayPerRequest,
	KeySchema: []any{urlTableKeySchema1},
	TimeToLiveSpecification: urlTableTimeToLiveSpecification,
}
