// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package ses

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// MailManagerRuleSet represents AWS::SES::MailManagerRuleSet.

type MailManagerRuleSet struct {
	// Attributes for Fn::GetAtt
	RuleSetArn wetwire.AttrRef `json:"-"`
	RuleSetId  wetwire.AttrRef `json:"-"`

	// Properties
	RuleSetName any   `json:"RuleSetName,omitempty"`
	Rules       []any `json:"Rules,omitempty"`
	Tags        []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r MailManagerRuleSet) ResourceType() string {
	return "AWS::SES::MailManagerRuleSet"
}
