// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ses

// Template_Template represents AWS::SES::Template.Template.
type Template_Template struct {
	HtmlPart     any `json:"HtmlPart,omitempty"`
	SubjectPart  any `json:"SubjectPart,omitempty"`
	TemplateName any `json:"TemplateName,omitempty"`
	TextPart     any `json:"TextPart,omitempty"`
}
