// Package vpcflowlogss3_cfn contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package vpcflowlogss3_cfn

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// S3AccessLogsBucketName - (Optional) S3 Server Access Logs bucket name for where Amazon S3 should store...
var S3AccessLogsBucketName = Param("S3AccessLogsBucketName")

// VPCFlowLogsBucketKMSKey - (Optional) KMS Key ID or ARN to use for the default encryption. If empty, ser...
var VPCFlowLogsBucketKMSKey = Param("VPCFlowLogsBucketKMSKey")

// VPCFlowLogsBucketKeyEnabled - Set to true to have Amazon S3 use an S3 Bucket Key with server-side encryptio...
var VPCFlowLogsBucketKeyEnabled = Param("VPCFlowLogsBucketKeyEnabled")

// VPCFlowLogsBucketName - (Optional) S3 bucket name where VPC Flow Log data can be published. S3 bucket...
var VPCFlowLogsBucketName = Param("VPCFlowLogsBucketName")

// VPCFlowLogsLogFormat - The fields to include in the flow log record, in the order in which they shou...
var VPCFlowLogsLogFormat = Param("VPCFlowLogsLogFormat")

// VPCFlowLogsMaxAggregationInterval - The maximum interval of time during which a flow of packets is captured and a...
var VPCFlowLogsMaxAggregationInterval = Param("VPCFlowLogsMaxAggregationInterval")

// VPCFlowLogsTrafficType - The type of traffic to log. You can log traffic that the resource accepts or ...
var VPCFlowLogsTrafficType = Param("VPCFlowLogsTrafficType")

// VPCID - ID of the VPC (e.g., vpc-0343606e)
var VPCID = Param("VPCID")

var S3AccessLogsConditionCondition = Not{Equals{S3AccessLogsBucketName, ""}}

var VPCFlowLogsBucketKMSKeyConditionCondition = Not{Equals{VPCFlowLogsBucketKMSKey, ""}}

var VPCFlowLogsNewBucketConditionCondition = Equals{VPCFlowLogsBucketName, ""}
