// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package datasync

// LocationFSxOpenZFS_MountOptions represents AWS::DataSync::LocationFSxOpenZFS.MountOptions.
type LocationFSxOpenZFS_MountOptions struct {
	Version any `json:"Version,omitempty"`
}

// LocationFSxOpenZFS_NFS represents AWS::DataSync::LocationFSxOpenZFS.NFS.
type LocationFSxOpenZFS_NFS struct {
	MountOptions LocationFSxOpenZFS_MountOptions `json:"MountOptions,omitempty"`
}

// LocationFSxOpenZFS_Protocol represents AWS::DataSync::LocationFSxOpenZFS.Protocol.
type LocationFSxOpenZFS_Protocol struct {
	NFS any `json:"NFS,omitempty"`
}
