// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package datasync

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// LocationEFS represents AWS::DataSync::LocationEFS.

type LocationEFS struct {
	// Attributes for Fn::GetAtt
	LocationArn wetwire.AttrRef `json:"-"`
	LocationUri wetwire.AttrRef `json:"-"`

	// Properties
	AccessPointArn          any                   `json:"AccessPointArn,omitempty"`
	Ec2Config               LocationEFS_Ec2Config `json:"Ec2Config,omitempty"`
	EfsFilesystemArn        any                   `json:"EfsFilesystemArn,omitempty"`
	FileSystemAccessRoleArn any                   `json:"FileSystemAccessRoleArn,omitempty"`
	InTransitEncryption     any                   `json:"InTransitEncryption,omitempty"`
	Subdirectory            any                   `json:"Subdirectory,omitempty"`
	Tags                    []any                 `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r LocationEFS) ResourceType() string {
	return "AWS::DataSync::LocationEFS"
}
