// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package datasync

// LocationAzureBlob_AzureBlobSasConfiguration represents AWS::DataSync::LocationAzureBlob.AzureBlobSasConfiguration.
type LocationAzureBlob_AzureBlobSasConfiguration struct {
	AzureBlobSasToken any `json:"AzureBlobSasToken,omitempty"`
}

// LocationAzureBlob_CmkSecretConfig represents AWS::DataSync::LocationAzureBlob.CmkSecretConfig.
type LocationAzureBlob_CmkSecretConfig struct {
	KmsKeyArn any `json:"KmsKeyArn,omitempty"`
	SecretArn any `json:"SecretArn,omitempty"`
}

// LocationAzureBlob_CustomSecretConfig represents AWS::DataSync::LocationAzureBlob.CustomSecretConfig.
type LocationAzureBlob_CustomSecretConfig struct {
	SecretAccessRoleArn any `json:"SecretAccessRoleArn,omitempty"`
	SecretArn           any `json:"SecretArn,omitempty"`
}

// LocationAzureBlob_ManagedSecretConfig represents AWS::DataSync::LocationAzureBlob.ManagedSecretConfig.
type LocationAzureBlob_ManagedSecretConfig struct {
	SecretArn any `json:"SecretArn,omitempty"`
}
