// Package rds_mysql_with_read_replica contains CloudFormation resources.
// Database resources: RDS, DynamoDB, etc.
//
// Generated by wetwire-aws import.
package rds_mysql_with_read_replica

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/rds"
)

var MainDBTagName = Tag{
	Key: "Name",
	Value: "Master Database",
}

var MainDB = rds.DBInstance{
	AllocatedStorage: DBAllocatedStorage,
	BackupRetentionPeriod: 7,
	DBInstanceClass: DBInstanceClass,
	DBName: DBName,
	Engine: "MySQL",
	MasterUserPassword: Sub{String: "{{resolve:secretsmanager:${DBCredential}}}"},
	MasterUsername: DBUser,
	MultiAZ: MultiAZ,
	PubliclyAccessible: false,
	StorageEncrypted: true,
	Tags: []any{MainDBTagName},
	VPCSecurityGroups: If{"IsEC2VPC", []any{
	DBEC2SecurityGroup.GroupId,
}, AWS_NO_VALUE},
}

var ReplicaDBTagName = Tag{
	Key: "Name",
	Value: "Read Replica Database",
}

var ReplicaDB = rds.DBInstance{
	DBInstanceClass: DBInstanceClass,
	PubliclyAccessible: false,
	SourceDBInstanceIdentifier: MainDB,
	Tags: []any{ReplicaDBTagName},
}
