// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package managedblockchain

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Node represents AWS::ManagedBlockchain::Node.

type Node struct {
	// Attributes for Fn::GetAtt
	Arn    wetwire.AttrRef `json:"-"`
	NodeId wetwire.AttrRef `json:"-"`

	// Properties
	MemberId          any                    `json:"MemberId,omitempty"`
	NetworkId         any                    `json:"NetworkId,omitempty"`
	NodeConfiguration Node_NodeConfiguration `json:"NodeConfiguration,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Node) ResourceType() string {
	return "AWS::ManagedBlockchain::Node"
}
