// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package refactorspaces

// Application_ApiGatewayProxyInput represents AWS::RefactorSpaces::Application.ApiGatewayProxyInput.
type Application_ApiGatewayProxyInput struct {
	EndpointType any `json:"EndpointType,omitempty"`
	StageName    any `json:"StageName,omitempty"`
}
