// Package neptune contains CloudFormation resources.
// Security resources: IAM, Cognito, KMS, etc.
//
// Generated by wetwire-aws import.
package neptune

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/iam"
)

var NeptuneCloudWatchPolicyPolicyDocument = PolicyDocument{
	Statement: []any{NeptuneCloudWatchPolicyPolicyDocumentStatement0, NeptuneCloudWatchPolicyPolicyDocumentStatement1},
	Version: "2012-10-17",
}

var NeptuneCloudWatchPolicyPolicyDocumentStatement1 = PolicyStatement{
	Action: []any{"logs:CreateLogStream", "logs:PutLogEvents", "logs:DescribeLogStreams", "logs:GetLogEvents"},
	Effect: "Allow",
	Resource: []any{Sub{String: "arn:${AWS::Partition}:logs:*:*:log-group:/aws/neptune/*:log-stream:*"}},
	Sid: "EnableLogStreams",
}

var NeptuneCloudWatchPolicyPolicyDocumentStatement0 = PolicyStatement{
	Action: []any{"logs:CreateLogGroup", "logs:PutRetentionPolicy"},
	Effect: "Allow",
	Resource: []any{Sub{String: "arn:${AWS::Partition}:logs:*:*:log-group:/aws/neptune/*"}},
	Sid: "EnableLogGroups",
}

var NeptuneCloudWatchPolicy = iam.ManagedPolicy{
	Description: "Default policy for CloudWatch logs",
	ManagedPolicyName: Sub{String: "${Env}-${AppName}-neptune-cw-policy-${AWS::Region}"},
	PolicyDocument: NeptuneCloudWatchPolicyPolicyDocument,
}

var NeptuneS3PolicyPolicyDocument = PolicyDocument{
	Statement: []any{NeptuneS3PolicyPolicyDocumentStatement0},
	Version: "2012-10-17",
}

var NeptuneS3PolicyPolicyDocumentStatement0 = PolicyStatement{
	Action: []any{"s3:Get*", "s3:List*"},
	Effect: "Allow",
	Resource: []any{Sub{String: "arn:${AWS::Partition}:s3:::*"}},
	Sid: "AllowNeptuneAccessToS3",
}

var NeptuneS3Policy = iam.ManagedPolicy{
	Description: "Neptune default policy for S3 access for data load",
	ManagedPolicyName: Sub{String: "${Env}-${AppName}-neptune-s3-policy-${AWS::Region}"},
	PolicyDocument: NeptuneS3PolicyPolicyDocument,
}

var NeptuneRoleAssumeRolePolicyDocument = PolicyDocument{
	Statement: []any{NeptuneRoleAssumeRolePolicyDocumentStatement0},
	Version: "2012-10-17",
}

var NeptuneRoleAssumeRolePolicyDocumentStatement0 = PolicyStatement{
	Action: "sts:AssumeRole",
	Effect: "Allow",
	Principal: ServicePrincipal{"monitoring.rds.amazonaws.com", "rds.amazonaws.com"},
}

var NeptuneRole = iam.Role{
	AssumeRolePolicyDocument: NeptuneRoleAssumeRolePolicyDocument,
	ManagedPolicyArns: []any{NeptuneCloudWatchPolicy, NeptuneS3Policy},
	RoleName: Sub{String: "${Env}-${AppName}-neptune-iam-role-${AWS::Region}"},
}
