// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cleanrooms

// ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRule represents AWS::CleanRooms::ConfiguredTableAssociation.ConfiguredTableAssociationAnalysisRule.
type ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRule struct {
	Policy ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRulePolicy `json:"Policy,omitempty"`
	Type_  any                                                                     `json:"Type,omitempty"`
}

// ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleAggregation represents AWS::CleanRooms::ConfiguredTableAssociation.ConfiguredTableAssociationAnalysisRuleAggregation.
type ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleAggregation struct {
	AllowedAdditionalAnalyses []any `json:"AllowedAdditionalAnalyses,omitempty"`
	AllowedResultReceivers    []any `json:"AllowedResultReceivers,omitempty"`
}

// ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleCustom represents AWS::CleanRooms::ConfiguredTableAssociation.ConfiguredTableAssociationAnalysisRuleCustom.
type ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleCustom struct {
	AllowedAdditionalAnalyses []any `json:"AllowedAdditionalAnalyses,omitempty"`
	AllowedResultReceivers    []any `json:"AllowedResultReceivers,omitempty"`
}

// ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleList represents AWS::CleanRooms::ConfiguredTableAssociation.ConfiguredTableAssociationAnalysisRuleList.
type ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleList struct {
	AllowedAdditionalAnalyses []any `json:"AllowedAdditionalAnalyses,omitempty"`
	AllowedResultReceivers    []any `json:"AllowedResultReceivers,omitempty"`
}

// ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRulePolicy represents AWS::CleanRooms::ConfiguredTableAssociation.ConfiguredTableAssociationAnalysisRulePolicy.
type ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRulePolicy struct {
	V1 ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRulePolicyV1 `json:"V1,omitempty"`
}

// ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRulePolicyV1 represents AWS::CleanRooms::ConfiguredTableAssociation.ConfiguredTableAssociationAnalysisRulePolicyV1.
type ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRulePolicyV1 struct {
	Aggregation *ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleAggregation `json:"Aggregation,omitempty"`
	Custom      *ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleCustom      `json:"Custom,omitempty"`
	List        *ConfiguredTableAssociation_ConfiguredTableAssociationAnalysisRuleList        `json:"List,omitempty"`
}
