// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cleanrooms

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ConfiguredTable represents AWS::CleanRooms::ConfiguredTable.

type ConfiguredTable struct {
	// Attributes for Fn::GetAtt
	Arn                       wetwire.AttrRef `json:"-"`
	ConfiguredTableIdentifier wetwire.AttrRef `json:"-"`

	// Properties
	AllowedColumns          []any                          `json:"AllowedColumns,omitempty"`
	AnalysisMethod          any                            `json:"AnalysisMethod,omitempty"`
	AnalysisRules           []ConfiguredTable_AnalysisRule `json:"AnalysisRules,omitempty"`
	Description             any                            `json:"Description,omitempty"`
	Name                    any                            `json:"Name,omitempty"`
	SelectedAnalysisMethods []any                          `json:"SelectedAnalysisMethods,omitempty"`
	TableReference          ConfiguredTable_TableReference `json:"TableReference,omitempty"`
	Tags                    []any                          `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ConfiguredTable) ResourceType() string {
	return "AWS::CleanRooms::ConfiguredTable"
}
