// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package launchwizard

// Deployment_Tags represents AWS::LaunchWizard::Deployment.Tags.
type Deployment_Tags struct {
	Key   any `json:"Key,omitempty"`
	Value any `json:"Value,omitempty"`
}
