// Package template contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package template

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// ClientDomains - Array of domains for CORS
var ClientDomains = Parameter{
	Type: "CommaDelimitedList",
	Description: "Array of domains for CORS",
}
