// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package elasticbeanstalk

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ConfigurationTemplate represents AWS::ElasticBeanstalk::ConfigurationTemplate.

type ConfigurationTemplate struct {
	// Attributes for Fn::GetAtt
	TemplateName wetwire.AttrRef `json:"-"`

	// Properties
	ApplicationName     any   `json:"ApplicationName,omitempty"`
	Description         any   `json:"Description,omitempty"`
	EnvironmentId       any   `json:"EnvironmentId,omitempty"`
	OptionSettings      []any `json:"OptionSettings,omitempty"`
	PlatformArn         any   `json:"PlatformArn,omitempty"`
	SolutionStackName   any   `json:"SolutionStackName,omitempty"`
	SourceConfiguration any   `json:"SourceConfiguration,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ConfigurationTemplate) ResourceType() string {
	return "AWS::ElasticBeanstalk::ConfigurationTemplate"
}
