// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package elasticbeanstalk

// ActionHistoryStatus represents valid values for ActionHistoryStatus.
type ActionHistoryStatus string

const (
	ActionHistoryStatusCompleted ActionHistoryStatus = "Completed"
	ActionHistoryStatusFailed    ActionHistoryStatus = "Failed"
	ActionHistoryStatusUnknown   ActionHistoryStatus = "Unknown"
)

// ActionStatus represents valid values for ActionStatus.
type ActionStatus string

const (
	ActionStatusScheduled ActionStatus = "Scheduled"
	ActionStatusPending   ActionStatus = "Pending"
	ActionStatusRunning   ActionStatus = "Running"
	ActionStatusUnknown   ActionStatus = "Unknown"
)

// ActionType represents valid values for ActionType.
type ActionType string

const (
	ActionTypeInstancerefresh ActionType = "InstanceRefresh"
	ActionTypePlatformupdate  ActionType = "PlatformUpdate"
	ActionTypeUnknown         ActionType = "Unknown"
)

// ApplicationVersionStatus represents valid values for ApplicationVersionStatus.
type ApplicationVersionStatus string

const (
	ApplicationVersionStatusProcessed   ApplicationVersionStatus = "Processed"
	ApplicationVersionStatusUnprocessed ApplicationVersionStatus = "Unprocessed"
	ApplicationVersionStatusFailed      ApplicationVersionStatus = "Failed"
	ApplicationVersionStatusProcessing  ApplicationVersionStatus = "Processing"
	ApplicationVersionStatusBuilding    ApplicationVersionStatus = "Building"
)

// ComputeType represents valid values for ComputeType.
type ComputeType string

const (
	ComputeTypeBuildGeneral1Small  ComputeType = "BUILD_GENERAL1_SMALL"
	ComputeTypeBuildGeneral1Medium ComputeType = "BUILD_GENERAL1_MEDIUM"
	ComputeTypeBuildGeneral1Large  ComputeType = "BUILD_GENERAL1_LARGE"
)

// ConfigurationDeploymentStatus represents valid values for ConfigurationDeploymentStatus.
type ConfigurationDeploymentStatus string

const (
	ConfigurationDeploymentStatusDeployed ConfigurationDeploymentStatus = "deployed"
	ConfigurationDeploymentStatusPending  ConfigurationDeploymentStatus = "pending"
	ConfigurationDeploymentStatusFailed   ConfigurationDeploymentStatus = "failed"
)

// ConfigurationOptionValueType represents valid values for ConfigurationOptionValueType.
type ConfigurationOptionValueType string

const (
	ConfigurationOptionValueTypeScalar ConfigurationOptionValueType = "Scalar"
	ConfigurationOptionValueTypeList   ConfigurationOptionValueType = "List"
)

// EnvironmentHealth represents valid values for EnvironmentHealth.
type EnvironmentHealth string

const (
	EnvironmentHealthGreen  EnvironmentHealth = "Green"
	EnvironmentHealthYellow EnvironmentHealth = "Yellow"
	EnvironmentHealthRed    EnvironmentHealth = "Red"
	EnvironmentHealthGrey   EnvironmentHealth = "Grey"
)

// EnvironmentHealthAttribute represents valid values for EnvironmentHealthAttribute.
type EnvironmentHealthAttribute string

const (
	EnvironmentHealthAttributeStatus             EnvironmentHealthAttribute = "Status"
	EnvironmentHealthAttributeColor              EnvironmentHealthAttribute = "Color"
	EnvironmentHealthAttributeCauses             EnvironmentHealthAttribute = "Causes"
	EnvironmentHealthAttributeApplicationmetrics EnvironmentHealthAttribute = "ApplicationMetrics"
	EnvironmentHealthAttributeInstanceshealth    EnvironmentHealthAttribute = "InstancesHealth"
	EnvironmentHealthAttributeAll                EnvironmentHealthAttribute = "All"
	EnvironmentHealthAttributeHealthstatus       EnvironmentHealthAttribute = "HealthStatus"
	EnvironmentHealthAttributeRefreshedat        EnvironmentHealthAttribute = "RefreshedAt"
)

// EnvironmentHealthStatus represents valid values for EnvironmentHealthStatus.
type EnvironmentHealthStatus string

const (
	EnvironmentHealthStatusNodata    EnvironmentHealthStatus = "NoData"
	EnvironmentHealthStatusUnknown   EnvironmentHealthStatus = "Unknown"
	EnvironmentHealthStatusPending   EnvironmentHealthStatus = "Pending"
	EnvironmentHealthStatusOk        EnvironmentHealthStatus = "Ok"
	EnvironmentHealthStatusInfo      EnvironmentHealthStatus = "Info"
	EnvironmentHealthStatusWarning   EnvironmentHealthStatus = "Warning"
	EnvironmentHealthStatusDegraded  EnvironmentHealthStatus = "Degraded"
	EnvironmentHealthStatusSevere    EnvironmentHealthStatus = "Severe"
	EnvironmentHealthStatusSuspended EnvironmentHealthStatus = "Suspended"
)

// EnvironmentInfoType represents valid values for EnvironmentInfoType.
type EnvironmentInfoType string

const (
	EnvironmentInfoTypeTail   EnvironmentInfoType = "tail"
	EnvironmentInfoTypeBundle EnvironmentInfoType = "bundle"
)

// EnvironmentStatus represents valid values for EnvironmentStatus.
type EnvironmentStatus string

const (
	EnvironmentStatusAborting    EnvironmentStatus = "Aborting"
	EnvironmentStatusLaunching   EnvironmentStatus = "Launching"
	EnvironmentStatusUpdating    EnvironmentStatus = "Updating"
	EnvironmentStatusLinkingfrom EnvironmentStatus = "LinkingFrom"
	EnvironmentStatusLinkingto   EnvironmentStatus = "LinkingTo"
	EnvironmentStatusReady       EnvironmentStatus = "Ready"
	EnvironmentStatusTerminating EnvironmentStatus = "Terminating"
	EnvironmentStatusTerminated  EnvironmentStatus = "Terminated"
)

// EventSeverity represents valid values for EventSeverity.
type EventSeverity string

const (
	EventSeverityTrace EventSeverity = "TRACE"
	EventSeverityDebug EventSeverity = "DEBUG"
	EventSeverityInfo  EventSeverity = "INFO"
	EventSeverityWarn  EventSeverity = "WARN"
	EventSeverityError EventSeverity = "ERROR"
	EventSeverityFatal EventSeverity = "FATAL"
)

// FailureType represents valid values for FailureType.
type FailureType string

const (
	FailureTypeUpdatecancelled         FailureType = "UpdateCancelled"
	FailureTypeCancellationfailed      FailureType = "CancellationFailed"
	FailureTypeRollbackfailed          FailureType = "RollbackFailed"
	FailureTypeRollbacksuccessful      FailureType = "RollbackSuccessful"
	FailureTypeInternalfailure         FailureType = "InternalFailure"
	FailureTypeInvalidenvironmentstate FailureType = "InvalidEnvironmentState"
	FailureTypePermissionserror        FailureType = "PermissionsError"
)

// InstancesHealthAttribute represents valid values for InstancesHealthAttribute.
type InstancesHealthAttribute string

const (
	InstancesHealthAttributeHealthstatus       InstancesHealthAttribute = "HealthStatus"
	InstancesHealthAttributeColor              InstancesHealthAttribute = "Color"
	InstancesHealthAttributeCauses             InstancesHealthAttribute = "Causes"
	InstancesHealthAttributeApplicationmetrics InstancesHealthAttribute = "ApplicationMetrics"
	InstancesHealthAttributeRefreshedat        InstancesHealthAttribute = "RefreshedAt"
	InstancesHealthAttributeLaunchedat         InstancesHealthAttribute = "LaunchedAt"
	InstancesHealthAttributeSystem             InstancesHealthAttribute = "System"
	InstancesHealthAttributeDeployment         InstancesHealthAttribute = "Deployment"
	InstancesHealthAttributeAvailabilityzone   InstancesHealthAttribute = "AvailabilityZone"
	InstancesHealthAttributeInstancetype       InstancesHealthAttribute = "InstanceType"
	InstancesHealthAttributeAll                InstancesHealthAttribute = "All"
)

// PlatformStatus represents valid values for PlatformStatus.
type PlatformStatus string

const (
	PlatformStatusCreating PlatformStatus = "Creating"
	PlatformStatusFailed   PlatformStatus = "Failed"
	PlatformStatusReady    PlatformStatus = "Ready"
	PlatformStatusDeleting PlatformStatus = "Deleting"
	PlatformStatusDeleted  PlatformStatus = "Deleted"
)

// SourceRepository represents valid values for SourceRepository.
type SourceRepository string

const (
	SourceRepositoryCodecommit SourceRepository = "CodeCommit"
	SourceRepositoryS3         SourceRepository = "S3"
)

// SourceType represents valid values for SourceType.
type SourceType string

const (
	SourceTypeGit SourceType = "Git"
	SourceTypeZip SourceType = "Zip"
)

// ValidationSeverity represents valid values for ValidationSeverity.
type ValidationSeverity string

const (
	ValidationSeverityError   ValidationSeverity = "error"
	ValidationSeverityWarning ValidationSeverity = "warning"
)
