// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package mediatailor

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// LiveSource represents AWS::MediaTailor::LiveSource.

type LiveSource struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	HttpPackageConfigurations []any `json:"HttpPackageConfigurations,omitempty"`
	LiveSourceName            any   `json:"LiveSourceName,omitempty"`
	SourceLocationName        any   `json:"SourceLocationName,omitempty"`
	Tags                      []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r LiveSource) ResourceType() string {
	return "AWS::MediaTailor::LiveSource"
}
