// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package autoscaling

// WarmPool represents AWS::AutoScaling::WarmPool.

type WarmPool struct {

	// Properties
	AutoScalingGroupName     any                           `json:"AutoScalingGroupName,omitempty"`
	InstanceReusePolicy      *WarmPool_InstanceReusePolicy `json:"InstanceReusePolicy,omitempty"`
	MaxGroupPreparedCapacity any                           `json:"MaxGroupPreparedCapacity,omitempty"`
	MinSize                  any                           `json:"MinSize,omitempty"`
	PoolState                any                           `json:"PoolState,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r WarmPool) ResourceType() string {
	return "AWS::AutoScaling::WarmPool"
}
