// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package appmesh

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Route represents AWS::AppMesh::Route.

type Route struct {
	// Attributes for Fn::GetAtt
	Arn           wetwire.AttrRef `json:"-"`
	ResourceOwner wetwire.AttrRef `json:"-"`
	Uid           wetwire.AttrRef `json:"-"`

	// Properties
	MeshName          any             `json:"MeshName,omitempty"`
	MeshOwner         any             `json:"MeshOwner,omitempty"`
	RouteName         any             `json:"RouteName,omitempty"`
	Spec              Route_RouteSpec `json:"Spec,omitempty"`
	Tags              []any           `json:"Tags,omitempty"`
	VirtualRouterName any             `json:"VirtualRouterName,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Route) ResourceType() string {
	return "AWS::AppMesh::Route"
}
