// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package devopsguru

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ResourceCollection represents AWS::DevOpsGuru::ResourceCollection.

type ResourceCollection struct {
	// Attributes for Fn::GetAtt
	ResourceCollectionType wetwire.AttrRef `json:"-"`

	// Properties
	ResourceCollectionFilter ResourceCollection_ResourceCollectionFilter `json:"ResourceCollectionFilter,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ResourceCollection) ResourceType() string {
	return "AWS::DevOpsGuru::ResourceCollection"
}
