// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:23-07:00

package securityhub

// SecurityControl_ParameterConfiguration represents AWS::SecurityHub::SecurityControl.ParameterConfiguration.
type SecurityControl_ParameterConfiguration struct {
	Value     any `json:"Value,omitempty"`
	ValueType any `json:"ValueType,omitempty"`
}

// SecurityControl_ParameterValue represents AWS::SecurityHub::SecurityControl.ParameterValue.
type SecurityControl_ParameterValue struct {
	Boolean     any   `json:"Boolean,omitempty"`
	Double      any   `json:"Double,omitempty"`
	Enum        any   `json:"Enum,omitempty"`
	EnumList    []any `json:"EnumList,omitempty"`
	Integer     any   `json:"Integer,omitempty"`
	IntegerList []any `json:"IntegerList,omitempty"`
	String      any   `json:"String,omitempty"`
	StringList  []any `json:"StringList,omitempty"`
}
