// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package securityhub

// SecurityControl represents AWS::SecurityHub::SecurityControl.

type SecurityControl struct {

	// Properties
	LastUpdateReason   any                                               `json:"LastUpdateReason,omitempty"`
	Parameters         map[string]SecurityControl_ParameterConfiguration `json:"Parameters,omitempty"`
	SecurityControlArn any                                               `json:"SecurityControlArn,omitempty"`
	SecurityControlId  any                                               `json:"SecurityControlId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r SecurityControl) ResourceType() string {
	return "AWS::SecurityHub::SecurityControl"
}
