// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:23-07:00

package securityhub

// Standard_StandardsControl represents AWS::SecurityHub::Standard.StandardsControl.
type Standard_StandardsControl struct {
	Reason              any `json:"Reason,omitempty"`
	StandardsControlArn any `json:"StandardsControlArn,omitempty"`
}
