// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ssm

// MaintenanceWindow represents AWS::SSM::MaintenanceWindow.

type MaintenanceWindow struct {

	// Properties
	AllowUnassociatedTargets any   `json:"AllowUnassociatedTargets,omitempty"`
	Cutoff                   any   `json:"Cutoff,omitempty"`
	Description              any   `json:"Description,omitempty"`
	Duration                 any   `json:"Duration,omitempty"`
	EndDate                  any   `json:"EndDate,omitempty"`
	Name                     any   `json:"Name,omitempty"`
	Schedule                 any   `json:"Schedule,omitempty"`
	ScheduleOffset           any   `json:"ScheduleOffset,omitempty"`
	ScheduleTimezone         any   `json:"ScheduleTimezone,omitempty"`
	StartDate                any   `json:"StartDate,omitempty"`
	Tags                     []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r MaintenanceWindow) ResourceType() string {
	return "AWS::SSM::MaintenanceWindow"
}
