// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ssm

// PatchBaseline_PatchFilter represents AWS::SSM::PatchBaseline.PatchFilter.
type PatchBaseline_PatchFilter struct {
	Key    any   `json:"Key,omitempty"`
	Values []any `json:"Values,omitempty"`
}

// PatchBaseline_PatchFilterGroup represents AWS::SSM::PatchBaseline.PatchFilterGroup.
type PatchBaseline_PatchFilterGroup struct {
	PatchFilters []PatchBaseline_PatchFilter `json:"PatchFilters,omitempty"`
}

// PatchBaseline_PatchSource represents AWS::SSM::PatchBaseline.PatchSource.
type PatchBaseline_PatchSource struct {
	Configuration any   `json:"Configuration,omitempty"`
	Name          any   `json:"Name,omitempty"`
	Products      []any `json:"Products,omitempty"`
}

// PatchBaseline_Rule represents AWS::SSM::PatchBaseline.Rule.
type PatchBaseline_Rule struct {
	ApproveAfterDays  any                             `json:"ApproveAfterDays,omitempty"`
	ApproveUntilDate  any                             `json:"ApproveUntilDate,omitempty"`
	ComplianceLevel   any                             `json:"ComplianceLevel,omitempty"`
	EnableNonSecurity any                             `json:"EnableNonSecurity,omitempty"`
	PatchFilterGroup  *PatchBaseline_PatchFilterGroup `json:"PatchFilterGroup,omitempty"`
}

// PatchBaseline_RuleGroup represents AWS::SSM::PatchBaseline.RuleGroup.
type PatchBaseline_RuleGroup struct {
	PatchRules []PatchBaseline_Rule `json:"PatchRules,omitempty"`
}
