// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ssm

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ResourcePolicy represents AWS::SSM::ResourcePolicy.

type ResourcePolicy struct {
	// Attributes for Fn::GetAtt
	PolicyHash wetwire.AttrRef `json:"-"`
	PolicyId   wetwire.AttrRef `json:"-"`

	// Properties
	Policy      any `json:"Policy,omitempty"`
	ResourceArn any `json:"ResourceArn,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ResourcePolicy) ResourceType() string {
	return "AWS::SSM::ResourcePolicy"
}
