// Package autoscalingmultiazwithnotifications contains CloudFormation resources.
// Compute resources: EC2, Lambda, ECS, etc.
//
// Generated by wetwire-aws import.
package autoscalingmultiazwithnotifications

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/autoscaling"
	"github.com/lex00/wetwire-aws-go/resources/ec2"
)

var LaunchTemplateLaunchTemplateDataBlockDeviceMappingDevsda1Ebs = &ec2.EC2Fleet_EbsBlockDevice{
	VolumeSize: 32,
}

var LaunchTemplateLaunchTemplateDataTagSpecification1 = ec2.CapacityReservationFleet_TagSpecification{
	ResourceTypeProp: "instance",
	Tags: []any{map[string]any{"Key": "Name", "Value": Sub{String: "${AWS::StackName}-Instance"}}},
}

var LaunchTemplateLaunchTemplateDataBlockDeviceMappingDevsda1 = ec2.EC2Fleet_BlockDeviceMapping{
	DeviceName: "/dev/sda1",
	Ebs: LaunchTemplateLaunchTemplateDataBlockDeviceMappingDevsda1Ebs,
}

var LaunchTemplateLaunchTemplateData = ec2.LaunchTemplate_LaunchTemplateData{
	BlockDeviceMappings: List(LaunchTemplateLaunchTemplateDataBlockDeviceMappingDevsda1),
	ImageId: LatestAmiId,
	InstanceType: InstanceType,
	KeyName: KeyName,
	SecurityGroupIds: SecurityGroups,
	TagSpecifications: List(LaunchTemplateLaunchTemplateDataTagSpecification1),
	UserData: Base64{Sub{String: "#!/bin/bash\n/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchTemplate --region ${AWS::Region}\n/opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WebServerGroup --region ${AWS::Region}\n"}},
}

var LaunchTemplate = ec2.LaunchTemplate{
	LaunchTemplateData: LaunchTemplateLaunchTemplateData,
	LaunchTemplateName: Sub{String: "${AWS::StackName}-LaunchTemplate"},
}

var WebServerGroupNotificationConfiguration1 = autoscaling.AutoScalingGroup_NotificationConfiguration{
	NotificationTypes: []any{"autoscaling:EC2_INSTANCE_LAUNCH", "autoscaling:EC2_INSTANCE_LAUNCH_ERROR", "autoscaling:EC2_INSTANCE_TERMINATE", "autoscaling:EC2_INSTANCE_TERMINATE_ERROR"},
	TopicARN: NotificationTopic,
}

var WebServerGroupLaunchTemplate = &autoscaling.AutoScalingGroup_LaunchTemplateSpecification{
	LaunchTemplateId: LaunchTemplate,
	Version: LaunchTemplate.LatestVersionNumber,
}

var WebServerGroup = autoscaling.AutoScalingGroup{
	AvailabilityZones: AZs,
	HealthCheckType: "ELB",
	LaunchTemplate: WebServerGroupLaunchTemplate,
	MaxSize: "3",
	MinSize: "1",
	NotificationConfigurations: List(WebServerGroupNotificationConfiguration1),
	TargetGroupARNs: []any{TargetGroup},
	VPCZoneIdentifier: Subnets,
}

var WebServerScaleUpPolicy = autoscaling.ScalingPolicy{
	AdjustmentType: "ChangeInCapacity",
	AutoScalingGroupName: WebServerGroup,
	Cooldown: "60",
	ScalingAdjustment: 1,
}

var WebServerScaleDownPolicy = autoscaling.ScalingPolicy{
	AdjustmentType: "ChangeInCapacity",
	AutoScalingGroupName: WebServerGroup,
	Cooldown: "60",
	ScalingAdjustment: -1,
}
