// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package osis

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Pipeline represents AWS::OSIS::Pipeline.

type Pipeline struct {
	// Attributes for Fn::GetAtt
	IngestEndpointUrls wetwire.AttrRef `json:"-"`
	PipelineArn        wetwire.AttrRef `json:"-"`
	VpcEndpointService wetwire.AttrRef `json:"-"`
	VpcEndpoints       wetwire.AttrRef `json:"-"`

	// Properties
	BufferOptions             *Pipeline_BufferOptions           `json:"BufferOptions,omitempty"`
	EncryptionAtRestOptions   *Pipeline_EncryptionAtRestOptions `json:"EncryptionAtRestOptions,omitempty"`
	LogPublishingOptions      *Pipeline_LogPublishingOptions    `json:"LogPublishingOptions,omitempty"`
	MaxUnits                  any                               `json:"MaxUnits,omitempty"`
	MinUnits                  any                               `json:"MinUnits,omitempty"`
	PipelineConfigurationBody any                               `json:"PipelineConfigurationBody,omitempty"`
	PipelineName              any                               `json:"PipelineName,omitempty"`
	PipelineRoleArn           any                               `json:"PipelineRoleArn,omitempty"`
	ResourcePolicy            *Pipeline_ResourcePolicy          `json:"ResourcePolicy,omitempty"`
	Tags                      []any                             `json:"Tags,omitempty"`
	VpcOptions                *Pipeline_VpcOptions              `json:"VpcOptions,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Pipeline) ResourceType() string {
	return "AWS::OSIS::Pipeline"
}
