// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package wafregional

// GeoMatchSet_GeoMatchConstraint represents AWS::WAFRegional::GeoMatchSet.GeoMatchConstraint.
type GeoMatchSet_GeoMatchConstraint struct {
	Type_ any `json:"Type,omitempty"`
	Value any `json:"Value,omitempty"`
}
