// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package appsync

// Resolver_AppSyncRuntime represents AWS::AppSync::Resolver.AppSyncRuntime.
type Resolver_AppSyncRuntime struct {
	Name           any `json:"Name,omitempty"`
	RuntimeVersion any `json:"RuntimeVersion,omitempty"`
}

// Resolver_CachingConfig represents AWS::AppSync::Resolver.CachingConfig.
type Resolver_CachingConfig struct {
	CachingKeys []any `json:"CachingKeys,omitempty"`
	Ttl         any   `json:"Ttl,omitempty"`
}

// Resolver_LambdaConflictHandlerConfig represents AWS::AppSync::Resolver.LambdaConflictHandlerConfig.
type Resolver_LambdaConflictHandlerConfig struct {
	LambdaConflictHandlerArn any `json:"LambdaConflictHandlerArn,omitempty"`
}

// Resolver_PipelineConfig represents AWS::AppSync::Resolver.PipelineConfig.
type Resolver_PipelineConfig struct {
	Functions []any `json:"Functions,omitempty"`
}

// Resolver_SyncConfig represents AWS::AppSync::Resolver.SyncConfig.
type Resolver_SyncConfig struct {
	ConflictDetection           any                                                `json:"ConflictDetection,omitempty"`
	ConflictHandler             any                                                `json:"ConflictHandler,omitempty"`
	LambdaConflictHandlerConfig *FunctionConfiguration_LambdaConflictHandlerConfig `json:"LambdaConflictHandlerConfig,omitempty"`
}
