// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package codecommit

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Repository represents AWS::CodeCommit::Repository.

type Repository struct {
	// Attributes for Fn::GetAtt
	Arn          wetwire.AttrRef `json:"-"`
	CloneUrlHttp wetwire.AttrRef `json:"-"`
	CloneUrlSsh  wetwire.AttrRef `json:"-"`
	Name         wetwire.AttrRef `json:"-"`

	// Properties
	Code                  *Repository_Code               `json:"Code,omitempty"`
	KmsKeyId              any                            `json:"KmsKeyId,omitempty"`
	RepositoryDescription any                            `json:"RepositoryDescription,omitempty"`
	RepositoryName        any                            `json:"RepositoryName,omitempty"`
	Tags                  []any                          `json:"Tags,omitempty"`
	Triggers              []Repository_RepositoryTrigger `json:"Triggers,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Repository) ResourceType() string {
	return "AWS::CodeCommit::Repository"
}
