// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package panorama

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Package represents AWS::Panorama::Package.

type Package struct {
	// Attributes for Fn::GetAtt
	Arn                                     wetwire.AttrRef `json:"-"`
	CreatedTime                             wetwire.AttrRef `json:"-"`
	PackageId                               wetwire.AttrRef `json:"-"`
	StorageLocation_BinaryPrefixLocation    wetwire.AttrRef `json:"-"`
	StorageLocation_Bucket                  wetwire.AttrRef `json:"-"`
	StorageLocation_GeneratedPrefixLocation wetwire.AttrRef `json:"-"`
	StorageLocation_ManifestPrefixLocation  wetwire.AttrRef `json:"-"`
	StorageLocation_RepoPrefixLocation      wetwire.AttrRef `json:"-"`

	// Properties
	PackageName     any                      `json:"PackageName,omitempty"`
	StorageLocation *Package_StorageLocation `json:"StorageLocation,omitempty"`
	Tags            []any                    `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Package) ResourceType() string {
	return "AWS::Panorama::Package"
}
