// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package healthlake

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// FHIRDatastore represents AWS::HealthLake::FHIRDatastore.

type FHIRDatastore struct {
	// Attributes for Fn::GetAtt
	CreatedAt         wetwire.AttrRef `json:"-"`
	CreatedAt_Nanos   wetwire.AttrRef `json:"-"`
	CreatedAt_Seconds wetwire.AttrRef `json:"-"`
	DatastoreArn      wetwire.AttrRef `json:"-"`
	DatastoreEndpoint wetwire.AttrRef `json:"-"`
	DatastoreId       wetwire.AttrRef `json:"-"`
	DatastoreStatus   wetwire.AttrRef `json:"-"`

	// Properties
	DatastoreName                 any                                          `json:"DatastoreName,omitempty"`
	DatastoreTypeVersion          any                                          `json:"DatastoreTypeVersion,omitempty"`
	IdentityProviderConfiguration *FHIRDatastore_IdentityProviderConfiguration `json:"IdentityProviderConfiguration,omitempty"`
	PreloadDataConfig             *FHIRDatastore_PreloadDataConfig             `json:"PreloadDataConfig,omitempty"`
	SseConfiguration              *FHIRDatastore_SseConfiguration              `json:"SseConfiguration,omitempty"`
	Tags                          []any                                        `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r FHIRDatastore) ResourceType() string {
	return "AWS::HealthLake::FHIRDatastore"
}
