// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package vpclattice

// Rule_Action represents AWS::VpcLattice::Rule.Action.
type Rule_Action struct {
	FixedResponse *Listener_FixedResponse `json:"FixedResponse,omitempty"`
	Forward       *Listener_Forward       `json:"Forward,omitempty"`
}

// Rule_FixedResponse represents AWS::VpcLattice::Rule.FixedResponse.
type Rule_FixedResponse struct {
	StatusCode any `json:"StatusCode,omitempty"`
}

// Rule_Forward represents AWS::VpcLattice::Rule.Forward.
type Rule_Forward struct {
	TargetGroups []Listener_WeightedTargetGroup `json:"TargetGroups,omitempty"`
}

// Rule_HeaderMatch represents AWS::VpcLattice::Rule.HeaderMatch.
type Rule_HeaderMatch struct {
	CaseSensitive any                  `json:"CaseSensitive,omitempty"`
	Match         Rule_HeaderMatchType `json:"Match,omitempty"`
	Name          any                  `json:"Name,omitempty"`
}

// Rule_HeaderMatchType represents AWS::VpcLattice::Rule.HeaderMatchType.
type Rule_HeaderMatchType struct {
	Contains any `json:"Contains,omitempty"`
	Exact    any `json:"Exact,omitempty"`
	Prefix   any `json:"Prefix,omitempty"`
}

// Rule_HttpMatch represents AWS::VpcLattice::Rule.HttpMatch.
type Rule_HttpMatch struct {
	HeaderMatches []Rule_HeaderMatch `json:"HeaderMatches,omitempty"`
	Method        any                `json:"Method,omitempty"`
	PathMatch     *Rule_PathMatch    `json:"PathMatch,omitempty"`
}

// Rule_Match represents AWS::VpcLattice::Rule.Match.
type Rule_Match struct {
	HttpMatch Rule_HttpMatch `json:"HttpMatch,omitempty"`
}

// Rule_PathMatch represents AWS::VpcLattice::Rule.PathMatch.
type Rule_PathMatch struct {
	CaseSensitive any                `json:"CaseSensitive,omitempty"`
	Match         Rule_PathMatchType `json:"Match,omitempty"`
}

// Rule_PathMatchType represents AWS::VpcLattice::Rule.PathMatchType.
type Rule_PathMatchType struct {
	Exact  any `json:"Exact,omitempty"`
	Prefix any `json:"Prefix,omitempty"`
}

// Rule_WeightedTargetGroup represents AWS::VpcLattice::Rule.WeightedTargetGroup.
type Rule_WeightedTargetGroup struct {
	TargetGroupIdentifier any `json:"TargetGroupIdentifier,omitempty"`
	Weight                any `json:"Weight,omitempty"`
}
