// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package paymentcryptography

// Alias represents AWS::PaymentCryptography::Alias.

type Alias struct {

	// Properties
	AliasName any `json:"AliasName,omitempty"`
	KeyArn    any `json:"KeyArn,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Alias) ResourceType() string {
	return "AWS::PaymentCryptography::Alias"
}
