// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package pinpoint

// Campaign_AttributeDimension represents AWS::Pinpoint::Campaign.AttributeDimension.
type Campaign_AttributeDimension struct {
	AttributeType any   `json:"AttributeType,omitempty"`
	Values        []any `json:"Values,omitempty"`
}

// Campaign_CampaignCustomMessage represents AWS::Pinpoint::Campaign.CampaignCustomMessage.
type Campaign_CampaignCustomMessage struct {
	Data any `json:"Data,omitempty"`
}

// Campaign_CampaignEmailMessage represents AWS::Pinpoint::Campaign.CampaignEmailMessage.
type Campaign_CampaignEmailMessage struct {
	Body        any `json:"Body,omitempty"`
	FromAddress any `json:"FromAddress,omitempty"`
	HtmlBody    any `json:"HtmlBody,omitempty"`
	Title       any `json:"Title,omitempty"`
}

// Campaign_CampaignEventFilter represents AWS::Pinpoint::Campaign.CampaignEventFilter.
type Campaign_CampaignEventFilter struct {
	Dimensions *Campaign_EventDimensions `json:"Dimensions,omitempty"`
	FilterType any                       `json:"FilterType,omitempty"`
}

// Campaign_CampaignHook represents AWS::Pinpoint::Campaign.CampaignHook.
type Campaign_CampaignHook struct {
	LambdaFunctionName any `json:"LambdaFunctionName,omitempty"`
	Mode               any `json:"Mode,omitempty"`
	WebUrl             any `json:"WebUrl,omitempty"`
}

// Campaign_CampaignInAppMessage represents AWS::Pinpoint::Campaign.CampaignInAppMessage.
type Campaign_CampaignInAppMessage struct {
	Content      []Campaign_InAppMessageContent `json:"Content,omitempty"`
	CustomConfig any                            `json:"CustomConfig,omitempty"`
	Layout       any                            `json:"Layout,omitempty"`
}

// Campaign_CampaignSmsMessage represents AWS::Pinpoint::Campaign.CampaignSmsMessage.
type Campaign_CampaignSmsMessage struct {
	Body              any `json:"Body,omitempty"`
	EntityId          any `json:"EntityId,omitempty"`
	MessageType       any `json:"MessageType,omitempty"`
	OriginationNumber any `json:"OriginationNumber,omitempty"`
	SenderId          any `json:"SenderId,omitempty"`
	TemplateId        any `json:"TemplateId,omitempty"`
}

// Campaign_CustomDeliveryConfiguration represents AWS::Pinpoint::Campaign.CustomDeliveryConfiguration.
type Campaign_CustomDeliveryConfiguration struct {
	DeliveryUri   any   `json:"DeliveryUri,omitempty"`
	EndpointTypes []any `json:"EndpointTypes,omitempty"`
}

// Campaign_DefaultButtonConfiguration represents AWS::Pinpoint::Campaign.DefaultButtonConfiguration.
type Campaign_DefaultButtonConfiguration struct {
	BackgroundColor any `json:"BackgroundColor,omitempty"`
	BorderRadius    any `json:"BorderRadius,omitempty"`
	ButtonAction    any `json:"ButtonAction,omitempty"`
	Link            any `json:"Link,omitempty"`
	Text            any `json:"Text,omitempty"`
	TextColor       any `json:"TextColor,omitempty"`
}

// Campaign_EventDimensions represents AWS::Pinpoint::Campaign.EventDimensions.
type Campaign_EventDimensions struct {
	Attributes any                    `json:"Attributes,omitempty"`
	EventType  *Campaign_SetDimension `json:"EventType,omitempty"`
	Metrics    any                    `json:"Metrics,omitempty"`
}

// Campaign_InAppMessageBodyConfig represents AWS::Pinpoint::Campaign.InAppMessageBodyConfig.
type Campaign_InAppMessageBodyConfig struct {
	Alignment any `json:"Alignment,omitempty"`
	Body      any `json:"Body,omitempty"`
	TextColor any `json:"TextColor,omitempty"`
}

// Campaign_InAppMessageButton represents AWS::Pinpoint::Campaign.InAppMessageButton.
type Campaign_InAppMessageButton struct {
	Android       *Campaign_OverrideButtonConfiguration `json:"Android,omitempty"`
	DefaultConfig *Campaign_DefaultButtonConfiguration  `json:"DefaultConfig,omitempty"`
	IOS           *Campaign_OverrideButtonConfiguration `json:"IOS,omitempty"`
	Web           *Campaign_OverrideButtonConfiguration `json:"Web,omitempty"`
}

// Campaign_InAppMessageContent represents AWS::Pinpoint::Campaign.InAppMessageContent.
type Campaign_InAppMessageContent struct {
	BackgroundColor any                                `json:"BackgroundColor,omitempty"`
	BodyConfig      *Campaign_InAppMessageBodyConfig   `json:"BodyConfig,omitempty"`
	HeaderConfig    *Campaign_InAppMessageHeaderConfig `json:"HeaderConfig,omitempty"`
	ImageUrl        any                                `json:"ImageUrl,omitempty"`
	PrimaryBtn      *Campaign_InAppMessageButton       `json:"PrimaryBtn,omitempty"`
	SecondaryBtn    *Campaign_InAppMessageButton       `json:"SecondaryBtn,omitempty"`
}

// Campaign_InAppMessageHeaderConfig represents AWS::Pinpoint::Campaign.InAppMessageHeaderConfig.
type Campaign_InAppMessageHeaderConfig struct {
	Alignment any `json:"Alignment,omitempty"`
	Header    any `json:"Header,omitempty"`
	TextColor any `json:"TextColor,omitempty"`
}

// Campaign_Limits represents AWS::Pinpoint::Campaign.Limits.
type Campaign_Limits struct {
	Daily             any `json:"Daily,omitempty"`
	MaximumDuration   any `json:"MaximumDuration,omitempty"`
	MessagesPerSecond any `json:"MessagesPerSecond,omitempty"`
	Session           any `json:"Session,omitempty"`
	Total             any `json:"Total,omitempty"`
}

// Campaign_Message represents AWS::Pinpoint::Campaign.Message.
type Campaign_Message struct {
	Action            any `json:"Action,omitempty"`
	Body              any `json:"Body,omitempty"`
	ImageIconUrl      any `json:"ImageIconUrl,omitempty"`
	ImageSmallIconUrl any `json:"ImageSmallIconUrl,omitempty"`
	ImageUrl          any `json:"ImageUrl,omitempty"`
	JsonBody          any `json:"JsonBody,omitempty"`
	MediaUrl          any `json:"MediaUrl,omitempty"`
	RawContent        any `json:"RawContent,omitempty"`
	SilentPush        any `json:"SilentPush,omitempty"`
	TimeToLive        any `json:"TimeToLive,omitempty"`
	Title             any `json:"Title,omitempty"`
	Url               any `json:"Url,omitempty"`
}

// Campaign_MessageConfiguration represents AWS::Pinpoint::Campaign.MessageConfiguration.
type Campaign_MessageConfiguration struct {
	ADMMessage     *Campaign_Message               `json:"ADMMessage,omitempty"`
	APNSMessage    *Campaign_Message               `json:"APNSMessage,omitempty"`
	BaiduMessage   *Campaign_Message               `json:"BaiduMessage,omitempty"`
	CustomMessage  *Campaign_CampaignCustomMessage `json:"CustomMessage,omitempty"`
	DefaultMessage *Campaign_Message               `json:"DefaultMessage,omitempty"`
	EmailMessage   *Campaign_CampaignEmailMessage  `json:"EmailMessage,omitempty"`
	GCMMessage     *Campaign_Message               `json:"GCMMessage,omitempty"`
	InAppMessage   *Campaign_CampaignInAppMessage  `json:"InAppMessage,omitempty"`
	SMSMessage     *Campaign_CampaignSmsMessage    `json:"SMSMessage,omitempty"`
}

// Campaign_MetricDimension represents AWS::Pinpoint::Campaign.MetricDimension.
type Campaign_MetricDimension struct {
	ComparisonOperator any `json:"ComparisonOperator,omitempty"`
	Value              any `json:"Value,omitempty"`
}

// Campaign_OverrideButtonConfiguration represents AWS::Pinpoint::Campaign.OverrideButtonConfiguration.
type Campaign_OverrideButtonConfiguration struct {
	ButtonAction any `json:"ButtonAction,omitempty"`
	Link         any `json:"Link,omitempty"`
}

// Campaign_QuietTime represents AWS::Pinpoint::Campaign.QuietTime.
type Campaign_QuietTime struct {
	End   any `json:"End,omitempty"`
	Start any `json:"Start,omitempty"`
}

// Campaign_Schedule represents AWS::Pinpoint::Campaign.Schedule.
type Campaign_Schedule struct {
	EndTime     any                            `json:"EndTime,omitempty"`
	EventFilter *Campaign_CampaignEventFilter  `json:"EventFilter,omitempty"`
	Frequency   any                            `json:"Frequency,omitempty"`
	IsLocalTime any                            `json:"IsLocalTime,omitempty"`
	QuietTime   *ApplicationSettings_QuietTime `json:"QuietTime,omitempty"`
	StartTime   any                            `json:"StartTime,omitempty"`
	TimeZone    any                            `json:"TimeZone,omitempty"`
}

// Campaign_SetDimension represents AWS::Pinpoint::Campaign.SetDimension.
type Campaign_SetDimension struct {
	DimensionType any   `json:"DimensionType,omitempty"`
	Values        []any `json:"Values,omitempty"`
}

// Campaign_Template represents AWS::Pinpoint::Campaign.Template.
type Campaign_Template struct {
	Name    any `json:"Name,omitempty"`
	Version any `json:"Version,omitempty"`
}

// Campaign_TemplateConfiguration represents AWS::Pinpoint::Campaign.TemplateConfiguration.
type Campaign_TemplateConfiguration struct {
	EmailTemplate *Campaign_Template `json:"EmailTemplate,omitempty"`
	PushTemplate  *Campaign_Template `json:"PushTemplate,omitempty"`
	SMSTemplate   *Campaign_Template `json:"SMSTemplate,omitempty"`
	VoiceTemplate *Campaign_Template `json:"VoiceTemplate,omitempty"`
}

// Campaign_WriteTreatmentResource represents AWS::Pinpoint::Campaign.WriteTreatmentResource.
type Campaign_WriteTreatmentResource struct {
	CustomDeliveryConfiguration *Campaign_CustomDeliveryConfiguration `json:"CustomDeliveryConfiguration,omitempty"`
	MessageConfiguration        *Campaign_MessageConfiguration        `json:"MessageConfiguration,omitempty"`
	Schedule                    *Campaign_Schedule                    `json:"Schedule,omitempty"`
	SizePercent                 any                                   `json:"SizePercent,omitempty"`
	TemplateConfiguration       *Campaign_TemplateConfiguration       `json:"TemplateConfiguration,omitempty"`
	TreatmentDescription        any                                   `json:"TreatmentDescription,omitempty"`
	TreatmentName               any                                   `json:"TreatmentName,omitempty"`
}
