// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package pinpoint

// EventStream represents AWS::Pinpoint::EventStream.

type EventStream struct {

	// Properties
	ApplicationId        any `json:"ApplicationId,omitempty"`
	DestinationStreamArn any `json:"DestinationStreamArn,omitempty"`
	RoleArn              any `json:"RoleArn,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r EventStream) ResourceType() string {
	return "AWS::Pinpoint::EventStream"
}
