// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package memorydb

// User_AuthenticationMode represents AWS::MemoryDB::User.AuthenticationMode.
type User_AuthenticationMode struct {
	Passwords []any `json:"Passwords,omitempty"`
	Type_     any   `json:"Type,omitempty"`
}
