// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package waf

// XssMatchSet represents AWS::WAF::XssMatchSet.

type XssMatchSet struct {

	// Properties
	Name           any   `json:"Name,omitempty"`
	XssMatchTuples []any `json:"XssMatchTuples,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r XssMatchSet) ResourceType() string {
	return "AWS::WAF::XssMatchSet"
}
