// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package lex

// BotAlias_AudioLogDestination represents AWS::Lex::BotAlias.AudioLogDestination.
type BotAlias_AudioLogDestination struct {
	S3Bucket BotAlias_S3BucketLogDestination `json:"S3Bucket,omitempty"`
}

// BotAlias_AudioLogSetting represents AWS::Lex::BotAlias.AudioLogSetting.
type BotAlias_AudioLogSetting struct {
	Destination BotAlias_AudioLogDestination `json:"Destination,omitempty"`
	Enabled     any                          `json:"Enabled,omitempty"`
}

// BotAlias_BotAliasLocaleSettings represents AWS::Lex::BotAlias.BotAliasLocaleSettings.
type BotAlias_BotAliasLocaleSettings struct {
	CodeHookSpecification *BotAlias_CodeHookSpecification `json:"CodeHookSpecification,omitempty"`
	Enabled               any                             `json:"Enabled,omitempty"`
}

// BotAlias_BotAliasLocaleSettingsItem represents AWS::Lex::BotAlias.BotAliasLocaleSettingsItem.
type BotAlias_BotAliasLocaleSettingsItem struct {
	BotAliasLocaleSetting BotAlias_BotAliasLocaleSettings `json:"BotAliasLocaleSetting,omitempty"`
	LocaleId              any                             `json:"LocaleId,omitempty"`
}

// BotAlias_CloudWatchLogGroupLogDestination represents AWS::Lex::BotAlias.CloudWatchLogGroupLogDestination.
type BotAlias_CloudWatchLogGroupLogDestination struct {
	CloudWatchLogGroupArn any `json:"CloudWatchLogGroupArn,omitempty"`
	LogPrefix             any `json:"LogPrefix,omitempty"`
}

// BotAlias_CodeHookSpecification represents AWS::Lex::BotAlias.CodeHookSpecification.
type BotAlias_CodeHookSpecification struct {
	LambdaCodeHook BotAlias_LambdaCodeHook `json:"LambdaCodeHook,omitempty"`
}

// BotAlias_ConversationLogSettings represents AWS::Lex::BotAlias.ConversationLogSettings.
type BotAlias_ConversationLogSettings struct {
	AudioLogSettings []BotAlias_AudioLogSetting `json:"AudioLogSettings,omitempty"`
	TextLogSettings  []BotAlias_TextLogSetting  `json:"TextLogSettings,omitempty"`
}

// BotAlias_LambdaCodeHook represents AWS::Lex::BotAlias.LambdaCodeHook.
type BotAlias_LambdaCodeHook struct {
	CodeHookInterfaceVersion any `json:"CodeHookInterfaceVersion,omitempty"`
	LambdaArn                any `json:"LambdaArn,omitempty"`
}

// BotAlias_S3BucketLogDestination represents AWS::Lex::BotAlias.S3BucketLogDestination.
type BotAlias_S3BucketLogDestination struct {
	KmsKeyArn   any `json:"KmsKeyArn,omitempty"`
	LogPrefix   any `json:"LogPrefix,omitempty"`
	S3BucketArn any `json:"S3BucketArn,omitempty"`
}

// BotAlias_SentimentAnalysisSettings represents AWS::Lex::BotAlias.SentimentAnalysisSettings.
type BotAlias_SentimentAnalysisSettings struct {
	DetectSentiment any `json:"DetectSentiment,omitempty"`
}

// BotAlias_TextLogDestination represents AWS::Lex::BotAlias.TextLogDestination.
type BotAlias_TextLogDestination struct {
	CloudWatch BotAlias_CloudWatchLogGroupLogDestination `json:"CloudWatch,omitempty"`
}

// BotAlias_TextLogSetting represents AWS::Lex::BotAlias.TextLogSetting.
type BotAlias_TextLogSetting struct {
	Destination BotAlias_TextLogDestination `json:"Destination,omitempty"`
	Enabled     any                         `json:"Enabled,omitempty"`
}
