// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ecs

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Cluster represents AWS::ECS::Cluster.

type Cluster struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	CapacityProviders               []any `json:"CapacityProviders,omitempty"`
	ClusterName                     any   `json:"ClusterName,omitempty"`
	ClusterSettings                 []any `json:"ClusterSettings,omitempty"`
	Configuration                   any   `json:"Configuration,omitempty"`
	DefaultCapacityProviderStrategy []any `json:"DefaultCapacityProviderStrategy,omitempty"`
	ServiceConnectDefaults          any   `json:"ServiceConnectDefaults,omitempty"`
	Tags                            []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Cluster) ResourceType() string {
	return "AWS::ECS::Cluster"
}
