// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ecs

// TaskSet_AwsVpcConfiguration represents AWS::ECS::TaskSet.AwsVpcConfiguration.
type TaskSet_AwsVpcConfiguration struct {
	AssignPublicIp any   `json:"AssignPublicIp,omitempty"`
	SecurityGroups []any `json:"SecurityGroups,omitempty"`
	Subnets        []any `json:"Subnets,omitempty"`
}

// TaskSet_CapacityProviderStrategyItem represents AWS::ECS::TaskSet.CapacityProviderStrategyItem.
type TaskSet_CapacityProviderStrategyItem struct {
	Base             any `json:"Base,omitempty"`
	CapacityProvider any `json:"CapacityProvider,omitempty"`
	Weight           any `json:"Weight,omitempty"`
}

// TaskSet_LoadBalancer represents AWS::ECS::TaskSet.LoadBalancer.
type TaskSet_LoadBalancer struct {
	ContainerName  any `json:"ContainerName,omitempty"`
	ContainerPort  any `json:"ContainerPort,omitempty"`
	TargetGroupArn any `json:"TargetGroupArn,omitempty"`
}

// TaskSet_NetworkConfiguration represents AWS::ECS::TaskSet.NetworkConfiguration.
type TaskSet_NetworkConfiguration struct {
	AwsVpcConfiguration *Service_AwsVpcConfiguration `json:"AwsVpcConfiguration,omitempty"`
}

// TaskSet_Scale represents AWS::ECS::TaskSet.Scale.
type TaskSet_Scale struct {
	Unit  any `json:"Unit,omitempty"`
	Value any `json:"Value,omitempty"`
}

// TaskSet_ServiceRegistry represents AWS::ECS::TaskSet.ServiceRegistry.
type TaskSet_ServiceRegistry struct {
	ContainerName any `json:"ContainerName,omitempty"`
	ContainerPort any `json:"ContainerPort,omitempty"`
	Port          any `json:"Port,omitempty"`
	RegistryArn   any `json:"RegistryArn,omitempty"`
}
