// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package apigatewayv2

// RouteResponse_ParameterConstraints represents AWS::ApiGatewayV2::RouteResponse.ParameterConstraints.
type RouteResponse_ParameterConstraints struct {
	Required any `json:"Required,omitempty"`
}
