// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package apigatewayv2

// Stage represents AWS::ApiGatewayV2::Stage.

type Stage struct {

	// Properties
	AccessLogSettings    any `json:"AccessLogSettings,omitempty"`
	AccessPolicyId       any `json:"AccessPolicyId,omitempty"`
	ApiId                any `json:"ApiId,omitempty"`
	AutoDeploy           any `json:"AutoDeploy,omitempty"`
	ClientCertificateId  any `json:"ClientCertificateId,omitempty"`
	DefaultRouteSettings any `json:"DefaultRouteSettings,omitempty"`
	DeploymentId         any `json:"DeploymentId,omitempty"`
	Description          any `json:"Description,omitempty"`
	RouteSettings        any `json:"RouteSettings,omitempty"`
	StageName            any `json:"StageName,omitempty"`
	StageVariables       any `json:"StageVariables,omitempty"`
	Tags                 any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Stage) ResourceType() string {
	return "AWS::ApiGatewayV2::Stage"
}
