// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:17-07:00

package apigatewayv2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// VpcLink represents AWS::ApiGatewayV2::VpcLink.

type VpcLink struct {
	// Attributes for Fn::GetAtt
	VpcLinkId wetwire.AttrRef `json:"-"`

	// Properties
	Name             any            `json:"Name,omitempty"`
	SecurityGroupIds []any          `json:"SecurityGroupIds,omitempty"`
	SubnetIds        []any          `json:"SubnetIds,omitempty"`
	Tags             map[string]any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r VpcLink) ResourceType() string {
	return "AWS::ApiGatewayV2::VpcLink"
}
