// Package efs_with_automount_to_ec2 contains CloudFormation resources.
// Network resources: VPC, Subnets, Load Balancers, CloudFront, etc.
//
// Generated by wetwire-aws import.
package efs_with_automount_to_ec2

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/ec2"
	"github.com/lex00/wetwire-aws-go/resources/elasticloadbalancing"
)

var ELBSecurityGroupSecurityGroupIngressPortN443 = ec2.SecurityGroup_Ingress{
	CidrIp: "0.0.0.0/0",
	FromPort: "443",
	IpProtocol: "tcp",
	ToPort: "443",
}

var ELBSecurityGroupSecurityGroupIngressPortN80 = ec2.SecurityGroup_Ingress{
	CidrIp: "0.0.0.0/0",
	FromPort: "80",
	IpProtocol: "tcp",
	ToPort: "80",
}

var ELBSecurityGroup = ec2.SecurityGroup{
	GroupDescription: "Enable public access HTTP and HTTPS",
	SecurityGroupIngress: List(ELBSecurityGroupSecurityGroupIngressPortN80, ELBSecurityGroupSecurityGroupIngressPortN443),
	VpcId: VPC,
}

var ElasticLoadBalancerListener1 = elasticloadbalancing.LoadBalancer_Listeners{
	InstancePort: "80",
	LoadBalancerPort: "80",
	Protocol: "HTTP",
}

var ElasticLoadBalancerHealthCheck = elasticloadbalancing.LoadBalancer_HealthCheck{
	HealthyThreshold: "3",
	Interval: "30",
	Target: Join{Delimiter: "", Values: []any{
	"HTTP:",
	"80",
	"/",
}},
	Timeout: "5",
	UnhealthyThreshold: "5",
}

var ElasticLoadBalancer = elasticloadbalancing.LoadBalancer{
	CrossZone: "true",
	HealthCheck: &ElasticLoadBalancerHealthCheck,
	Listeners: List(ElasticLoadBalancerListener1),
	SecurityGroups: Any(ELBSecurityGroup),
	Subnets: Subnets,
}

var InstanceSecurityGroupSecurityGroupIngressPortN80 = ec2.SecurityGroup_Ingress{
	FromPort: "80",
	IpProtocol: "tcp",
	SourceSecurityGroupId: ELBSecurityGroup.GroupId,
	ToPort: "80",
}

var InstanceSecurityGroupSecurityGroupIngressPortN22 = ec2.SecurityGroup_Ingress{
	CidrIp: "0.0.0.0/0",
	FromPort: "22",
	IpProtocol: "tcp",
	ToPort: "22",
}

var InstanceSecurityGroup = ec2.SecurityGroup{
	GroupDescription: "Enable SSH public access and HTTP from the load balancer only",
	SecurityGroupIngress: List(InstanceSecurityGroupSecurityGroupIngressPortN22, InstanceSecurityGroupSecurityGroupIngressPortN80),
	VpcId: VPC,
}

var EFSSecurityGroupSecurityGroupIngressPortN2049 = ec2.SecurityGroup_Ingress{
	FromPort: "2049",
	IpProtocol: "tcp",
	SourceSecurityGroupId: InstanceSecurityGroup.GroupId,
	ToPort: "2049",
}

var EFSSecurityGroup = ec2.SecurityGroup{
	GroupDescription: "Enable NFS access from EC2",
	SecurityGroupIngress: List(EFSSecurityGroupSecurityGroupIngressPortN2049),
	VpcId: VPC,
}
