// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ram

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ResourceShare represents AWS::RAM::ResourceShare.

type ResourceShare struct {
	// Attributes for Fn::GetAtt
	Arn             wetwire.AttrRef `json:"-"`
	CreationTime    wetwire.AttrRef `json:"-"`
	FeatureSet      wetwire.AttrRef `json:"-"`
	LastUpdatedTime wetwire.AttrRef `json:"-"`
	OwningAccountId wetwire.AttrRef `json:"-"`
	Status          wetwire.AttrRef `json:"-"`

	// Properties
	AllowExternalPrincipals any   `json:"AllowExternalPrincipals,omitempty"`
	Name                    any   `json:"Name,omitempty"`
	PermissionArns          []any `json:"PermissionArns,omitempty"`
	Principals              []any `json:"Principals,omitempty"`
	ResourceArns            []any `json:"ResourceArns,omitempty"`
	Sources                 []any `json:"Sources,omitempty"`
	Tags                    []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ResourceShare) ResourceType() string {
	return "AWS::RAM::ResourceShare"
}
