// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package codestarnotifications

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// NotificationRule represents AWS::CodeStarNotifications::NotificationRule.

type NotificationRule struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	CreatedBy     any                       `json:"CreatedBy,omitempty"`
	DetailType    any                       `json:"DetailType,omitempty"`
	EventTypeId   any                       `json:"EventTypeId,omitempty"`
	EventTypeIds  []any                     `json:"EventTypeIds,omitempty"`
	Name          any                       `json:"Name,omitempty"`
	Resource      any                       `json:"Resource,omitempty"`
	Status        any                       `json:"Status,omitempty"`
	Tags          map[string]any            `json:"Tags,omitempty"`
	TargetAddress any                       `json:"TargetAddress,omitempty"`
	Targets       []NotificationRule_Target `json:"Targets,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r NotificationRule) ResourceType() string {
	return "AWS::CodeStarNotifications::NotificationRule"
}
