// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package appconfig

// ConfigurationProfile_Tags represents AWS::AppConfig::ConfigurationProfile.Tags.
type ConfigurationProfile_Tags struct {
	Key   any `json:"Key,omitempty"`
	Value any `json:"Value,omitempty"`
}

// ConfigurationProfile_Validators represents AWS::AppConfig::ConfigurationProfile.Validators.
type ConfigurationProfile_Validators struct {
	Content any `json:"Content,omitempty"`
	Type_   any `json:"Type,omitempty"`
}
