// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package iotwireless

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// WirelessDeviceImportTask represents AWS::IoTWireless::WirelessDeviceImportTask.

type WirelessDeviceImportTask struct {
	// Attributes for Fn::GetAtt
	Arn                             wetwire.AttrRef `json:"-"`
	CreationDate                    wetwire.AttrRef `json:"-"`
	FailedImportedDevicesCount      wetwire.AttrRef `json:"-"`
	Id                              wetwire.AttrRef `json:"-"`
	InitializedImportedDevicesCount wetwire.AttrRef `json:"-"`
	OnboardedImportedDevicesCount   wetwire.AttrRef `json:"-"`
	PendingImportedDevicesCount     wetwire.AttrRef `json:"-"`
	Sidewalk_DeviceCreationFileList wetwire.AttrRef `json:"-"`
	Status                          wetwire.AttrRef `json:"-"`
	StatusReason                    wetwire.AttrRef `json:"-"`

	// Properties
	DestinationName any                               `json:"DestinationName,omitempty"`
	Sidewalk        WirelessDeviceImportTask_Sidewalk `json:"Sidewalk,omitempty"`
	Tags            []any                             `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r WirelessDeviceImportTask) ResourceType() string {
	return "AWS::IoTWireless::WirelessDeviceImportTask"
}
