// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package rds

// DBSecurityGroup represents AWS::RDS::DBSecurityGroup.

type DBSecurityGroup struct {

	// Properties
	DBSecurityGroupIngress []DBSecurityGroup_Ingress `json:"DBSecurityGroupIngress,omitempty"`
	EC2VpcId               any                       `json:"EC2VpcId,omitempty"`
	GroupDescription       any                       `json:"GroupDescription,omitempty"`
	Tags                   []any                     `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r DBSecurityGroup) ResourceType() string {
	return "AWS::RDS::DBSecurityGroup"
}
