// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package rds

// EventSubscription represents AWS::RDS::EventSubscription.

type EventSubscription struct {

	// Properties
	Enabled          any   `json:"Enabled,omitempty"`
	EventCategories  []any `json:"EventCategories,omitempty"`
	SnsTopicArn      any   `json:"SnsTopicArn,omitempty"`
	SourceIds        []any `json:"SourceIds,omitempty"`
	SourceType       any   `json:"SourceType,omitempty"`
	SubscriptionName any   `json:"SubscriptionName,omitempty"`
	Tags             []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r EventSubscription) ResourceType() string {
	return "AWS::RDS::EventSubscription"
}
