// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ec2

// ClientVpnAuthorizationRule represents AWS::EC2::ClientVpnAuthorizationRule.

type ClientVpnAuthorizationRule struct {

	// Properties
	AccessGroupId       any `json:"AccessGroupId,omitempty"`
	AuthorizeAllGroups  any `json:"AuthorizeAllGroups,omitempty"`
	ClientVpnEndpointId any `json:"ClientVpnEndpointId,omitempty"`
	Description         any `json:"Description,omitempty"`
	TargetNetworkCidr   any `json:"TargetNetworkCidr,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ClientVpnAuthorizationRule) ResourceType() string {
	return "AWS::EC2::ClientVpnAuthorizationRule"
}
