// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ec2

// ClientVpnEndpoint represents AWS::EC2::ClientVpnEndpoint.

type ClientVpnEndpoint struct {

	// Properties
	AuthenticationOptions         []any                                  `json:"AuthenticationOptions,omitempty"`
	ClientCidrBlock               any                                    `json:"ClientCidrBlock,omitempty"`
	ClientConnectOptions          any                                    `json:"ClientConnectOptions,omitempty"`
	ClientLoginBannerOptions      any                                    `json:"ClientLoginBannerOptions,omitempty"`
	ClientRouteEnforcementOptions any                                    `json:"ClientRouteEnforcementOptions,omitempty"`
	ConnectionLogOptions          ClientVpnEndpoint_ConnectionLogOptions `json:"ConnectionLogOptions,omitempty"`
	Description                   any                                    `json:"Description,omitempty"`
	DisconnectOnSessionTimeout    any                                    `json:"DisconnectOnSessionTimeout,omitempty"`
	DnsServers                    []any                                  `json:"DnsServers,omitempty"`
	EndpointIpAddressType         any                                    `json:"EndpointIpAddressType,omitempty"`
	SecurityGroupIds              []any                                  `json:"SecurityGroupIds,omitempty"`
	SelfServicePortal             any                                    `json:"SelfServicePortal,omitempty"`
	ServerCertificateArn          any                                    `json:"ServerCertificateArn,omitempty"`
	SessionTimeoutHours           any                                    `json:"SessionTimeoutHours,omitempty"`
	SplitTunnel                   any                                    `json:"SplitTunnel,omitempty"`
	TagSpecifications             []any                                  `json:"TagSpecifications,omitempty"`
	TrafficIpAddressType          any                                    `json:"TrafficIpAddressType,omitempty"`
	TransportProtocol             any                                    `json:"TransportProtocol,omitempty"`
	VpcId                         any                                    `json:"VpcId,omitempty"`
	VpnPort                       any                                    `json:"VpnPort,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ClientVpnEndpoint) ResourceType() string {
	return "AWS::EC2::ClientVpnEndpoint"
}
