// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// EnclaveCertificateIamRoleAssociation represents AWS::EC2::EnclaveCertificateIamRoleAssociation.

type EnclaveCertificateIamRoleAssociation struct {
	// Attributes for Fn::GetAtt
	CertificateS3BucketName wetwire.AttrRef `json:"-"`
	CertificateS3ObjectKey  wetwire.AttrRef `json:"-"`
	EncryptionKmsKeyId      wetwire.AttrRef `json:"-"`

	// Properties
	CertificateArn any `json:"CertificateArn,omitempty"`
	RoleArn        any `json:"RoleArn,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r EnclaveCertificateIamRoleAssociation) ResourceType() string {
	return "AWS::EC2::EnclaveCertificateIamRoleAssociation"
}
