// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// IPAMScope represents AWS::EC2::IPAMScope.

type IPAMScope struct {
	// Attributes for Fn::GetAtt
	Arn           wetwire.AttrRef `json:"-"`
	IpamArn       wetwire.AttrRef `json:"-"`
	IpamScopeId   wetwire.AttrRef `json:"-"`
	IpamScopeType wetwire.AttrRef `json:"-"`
	IsDefault     wetwire.AttrRef `json:"-"`
	PoolCount     wetwire.AttrRef `json:"-"`

	// Properties
	Description                    any                                                `json:"Description,omitempty"`
	ExternalAuthorityConfiguration *IPAMScope_IpamScopeExternalAuthorityConfiguration `json:"ExternalAuthorityConfiguration,omitempty"`
	IpamId                         any                                                `json:"IpamId,omitempty"`
	Tags                           []any                                              `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r IPAMScope) ResourceType() string {
	return "AWS::EC2::IPAMScope"
}
