// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// KeyPair represents AWS::EC2::KeyPair.

type KeyPair struct {
	// Attributes for Fn::GetAtt
	KeyFingerprint wetwire.AttrRef `json:"-"`
	KeyPairId      wetwire.AttrRef `json:"-"`

	// Properties
	KeyFormat         any   `json:"KeyFormat,omitempty"`
	KeyName           any   `json:"KeyName,omitempty"`
	KeyType           any   `json:"KeyType,omitempty"`
	PublicKeyMaterial any   `json:"PublicKeyMaterial,omitempty"`
	Tags              []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r KeyPair) ResourceType() string {
	return "AWS::EC2::KeyPair"
}
