// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package ec2

// NetworkAclEntry_Icmp represents AWS::EC2::NetworkAclEntry.Icmp.
type NetworkAclEntry_Icmp struct {
	Code  any `json:"Code,omitempty"`
	Type_ any `json:"Type,omitempty"`
}

// NetworkAclEntry_PortRange represents AWS::EC2::NetworkAclEntry.PortRange.
type NetworkAclEntry_PortRange struct {
	From any `json:"From,omitempty"`
	To   any `json:"To,omitempty"`
}
