// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// NetworkAcl represents AWS::EC2::NetworkAcl.

type NetworkAcl struct {
	// Attributes for Fn::GetAtt
	Id wetwire.AttrRef `json:"-"`

	// Properties
	Tags  []any `json:"Tags,omitempty"`
	VpcId any   `json:"VpcId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r NetworkAcl) ResourceType() string {
	return "AWS::EC2::NetworkAcl"
}
