// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// PlacementGroup represents AWS::EC2::PlacementGroup.

type PlacementGroup struct {
	// Attributes for Fn::GetAtt
	GroupName wetwire.AttrRef `json:"-"`

	// Properties
	PartitionCount any   `json:"PartitionCount,omitempty"`
	SpreadLevel    any   `json:"SpreadLevel,omitempty"`
	Strategy       any   `json:"Strategy,omitempty"`
	Tags           []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r PlacementGroup) ResourceType() string {
	return "AWS::EC2::PlacementGroup"
}
