// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// TransitGatewayMulticastGroupSource represents AWS::EC2::TransitGatewayMulticastGroupSource.

type TransitGatewayMulticastGroupSource struct {
	// Attributes for Fn::GetAtt
	GroupMember                wetwire.AttrRef `json:"-"`
	GroupSource                wetwire.AttrRef `json:"-"`
	ResourceId                 wetwire.AttrRef `json:"-"`
	ResourceTypeAttr           wetwire.AttrRef `json:"-"`
	SourceType                 wetwire.AttrRef `json:"-"`
	SubnetId                   wetwire.AttrRef `json:"-"`
	TransitGatewayAttachmentId wetwire.AttrRef `json:"-"`

	// Properties
	GroupIpAddress                  any `json:"GroupIpAddress,omitempty"`
	NetworkInterfaceId              any `json:"NetworkInterfaceId,omitempty"`
	TransitGatewayMulticastDomainId any `json:"TransitGatewayMulticastDomainId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r TransitGatewayMulticastGroupSource) ResourceType() string {
	return "AWS::EC2::TransitGatewayMulticastGroupSource"
}
