// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// TransitGatewayMulticastDomain represents AWS::EC2::TransitGatewayMulticastDomain.

type TransitGatewayMulticastDomain struct {
	// Attributes for Fn::GetAtt
	CreationTime                     wetwire.AttrRef `json:"-"`
	State                            wetwire.AttrRef `json:"-"`
	TransitGatewayMulticastDomainArn wetwire.AttrRef `json:"-"`
	TransitGatewayMulticastDomainId  wetwire.AttrRef `json:"-"`

	// Properties
	Options          any   `json:"Options,omitempty"`
	Tags             []any `json:"Tags,omitempty"`
	TransitGatewayId any   `json:"TransitGatewayId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r TransitGatewayMulticastDomain) ResourceType() string {
	return "AWS::EC2::TransitGatewayMulticastDomain"
}
