// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package ec2

// VPCEndpointServicePermissions represents AWS::EC2::VPCEndpointServicePermissions.

type VPCEndpointServicePermissions struct {

	// Properties
	AllowedPrincipals []any `json:"AllowedPrincipals,omitempty"`
	ServiceId         any   `json:"ServiceId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r VPCEndpointServicePermissions) ResourceType() string {
	return "AWS::EC2::VPCEndpointServicePermissions"
}
