// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ec2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// VPCEncryptionControl represents AWS::EC2::VPCEncryptionControl.

type VPCEncryptionControl struct {
	// Attributes for Fn::GetAtt
	ResourceExclusions                                        wetwire.AttrRef `json:"-"`
	ResourceExclusions_EgressOnlyInternetGateway              wetwire.AttrRef `json:"-"`
	ResourceExclusions_EgressOnlyInternetGateway_State        wetwire.AttrRef `json:"-"`
	ResourceExclusions_EgressOnlyInternetGateway_StateMessage wetwire.AttrRef `json:"-"`
	ResourceExclusions_ElasticFileSystem                      wetwire.AttrRef `json:"-"`
	ResourceExclusions_ElasticFileSystem_State                wetwire.AttrRef `json:"-"`
	ResourceExclusions_ElasticFileSystem_StateMessage         wetwire.AttrRef `json:"-"`
	ResourceExclusions_InternetGateway                        wetwire.AttrRef `json:"-"`
	ResourceExclusions_InternetGateway_State                  wetwire.AttrRef `json:"-"`
	ResourceExclusions_InternetGateway_StateMessage           wetwire.AttrRef `json:"-"`
	ResourceExclusions_Lambda                                 wetwire.AttrRef `json:"-"`
	ResourceExclusions_Lambda_State                           wetwire.AttrRef `json:"-"`
	ResourceExclusions_Lambda_StateMessage                    wetwire.AttrRef `json:"-"`
	ResourceExclusions_NatGateway                             wetwire.AttrRef `json:"-"`
	ResourceExclusions_NatGateway_State                       wetwire.AttrRef `json:"-"`
	ResourceExclusions_NatGateway_StateMessage                wetwire.AttrRef `json:"-"`
	ResourceExclusions_VirtualPrivateGateway                  wetwire.AttrRef `json:"-"`
	ResourceExclusions_VirtualPrivateGateway_State            wetwire.AttrRef `json:"-"`
	ResourceExclusions_VirtualPrivateGateway_StateMessage     wetwire.AttrRef `json:"-"`
	ResourceExclusions_VpcLattice                             wetwire.AttrRef `json:"-"`
	ResourceExclusions_VpcLattice_State                       wetwire.AttrRef `json:"-"`
	ResourceExclusions_VpcLattice_StateMessage                wetwire.AttrRef `json:"-"`
	ResourceExclusions_VpcPeering                             wetwire.AttrRef `json:"-"`
	ResourceExclusions_VpcPeering_State                       wetwire.AttrRef `json:"-"`
	ResourceExclusions_VpcPeering_StateMessage                wetwire.AttrRef `json:"-"`
	State                                                     wetwire.AttrRef `json:"-"`
	StateMessage                                              wetwire.AttrRef `json:"-"`
	VpcEncryptionControlId                                    wetwire.AttrRef `json:"-"`

	// Properties
	EgressOnlyInternetGatewayExclusionInput any   `json:"EgressOnlyInternetGatewayExclusionInput,omitempty"`
	ElasticFileSystemExclusionInput         any   `json:"ElasticFileSystemExclusionInput,omitempty"`
	InternetGatewayExclusionInput           any   `json:"InternetGatewayExclusionInput,omitempty"`
	LambdaExclusionInput                    any   `json:"LambdaExclusionInput,omitempty"`
	Mode                                    any   `json:"Mode,omitempty"`
	NatGatewayExclusionInput                any   `json:"NatGatewayExclusionInput,omitempty"`
	Tags                                    []any `json:"Tags,omitempty"`
	VirtualPrivateGatewayExclusionInput     any   `json:"VirtualPrivateGatewayExclusionInput,omitempty"`
	VpcId                                   any   `json:"VpcId,omitempty"`
	VpcLatticeExclusionInput                any   `json:"VpcLatticeExclusionInput,omitempty"`
	VpcPeeringExclusionInput                any   `json:"VpcPeeringExclusionInput,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r VPCEncryptionControl) ResourceType() string {
	return "AWS::EC2::VPCEncryptionControl"
}
