// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ec2

// VPCEncryptionControl_ResourceExclusions represents AWS::EC2::VPCEncryptionControl.ResourceExclusions.
type VPCEncryptionControl_ResourceExclusions struct {
	EgressOnlyInternetGateway *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"EgressOnlyInternetGateway,omitempty"`
	ElasticFileSystem         *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"ElasticFileSystem,omitempty"`
	InternetGateway           *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"InternetGateway,omitempty"`
	Lambda                    *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"Lambda,omitempty"`
	NatGateway                *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"NatGateway,omitempty"`
	VirtualPrivateGateway     *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"VirtualPrivateGateway,omitempty"`
	VpcLattice                *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"VpcLattice,omitempty"`
	VpcPeering                *VPCEncryptionControl_VpcEncryptionControlExclusion `json:"VpcPeering,omitempty"`
}

// VPCEncryptionControl_VpcEncryptionControlExclusion represents AWS::EC2::VPCEncryptionControl.VpcEncryptionControlExclusion.
type VPCEncryptionControl_VpcEncryptionControlExclusion struct {
	State        any `json:"State,omitempty"`
	StateMessage any `json:"StateMessage,omitempty"`
}
