// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ec2

// VerifiedAccessInstance_CloudWatchLogs represents AWS::EC2::VerifiedAccessInstance.CloudWatchLogs.
type VerifiedAccessInstance_CloudWatchLogs struct {
	Enabled  any `json:"Enabled,omitempty"`
	LogGroup any `json:"LogGroup,omitempty"`
}

// VerifiedAccessInstance_KinesisDataFirehose represents AWS::EC2::VerifiedAccessInstance.KinesisDataFirehose.
type VerifiedAccessInstance_KinesisDataFirehose struct {
	DeliveryStream any `json:"DeliveryStream,omitempty"`
	Enabled        any `json:"Enabled,omitempty"`
}

// VerifiedAccessInstance_S3 represents AWS::EC2::VerifiedAccessInstance.S3.
type VerifiedAccessInstance_S3 struct {
	BucketName  any `json:"BucketName,omitempty"`
	BucketOwner any `json:"BucketOwner,omitempty"`
	Enabled     any `json:"Enabled,omitempty"`
	Prefix      any `json:"Prefix,omitempty"`
}

// VerifiedAccessInstance_VerifiedAccessLogs represents AWS::EC2::VerifiedAccessInstance.VerifiedAccessLogs.
type VerifiedAccessInstance_VerifiedAccessLogs struct {
	CloudWatchLogs      any `json:"CloudWatchLogs,omitempty"`
	IncludeTrustContext any `json:"IncludeTrustContext,omitempty"`
	KinesisDataFirehose any `json:"KinesisDataFirehose,omitempty"`
	LogVersion          any `json:"LogVersion,omitempty"`
	S3                  any `json:"S3,omitempty"`
}

// VerifiedAccessInstance_VerifiedAccessTrustProvider represents AWS::EC2::VerifiedAccessInstance.VerifiedAccessTrustProvider.
type VerifiedAccessInstance_VerifiedAccessTrustProvider struct {
	Description                   any `json:"Description,omitempty"`
	DeviceTrustProviderType       any `json:"DeviceTrustProviderType,omitempty"`
	TrustProviderType             any `json:"TrustProviderType,omitempty"`
	UserTrustProviderType         any `json:"UserTrustProviderType,omitempty"`
	VerifiedAccessTrustProviderId any `json:"VerifiedAccessTrustProviderId,omitempty"`
}
