// Package emrclusterwithadditionalsecuritygroups contains CloudFormation resources.
// Main resources
//
// Generated by wetwire-aws import.
package emrclusterwithadditionalsecuritygroups

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/emr"
)

var EMRClusterInstancesMasterInstanceGroup = emr.Cluster_InstanceGroupConfig{
	InstanceCount: 1,
	InstanceType: MasterInstanceType,
	Market: "ON_DEMAND",
	Name: "Master",
}

var EMRClusterInstancesCoreInstanceGroup = emr.Cluster_InstanceGroupConfig{
	InstanceCount: NumberOfCoreInstances,
	InstanceType: CoreInstanceType,
	Market: "ON_DEMAND",
	Name: "Core",
}

var EMRClusterInstances = emr.Cluster_JobFlowInstancesConfig{
	AdditionalMasterSecurityGroups: []any{AdditionalPrimaryNodeSecurityGroups},
	AdditionalSlaveSecurityGroups: []any{AdditionalCoreNodeSecurityGroups},
	CoreInstanceGroup: EMRClusterInstancesCoreInstanceGroup,
	Ec2KeyName: KeyName,
	Ec2SubnetId: SubnetID,
	MasterInstanceGroup: EMRClusterInstancesMasterInstanceGroup,
	TerminationProtected: false,
}

var EMRClusterConfiguration2 = emr.Cluster_Configuration{
	Classification: "hbase",
	ConfigurationProperties: Json{"hbase.emr.storageMode": "s3"},
}

var EMRClusterConfiguration1 = emr.Cluster_Configuration{
	Classification: "hbase-site",
	ConfigurationProperties: Json{"hbase.rootdir": S3DataUri},
}

var EMRClusterApplicationGanglia = emr.Cluster_Application{
	Name: "Ganglia",
}

var EMRCluster = emr.Cluster{
	Applications: []any{EMRClusterApplicationGanglia},
	AutoScalingRole: "EMR_AutoScaling_DefaultRole",
	Configurations: []any{EMRClusterConfiguration1, EMRClusterConfiguration2},
	Instances: EMRClusterInstances,
	JobFlowRole: EMRClusterinstanceProfile,
	LogUri: LogUri,
	Name: EMRClusterName,
	ReleaseLabel: ReleaseLabel,
	ServiceRole: EMRClusterServiceRole,
	VisibleToAllUsers: true,
}
