// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package opensearchserverless

// SecurityConfig_IamFederationConfigOptions represents AWS::OpenSearchServerless::SecurityConfig.IamFederationConfigOptions.
type SecurityConfig_IamFederationConfigOptions struct {
	GroupAttribute any `json:"GroupAttribute,omitempty"`
	UserAttribute  any `json:"UserAttribute,omitempty"`
}

// SecurityConfig_IamIdentityCenterConfigOptions represents AWS::OpenSearchServerless::SecurityConfig.IamIdentityCenterConfigOptions.
type SecurityConfig_IamIdentityCenterConfigOptions struct {
	ApplicationArn         any `json:"ApplicationArn,omitempty"`
	ApplicationDescription any `json:"ApplicationDescription,omitempty"`
	ApplicationName        any `json:"ApplicationName,omitempty"`
	GroupAttribute         any `json:"GroupAttribute,omitempty"`
	InstanceArn            any `json:"InstanceArn,omitempty"`
	UserAttribute          any `json:"UserAttribute,omitempty"`
}

// SecurityConfig_SamlConfigOptions represents AWS::OpenSearchServerless::SecurityConfig.SamlConfigOptions.
type SecurityConfig_SamlConfigOptions struct {
	GroupAttribute               any `json:"GroupAttribute,omitempty"`
	Metadata                     any `json:"Metadata,omitempty"`
	OpenSearchServerlessEntityId any `json:"OpenSearchServerlessEntityId,omitempty"`
	SessionTimeout               any `json:"SessionTimeout,omitempty"`
	UserAttribute                any `json:"UserAttribute,omitempty"`
}
