// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cloudfront

// DistributionTenant_Certificate represents AWS::CloudFront::DistributionTenant.Certificate.
type DistributionTenant_Certificate struct {
	Arn any `json:"Arn,omitempty"`
}

// DistributionTenant_Customizations represents AWS::CloudFront::DistributionTenant.Customizations.
type DistributionTenant_Customizations struct {
	Certificate     *DistributionTenant_Certificate                 `json:"Certificate,omitempty"`
	GeoRestrictions *DistributionTenant_GeoRestrictionCustomization `json:"GeoRestrictions,omitempty"`
	WebAcl          *DistributionTenant_WebAclCustomization         `json:"WebAcl,omitempty"`
}

// DistributionTenant_DomainResult represents AWS::CloudFront::DistributionTenant.DomainResult.
type DistributionTenant_DomainResult struct {
	Domain any `json:"Domain,omitempty"`
	Status any `json:"Status,omitempty"`
}

// DistributionTenant_GeoRestrictionCustomization represents AWS::CloudFront::DistributionTenant.GeoRestrictionCustomization.
type DistributionTenant_GeoRestrictionCustomization struct {
	Locations       []any `json:"Locations,omitempty"`
	RestrictionType any   `json:"RestrictionType,omitempty"`
}

// DistributionTenant_ManagedCertificateRequest represents AWS::CloudFront::DistributionTenant.ManagedCertificateRequest.
type DistributionTenant_ManagedCertificateRequest struct {
	CertificateTransparencyLoggingPreference any `json:"CertificateTransparencyLoggingPreference,omitempty"`
	PrimaryDomainName                        any `json:"PrimaryDomainName,omitempty"`
	ValidationTokenHost                      any `json:"ValidationTokenHost,omitempty"`
}

// DistributionTenant_Parameter represents AWS::CloudFront::DistributionTenant.Parameter.
type DistributionTenant_Parameter struct {
	Name  any `json:"Name,omitempty"`
	Value any `json:"Value,omitempty"`
}

// DistributionTenant_WebAclCustomization represents AWS::CloudFront::DistributionTenant.WebAclCustomization.
type DistributionTenant_WebAclCustomization struct {
	Action any `json:"Action,omitempty"`
	Arn    any `json:"Arn,omitempty"`
}
