// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package cloudfront

// Function_FunctionConfig represents AWS::CloudFront::Function.FunctionConfig.
type Function_FunctionConfig struct {
	Comment                   any   `json:"Comment,omitempty"`
	KeyValueStoreAssociations []any `json:"KeyValueStoreAssociations,omitempty"`
	Runtime                   any   `json:"Runtime,omitempty"`
}

// Function_FunctionMetadata represents AWS::CloudFront::Function.FunctionMetadata.
type Function_FunctionMetadata struct {
	FunctionARN any `json:"FunctionARN,omitempty"`
}

// Function_KeyValueStoreAssociation represents AWS::CloudFront::Function.KeyValueStoreAssociation.
type Function_KeyValueStoreAssociation struct {
	KeyValueStoreARN any `json:"KeyValueStoreARN,omitempty"`
}
