// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cloudfront

// ResponseHeadersPolicy_AccessControlAllowHeaders represents AWS::CloudFront::ResponseHeadersPolicy.AccessControlAllowHeaders.
type ResponseHeadersPolicy_AccessControlAllowHeaders struct {
	Items []any `json:"Items,omitempty"`
}

// ResponseHeadersPolicy_AccessControlAllowMethods represents AWS::CloudFront::ResponseHeadersPolicy.AccessControlAllowMethods.
type ResponseHeadersPolicy_AccessControlAllowMethods struct {
	Items []any `json:"Items,omitempty"`
}

// ResponseHeadersPolicy_AccessControlAllowOrigins represents AWS::CloudFront::ResponseHeadersPolicy.AccessControlAllowOrigins.
type ResponseHeadersPolicy_AccessControlAllowOrigins struct {
	Items []any `json:"Items,omitempty"`
}

// ResponseHeadersPolicy_AccessControlExposeHeaders represents AWS::CloudFront::ResponseHeadersPolicy.AccessControlExposeHeaders.
type ResponseHeadersPolicy_AccessControlExposeHeaders struct {
	Items []any `json:"Items,omitempty"`
}

// ResponseHeadersPolicy_ContentSecurityPolicy represents AWS::CloudFront::ResponseHeadersPolicy.ContentSecurityPolicy.
type ResponseHeadersPolicy_ContentSecurityPolicy struct {
	ContentSecurityPolicy any `json:"ContentSecurityPolicy,omitempty"`
	Override              any `json:"Override,omitempty"`
}

// ResponseHeadersPolicy_ContentTypeOptions represents AWS::CloudFront::ResponseHeadersPolicy.ContentTypeOptions.
type ResponseHeadersPolicy_ContentTypeOptions struct {
	Override any `json:"Override,omitempty"`
}

// ResponseHeadersPolicy_CorsConfig represents AWS::CloudFront::ResponseHeadersPolicy.CorsConfig.
type ResponseHeadersPolicy_CorsConfig struct {
	AccessControlAllowCredentials any                                               `json:"AccessControlAllowCredentials,omitempty"`
	AccessControlAllowHeaders     ResponseHeadersPolicy_AccessControlAllowHeaders   `json:"AccessControlAllowHeaders,omitempty"`
	AccessControlAllowMethods     ResponseHeadersPolicy_AccessControlAllowMethods   `json:"AccessControlAllowMethods,omitempty"`
	AccessControlAllowOrigins     ResponseHeadersPolicy_AccessControlAllowOrigins   `json:"AccessControlAllowOrigins,omitempty"`
	AccessControlExposeHeaders    *ResponseHeadersPolicy_AccessControlExposeHeaders `json:"AccessControlExposeHeaders,omitempty"`
	AccessControlMaxAgeSec        any                                               `json:"AccessControlMaxAgeSec,omitempty"`
	OriginOverride                any                                               `json:"OriginOverride,omitempty"`
}

// ResponseHeadersPolicy_CustomHeader represents AWS::CloudFront::ResponseHeadersPolicy.CustomHeader.
type ResponseHeadersPolicy_CustomHeader struct {
	Header   any `json:"Header,omitempty"`
	Override any `json:"Override,omitempty"`
	Value    any `json:"Value,omitempty"`
}

// ResponseHeadersPolicy_CustomHeadersConfig represents AWS::CloudFront::ResponseHeadersPolicy.CustomHeadersConfig.
type ResponseHeadersPolicy_CustomHeadersConfig struct {
	Items []ResponseHeadersPolicy_CustomHeader `json:"Items,omitempty"`
}

// ResponseHeadersPolicy_FrameOptions represents AWS::CloudFront::ResponseHeadersPolicy.FrameOptions.
type ResponseHeadersPolicy_FrameOptions struct {
	FrameOption any `json:"FrameOption,omitempty"`
	Override    any `json:"Override,omitempty"`
}

// ResponseHeadersPolicy_ReferrerPolicy represents AWS::CloudFront::ResponseHeadersPolicy.ReferrerPolicy.
type ResponseHeadersPolicy_ReferrerPolicy struct {
	Override       any `json:"Override,omitempty"`
	ReferrerPolicy any `json:"ReferrerPolicy,omitempty"`
}

// ResponseHeadersPolicy_RemoveHeader represents AWS::CloudFront::ResponseHeadersPolicy.RemoveHeader.
type ResponseHeadersPolicy_RemoveHeader struct {
	Header any `json:"Header,omitempty"`
}

// ResponseHeadersPolicy_RemoveHeadersConfig represents AWS::CloudFront::ResponseHeadersPolicy.RemoveHeadersConfig.
type ResponseHeadersPolicy_RemoveHeadersConfig struct {
	Items []ResponseHeadersPolicy_RemoveHeader `json:"Items,omitempty"`
}

// ResponseHeadersPolicy_ResponseHeadersPolicyConfig represents AWS::CloudFront::ResponseHeadersPolicy.ResponseHeadersPolicyConfig.
type ResponseHeadersPolicy_ResponseHeadersPolicyConfig struct {
	Comment                   any                                              `json:"Comment,omitempty"`
	CorsConfig                *ResponseHeadersPolicy_CorsConfig                `json:"CorsConfig,omitempty"`
	CustomHeadersConfig       *ResponseHeadersPolicy_CustomHeadersConfig       `json:"CustomHeadersConfig,omitempty"`
	Name                      any                                              `json:"Name,omitempty"`
	RemoveHeadersConfig       *ResponseHeadersPolicy_RemoveHeadersConfig       `json:"RemoveHeadersConfig,omitempty"`
	SecurityHeadersConfig     *ResponseHeadersPolicy_SecurityHeadersConfig     `json:"SecurityHeadersConfig,omitempty"`
	ServerTimingHeadersConfig *ResponseHeadersPolicy_ServerTimingHeadersConfig `json:"ServerTimingHeadersConfig,omitempty"`
}

// ResponseHeadersPolicy_SecurityHeadersConfig represents AWS::CloudFront::ResponseHeadersPolicy.SecurityHeadersConfig.
type ResponseHeadersPolicy_SecurityHeadersConfig struct {
	ContentSecurityPolicy   *ResponseHeadersPolicy_ContentSecurityPolicy   `json:"ContentSecurityPolicy,omitempty"`
	ContentTypeOptions      *ResponseHeadersPolicy_ContentTypeOptions      `json:"ContentTypeOptions,omitempty"`
	FrameOptions            *ResponseHeadersPolicy_FrameOptions            `json:"FrameOptions,omitempty"`
	ReferrerPolicy          *ResponseHeadersPolicy_ReferrerPolicy          `json:"ReferrerPolicy,omitempty"`
	StrictTransportSecurity *ResponseHeadersPolicy_StrictTransportSecurity `json:"StrictTransportSecurity,omitempty"`
	XSSProtection           *ResponseHeadersPolicy_XSSProtection           `json:"XSSProtection,omitempty"`
}

// ResponseHeadersPolicy_ServerTimingHeadersConfig represents AWS::CloudFront::ResponseHeadersPolicy.ServerTimingHeadersConfig.
type ResponseHeadersPolicy_ServerTimingHeadersConfig struct {
	Enabled      any `json:"Enabled,omitempty"`
	SamplingRate any `json:"SamplingRate,omitempty"`
}

// ResponseHeadersPolicy_StrictTransportSecurity represents AWS::CloudFront::ResponseHeadersPolicy.StrictTransportSecurity.
type ResponseHeadersPolicy_StrictTransportSecurity struct {
	AccessControlMaxAgeSec any `json:"AccessControlMaxAgeSec,omitempty"`
	IncludeSubdomains      any `json:"IncludeSubdomains,omitempty"`
	Override               any `json:"Override,omitempty"`
	Preload                any `json:"Preload,omitempty"`
}

// ResponseHeadersPolicy_XSSProtection represents AWS::CloudFront::ResponseHeadersPolicy.XSSProtection.
type ResponseHeadersPolicy_XSSProtection struct {
	ModeBlock  any `json:"ModeBlock,omitempty"`
	Override   any `json:"Override,omitempty"`
	Protection any `json:"Protection,omitempty"`
	ReportUri  any `json:"ReportUri,omitempty"`
}
