// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:23-07:00

package voiceid

// Domain_ServerSideEncryptionConfiguration represents AWS::VoiceID::Domain.ServerSideEncryptionConfiguration.
type Domain_ServerSideEncryptionConfiguration struct {
	KmsKeyId any `json:"KmsKeyId,omitempty"`
}
