// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package connect

// RoutingProfile_CrossChannelBehavior represents AWS::Connect::RoutingProfile.CrossChannelBehavior.
type RoutingProfile_CrossChannelBehavior struct {
	BehaviorType any `json:"BehaviorType,omitempty"`
}

// RoutingProfile_MediaConcurrency represents AWS::Connect::RoutingProfile.MediaConcurrency.
type RoutingProfile_MediaConcurrency struct {
	Channel              any                                  `json:"Channel,omitempty"`
	Concurrency          any                                  `json:"Concurrency,omitempty"`
	CrossChannelBehavior *RoutingProfile_CrossChannelBehavior `json:"CrossChannelBehavior,omitempty"`
}

// RoutingProfile_RoutingProfileManualAssignmentQueueConfig represents AWS::Connect::RoutingProfile.RoutingProfileManualAssignmentQueueConfig.
type RoutingProfile_RoutingProfileManualAssignmentQueueConfig struct {
	QueueReference RoutingProfile_RoutingProfileQueueReference `json:"QueueReference,omitempty"`
}

// RoutingProfile_RoutingProfileQueueConfig represents AWS::Connect::RoutingProfile.RoutingProfileQueueConfig.
type RoutingProfile_RoutingProfileQueueConfig struct {
	Delay          any                                         `json:"Delay,omitempty"`
	Priority       any                                         `json:"Priority,omitempty"`
	QueueReference RoutingProfile_RoutingProfileQueueReference `json:"QueueReference,omitempty"`
}

// RoutingProfile_RoutingProfileQueueReference represents AWS::Connect::RoutingProfile.RoutingProfileQueueReference.
type RoutingProfile_RoutingProfileQueueReference struct {
	Channel  any `json:"Channel,omitempty"`
	QueueArn any `json:"QueueArn,omitempty"`
}
