// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package connect

// SecurityProfile_Application represents AWS::Connect::SecurityProfile.Application.
type SecurityProfile_Application struct {
	ApplicationPermissions []any `json:"ApplicationPermissions,omitempty"`
	Namespace              any   `json:"Namespace,omitempty"`
}

// SecurityProfile_DataTableAccessControlConfiguration represents AWS::Connect::SecurityProfile.DataTableAccessControlConfiguration.
type SecurityProfile_DataTableAccessControlConfiguration struct {
	PrimaryAttributeAccessControlConfiguration *SecurityProfile_PrimaryAttributeAccessControlConfigurationItem `json:"PrimaryAttributeAccessControlConfiguration,omitempty"`
}

// SecurityProfile_GranularAccessControlConfiguration represents AWS::Connect::SecurityProfile.GranularAccessControlConfiguration.
type SecurityProfile_GranularAccessControlConfiguration struct {
	DataTableAccessControlConfiguration *SecurityProfile_DataTableAccessControlConfiguration `json:"DataTableAccessControlConfiguration,omitempty"`
}

// SecurityProfile_PrimaryAttributeAccessControlConfigurationItem represents AWS::Connect::SecurityProfile.PrimaryAttributeAccessControlConfigurationItem.
type SecurityProfile_PrimaryAttributeAccessControlConfigurationItem struct {
	PrimaryAttributeValues []SecurityProfile_PrimaryAttributeValue `json:"PrimaryAttributeValues,omitempty"`
}

// SecurityProfile_PrimaryAttributeValue represents AWS::Connect::SecurityProfile.PrimaryAttributeValue.
type SecurityProfile_PrimaryAttributeValue struct {
	AccessType    any   `json:"AccessType,omitempty"`
	AttributeName any   `json:"AttributeName,omitempty"`
	Values        []any `json:"Values,omitempty"`
}
