// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package cases

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Field represents AWS::Cases::Field.

type Field struct {
	// Attributes for Fn::GetAtt
	CreatedTime      wetwire.AttrRef `json:"-"`
	FieldArn         wetwire.AttrRef `json:"-"`
	FieldId          wetwire.AttrRef `json:"-"`
	LastModifiedTime wetwire.AttrRef `json:"-"`
	Namespace        wetwire.AttrRef `json:"-"`

	// Properties
	Description any   `json:"Description,omitempty"`
	DomainId    any   `json:"DomainId,omitempty"`
	Name        any   `json:"Name,omitempty"`
	Tags        []any `json:"Tags,omitempty"`
	Type_       any   `json:"Type,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Field) ResourceType() string {
	return "AWS::Cases::Field"
}
