// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package s3objectlambda

// AccessPointPolicy represents AWS::S3ObjectLambda::AccessPointPolicy.

type AccessPointPolicy struct {

	// Properties
	ObjectLambdaAccessPoint any `json:"ObjectLambdaAccessPoint,omitempty"`
	PolicyDocument          any `json:"PolicyDocument,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r AccessPointPolicy) ResourceType() string {
	return "AWS::S3ObjectLambda::AccessPointPolicy"
}
