// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package lightsail

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Bucket represents AWS::Lightsail::Bucket.

type Bucket struct {
	// Attributes for Fn::GetAtt
	AbleToUpdateBundle wetwire.AttrRef `json:"-"`
	BucketArn          wetwire.AttrRef `json:"-"`
	Url                wetwire.AttrRef `json:"-"`

	// Properties
	AccessRules              *Bucket_AccessRules `json:"AccessRules,omitempty"`
	BucketName               any                 `json:"BucketName,omitempty"`
	BundleId                 any                 `json:"BundleId,omitempty"`
	ObjectVersioning         any                 `json:"ObjectVersioning,omitempty"`
	ReadOnlyAccessAccounts   []any               `json:"ReadOnlyAccessAccounts,omitempty"`
	ResourcesReceivingAccess []any               `json:"ResourcesReceivingAccess,omitempty"`
	Tags                     []any               `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Bucket) ResourceType() string {
	return "AWS::Lightsail::Bucket"
}
