// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package lightsail

// AccessDirection represents valid values for AccessDirection.
type AccessDirection string

const (
	AccessDirectionInbound  AccessDirection = "inbound"
	AccessDirectionOutbound AccessDirection = "outbound"
)

// AccessType represents valid values for AccessType.
type AccessType string

const (
	AccessTypePublic  AccessType = "public"
	AccessTypePrivate AccessType = "private"
)

// AccountLevelBpaSyncStatus represents valid values for AccountLevelBpaSyncStatus.
type AccountLevelBpaSyncStatus string

const (
	AccountLevelBpaSyncStatusInsync      AccountLevelBpaSyncStatus = "InSync"
	AccountLevelBpaSyncStatusFailed      AccountLevelBpaSyncStatus = "Failed"
	AccountLevelBpaSyncStatusNeversynced AccountLevelBpaSyncStatus = "NeverSynced"
	AccountLevelBpaSyncStatusDefaulted   AccountLevelBpaSyncStatus = "Defaulted"
)

// AddOnType represents valid values for AddOnType.
type AddOnType string

const (
	AddOnTypeAutosnapshot       AddOnType = "AutoSnapshot"
	AddOnTypeStopinstanceonidle AddOnType = "StopInstanceOnIdle"
)

// AlarmState represents valid values for AlarmState.
type AlarmState string

const (
	AlarmStateOk               AlarmState = "OK"
	AlarmStateAlarm            AlarmState = "ALARM"
	AlarmStateInsufficientData AlarmState = "INSUFFICIENT_DATA"
)

// AppCategory represents valid values for AppCategory.
type AppCategory string

const (
	AppCategoryLfr AppCategory = "LfR"
)

// AutoMountStatus represents valid values for AutoMountStatus.
type AutoMountStatus string

const (
	AutoMountStatusFailed     AutoMountStatus = "Failed"
	AutoMountStatusPending    AutoMountStatus = "Pending"
	AutoMountStatusMounted    AutoMountStatus = "Mounted"
	AutoMountStatusNotmounted AutoMountStatus = "NotMounted"
)

// AutoSnapshotStatus represents valid values for AutoSnapshotStatus.
type AutoSnapshotStatus string

const (
	AutoSnapshotStatusSuccess    AutoSnapshotStatus = "Success"
	AutoSnapshotStatusFailed     AutoSnapshotStatus = "Failed"
	AutoSnapshotStatusInprogress AutoSnapshotStatus = "InProgress"
	AutoSnapshotStatusNotfound   AutoSnapshotStatus = "NotFound"
)

// BPAStatusMessage represents valid values for BPAStatusMessage.
type BPAStatusMessage string

const (
	BPAStatusMessageDefaultedForSlrMissing       BPAStatusMessage = "DEFAULTED_FOR_SLR_MISSING"
	BPAStatusMessageSyncOnHold                   BPAStatusMessage = "SYNC_ON_HOLD"
	BPAStatusMessageDefaultedForSlrMissingOnHold BPAStatusMessage = "DEFAULTED_FOR_SLR_MISSING_ON_HOLD"
	BPAStatusMessageUnknown                      BPAStatusMessage = "Unknown"
)

// BehaviorEnum represents valid values for BehaviorEnum.
type BehaviorEnum string

const (
	BehaviorEnumDontCache BehaviorEnum = "dont-cache"
	BehaviorEnumCache     BehaviorEnum = "cache"
)

// BlueprintType represents valid values for BlueprintType.
type BlueprintType string

const (
	BlueprintTypeOs  BlueprintType = "os"
	BlueprintTypeApp BlueprintType = "app"
)

// BucketMetricName represents valid values for BucketMetricName.
type BucketMetricName string

const (
	BucketMetricNameBucketsizebytes BucketMetricName = "BucketSizeBytes"
	BucketMetricNameNumberofobjects BucketMetricName = "NumberOfObjects"
)

// CertificateDomainValidationStatus represents valid values for CertificateDomainValidationStatus.
type CertificateDomainValidationStatus string

const (
	CertificateDomainValidationStatusPendingValidation CertificateDomainValidationStatus = "PENDING_VALIDATION"
	CertificateDomainValidationStatusFailed            CertificateDomainValidationStatus = "FAILED"
	CertificateDomainValidationStatusSuccess           CertificateDomainValidationStatus = "SUCCESS"
)

// CertificateProvider represents valid values for CertificateProvider.
type CertificateProvider string

const (
	CertificateProviderLetsencrypt CertificateProvider = "LetsEncrypt"
)

// CertificateStatus represents valid values for CertificateStatus.
type CertificateStatus string

const (
	CertificateStatusPendingValidation  CertificateStatus = "PENDING_VALIDATION"
	CertificateStatusIssued             CertificateStatus = "ISSUED"
	CertificateStatusInactive           CertificateStatus = "INACTIVE"
	CertificateStatusExpired            CertificateStatus = "EXPIRED"
	CertificateStatusValidationTimedOut CertificateStatus = "VALIDATION_TIMED_OUT"
	CertificateStatusRevoked            CertificateStatus = "REVOKED"
	CertificateStatusFailed             CertificateStatus = "FAILED"
)

// CloudFormationStackRecordSourceType represents valid values for CloudFormationStackRecordSourceType.
type CloudFormationStackRecordSourceType string

const (
	CloudFormationStackRecordSourceTypeExportsnapshotrecord CloudFormationStackRecordSourceType = "ExportSnapshotRecord"
)

// ComparisonOperator represents valid values for ComparisonOperator.
type ComparisonOperator string

const (
	ComparisonOperatorGreaterthanorequaltothreshold ComparisonOperator = "GreaterThanOrEqualToThreshold"
	ComparisonOperatorGreaterthanthreshold          ComparisonOperator = "GreaterThanThreshold"
	ComparisonOperatorLessthanthreshold             ComparisonOperator = "LessThanThreshold"
	ComparisonOperatorLessthanorequaltothreshold    ComparisonOperator = "LessThanOrEqualToThreshold"
)

// ContactMethodStatus represents valid values for ContactMethodStatus.
type ContactMethodStatus string

const (
	ContactMethodStatusPendingverification ContactMethodStatus = "PendingVerification"
	ContactMethodStatusValid               ContactMethodStatus = "Valid"
	ContactMethodStatusInvalid             ContactMethodStatus = "Invalid"
)

// ContactMethodVerificationProtocol represents valid values for ContactMethodVerificationProtocol.
type ContactMethodVerificationProtocol string

const (
	ContactMethodVerificationProtocolEmail ContactMethodVerificationProtocol = "Email"
)

// ContactProtocol represents valid values for ContactProtocol.
type ContactProtocol string

const (
	ContactProtocolEmail ContactProtocol = "Email"
	ContactProtocolSms   ContactProtocol = "SMS"
)

// ContainerServiceDeploymentState represents valid values for ContainerServiceDeploymentState.
type ContainerServiceDeploymentState string

const (
	ContainerServiceDeploymentStateActivating ContainerServiceDeploymentState = "ACTIVATING"
	ContainerServiceDeploymentStateActive     ContainerServiceDeploymentState = "ACTIVE"
	ContainerServiceDeploymentStateInactive   ContainerServiceDeploymentState = "INACTIVE"
	ContainerServiceDeploymentStateFailed     ContainerServiceDeploymentState = "FAILED"
)

// ContainerServiceMetricName represents valid values for ContainerServiceMetricName.
type ContainerServiceMetricName string

const (
	ContainerServiceMetricNameCpuutilization    ContainerServiceMetricName = "CPUUtilization"
	ContainerServiceMetricNameMemoryutilization ContainerServiceMetricName = "MemoryUtilization"
)

// ContainerServicePowerName represents valid values for ContainerServicePowerName.
type ContainerServicePowerName string

const (
	ContainerServicePowerNameNano   ContainerServicePowerName = "nano"
	ContainerServicePowerNameMicro  ContainerServicePowerName = "micro"
	ContainerServicePowerNameSmall  ContainerServicePowerName = "small"
	ContainerServicePowerNameMedium ContainerServicePowerName = "medium"
	ContainerServicePowerNameLarge  ContainerServicePowerName = "large"
	ContainerServicePowerNameXlarge ContainerServicePowerName = "xlarge"
)

// ContainerServiceProtocol represents valid values for ContainerServiceProtocol.
type ContainerServiceProtocol string

const (
	ContainerServiceProtocolHttp  ContainerServiceProtocol = "HTTP"
	ContainerServiceProtocolHttps ContainerServiceProtocol = "HTTPS"
	ContainerServiceProtocolTcp   ContainerServiceProtocol = "TCP"
	ContainerServiceProtocolUdp   ContainerServiceProtocol = "UDP"
)

// ContainerServiceState represents valid values for ContainerServiceState.
type ContainerServiceState string

const (
	ContainerServiceStatePending   ContainerServiceState = "PENDING"
	ContainerServiceStateReady     ContainerServiceState = "READY"
	ContainerServiceStateRunning   ContainerServiceState = "RUNNING"
	ContainerServiceStateUpdating  ContainerServiceState = "UPDATING"
	ContainerServiceStateDeleting  ContainerServiceState = "DELETING"
	ContainerServiceStateDisabled  ContainerServiceState = "DISABLED"
	ContainerServiceStateDeploying ContainerServiceState = "DEPLOYING"
)

// ContainerServiceStateDetailCode represents valid values for ContainerServiceStateDetailCode.
type ContainerServiceStateDetailCode string

const (
	ContainerServiceStateDetailCodeCreatingSystemResources       ContainerServiceStateDetailCode = "CREATING_SYSTEM_RESOURCES"
	ContainerServiceStateDetailCodeCreatingNetworkInfrastructure ContainerServiceStateDetailCode = "CREATING_NETWORK_INFRASTRUCTURE"
	ContainerServiceStateDetailCodeProvisioningCertificate       ContainerServiceStateDetailCode = "PROVISIONING_CERTIFICATE"
	ContainerServiceStateDetailCodeProvisioningService           ContainerServiceStateDetailCode = "PROVISIONING_SERVICE"
	ContainerServiceStateDetailCodeCreatingDeployment            ContainerServiceStateDetailCode = "CREATING_DEPLOYMENT"
	ContainerServiceStateDetailCodeEvaluatingHealthCheck         ContainerServiceStateDetailCode = "EVALUATING_HEALTH_CHECK"
	ContainerServiceStateDetailCodeActivatingDeployment          ContainerServiceStateDetailCode = "ACTIVATING_DEPLOYMENT"
	ContainerServiceStateDetailCodeCertificateLimitExceeded      ContainerServiceStateDetailCode = "CERTIFICATE_LIMIT_EXCEEDED"
	ContainerServiceStateDetailCodeUnknownError                  ContainerServiceStateDetailCode = "UNKNOWN_ERROR"
)

// Currency represents valid values for Currency.
type Currency string

const (
	CurrencyUsd Currency = "USD"
)

// DiskSnapshotState represents valid values for DiskSnapshotState.
type DiskSnapshotState string

const (
	DiskSnapshotStatePending   DiskSnapshotState = "pending"
	DiskSnapshotStateCompleted DiskSnapshotState = "completed"
	DiskSnapshotStateError     DiskSnapshotState = "error"
	DiskSnapshotStateUnknown   DiskSnapshotState = "unknown"
)

// DiskState represents valid values for DiskState.
type DiskState string

const (
	DiskStatePending   DiskState = "pending"
	DiskStateError     DiskState = "error"
	DiskStateAvailable DiskState = "available"
	DiskStateInUse     DiskState = "in-use"
	DiskStateUnknown   DiskState = "unknown"
)

// DistributionMetricName represents valid values for DistributionMetricName.
type DistributionMetricName string

const (
	DistributionMetricNameRequests         DistributionMetricName = "Requests"
	DistributionMetricNameBytesdownloaded  DistributionMetricName = "BytesDownloaded"
	DistributionMetricNameBytesuploaded    DistributionMetricName = "BytesUploaded"
	DistributionMetricNameTotalerrorrate   DistributionMetricName = "TotalErrorRate"
	DistributionMetricNameHttp4xxerrorrate DistributionMetricName = "Http4xxErrorRate"
	DistributionMetricNameHttp5xxerrorrate DistributionMetricName = "Http5xxErrorRate"
)

// DnsRecordCreationStateCode represents valid values for DnsRecordCreationStateCode.
type DnsRecordCreationStateCode string

const (
	DnsRecordCreationStateCodeSucceeded DnsRecordCreationStateCode = "SUCCEEDED"
	DnsRecordCreationStateCodeStarted   DnsRecordCreationStateCode = "STARTED"
	DnsRecordCreationStateCodeFailed    DnsRecordCreationStateCode = "FAILED"
)

// ExportSnapshotRecordSourceType represents valid values for ExportSnapshotRecordSourceType.
type ExportSnapshotRecordSourceType string

const (
	ExportSnapshotRecordSourceTypeInstancesnapshot ExportSnapshotRecordSourceType = "InstanceSnapshot"
	ExportSnapshotRecordSourceTypeDisksnapshot     ExportSnapshotRecordSourceType = "DiskSnapshot"
)

// ForwardValues represents valid values for ForwardValues.
type ForwardValues string

const (
	ForwardValuesNone      ForwardValues = "none"
	ForwardValuesAllowList ForwardValues = "allow-list"
	ForwardValuesAll       ForwardValues = "all"
)

// HeaderEnum represents valid values for HeaderEnum.
type HeaderEnum string

const (
	HeaderEnumAccept                    HeaderEnum = "Accept"
	HeaderEnumAcceptCharset             HeaderEnum = "Accept-Charset"
	HeaderEnumAcceptDatetime            HeaderEnum = "Accept-Datetime"
	HeaderEnumAcceptEncoding            HeaderEnum = "Accept-Encoding"
	HeaderEnumAcceptLanguage            HeaderEnum = "Accept-Language"
	HeaderEnumAuthorization             HeaderEnum = "Authorization"
	HeaderEnumCloudfrontForwardedProto  HeaderEnum = "CloudFront-Forwarded-Proto"
	HeaderEnumCloudfrontIsDesktopViewer HeaderEnum = "CloudFront-Is-Desktop-Viewer"
	HeaderEnumCloudfrontIsMobileViewer  HeaderEnum = "CloudFront-Is-Mobile-Viewer"
	HeaderEnumCloudfrontIsSmarttvViewer HeaderEnum = "CloudFront-Is-SmartTV-Viewer"
	HeaderEnumCloudfrontIsTabletViewer  HeaderEnum = "CloudFront-Is-Tablet-Viewer"
	HeaderEnumCloudfrontViewerCountry   HeaderEnum = "CloudFront-Viewer-Country"
	HeaderEnumHost                      HeaderEnum = "Host"
	HeaderEnumOrigin                    HeaderEnum = "Origin"
	HeaderEnumReferer                   HeaderEnum = "Referer"
)

// HttpEndpoint represents valid values for HttpEndpoint.
type HttpEndpoint string

const (
	HttpEndpointDisabled HttpEndpoint = "disabled"
	HttpEndpointEnabled  HttpEndpoint = "enabled"
)

// HttpProtocolIpv6 represents valid values for HttpProtocolIpv6.
type HttpProtocolIpv6 string

const (
	HttpProtocolIpv6Disabled HttpProtocolIpv6 = "disabled"
	HttpProtocolIpv6Enabled  HttpProtocolIpv6 = "enabled"
)

// HttpTokens represents valid values for HttpTokens.
type HttpTokens string

const (
	HttpTokensOptional HttpTokens = "optional"
	HttpTokensRequired HttpTokens = "required"
)

// InstanceAccessProtocol represents valid values for InstanceAccessProtocol.
type InstanceAccessProtocol string

const (
	InstanceAccessProtocolSsh InstanceAccessProtocol = "ssh"
	InstanceAccessProtocolRdp InstanceAccessProtocol = "rdp"
)

// InstanceHealthReason represents valid values for InstanceHealthReason.
type InstanceHealthReason string

const (
	InstanceHealthReasonLbRegistrationinprogress         InstanceHealthReason = "Lb.RegistrationInProgress"
	InstanceHealthReasonLbInitialhealthchecking          InstanceHealthReason = "Lb.InitialHealthChecking"
	InstanceHealthReasonLbInternalerror                  InstanceHealthReason = "Lb.InternalError"
	InstanceHealthReasonInstanceResponsecodemismatch     InstanceHealthReason = "Instance.ResponseCodeMismatch"
	InstanceHealthReasonInstanceTimeout                  InstanceHealthReason = "Instance.Timeout"
	InstanceHealthReasonInstanceFailedhealthchecks       InstanceHealthReason = "Instance.FailedHealthChecks"
	InstanceHealthReasonInstanceNotregistered            InstanceHealthReason = "Instance.NotRegistered"
	InstanceHealthReasonInstanceNotinuse                 InstanceHealthReason = "Instance.NotInUse"
	InstanceHealthReasonInstanceDeregistrationinprogress InstanceHealthReason = "Instance.DeregistrationInProgress"
	InstanceHealthReasonInstanceInvalidstate             InstanceHealthReason = "Instance.InvalidState"
	InstanceHealthReasonInstanceIpunusable               InstanceHealthReason = "Instance.IpUnusable"
)

// InstanceHealthState represents valid values for InstanceHealthState.
type InstanceHealthState string

const (
	InstanceHealthStateInitial     InstanceHealthState = "initial"
	InstanceHealthStateHealthy     InstanceHealthState = "healthy"
	InstanceHealthStateUnhealthy   InstanceHealthState = "unhealthy"
	InstanceHealthStateUnused      InstanceHealthState = "unused"
	InstanceHealthStateDraining    InstanceHealthState = "draining"
	InstanceHealthStateUnavailable InstanceHealthState = "unavailable"
)

// InstanceMetadataState represents valid values for InstanceMetadataState.
type InstanceMetadataState string

const (
	InstanceMetadataStatePending InstanceMetadataState = "pending"
	InstanceMetadataStateApplied InstanceMetadataState = "applied"
)

// InstanceMetricName represents valid values for InstanceMetricName.
type InstanceMetricName string

const (
	InstanceMetricNameCpuutilization            InstanceMetricName = "CPUUtilization"
	InstanceMetricNameNetworkin                 InstanceMetricName = "NetworkIn"
	InstanceMetricNameNetworkout                InstanceMetricName = "NetworkOut"
	InstanceMetricNameStatuscheckfailed         InstanceMetricName = "StatusCheckFailed"
	InstanceMetricNameStatuscheckfailedInstance InstanceMetricName = "StatusCheckFailed_Instance"
	InstanceMetricNameStatuscheckfailedSystem   InstanceMetricName = "StatusCheckFailed_System"
	InstanceMetricNameBurstcapacitytime         InstanceMetricName = "BurstCapacityTime"
	InstanceMetricNameBurstcapacitypercentage   InstanceMetricName = "BurstCapacityPercentage"
	InstanceMetricNameMetadatanotoken           InstanceMetricName = "MetadataNoToken"
)

// InstancePlatform represents valid values for InstancePlatform.
type InstancePlatform string

const (
	InstancePlatformLinuxUnix InstancePlatform = "LINUX_UNIX"
	InstancePlatformWindows   InstancePlatform = "WINDOWS"
)

// InstanceSnapshotState represents valid values for InstanceSnapshotState.
type InstanceSnapshotState string

const (
	InstanceSnapshotStatePending   InstanceSnapshotState = "pending"
	InstanceSnapshotStateError     InstanceSnapshotState = "error"
	InstanceSnapshotStateAvailable InstanceSnapshotState = "available"
)

// IpAddressType represents valid values for IpAddressType.
type IpAddressType string

const (
	IpAddressTypeDualstack IpAddressType = "dualstack"
	IpAddressTypeIpv4      IpAddressType = "ipv4"
	IpAddressTypeIpv6      IpAddressType = "ipv6"
)

// LoadBalancerAttributeName represents valid values for LoadBalancerAttributeName.
type LoadBalancerAttributeName string

const (
	LoadBalancerAttributeNameHealthcheckpath                          LoadBalancerAttributeName = "HealthCheckPath"
	LoadBalancerAttributeNameSessionstickinessenabled                 LoadBalancerAttributeName = "SessionStickinessEnabled"
	LoadBalancerAttributeNameSessionstickinessLbCookiedurationseconds LoadBalancerAttributeName = "SessionStickiness_LB_CookieDurationSeconds"
	LoadBalancerAttributeNameHttpsredirectionenabled                  LoadBalancerAttributeName = "HttpsRedirectionEnabled"
	LoadBalancerAttributeNameTlspolicyname                            LoadBalancerAttributeName = "TlsPolicyName"
)

// LoadBalancerMetricName represents valid values for LoadBalancerMetricName.
type LoadBalancerMetricName string

const (
	LoadBalancerMetricNameClienttlsnegotiationerrorcount LoadBalancerMetricName = "ClientTLSNegotiationErrorCount"
	LoadBalancerMetricNameHealthyhostcount               LoadBalancerMetricName = "HealthyHostCount"
	LoadBalancerMetricNameUnhealthyhostcount             LoadBalancerMetricName = "UnhealthyHostCount"
	LoadBalancerMetricNameHttpcodeLb4xxCount             LoadBalancerMetricName = "HTTPCode_LB_4XX_Count"
	LoadBalancerMetricNameHttpcodeLb5xxCount             LoadBalancerMetricName = "HTTPCode_LB_5XX_Count"
	LoadBalancerMetricNameHttpcodeInstance2xxCount       LoadBalancerMetricName = "HTTPCode_Instance_2XX_Count"
	LoadBalancerMetricNameHttpcodeInstance3xxCount       LoadBalancerMetricName = "HTTPCode_Instance_3XX_Count"
	LoadBalancerMetricNameHttpcodeInstance4xxCount       LoadBalancerMetricName = "HTTPCode_Instance_4XX_Count"
	LoadBalancerMetricNameHttpcodeInstance5xxCount       LoadBalancerMetricName = "HTTPCode_Instance_5XX_Count"
	LoadBalancerMetricNameInstanceresponsetime           LoadBalancerMetricName = "InstanceResponseTime"
	LoadBalancerMetricNameRejectedconnectioncount        LoadBalancerMetricName = "RejectedConnectionCount"
	LoadBalancerMetricNameRequestcount                   LoadBalancerMetricName = "RequestCount"
)

// LoadBalancerProtocol represents valid values for LoadBalancerProtocol.
type LoadBalancerProtocol string

const (
	LoadBalancerProtocolHttpHttps LoadBalancerProtocol = "HTTP_HTTPS"
	LoadBalancerProtocolHttp      LoadBalancerProtocol = "HTTP"
)

// LoadBalancerState represents valid values for LoadBalancerState.
type LoadBalancerState string

const (
	LoadBalancerStateActive         LoadBalancerState = "active"
	LoadBalancerStateProvisioning   LoadBalancerState = "provisioning"
	LoadBalancerStateActiveImpaired LoadBalancerState = "active_impaired"
	LoadBalancerStateFailed         LoadBalancerState = "failed"
	LoadBalancerStateUnknown        LoadBalancerState = "unknown"
)

// LoadBalancerTlsCertificateDnsRecordCreationStateCode represents valid values for LoadBalancerTlsCertificateDnsRecordCreationStateCode.
type LoadBalancerTlsCertificateDnsRecordCreationStateCode string

const (
	LoadBalancerTlsCertificateDnsRecordCreationStateCodeSucceeded LoadBalancerTlsCertificateDnsRecordCreationStateCode = "SUCCEEDED"
	LoadBalancerTlsCertificateDnsRecordCreationStateCodeStarted   LoadBalancerTlsCertificateDnsRecordCreationStateCode = "STARTED"
	LoadBalancerTlsCertificateDnsRecordCreationStateCodeFailed    LoadBalancerTlsCertificateDnsRecordCreationStateCode = "FAILED"
)

// LoadBalancerTlsCertificateDomainStatus represents valid values for LoadBalancerTlsCertificateDomainStatus.
type LoadBalancerTlsCertificateDomainStatus string

const (
	LoadBalancerTlsCertificateDomainStatusPendingValidation LoadBalancerTlsCertificateDomainStatus = "PENDING_VALIDATION"
	LoadBalancerTlsCertificateDomainStatusFailed            LoadBalancerTlsCertificateDomainStatus = "FAILED"
	LoadBalancerTlsCertificateDomainStatusSuccess           LoadBalancerTlsCertificateDomainStatus = "SUCCESS"
)

// LoadBalancerTlsCertificateFailureReason represents valid values for LoadBalancerTlsCertificateFailureReason.
type LoadBalancerTlsCertificateFailureReason string

const (
	LoadBalancerTlsCertificateFailureReasonNoAvailableContacts            LoadBalancerTlsCertificateFailureReason = "NO_AVAILABLE_CONTACTS"
	LoadBalancerTlsCertificateFailureReasonAdditionalVerificationRequired LoadBalancerTlsCertificateFailureReason = "ADDITIONAL_VERIFICATION_REQUIRED"
	LoadBalancerTlsCertificateFailureReasonDomainNotAllowed               LoadBalancerTlsCertificateFailureReason = "DOMAIN_NOT_ALLOWED"
	LoadBalancerTlsCertificateFailureReasonInvalidPublicDomain            LoadBalancerTlsCertificateFailureReason = "INVALID_PUBLIC_DOMAIN"
	LoadBalancerTlsCertificateFailureReasonOther                          LoadBalancerTlsCertificateFailureReason = "OTHER"
)

// LoadBalancerTlsCertificateRenewalStatus represents valid values for LoadBalancerTlsCertificateRenewalStatus.
type LoadBalancerTlsCertificateRenewalStatus string

const (
	LoadBalancerTlsCertificateRenewalStatusPendingAutoRenewal LoadBalancerTlsCertificateRenewalStatus = "PENDING_AUTO_RENEWAL"
	LoadBalancerTlsCertificateRenewalStatusPendingValidation  LoadBalancerTlsCertificateRenewalStatus = "PENDING_VALIDATION"
	LoadBalancerTlsCertificateRenewalStatusSuccess            LoadBalancerTlsCertificateRenewalStatus = "SUCCESS"
	LoadBalancerTlsCertificateRenewalStatusFailed             LoadBalancerTlsCertificateRenewalStatus = "FAILED"
)

// LoadBalancerTlsCertificateRevocationReason represents valid values for LoadBalancerTlsCertificateRevocationReason.
type LoadBalancerTlsCertificateRevocationReason string

const (
	LoadBalancerTlsCertificateRevocationReasonUnspecified          LoadBalancerTlsCertificateRevocationReason = "UNSPECIFIED"
	LoadBalancerTlsCertificateRevocationReasonKeyCompromise        LoadBalancerTlsCertificateRevocationReason = "KEY_COMPROMISE"
	LoadBalancerTlsCertificateRevocationReasonCaCompromise         LoadBalancerTlsCertificateRevocationReason = "CA_COMPROMISE"
	LoadBalancerTlsCertificateRevocationReasonAffiliationChanged   LoadBalancerTlsCertificateRevocationReason = "AFFILIATION_CHANGED"
	LoadBalancerTlsCertificateRevocationReasonSuperceded           LoadBalancerTlsCertificateRevocationReason = "SUPERCEDED"
	LoadBalancerTlsCertificateRevocationReasonCessationOfOperation LoadBalancerTlsCertificateRevocationReason = "CESSATION_OF_OPERATION"
	LoadBalancerTlsCertificateRevocationReasonCertificateHold      LoadBalancerTlsCertificateRevocationReason = "CERTIFICATE_HOLD"
	LoadBalancerTlsCertificateRevocationReasonRemoveFromCrl        LoadBalancerTlsCertificateRevocationReason = "REMOVE_FROM_CRL"
	LoadBalancerTlsCertificateRevocationReasonPrivilegeWithdrawn   LoadBalancerTlsCertificateRevocationReason = "PRIVILEGE_WITHDRAWN"
	LoadBalancerTlsCertificateRevocationReasonAACompromise         LoadBalancerTlsCertificateRevocationReason = "A_A_COMPROMISE"
)

// LoadBalancerTlsCertificateStatus represents valid values for LoadBalancerTlsCertificateStatus.
type LoadBalancerTlsCertificateStatus string

const (
	LoadBalancerTlsCertificateStatusPendingValidation  LoadBalancerTlsCertificateStatus = "PENDING_VALIDATION"
	LoadBalancerTlsCertificateStatusIssued             LoadBalancerTlsCertificateStatus = "ISSUED"
	LoadBalancerTlsCertificateStatusInactive           LoadBalancerTlsCertificateStatus = "INACTIVE"
	LoadBalancerTlsCertificateStatusExpired            LoadBalancerTlsCertificateStatus = "EXPIRED"
	LoadBalancerTlsCertificateStatusValidationTimedOut LoadBalancerTlsCertificateStatus = "VALIDATION_TIMED_OUT"
	LoadBalancerTlsCertificateStatusRevoked            LoadBalancerTlsCertificateStatus = "REVOKED"
	LoadBalancerTlsCertificateStatusFailed             LoadBalancerTlsCertificateStatus = "FAILED"
	LoadBalancerTlsCertificateStatusUnknown            LoadBalancerTlsCertificateStatus = "UNKNOWN"
)

// MetricName represents valid values for MetricName.
type MetricName string

const (
	MetricNameCpuutilization                 MetricName = "CPUUtilization"
	MetricNameNetworkin                      MetricName = "NetworkIn"
	MetricNameNetworkout                     MetricName = "NetworkOut"
	MetricNameStatuscheckfailed              MetricName = "StatusCheckFailed"
	MetricNameStatuscheckfailedInstance      MetricName = "StatusCheckFailed_Instance"
	MetricNameStatuscheckfailedSystem        MetricName = "StatusCheckFailed_System"
	MetricNameClienttlsnegotiationerrorcount MetricName = "ClientTLSNegotiationErrorCount"
	MetricNameHealthyhostcount               MetricName = "HealthyHostCount"
	MetricNameUnhealthyhostcount             MetricName = "UnhealthyHostCount"
	MetricNameHttpcodeLb4xxCount             MetricName = "HTTPCode_LB_4XX_Count"
	MetricNameHttpcodeLb5xxCount             MetricName = "HTTPCode_LB_5XX_Count"
	MetricNameHttpcodeInstance2xxCount       MetricName = "HTTPCode_Instance_2XX_Count"
	MetricNameHttpcodeInstance3xxCount       MetricName = "HTTPCode_Instance_3XX_Count"
	MetricNameHttpcodeInstance4xxCount       MetricName = "HTTPCode_Instance_4XX_Count"
	MetricNameHttpcodeInstance5xxCount       MetricName = "HTTPCode_Instance_5XX_Count"
	MetricNameInstanceresponsetime           MetricName = "InstanceResponseTime"
	MetricNameRejectedconnectioncount        MetricName = "RejectedConnectionCount"
	MetricNameRequestcount                   MetricName = "RequestCount"
	MetricNameDatabaseconnections            MetricName = "DatabaseConnections"
	MetricNameDiskqueuedepth                 MetricName = "DiskQueueDepth"
	MetricNameFreestoragespace               MetricName = "FreeStorageSpace"
	MetricNameNetworkreceivethroughput       MetricName = "NetworkReceiveThroughput"
	MetricNameNetworktransmitthroughput      MetricName = "NetworkTransmitThroughput"
	MetricNameBurstcapacitytime              MetricName = "BurstCapacityTime"
	MetricNameBurstcapacitypercentage        MetricName = "BurstCapacityPercentage"
)

// MetricStatistic represents valid values for MetricStatistic.
type MetricStatistic string

const (
	MetricStatisticMinimum     MetricStatistic = "Minimum"
	MetricStatisticMaximum     MetricStatistic = "Maximum"
	MetricStatisticSum         MetricStatistic = "Sum"
	MetricStatisticAverage     MetricStatistic = "Average"
	MetricStatisticSamplecount MetricStatistic = "SampleCount"
)

// MetricUnit represents valid values for MetricUnit.
type MetricUnit string

const (
	MetricUnitSeconds            MetricUnit = "Seconds"
	MetricUnitMicroseconds       MetricUnit = "Microseconds"
	MetricUnitMilliseconds       MetricUnit = "Milliseconds"
	MetricUnitBytes              MetricUnit = "Bytes"
	MetricUnitKilobytes          MetricUnit = "Kilobytes"
	MetricUnitMegabytes          MetricUnit = "Megabytes"
	MetricUnitGigabytes          MetricUnit = "Gigabytes"
	MetricUnitTerabytes          MetricUnit = "Terabytes"
	MetricUnitBits               MetricUnit = "Bits"
	MetricUnitKilobits           MetricUnit = "Kilobits"
	MetricUnitMegabits           MetricUnit = "Megabits"
	MetricUnitGigabits           MetricUnit = "Gigabits"
	MetricUnitTerabits           MetricUnit = "Terabits"
	MetricUnitPercent            MetricUnit = "Percent"
	MetricUnitCount              MetricUnit = "Count"
	MetricUnitBytespersecond     MetricUnit = "Bytes/Second"
	MetricUnitKilobytespersecond MetricUnit = "Kilobytes/Second"
	MetricUnitMegabytespersecond MetricUnit = "Megabytes/Second"
	MetricUnitGigabytespersecond MetricUnit = "Gigabytes/Second"
	MetricUnitTerabytespersecond MetricUnit = "Terabytes/Second"
	MetricUnitBitspersecond      MetricUnit = "Bits/Second"
	MetricUnitKilobitspersecond  MetricUnit = "Kilobits/Second"
	MetricUnitMegabitspersecond  MetricUnit = "Megabits/Second"
	MetricUnitGigabitspersecond  MetricUnit = "Gigabits/Second"
	MetricUnitTerabitspersecond  MetricUnit = "Terabits/Second"
	MetricUnitCountpersecond     MetricUnit = "Count/Second"
	MetricUnitNone               MetricUnit = "None"
)

// NameServersUpdateStateCode represents valid values for NameServersUpdateStateCode.
type NameServersUpdateStateCode string

const (
	NameServersUpdateStateCodeSucceeded NameServersUpdateStateCode = "SUCCEEDED"
	NameServersUpdateStateCodePending   NameServersUpdateStateCode = "PENDING"
	NameServersUpdateStateCodeFailed    NameServersUpdateStateCode = "FAILED"
	NameServersUpdateStateCodeStarted   NameServersUpdateStateCode = "STARTED"
)

// NetworkProtocol represents valid values for NetworkProtocol.
type NetworkProtocol string

const (
	NetworkProtocolTcp    NetworkProtocol = "tcp"
	NetworkProtocolAll    NetworkProtocol = "all"
	NetworkProtocolUdp    NetworkProtocol = "udp"
	NetworkProtocolIcmp   NetworkProtocol = "icmp"
	NetworkProtocolIcmpv6 NetworkProtocol = "icmpv6"
)

// OperationStatus represents valid values for OperationStatus.
type OperationStatus string

const (
	OperationStatusNotstarted OperationStatus = "NotStarted"
	OperationStatusStarted    OperationStatus = "Started"
	OperationStatusFailed     OperationStatus = "Failed"
	OperationStatusCompleted  OperationStatus = "Completed"
	OperationStatusSucceeded  OperationStatus = "Succeeded"
)

// OperationType represents valid values for OperationType.
type OperationType string

const (
	OperationTypeDeleteknownhostkeys                  OperationType = "DeleteKnownHostKeys"
	OperationTypeDeleteinstance                       OperationType = "DeleteInstance"
	OperationTypeCreateinstance                       OperationType = "CreateInstance"
	OperationTypeStopinstance                         OperationType = "StopInstance"
	OperationTypeStartinstance                        OperationType = "StartInstance"
	OperationTypeRebootinstance                       OperationType = "RebootInstance"
	OperationTypeOpeninstancepublicports              OperationType = "OpenInstancePublicPorts"
	OperationTypePutinstancepublicports               OperationType = "PutInstancePublicPorts"
	OperationTypeCloseinstancepublicports             OperationType = "CloseInstancePublicPorts"
	OperationTypeAllocatestaticip                     OperationType = "AllocateStaticIp"
	OperationTypeReleasestaticip                      OperationType = "ReleaseStaticIp"
	OperationTypeAttachstaticip                       OperationType = "AttachStaticIp"
	OperationTypeDetachstaticip                       OperationType = "DetachStaticIp"
	OperationTypeUpdatedomainentry                    OperationType = "UpdateDomainEntry"
	OperationTypeDeletedomainentry                    OperationType = "DeleteDomainEntry"
	OperationTypeCreatedomain                         OperationType = "CreateDomain"
	OperationTypeDeletedomain                         OperationType = "DeleteDomain"
	OperationTypeCreateinstancesnapshot               OperationType = "CreateInstanceSnapshot"
	OperationTypeDeleteinstancesnapshot               OperationType = "DeleteInstanceSnapshot"
	OperationTypeCreateinstancesfromsnapshot          OperationType = "CreateInstancesFromSnapshot"
	OperationTypeCreateloadbalancer                   OperationType = "CreateLoadBalancer"
	OperationTypeDeleteloadbalancer                   OperationType = "DeleteLoadBalancer"
	OperationTypeAttachinstancestoloadbalancer        OperationType = "AttachInstancesToLoadBalancer"
	OperationTypeDetachinstancesfromloadbalancer      OperationType = "DetachInstancesFromLoadBalancer"
	OperationTypeUpdateloadbalancerattribute          OperationType = "UpdateLoadBalancerAttribute"
	OperationTypeCreateloadbalancertlscertificate     OperationType = "CreateLoadBalancerTlsCertificate"
	OperationTypeDeleteloadbalancertlscertificate     OperationType = "DeleteLoadBalancerTlsCertificate"
	OperationTypeAttachloadbalancertlscertificate     OperationType = "AttachLoadBalancerTlsCertificate"
	OperationTypeCreatedisk                           OperationType = "CreateDisk"
	OperationTypeDeletedisk                           OperationType = "DeleteDisk"
	OperationTypeAttachdisk                           OperationType = "AttachDisk"
	OperationTypeDetachdisk                           OperationType = "DetachDisk"
	OperationTypeCreatedisksnapshot                   OperationType = "CreateDiskSnapshot"
	OperationTypeDeletedisksnapshot                   OperationType = "DeleteDiskSnapshot"
	OperationTypeCreatediskfromsnapshot               OperationType = "CreateDiskFromSnapshot"
	OperationTypeCreaterelationaldatabase             OperationType = "CreateRelationalDatabase"
	OperationTypeUpdaterelationaldatabase             OperationType = "UpdateRelationalDatabase"
	OperationTypeDeleterelationaldatabase             OperationType = "DeleteRelationalDatabase"
	OperationTypeCreaterelationaldatabasefromsnapshot OperationType = "CreateRelationalDatabaseFromSnapshot"
	OperationTypeCreaterelationaldatabasesnapshot     OperationType = "CreateRelationalDatabaseSnapshot"
	OperationTypeDeleterelationaldatabasesnapshot     OperationType = "DeleteRelationalDatabaseSnapshot"
	OperationTypeUpdaterelationaldatabaseparameters   OperationType = "UpdateRelationalDatabaseParameters"
	OperationTypeStartrelationaldatabase              OperationType = "StartRelationalDatabase"
	OperationTypeRebootrelationaldatabase             OperationType = "RebootRelationalDatabase"
	OperationTypeStoprelationaldatabase               OperationType = "StopRelationalDatabase"
	OperationTypeEnableaddon                          OperationType = "EnableAddOn"
	OperationTypeDisableaddon                         OperationType = "DisableAddOn"
	OperationTypePutalarm                             OperationType = "PutAlarm"
	OperationTypeGetalarms                            OperationType = "GetAlarms"
	OperationTypeDeletealarm                          OperationType = "DeleteAlarm"
	OperationTypeTestalarm                            OperationType = "TestAlarm"
	OperationTypeCreatecontactmethod                  OperationType = "CreateContactMethod"
	OperationTypeGetcontactmethods                    OperationType = "GetContactMethods"
	OperationTypeSendcontactmethodverification        OperationType = "SendContactMethodVerification"
	OperationTypeDeletecontactmethod                  OperationType = "DeleteContactMethod"
	OperationTypeCreatedistribution                   OperationType = "CreateDistribution"
	OperationTypeUpdatedistribution                   OperationType = "UpdateDistribution"
	OperationTypeDeletedistribution                   OperationType = "DeleteDistribution"
	OperationTypeResetdistributioncache               OperationType = "ResetDistributionCache"
	OperationTypeAttachcertificatetodistribution      OperationType = "AttachCertificateToDistribution"
	OperationTypeDetachcertificatefromdistribution    OperationType = "DetachCertificateFromDistribution"
	OperationTypeUpdatedistributionbundle             OperationType = "UpdateDistributionBundle"
	OperationTypeSetipaddresstype                     OperationType = "SetIpAddressType"
	OperationTypeCreatecertificate                    OperationType = "CreateCertificate"
	OperationTypeDeletecertificate                    OperationType = "DeleteCertificate"
	OperationTypeCreatecontainerservice               OperationType = "CreateContainerService"
	OperationTypeUpdatecontainerservice               OperationType = "UpdateContainerService"
	OperationTypeDeletecontainerservice               OperationType = "DeleteContainerService"
	OperationTypeCreatecontainerservicedeployment     OperationType = "CreateContainerServiceDeployment"
	OperationTypeCreatecontainerserviceregistrylogin  OperationType = "CreateContainerServiceRegistryLogin"
	OperationTypeRegistercontainerimage               OperationType = "RegisterContainerImage"
	OperationTypeDeletecontainerimage                 OperationType = "DeleteContainerImage"
	OperationTypeCreatebucket                         OperationType = "CreateBucket"
	OperationTypeDeletebucket                         OperationType = "DeleteBucket"
	OperationTypeCreatebucketaccesskey                OperationType = "CreateBucketAccessKey"
	OperationTypeDeletebucketaccesskey                OperationType = "DeleteBucketAccessKey"
	OperationTypeUpdatebucketbundle                   OperationType = "UpdateBucketBundle"
	OperationTypeUpdatebucket                         OperationType = "UpdateBucket"
	OperationTypeSetresourceaccessforbucket           OperationType = "SetResourceAccessForBucket"
	OperationTypeUpdateinstancemetadataoptions        OperationType = "UpdateInstanceMetadataOptions"
	OperationTypeStartguisession                      OperationType = "StartGUISession"
	OperationTypeStopguisession                       OperationType = "StopGUISession"
	OperationTypeSetupinstancehttps                   OperationType = "SetupInstanceHttps"
)

// OriginProtocolPolicyEnum represents valid values for OriginProtocolPolicyEnum.
type OriginProtocolPolicyEnum string

const (
	OriginProtocolPolicyEnumHttpOnly  OriginProtocolPolicyEnum = "http-only"
	OriginProtocolPolicyEnumHttpsOnly OriginProtocolPolicyEnum = "https-only"
)

// PortAccessType represents valid values for PortAccessType.
type PortAccessType string

const (
	PortAccessTypePublic  PortAccessType = "Public"
	PortAccessTypePrivate PortAccessType = "Private"
)

// PortInfoSourceType represents valid values for PortInfoSourceType.
type PortInfoSourceType string

const (
	PortInfoSourceTypeDefault  PortInfoSourceType = "DEFAULT"
	PortInfoSourceTypeInstance PortInfoSourceType = "INSTANCE"
	PortInfoSourceTypeNone     PortInfoSourceType = "NONE"
	PortInfoSourceTypeClosed   PortInfoSourceType = "CLOSED"
)

// PortState represents valid values for PortState.
type PortState string

const (
	PortStateOpen   PortState = "open"
	PortStateClosed PortState = "closed"
)

// PricingUnit represents valid values for PricingUnit.
type PricingUnit string

const (
	PricingUnitGb      PricingUnit = "GB"
	PricingUnitHrs     PricingUnit = "Hrs"
	PricingUnitGbMo    PricingUnit = "GB-Mo"
	PricingUnitBundles PricingUnit = "Bundles"
	PricingUnitQueries PricingUnit = "Queries"
)

// R53HostedZoneDeletionStateCode represents valid values for R53HostedZoneDeletionStateCode.
type R53HostedZoneDeletionStateCode string

const (
	R53HostedZoneDeletionStateCodeSucceeded R53HostedZoneDeletionStateCode = "SUCCEEDED"
	R53HostedZoneDeletionStateCodePending   R53HostedZoneDeletionStateCode = "PENDING"
	R53HostedZoneDeletionStateCodeFailed    R53HostedZoneDeletionStateCode = "FAILED"
	R53HostedZoneDeletionStateCodeStarted   R53HostedZoneDeletionStateCode = "STARTED"
)

// RecordState represents valid values for RecordState.
type RecordState string

const (
	RecordStateStarted   RecordState = "Started"
	RecordStateSucceeded RecordState = "Succeeded"
	RecordStateFailed    RecordState = "Failed"
)

// RegionName represents valid values for RegionName.
type RegionName string

const (
	RegionNameUsEast1      RegionName = "us-east-1"
	RegionNameUsEast2      RegionName = "us-east-2"
	RegionNameUsWest1      RegionName = "us-west-1"
	RegionNameUsWest2      RegionName = "us-west-2"
	RegionNameEuWest1      RegionName = "eu-west-1"
	RegionNameEuWest2      RegionName = "eu-west-2"
	RegionNameEuWest3      RegionName = "eu-west-3"
	RegionNameEuCentral1   RegionName = "eu-central-1"
	RegionNameCaCentral1   RegionName = "ca-central-1"
	RegionNameApSouth1     RegionName = "ap-south-1"
	RegionNameApSoutheast1 RegionName = "ap-southeast-1"
	RegionNameApSoutheast2 RegionName = "ap-southeast-2"
	RegionNameApNortheast1 RegionName = "ap-northeast-1"
	RegionNameApNortheast2 RegionName = "ap-northeast-2"
	RegionNameEuNorth1     RegionName = "eu-north-1"
	RegionNameApSoutheast3 RegionName = "ap-southeast-3"
)

// RelationalDatabaseEngine represents valid values for RelationalDatabaseEngine.
type RelationalDatabaseEngine string

const (
	RelationalDatabaseEngineMysql RelationalDatabaseEngine = "mysql"
)

// RelationalDatabaseMetricName represents valid values for RelationalDatabaseMetricName.
type RelationalDatabaseMetricName string

const (
	RelationalDatabaseMetricNameCpuutilization            RelationalDatabaseMetricName = "CPUUtilization"
	RelationalDatabaseMetricNameDatabaseconnections       RelationalDatabaseMetricName = "DatabaseConnections"
	RelationalDatabaseMetricNameDiskqueuedepth            RelationalDatabaseMetricName = "DiskQueueDepth"
	RelationalDatabaseMetricNameFreestoragespace          RelationalDatabaseMetricName = "FreeStorageSpace"
	RelationalDatabaseMetricNameNetworkreceivethroughput  RelationalDatabaseMetricName = "NetworkReceiveThroughput"
	RelationalDatabaseMetricNameNetworktransmitthroughput RelationalDatabaseMetricName = "NetworkTransmitThroughput"
)

// RelationalDatabasePasswordVersion represents valid values for RelationalDatabasePasswordVersion.
type RelationalDatabasePasswordVersion string

const (
	RelationalDatabasePasswordVersionCurrent  RelationalDatabasePasswordVersion = "CURRENT"
	RelationalDatabasePasswordVersionPrevious RelationalDatabasePasswordVersion = "PREVIOUS"
	RelationalDatabasePasswordVersionPending  RelationalDatabasePasswordVersion = "PENDING"
)

// RenewalStatus represents valid values for RenewalStatus.
type RenewalStatus string

const (
	RenewalStatusPendingautorenewal RenewalStatus = "PendingAutoRenewal"
	RenewalStatusPendingvalidation  RenewalStatus = "PendingValidation"
	RenewalStatusSuccess            RenewalStatus = "Success"
	RenewalStatusFailed             RenewalStatus = "Failed"
)

// ResourceBucketAccess represents valid values for ResourceBucketAccess.
type ResourceBucketAccess string

const (
	ResourceBucketAccessAllow ResourceBucketAccess = "allow"
	ResourceBucketAccessDeny  ResourceBucketAccess = "deny"
)

// ResourceType represents valid values for ResourceType.
type ResourceType string

const (
	ResourceTypeContainerservice           ResourceType = "ContainerService"
	ResourceTypeInstance                   ResourceType = "Instance"
	ResourceTypeStaticip                   ResourceType = "StaticIp"
	ResourceTypeKeypair                    ResourceType = "KeyPair"
	ResourceTypeInstancesnapshot           ResourceType = "InstanceSnapshot"
	ResourceTypeDomain                     ResourceType = "Domain"
	ResourceTypePeeredvpc                  ResourceType = "PeeredVpc"
	ResourceTypeLoadbalancer               ResourceType = "LoadBalancer"
	ResourceTypeLoadbalancertlscertificate ResourceType = "LoadBalancerTlsCertificate"
	ResourceTypeDisk                       ResourceType = "Disk"
	ResourceTypeDisksnapshot               ResourceType = "DiskSnapshot"
	ResourceTypeRelationaldatabase         ResourceType = "RelationalDatabase"
	ResourceTypeRelationaldatabasesnapshot ResourceType = "RelationalDatabaseSnapshot"
	ResourceTypeExportsnapshotrecord       ResourceType = "ExportSnapshotRecord"
	ResourceTypeCloudformationstackrecord  ResourceType = "CloudFormationStackRecord"
	ResourceTypeAlarm                      ResourceType = "Alarm"
	ResourceTypeContactmethod              ResourceType = "ContactMethod"
	ResourceTypeDistribution               ResourceType = "Distribution"
	ResourceTypeCertificate                ResourceType = "Certificate"
	ResourceTypeBucket                     ResourceType = "Bucket"
)

// SetupStatus represents valid values for SetupStatus.
type SetupStatus string

const (
	SetupStatusSucceeded  SetupStatus = "succeeded"
	SetupStatusFailed     SetupStatus = "failed"
	SetupStatusInprogress SetupStatus = "inProgress"
)

// Status represents valid values for Status.
type Status string

const (
	StatusStartexpired             Status = "startExpired"
	StatusNotstarted               Status = "notStarted"
	StatusStarted                  Status = "started"
	StatusStarting                 Status = "starting"
	StatusStopped                  Status = "stopped"
	StatusStopping                 Status = "stopping"
	StatusSettingupinstance        Status = "settingUpInstance"
	StatusFailedinstancecreation   Status = "failedInstanceCreation"
	StatusFailedstartingguisession Status = "failedStartingGUISession"
	StatusFailedstoppingguisession Status = "failedStoppingGUISession"
)

// StatusType represents valid values for StatusType.
type StatusType string

const (
	StatusTypeActive   StatusType = "Active"
	StatusTypeInactive StatusType = "Inactive"
)

// TreatMissingData represents valid values for TreatMissingData.
type TreatMissingData string

const (
	TreatMissingDataBreaching    TreatMissingData = "breaching"
	TreatMissingDataNotbreaching TreatMissingData = "notBreaching"
	TreatMissingDataIgnore       TreatMissingData = "ignore"
	TreatMissingDataMissing      TreatMissingData = "missing"
)

// ViewerMinimumTlsProtocolVersionEnum represents valid values for ViewerMinimumTlsProtocolVersionEnum.
type ViewerMinimumTlsProtocolVersionEnum string

const (
	ViewerMinimumTlsProtocolVersionEnumTlsv112016 ViewerMinimumTlsProtocolVersionEnum = "TLSv1.1_2016"
	ViewerMinimumTlsProtocolVersionEnumTlsv122018 ViewerMinimumTlsProtocolVersionEnum = "TLSv1.2_2018"
	ViewerMinimumTlsProtocolVersionEnumTlsv122019 ViewerMinimumTlsProtocolVersionEnum = "TLSv1.2_2019"
	ViewerMinimumTlsProtocolVersionEnumTlsv122021 ViewerMinimumTlsProtocolVersionEnum = "TLSv1.2_2021"
)
