// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package mediaconnect

// Bridge_BridgeFlowSource represents AWS::MediaConnect::Bridge.BridgeFlowSource.
type Bridge_BridgeFlowSource struct {
	FlowArn                    any                                  `json:"FlowArn,omitempty"`
	FlowVpcInterfaceAttachment *BridgeSource_VpcInterfaceAttachment `json:"FlowVpcInterfaceAttachment,omitempty"`
	Name                       any                                  `json:"Name,omitempty"`
}

// Bridge_BridgeNetworkOutput represents AWS::MediaConnect::Bridge.BridgeNetworkOutput.
type Bridge_BridgeNetworkOutput struct {
	IpAddress   any `json:"IpAddress,omitempty"`
	Name        any `json:"Name,omitempty"`
	NetworkName any `json:"NetworkName,omitempty"`
	Port        any `json:"Port,omitempty"`
	Protocol    any `json:"Protocol,omitempty"`
	Ttl         any `json:"Ttl,omitempty"`
}

// Bridge_BridgeNetworkSource represents AWS::MediaConnect::Bridge.BridgeNetworkSource.
type Bridge_BridgeNetworkSource struct {
	MulticastIp             any                                   `json:"MulticastIp,omitempty"`
	MulticastSourceSettings *BridgeSource_MulticastSourceSettings `json:"MulticastSourceSettings,omitempty"`
	Name                    any                                   `json:"Name,omitempty"`
	NetworkName             any                                   `json:"NetworkName,omitempty"`
	Port                    any                                   `json:"Port,omitempty"`
	Protocol                any                                   `json:"Protocol,omitempty"`
}

// Bridge_BridgeOutput represents AWS::MediaConnect::Bridge.BridgeOutput.
type Bridge_BridgeOutput struct {
	NetworkOutput *BridgeOutput_BridgeNetworkOutput `json:"NetworkOutput,omitempty"`
}

// Bridge_BridgeSource represents AWS::MediaConnect::Bridge.BridgeSource.
type Bridge_BridgeSource struct {
	FlowSource    *BridgeSource_BridgeFlowSource    `json:"FlowSource,omitempty"`
	NetworkSource *BridgeSource_BridgeNetworkSource `json:"NetworkSource,omitempty"`
}

// Bridge_EgressGatewayBridge represents AWS::MediaConnect::Bridge.EgressGatewayBridge.
type Bridge_EgressGatewayBridge struct {
	MaxBitrate any `json:"MaxBitrate,omitempty"`
}

// Bridge_FailoverConfig represents AWS::MediaConnect::Bridge.FailoverConfig.
type Bridge_FailoverConfig struct {
	FailoverMode   any                    `json:"FailoverMode,omitempty"`
	SourcePriority *Bridge_SourcePriority `json:"SourcePriority,omitempty"`
	State          any                    `json:"State,omitempty"`
}

// Bridge_IngressGatewayBridge represents AWS::MediaConnect::Bridge.IngressGatewayBridge.
type Bridge_IngressGatewayBridge struct {
	MaxBitrate any `json:"MaxBitrate,omitempty"`
	MaxOutputs any `json:"MaxOutputs,omitempty"`
}

// Bridge_MulticastSourceSettings represents AWS::MediaConnect::Bridge.MulticastSourceSettings.
type Bridge_MulticastSourceSettings struct {
	MulticastSourceIp any `json:"MulticastSourceIp,omitempty"`
}

// Bridge_SourcePriority represents AWS::MediaConnect::Bridge.SourcePriority.
type Bridge_SourcePriority struct {
	PrimarySource any `json:"PrimarySource,omitempty"`
}

// Bridge_VpcInterfaceAttachment represents AWS::MediaConnect::Bridge.VpcInterfaceAttachment.
type Bridge_VpcInterfaceAttachment struct {
	VpcInterfaceName any `json:"VpcInterfaceName,omitempty"`
}
