// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package mediaconnect

// FlowOutput_DestinationConfiguration represents AWS::MediaConnect::FlowOutput.DestinationConfiguration.
type FlowOutput_DestinationConfiguration struct {
	DestinationIp   any                  `json:"DestinationIp,omitempty"`
	DestinationPort any                  `json:"DestinationPort,omitempty"`
	Interface_      FlowOutput_Interface `json:"Interface,omitempty"`
}

// FlowOutput_EncodingParameters represents AWS::MediaConnect::FlowOutput.EncodingParameters.
type FlowOutput_EncodingParameters struct {
	CompressionFactor any `json:"CompressionFactor,omitempty"`
	EncoderProfile    any `json:"EncoderProfile,omitempty"`
}

// FlowOutput_Encryption represents AWS::MediaConnect::FlowOutput.Encryption.
type FlowOutput_Encryption struct {
	Algorithm any `json:"Algorithm,omitempty"`
	KeyType   any `json:"KeyType,omitempty"`
	RoleArn   any `json:"RoleArn,omitempty"`
	SecretArn any `json:"SecretArn,omitempty"`
}

// FlowOutput_FlowTransitEncryption represents AWS::MediaConnect::FlowOutput.FlowTransitEncryption.
type FlowOutput_FlowTransitEncryption struct {
	EncryptionKeyConfiguration FlowOutput_FlowTransitEncryptionKeyConfiguration `json:"EncryptionKeyConfiguration,omitempty"`
	EncryptionKeyType          any                                              `json:"EncryptionKeyType,omitempty"`
}

// FlowOutput_FlowTransitEncryptionKeyConfiguration represents AWS::MediaConnect::FlowOutput.FlowTransitEncryptionKeyConfiguration.
type FlowOutput_FlowTransitEncryptionKeyConfiguration struct {
	Automatic      any `json:"Automatic,omitempty"`
	SecretsManager any `json:"SecretsManager,omitempty"`
}

// FlowOutput_Interface represents AWS::MediaConnect::FlowOutput.Interface.
type FlowOutput_Interface struct {
	Name any `json:"Name,omitempty"`
}

// FlowOutput_MediaStreamOutputConfiguration represents AWS::MediaConnect::FlowOutput.MediaStreamOutputConfiguration.
type FlowOutput_MediaStreamOutputConfiguration struct {
	DestinationConfigurations []any `json:"DestinationConfigurations,omitempty"`
	EncodingName              any   `json:"EncodingName,omitempty"`
	EncodingParameters        any   `json:"EncodingParameters,omitempty"`
	MediaStreamName           any   `json:"MediaStreamName,omitempty"`
}

// FlowOutput_SecretsManagerEncryptionKeyConfiguration represents AWS::MediaConnect::FlowOutput.SecretsManagerEncryptionKeyConfiguration.
type FlowOutput_SecretsManagerEncryptionKeyConfiguration struct {
	RoleArn   any `json:"RoleArn,omitempty"`
	SecretArn any `json:"SecretArn,omitempty"`
}

// FlowOutput_VpcInterfaceAttachment represents AWS::MediaConnect::FlowOutput.VpcInterfaceAttachment.
type FlowOutput_VpcInterfaceAttachment struct {
	VpcInterfaceName any `json:"VpcInterfaceName,omitempty"`
}
