// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package greengrass

// CoreDefinition_Core represents AWS::Greengrass::CoreDefinition.Core.
type CoreDefinition_Core struct {
	CertificateArn any `json:"CertificateArn,omitempty"`
	Id             any `json:"Id,omitempty"`
	SyncShadow     any `json:"SyncShadow,omitempty"`
	ThingArn       any `json:"ThingArn,omitempty"`
}

// CoreDefinition_CoreDefinitionVersion represents AWS::Greengrass::CoreDefinition.CoreDefinitionVersion.
type CoreDefinition_CoreDefinitionVersion struct {
	Cores []CoreDefinitionVersion_Core `json:"Cores,omitempty"`
}
