// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package greengrass

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ResourceDefinition represents AWS::Greengrass::ResourceDefinition.

type ResourceDefinition struct {
	// Attributes for Fn::GetAtt
	Arn              wetwire.AttrRef `json:"-"`
	Id               wetwire.AttrRef `json:"-"`
	LatestVersionArn wetwire.AttrRef `json:"-"`

	// Properties
	InitialVersion *ResourceDefinition_ResourceDefinitionVersion `json:"InitialVersion,omitempty"`
	Name           any                                           `json:"Name,omitempty"`
	Tags           any                                           `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ResourceDefinition) ResourceType() string {
	return "AWS::Greengrass::ResourceDefinition"
}
