// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package greengrass

// SubscriptionDefinitionVersion_Subscription represents AWS::Greengrass::SubscriptionDefinitionVersion.Subscription.
type SubscriptionDefinitionVersion_Subscription struct {
	Id      any `json:"Id,omitempty"`
	Source  any `json:"Source,omitempty"`
	Subject any `json:"Subject,omitempty"`
	Target  any `json:"Target,omitempty"`
}
