// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package codepipeline

// Webhook_WebhookAuthConfiguration represents AWS::CodePipeline::Webhook.WebhookAuthConfiguration.
type Webhook_WebhookAuthConfiguration struct {
	AllowedIPRange any `json:"AllowedIPRange,omitempty"`
	SecretToken    any `json:"SecretToken,omitempty"`
}

// Webhook_WebhookFilterRule represents AWS::CodePipeline::Webhook.WebhookFilterRule.
type Webhook_WebhookFilterRule struct {
	JsonPath    any `json:"JsonPath,omitempty"`
	MatchEquals any `json:"MatchEquals,omitempty"`
}
