// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package s3

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// MultiRegionAccessPointPolicy represents AWS::S3::MultiRegionAccessPointPolicy.

type MultiRegionAccessPointPolicy struct {
	// Attributes for Fn::GetAtt
	PolicyStatus          wetwire.AttrRef `json:"-"`
	PolicyStatus_IsPublic wetwire.AttrRef `json:"-"`

	// Properties
	MrapName any `json:"MrapName,omitempty"`
	Policy   any `json:"Policy,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r MultiRegionAccessPointPolicy) ResourceType() string {
	return "AWS::S3::MultiRegionAccessPointPolicy"
}
