// Package elasticache_snapshot contains CloudFormation resources.
// Database resources: RDS, DynamoDB, etc.
//
// Generated by wetwire-aws import.
package elasticache_snapshot

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/elasticache"
)

var RedisParameterGroup = elasticache.ParameterGroup{
	CacheParameterGroupFamily: "redis2.8",
	Description: "RedisParameterGroup",
}

var RedisSubnetGroup = elasticache.SubnetGroup{
	Description: "RedisSubnetGroup",
	SubnetIds: []any{PublicSubnetA, PublicSubnetB},
}

var RedisReplicationGroup = elasticache.ReplicationGroup{
	AutomaticFailoverEnabled: "true",
	CacheNodeType: RedisNodeType,
	CacheParameterGroupName: RedisParameterGroup,
	CacheSubnetGroupName: RedisSubnetGroup,
	Engine: "redis",
	EngineVersion: "2.8.24",
	NumCacheClusters: "2",
	PreferredCacheClusterAZs: []any{FindInMap{"AWSRegion2AZ", AWS_REGION, "A"}, FindInMap{"AWSRegion2AZ", AWS_REGION, "B"}},
	ReplicationGroupDescription: "RedisReplicationGroup",
	SecurityGroupIds: []any{RedisSecurityGroup},
}
