// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package verifiedpermissions

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Policy represents AWS::VerifiedPermissions::Policy.

type Policy struct {
	// Attributes for Fn::GetAtt
	PolicyId   wetwire.AttrRef `json:"-"`
	PolicyType wetwire.AttrRef `json:"-"`

	// Properties
	Definition    Policy_PolicyDefinition `json:"Definition,omitempty"`
	PolicyStoreId any                     `json:"PolicyStoreId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Policy) ResourceType() string {
	return "AWS::VerifiedPermissions::Policy"
}
