// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package dynamodb

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Table represents AWS::DynamoDB::Table.

type Table struct {
	// Attributes for Fn::GetAtt
	Arn       wetwire.AttrRef `json:"-"`
	StreamArn wetwire.AttrRef `json:"-"`

	// Properties
	AttributeDefinitions             []Table_AttributeDefinition             `json:"AttributeDefinitions,omitempty"`
	BillingMode                      any                                     `json:"BillingMode,omitempty"`
	ContributorInsightsSpecification *Table_ContributorInsightsSpecification `json:"ContributorInsightsSpecification,omitempty"`
	DeletionProtectionEnabled        any                                     `json:"DeletionProtectionEnabled,omitempty"`
	GlobalSecondaryIndexes           []Table_GlobalSecondaryIndex            `json:"GlobalSecondaryIndexes,omitempty"`
	ImportSourceSpecification        *Table_ImportSourceSpecification        `json:"ImportSourceSpecification,omitempty"`
	KeySchema                        []Table_KeySchema                       `json:"KeySchema,omitempty"`
	KinesisStreamSpecification       *Table_KinesisStreamSpecification       `json:"KinesisStreamSpecification,omitempty"`
	LocalSecondaryIndexes            []Table_LocalSecondaryIndex             `json:"LocalSecondaryIndexes,omitempty"`
	OnDemandThroughput               *Table_OnDemandThroughput               `json:"OnDemandThroughput,omitempty"`
	PointInTimeRecoverySpecification *Table_PointInTimeRecoverySpecification `json:"PointInTimeRecoverySpecification,omitempty"`
	ProvisionedThroughput            *Table_ProvisionedThroughput            `json:"ProvisionedThroughput,omitempty"`
	ResourcePolicy                   *Table_ResourcePolicy                   `json:"ResourcePolicy,omitempty"`
	SSESpecification                 *Table_SSESpecification                 `json:"SSESpecification,omitempty"`
	StreamSpecification              *Table_StreamSpecification              `json:"StreamSpecification,omitempty"`
	TableClass                       any                                     `json:"TableClass,omitempty"`
	TableName                        any                                     `json:"TableName,omitempty"`
	Tags                             []any                                   `json:"Tags,omitempty"`
	TimeToLiveSpecification          *Table_TimeToLiveSpecification          `json:"TimeToLiveSpecification,omitempty"`
	WarmThroughput                   *Table_WarmThroughput                   `json:"WarmThroughput,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Table) ResourceType() string {
	return "AWS::DynamoDB::Table"
}
