// Package s3_bucket_and_policy_for_caa_v1 contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package s3_bucket_and_policy_for_caa_v1

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// BucketName - The name of the S3 Bucket to create, make this unique
var BucketName = Parameter{
	Type: "String",
	Description: "The name of the S3 Bucket to create, make this unique",
}

// PublisherAccountID - The AWS account ID with whom you are sharing access
var PublisherAccountID = Parameter{
	Type: "String",
	Description: "The AWS account ID with whom you are sharing access",
}
