// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package inspectorv2

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// CisScanConfiguration represents AWS::InspectorV2::CisScanConfiguration.

type CisScanConfiguration struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`

	// Properties
	ScanName      any                             `json:"ScanName,omitempty"`
	Schedule      CisScanConfiguration_Schedule   `json:"Schedule,omitempty"`
	SecurityLevel any                             `json:"SecurityLevel,omitempty"`
	Tags          map[string]any                  `json:"Tags,omitempty"`
	Targets       CisScanConfiguration_CisTargets `json:"Targets,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r CisScanConfiguration) ResourceType() string {
	return "AWS::InspectorV2::CisScanConfiguration"
}
