// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package ivs

// RecordingConfiguration_DestinationConfiguration represents AWS::IVS::RecordingConfiguration.DestinationConfiguration.
type RecordingConfiguration_DestinationConfiguration struct {
	S3 *RecordingConfiguration_S3DestinationConfiguration `json:"S3,omitempty"`
}

// RecordingConfiguration_RenditionConfiguration represents AWS::IVS::RecordingConfiguration.RenditionConfiguration.
type RecordingConfiguration_RenditionConfiguration struct {
	RenditionSelection any   `json:"RenditionSelection,omitempty"`
	Renditions         []any `json:"Renditions,omitempty"`
}

// RecordingConfiguration_S3DestinationConfiguration represents AWS::IVS::RecordingConfiguration.S3DestinationConfiguration.
type RecordingConfiguration_S3DestinationConfiguration struct {
	BucketName any `json:"BucketName,omitempty"`
}

// RecordingConfiguration_ThumbnailConfiguration represents AWS::IVS::RecordingConfiguration.ThumbnailConfiguration.
type RecordingConfiguration_ThumbnailConfiguration struct {
	RecordingMode         any   `json:"RecordingMode,omitempty"`
	Resolution            any   `json:"Resolution,omitempty"`
	Storage               []any `json:"Storage,omitempty"`
	TargetIntervalSeconds any   `json:"TargetIntervalSeconds,omitempty"`
}
