// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package datapipeline

// Pipeline_Field represents AWS::DataPipeline::Pipeline.Field.
type Pipeline_Field struct {
	Key         any `json:"Key,omitempty"`
	RefValue    any `json:"RefValue,omitempty"`
	StringValue any `json:"StringValue,omitempty"`
}

// Pipeline_ParameterAttribute represents AWS::DataPipeline::Pipeline.ParameterAttribute.
type Pipeline_ParameterAttribute struct {
	Key         any `json:"Key,omitempty"`
	StringValue any `json:"StringValue,omitempty"`
}

// Pipeline_ParameterObject represents AWS::DataPipeline::Pipeline.ParameterObject.
type Pipeline_ParameterObject struct {
	Attributes []Pipeline_ParameterAttribute `json:"Attributes,omitempty"`
	Id         any                           `json:"Id,omitempty"`
}

// Pipeline_ParameterValue represents AWS::DataPipeline::Pipeline.ParameterValue.
type Pipeline_ParameterValue struct {
	Id          any `json:"Id,omitempty"`
	StringValue any `json:"StringValue,omitempty"`
}

// Pipeline_PipelineObject represents AWS::DataPipeline::Pipeline.PipelineObject.
type Pipeline_PipelineObject struct {
	Fields []Pipeline_Field `json:"Fields,omitempty"`
	Id     any              `json:"Id,omitempty"`
	Name   any              `json:"Name,omitempty"`
}

// Pipeline_PipelineTag represents AWS::DataPipeline::Pipeline.PipelineTag.
type Pipeline_PipelineTag struct {
	Key   any `json:"Key,omitempty"`
	Value any `json:"Value,omitempty"`
}
