package schema

// resourceSchemas contains known CloudFormation resource schemas.
// This is a subset of common resources - a complete implementation
// would fetch schemas from AWS CloudFormation Registry.
var resourceSchemas = map[string]ResourceSchema{
	"AWS::S3::Bucket": {
		Type:     "AWS::S3::Bucket",
		Required: []string{},
		Properties: map[string]PropertySchema{
			"BucketName": {Type: "String"},
			"AccessControl": {
				Type: "String",
				AllowedValues: []string{
					"Private", "PublicRead", "PublicReadWrite", "AuthenticatedRead",
					"LogDeliveryWrite", "BucketOwnerRead", "BucketOwnerFullControl",
				},
			},
			"BucketEncryption":               {Type: "Map"},
			"CorsConfiguration":              {Type: "Map"},
			"LifecycleConfiguration":         {Type: "Map"},
			"LoggingConfiguration":           {Type: "Map"},
			"NotificationConfiguration":      {Type: "Map"},
			"PublicAccessBlockConfiguration": {Type: "Map"},
			"ReplicationConfiguration":       {Type: "Map"},
			"Tags":                           {Type: "List"},
			"VersioningConfiguration":        {Type: "Map"},
			"WebsiteConfiguration":           {Type: "Map"},
		},
	},
	"AWS::Lambda::Function": {
		Type:     "AWS::Lambda::Function",
		Required: []string{"Role"},
		Properties: map[string]PropertySchema{
			"FunctionName":                  {Type: "String"},
			"Description":                   {Type: "String"},
			"Runtime":                       {Type: "String"},
			"Handler":                       {Type: "String"},
			"Code":                          {Type: "Map"},
			"Role":                          {Type: "String"},
			"Environment":                   {Type: "Map"},
			"MemorySize":                    {Type: "Integer"},
			"Timeout":                       {Type: "Integer"},
			"DeadLetterConfig":              {Type: "Map"},
			"VpcConfig":                     {Type: "Map"},
			"Tags":                          {Type: "List"},
			"Layers":                        {Type: "List"},
			"TracingConfig":                 {Type: "Map"},
			"ReservedConcurrentExecutions":  {Type: "Integer"},
			"EphemeralStorage":              {Type: "Map"},
			"PackageType":                   {Type: "String", AllowedValues: []string{"Zip", "Image"}},
			"Architectures":                 {Type: "List"},
			"SnapStart":                     {Type: "Map"},
			"RuntimeManagementConfig":       {Type: "Map"},
			"LoggingConfig":                 {Type: "Map"},
		},
	},
	"AWS::IAM::Role": {
		Type:     "AWS::IAM::Role",
		Required: []string{"AssumeRolePolicyDocument"},
		Properties: map[string]PropertySchema{
			"RoleName":                 {Type: "String"},
			"AssumeRolePolicyDocument": {Type: "Map"},
			"Description":              {Type: "String"},
			"ManagedPolicyArns":        {Type: "List"},
			"MaxSessionDuration":       {Type: "Integer"},
			"Path":                     {Type: "String"},
			"PermissionsBoundary":      {Type: "String"},
			"Policies":                 {Type: "List"},
			"Tags":                     {Type: "List"},
		},
	},
	"AWS::IAM::Policy": {
		Type:     "AWS::IAM::Policy",
		Required: []string{"PolicyDocument", "PolicyName"},
		Properties: map[string]PropertySchema{
			"PolicyName":     {Type: "String"},
			"PolicyDocument": {Type: "Map"},
			"Groups":         {Type: "List"},
			"Roles":          {Type: "List"},
			"Users":          {Type: "List"},
		},
	},
	"AWS::DynamoDB::Table": {
		Type:     "AWS::DynamoDB::Table",
		Required: []string{"KeySchema"},
		Properties: map[string]PropertySchema{
			"TableName":                   {Type: "String"},
			"AttributeDefinitions":        {Type: "List"},
			"KeySchema":                   {Type: "List"},
			"BillingMode":                 {Type: "String", AllowedValues: []string{"PROVISIONED", "PAY_PER_REQUEST"}},
			"ProvisionedThroughput":       {Type: "Map"},
			"GlobalSecondaryIndexes":      {Type: "List"},
			"LocalSecondaryIndexes":       {Type: "List"},
			"StreamSpecification":         {Type: "Map"},
			"TableClass":                  {Type: "String", AllowedValues: []string{"STANDARD", "STANDARD_INFREQUENT_ACCESS"}},
			"TimeToLiveSpecification":     {Type: "Map"},
			"PointInTimeRecoverySpecification": {Type: "Map"},
			"SSESpecification":            {Type: "Map"},
			"Tags":                        {Type: "List"},
			"ContributorInsightsSpecification": {Type: "Map"},
			"KinesisStreamSpecification":  {Type: "Map"},
		},
	},
	"AWS::EC2::Instance": {
		Type:     "AWS::EC2::Instance",
		Required: []string{},
		Properties: map[string]PropertySchema{
			"InstanceType":         {Type: "String"},
			"ImageId":              {Type: "String"},
			"KeyName":              {Type: "String"},
			"SecurityGroups":       {Type: "List"},
			"SecurityGroupIds":     {Type: "List"},
			"SubnetId":             {Type: "String"},
			"UserData":             {Type: "String"},
			"IamInstanceProfile":   {Type: "String"},
			"BlockDeviceMappings":  {Type: "List"},
			"DisableApiTermination": {Type: "Boolean"},
			"EbsOptimized":         {Type: "Boolean"},
			"Monitoring":           {Type: "Boolean"},
			"NetworkInterfaces":    {Type: "List"},
			"PlacementGroupName":   {Type: "String"},
			"PrivateIpAddress":     {Type: "String"},
			"SourceDestCheck":      {Type: "Boolean"},
			"Tags":                 {Type: "List"},
			"Tenancy":              {Type: "String", AllowedValues: []string{"default", "dedicated", "host"}},
			"Volumes":              {Type: "List"},
			"AvailabilityZone":     {Type: "String"},
			"CreditSpecification":  {Type: "Map"},
			"LaunchTemplate":       {Type: "Map"},
		},
	},
	"AWS::EC2::VPC": {
		Type:     "AWS::EC2::VPC",
		Required: []string{},
		Properties: map[string]PropertySchema{
			"CidrBlock":          {Type: "String"},
			"EnableDnsSupport":   {Type: "Boolean"},
			"EnableDnsHostnames": {Type: "Boolean"},
			"InstanceTenancy":    {Type: "String", AllowedValues: []string{"default", "dedicated", "host"}},
			"Tags":               {Type: "List"},
			"Ipv4IpamPoolId":     {Type: "String"},
			"Ipv4NetmaskLength":  {Type: "Integer"},
		},
	},
	"AWS::EC2::Subnet": {
		Type:     "AWS::EC2::Subnet",
		Required: []string{"VpcId"},
		Properties: map[string]PropertySchema{
			"VpcId":                       {Type: "String"},
			"CidrBlock":                   {Type: "String"},
			"AvailabilityZone":            {Type: "String"},
			"MapPublicIpOnLaunch":         {Type: "Boolean"},
			"Tags":                        {Type: "List"},
			"AssignIpv6AddressOnCreation": {Type: "Boolean"},
			"Ipv6CidrBlock":               {Type: "String"},
			"OutpostArn":                  {Type: "String"},
		},
	},
	"AWS::EC2::SecurityGroup": {
		Type:     "AWS::EC2::SecurityGroup",
		Required: []string{"GroupDescription"},
		Properties: map[string]PropertySchema{
			"GroupName":             {Type: "String"},
			"GroupDescription":      {Type: "String"},
			"VpcId":                 {Type: "String"},
			"SecurityGroupIngress":  {Type: "List"},
			"SecurityGroupEgress":   {Type: "List"},
			"Tags":                  {Type: "List"},
		},
	},
	"AWS::RDS::DBInstance": {
		Type:     "AWS::RDS::DBInstance",
		Required: []string{},
		Properties: map[string]PropertySchema{
			"DBInstanceIdentifier":      {Type: "String"},
			"DBInstanceClass":           {Type: "String"},
			"Engine":                    {Type: "String"},
			"EngineVersion":             {Type: "String"},
			"MasterUsername":            {Type: "String"},
			"MasterUserPassword":        {Type: "String"},
			"DBName":                    {Type: "String"},
			"AllocatedStorage":          {Type: "String"},
			"StorageType":               {Type: "String", AllowedValues: []string{"standard", "gp2", "gp3", "io1"}},
			"MultiAZ":                   {Type: "Boolean"},
			"StorageEncrypted":          {Type: "Boolean"},
			"BackupRetentionPeriod":     {Type: "Integer"},
			"PreferredBackupWindow":     {Type: "String"},
			"PreferredMaintenanceWindow": {Type: "String"},
			"PubliclyAccessible":        {Type: "Boolean"},
			"VPCSecurityGroups":         {Type: "List"},
			"DBSubnetGroupName":         {Type: "String"},
			"Tags":                      {Type: "List"},
			"DeletionProtection":        {Type: "Boolean"},
			"EnableIAMDatabaseAuthentication": {Type: "Boolean"},
			"KmsKeyId":                  {Type: "String"},
		},
	},
	"AWS::SNS::Topic": {
		Type:     "AWS::SNS::Topic",
		Required: []string{},
		Properties: map[string]PropertySchema{
			"TopicName":     {Type: "String"},
			"DisplayName":   {Type: "String"},
			"Subscription":  {Type: "List"},
			"Tags":          {Type: "List"},
			"KmsMasterKeyId": {Type: "String"},
			"FifoTopic":     {Type: "Boolean"},
			"ContentBasedDeduplication": {Type: "Boolean"},
		},
	},
	"AWS::SQS::Queue": {
		Type:     "AWS::SQS::Queue",
		Required: []string{},
		Properties: map[string]PropertySchema{
			"QueueName":                     {Type: "String"},
			"DelaySeconds":                  {Type: "Integer"},
			"MaximumMessageSize":            {Type: "Integer"},
			"MessageRetentionPeriod":        {Type: "Integer"},
			"ReceiveMessageWaitTimeSeconds": {Type: "Integer"},
			"VisibilityTimeout":             {Type: "Integer"},
			"KmsMasterKeyId":                {Type: "String"},
			"KmsDataKeyReusePeriodSeconds":  {Type: "Integer"},
			"FifoQueue":                     {Type: "Boolean"},
			"ContentBasedDeduplication":     {Type: "Boolean"},
			"DeduplicationScope":            {Type: "String"},
			"FifoThroughputLimit":           {Type: "String"},
			"Tags":                          {Type: "List"},
			"RedrivePolicy":                 {Type: "Json"},
			"RedriveAllowPolicy":            {Type: "Json"},
		},
	},
	"AWS::Logs::LogGroup": {
		Type:     "AWS::Logs::LogGroup",
		Required: []string{},
		Properties: map[string]PropertySchema{
			"LogGroupName":    {Type: "String"},
			"RetentionInDays": {Type: "Integer"},
			"KmsKeyId":        {Type: "String"},
			"Tags":            {Type: "List"},
		},
	},
	"AWS::CloudWatch::Alarm": {
		Type:     "AWS::CloudWatch::Alarm",
		Required: []string{"ComparisonOperator", "EvaluationPeriods"},
		Properties: map[string]PropertySchema{
			"AlarmName":           {Type: "String"},
			"AlarmDescription":    {Type: "String"},
			"ActionsEnabled":      {Type: "Boolean"},
			"AlarmActions":        {Type: "List"},
			"OKActions":           {Type: "List"},
			"InsufficientDataActions": {Type: "List"},
			"MetricName":          {Type: "String"},
			"Namespace":           {Type: "String"},
			"Statistic":           {Type: "String"},
			"Period":              {Type: "Integer"},
			"EvaluationPeriods":   {Type: "Integer"},
			"Threshold":           {Type: "Integer"},
			"ComparisonOperator":  {Type: "String"},
			"TreatMissingData":    {Type: "String"},
			"Dimensions":          {Type: "List"},
			"DatapointsToAlarm":   {Type: "Integer"},
		},
	},
}
