// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package appstream

// Fleet represents AWS::AppStream::Fleet.

type Fleet struct {

	// Properties
	ComputeCapacity                any   `json:"ComputeCapacity,omitempty"`
	Description                    any   `json:"Description,omitempty"`
	DisconnectTimeoutInSeconds     any   `json:"DisconnectTimeoutInSeconds,omitempty"`
	DisplayName                    any   `json:"DisplayName,omitempty"`
	DomainJoinInfo                 any   `json:"DomainJoinInfo,omitempty"`
	EnableDefaultInternetAccess    any   `json:"EnableDefaultInternetAccess,omitempty"`
	FleetType                      any   `json:"FleetType,omitempty"`
	IamRoleArn                     any   `json:"IamRoleArn,omitempty"`
	IdleDisconnectTimeoutInSeconds any   `json:"IdleDisconnectTimeoutInSeconds,omitempty"`
	ImageArn                       any   `json:"ImageArn,omitempty"`
	ImageName                      any   `json:"ImageName,omitempty"`
	InstanceType                   any   `json:"InstanceType,omitempty"`
	MaxConcurrentSessions          any   `json:"MaxConcurrentSessions,omitempty"`
	MaxSessionsPerInstance         any   `json:"MaxSessionsPerInstance,omitempty"`
	MaxUserDurationInSeconds       any   `json:"MaxUserDurationInSeconds,omitempty"`
	Name                           any   `json:"Name,omitempty"`
	Platform                       any   `json:"Platform,omitempty"`
	SessionScriptS3Location        any   `json:"SessionScriptS3Location,omitempty"`
	StreamView                     any   `json:"StreamView,omitempty"`
	Tags                           []any `json:"Tags,omitempty"`
	UsbDeviceFilterStrings         []any `json:"UsbDeviceFilterStrings,omitempty"`
	VpcConfig                      any   `json:"VpcConfig,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Fleet) ResourceType() string {
	return "AWS::AppStream::Fleet"
}
