// Package template contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package template

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

var pGlueJobName = Parameter{
	Type: "String",
}
