// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package glue

// IntegrationResourceProperty_SourceProcessingProperties represents AWS::Glue::IntegrationResourceProperty.SourceProcessingProperties.
type IntegrationResourceProperty_SourceProcessingProperties struct {
	RoleArn any `json:"RoleArn,omitempty"`
}

// IntegrationResourceProperty_TargetProcessingProperties represents AWS::Glue::IntegrationResourceProperty.TargetProcessingProperties.
type IntegrationResourceProperty_TargetProcessingProperties struct {
	ConnectionName any `json:"ConnectionName,omitempty"`
	EventBusArn    any `json:"EventBusArn,omitempty"`
	KmsArn         any `json:"KmsArn,omitempty"`
	RoleArn        any `json:"RoleArn,omitempty"`
}
