// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package glue

// SchemaVersionMetadata represents AWS::Glue::SchemaVersionMetadata.

type SchemaVersionMetadata struct {

	// Properties
	Key             any `json:"Key,omitempty"`
	SchemaVersionId any `json:"SchemaVersionId,omitempty"`
	Value           any `json:"Value,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r SchemaVersionMetadata) ResourceType() string {
	return "AWS::Glue::SchemaVersionMetadata"
}
