// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package glue

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// SchemaVersion represents AWS::Glue::SchemaVersion.

type SchemaVersion struct {
	// Attributes for Fn::GetAtt
	VersionId wetwire.AttrRef `json:"-"`

	// Properties
	Schema           SchemaVersion_Schema `json:"Schema,omitempty"`
	SchemaDefinition any                  `json:"SchemaDefinition,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r SchemaVersion) ResourceType() string {
	return "AWS::Glue::SchemaVersion"
}
