// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package glue

// SchemaVersion_Schema represents AWS::Glue::SchemaVersion.Schema.
type SchemaVersion_Schema struct {
	RegistryName any `json:"RegistryName,omitempty"`
	SchemaArn    any `json:"SchemaArn,omitempty"`
	SchemaName   any `json:"SchemaName,omitempty"`
}
