// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:23-07:00

package supportapp

// SlackWorkspaceConfiguration represents AWS::SupportApp::SlackWorkspaceConfiguration.

type SlackWorkspaceConfiguration struct {

	// Properties
	TeamId    any `json:"TeamId,omitempty"`
	VersionId any `json:"VersionId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r SlackWorkspaceConfiguration) ResourceType() string {
	return "AWS::SupportApp::SlackWorkspaceConfiguration"
}
