// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package arczonalshift

// ZonalAutoshiftConfiguration represents AWS::ARCZonalShift::ZonalAutoshiftConfiguration.

type ZonalAutoshiftConfiguration struct {

	// Properties
	PracticeRunConfiguration *ZonalAutoshiftConfiguration_PracticeRunConfiguration `json:"PracticeRunConfiguration,omitempty"`
	ResourceIdentifier       any                                                   `json:"ResourceIdentifier,omitempty"`
	ZonalAutoshiftStatus     any                                                   `json:"ZonalAutoshiftStatus,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ZonalAutoshiftConfiguration) ResourceType() string {
	return "AWS::ARCZonalShift::ZonalAutoshiftConfiguration"
}
