// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package s3tables

// TableBucket_EncryptionConfiguration represents AWS::S3Tables::TableBucket.EncryptionConfiguration.
type TableBucket_EncryptionConfiguration struct {
	KMSKeyArn    any `json:"KMSKeyArn,omitempty"`
	SSEAlgorithm any `json:"SSEAlgorithm,omitempty"`
}

// TableBucket_MetricsConfiguration represents AWS::S3Tables::TableBucket.MetricsConfiguration.
type TableBucket_MetricsConfiguration struct {
	Status any `json:"Status,omitempty"`
}

// TableBucket_StorageClassConfiguration represents AWS::S3Tables::TableBucket.StorageClassConfiguration.
type TableBucket_StorageClassConfiguration struct {
	StorageClass any `json:"StorageClass,omitempty"`
}

// TableBucket_UnreferencedFileRemoval represents AWS::S3Tables::TableBucket.UnreferencedFileRemoval.
type TableBucket_UnreferencedFileRemoval struct {
	NoncurrentDays   any `json:"NoncurrentDays,omitempty"`
	Status           any `json:"Status,omitempty"`
	UnreferencedDays any `json:"UnreferencedDays,omitempty"`
}
