// Package dmsauroratos3fullloadandongoingreplication contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package dmsauroratos3fullloadandongoingreplication

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// ClientIP - The IP address range that can be used to connect to the RDS instances from yo...
var ClientIP = Param("ClientIP")

// SnapshotIdentifier - The ARN of the Aurora DB Cluster Snapshot used to populate the Aurora DB Clus...
var SnapshotIdentifier = Param("SnapshotIdentifier")

var NotExistsDMSCloudwatchRoleCondition = Equals{ExistsDMSCloudwatchRole, "N"}

var NotExistsDMSVPCRoleCondition = Equals{ExistsDMSVPCRole, "N"}
