// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ecr

// RegistryScanningConfiguration_RepositoryFilter represents AWS::ECR::RegistryScanningConfiguration.RepositoryFilter.
type RegistryScanningConfiguration_RepositoryFilter struct {
	Filter     any `json:"Filter,omitempty"`
	FilterType any `json:"FilterType,omitempty"`
}

// RegistryScanningConfiguration_ScanningRule represents AWS::ECR::RegistryScanningConfiguration.ScanningRule.
type RegistryScanningConfiguration_ScanningRule struct {
	RepositoryFilters []any `json:"RepositoryFilters,omitempty"`
	ScanFrequency     any   `json:"ScanFrequency,omitempty"`
}
