// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package ecr

// ReplicationConfiguration_ReplicationConfiguration represents AWS::ECR::ReplicationConfiguration.ReplicationConfiguration.
type ReplicationConfiguration_ReplicationConfiguration struct {
	Rules []any `json:"Rules,omitempty"`
}

// ReplicationConfiguration_ReplicationDestination represents AWS::ECR::ReplicationConfiguration.ReplicationDestination.
type ReplicationConfiguration_ReplicationDestination struct {
	Region     any `json:"Region,omitempty"`
	RegistryId any `json:"RegistryId,omitempty"`
}

// ReplicationConfiguration_ReplicationRule represents AWS::ECR::ReplicationConfiguration.ReplicationRule.
type ReplicationConfiguration_ReplicationRule struct {
	Destinations      []any `json:"Destinations,omitempty"`
	RepositoryFilters []any `json:"RepositoryFilters,omitempty"`
}

// ReplicationConfiguration_RepositoryFilter represents AWS::ECR::ReplicationConfiguration.RepositoryFilter.
type ReplicationConfiguration_RepositoryFilter struct {
	Filter     any `json:"Filter,omitempty"`
	FilterType any `json:"FilterType,omitempty"`
}
