// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package ecr

// RepositoryCreationTemplate_EncryptionConfiguration represents AWS::ECR::RepositoryCreationTemplate.EncryptionConfiguration.
type RepositoryCreationTemplate_EncryptionConfiguration struct {
	EncryptionType any `json:"EncryptionType,omitempty"`
	KmsKey         any `json:"KmsKey,omitempty"`
}

// RepositoryCreationTemplate_ImageTagMutabilityExclusionFilter represents AWS::ECR::RepositoryCreationTemplate.ImageTagMutabilityExclusionFilter.
type RepositoryCreationTemplate_ImageTagMutabilityExclusionFilter struct {
	ImageTagMutabilityExclusionFilterType  any `json:"ImageTagMutabilityExclusionFilterType,omitempty"`
	ImageTagMutabilityExclusionFilterValue any `json:"ImageTagMutabilityExclusionFilterValue,omitempty"`
}
