// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package apigateway

// Method represents AWS::ApiGateway::Method.

type Method struct {

	// Properties
	ApiKeyRequired      any                     `json:"ApiKeyRequired,omitempty"`
	AuthorizationScopes []any                   `json:"AuthorizationScopes,omitempty"`
	AuthorizationType   any                     `json:"AuthorizationType,omitempty"`
	AuthorizerId        any                     `json:"AuthorizerId,omitempty"`
	HttpMethod          any                     `json:"HttpMethod,omitempty"`
	Integration         *Method_Integration     `json:"Integration,omitempty"`
	MethodResponses     []Method_MethodResponse `json:"MethodResponses,omitempty"`
	OperationName       any                     `json:"OperationName,omitempty"`
	RequestModels       map[string]any          `json:"RequestModels,omitempty"`
	RequestParameters   map[string]any          `json:"RequestParameters,omitempty"`
	RequestValidatorId  any                     `json:"RequestValidatorId,omitempty"`
	ResourceId          any                     `json:"ResourceId,omitempty"`
	RestApiId           any                     `json:"RestApiId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Method) ResourceType() string {
	return "AWS::ApiGateway::Method"
}
