// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package apigateway

// UsagePlan_ApiStage represents AWS::ApiGateway::UsagePlan.ApiStage.
type UsagePlan_ApiStage struct {
	ApiId    any                                   `json:"ApiId,omitempty"`
	Stage    any                                   `json:"Stage,omitempty"`
	Throttle map[string]UsagePlan_ThrottleSettings `json:"Throttle,omitempty"`
}

// UsagePlan_QuotaSettings represents AWS::ApiGateway::UsagePlan.QuotaSettings.
type UsagePlan_QuotaSettings struct {
	Limit  any `json:"Limit,omitempty"`
	Offset any `json:"Offset,omitempty"`
	Period any `json:"Period,omitempty"`
}

// UsagePlan_ThrottleSettings represents AWS::ApiGateway::UsagePlan.ThrottleSettings.
type UsagePlan_ThrottleSettings struct {
	BurstLimit any `json:"BurstLimit,omitempty"`
	RateLimit  any `json:"RateLimit,omitempty"`
}
