// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package apigateway

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// UsagePlan represents AWS::ApiGateway::UsagePlan.

type UsagePlan struct {
	// Attributes for Fn::GetAtt
	Id wetwire.AttrRef `json:"-"`

	// Properties
	ApiStages     []any `json:"ApiStages,omitempty"`
	Description   any   `json:"Description,omitempty"`
	Quota         any   `json:"Quota,omitempty"`
	Tags          []any `json:"Tags,omitempty"`
	Throttle      any   `json:"Throttle,omitempty"`
	UsagePlanName any   `json:"UsagePlanName,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r UsagePlan) ResourceType() string {
	return "AWS::ApiGateway::UsagePlan"
}
