// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package xray

// EncryptionStatus represents valid values for EncryptionStatus.
type EncryptionStatus string

const (
	EncryptionStatusUpdating EncryptionStatus = "UPDATING"
	EncryptionStatusActive   EncryptionStatus = "ACTIVE"
)

// EncryptionType represents valid values for EncryptionType.
type EncryptionType string

const (
	EncryptionTypeNone EncryptionType = "NONE"
	EncryptionTypeKms  EncryptionType = "KMS"
)

// InsightCategory represents valid values for InsightCategory.
type InsightCategory string

const (
	InsightCategoryFault InsightCategory = "FAULT"
)

// InsightState represents valid values for InsightState.
type InsightState string

const (
	InsightStateActive InsightState = "ACTIVE"
	InsightStateClosed InsightState = "CLOSED"
)

// RetrievalStatus represents valid values for RetrievalStatus.
type RetrievalStatus string

const (
	RetrievalStatusScheduled RetrievalStatus = "SCHEDULED"
	RetrievalStatusRunning   RetrievalStatus = "RUNNING"
	RetrievalStatusComplete  RetrievalStatus = "COMPLETE"
	RetrievalStatusFailed    RetrievalStatus = "FAILED"
	RetrievalStatusCancelled RetrievalStatus = "CANCELLED"
	RetrievalStatusTimeout   RetrievalStatus = "TIMEOUT"
)

// SamplingStrategyName represents valid values for SamplingStrategyName.
type SamplingStrategyName string

const (
	SamplingStrategyNamePartialscan SamplingStrategyName = "PartialScan"
	SamplingStrategyNameFixedrate   SamplingStrategyName = "FixedRate"
)

// TimeRangeType represents valid values for TimeRangeType.
type TimeRangeType string

const (
	TimeRangeTypeTraceid TimeRangeType = "TraceId"
	TimeRangeTypeEvent   TimeRangeType = "Event"
	TimeRangeTypeService TimeRangeType = "Service"
)

// TraceFormatType represents valid values for TraceFormatType.
type TraceFormatType string

const (
	TraceFormatTypeXray TraceFormatType = "XRAY"
	TraceFormatTypeOtel TraceFormatType = "OTEL"
)

// TraceSegmentDestination represents valid values for TraceSegmentDestination.
type TraceSegmentDestination string

const (
	TraceSegmentDestinationXray           TraceSegmentDestination = "XRay"
	TraceSegmentDestinationCloudwatchlogs TraceSegmentDestination = "CloudWatchLogs"
)

// TraceSegmentDestinationStatus represents valid values for TraceSegmentDestinationStatus.
type TraceSegmentDestinationStatus string

const (
	TraceSegmentDestinationStatusPending TraceSegmentDestinationStatus = "PENDING"
	TraceSegmentDestinationStatusActive  TraceSegmentDestinationStatus = "ACTIVE"
)
