// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package fms

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Policy represents AWS::FMS::Policy.

type Policy struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`
	Id  wetwire.AttrRef `json:"-"`

	// Properties
	DeleteAllPolicyResources   any                              `json:"DeleteAllPolicyResources,omitempty"`
	ExcludeMap                 *Policy_IEMap                    `json:"ExcludeMap,omitempty"`
	ExcludeResourceTags        any                              `json:"ExcludeResourceTags,omitempty"`
	IncludeMap                 *Policy_IEMap                    `json:"IncludeMap,omitempty"`
	PolicyDescription          any                              `json:"PolicyDescription,omitempty"`
	PolicyName                 any                              `json:"PolicyName,omitempty"`
	RemediationEnabled         any                              `json:"RemediationEnabled,omitempty"`
	ResourceSetIds             []any                            `json:"ResourceSetIds,omitempty"`
	ResourceTagLogicalOperator any                              `json:"ResourceTagLogicalOperator,omitempty"`
	ResourceTags               []Policy_ResourceTag             `json:"ResourceTags,omitempty"`
	ResourceTypeProp           any                              `json:"ResourceType,omitempty"`
	ResourceTypeList           []any                            `json:"ResourceTypeList,omitempty"`
	ResourcesCleanUp           any                              `json:"ResourcesCleanUp,omitempty"`
	SecurityServicePolicyData  Policy_SecurityServicePolicyData `json:"SecurityServicePolicyData,omitempty"`
	Tags                       []Policy_PolicyTag               `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Policy) ResourceType() string {
	return "AWS::FMS::Policy"
}
