// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package fms

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ResourceSet represents AWS::FMS::ResourceSet.

type ResourceSet struct {
	// Attributes for Fn::GetAtt
	Id wetwire.AttrRef `json:"-"`

	// Properties
	Description      any   `json:"Description,omitempty"`
	Name             any   `json:"Name,omitempty"`
	ResourceTypeList []any `json:"ResourceTypeList,omitempty"`
	Resources        []any `json:"Resources,omitempty"`
	Tags             []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ResourceSet) ResourceType() string {
	return "AWS::FMS::ResourceSet"
}
