// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package route53

// RecordSet_AliasTarget represents AWS::Route53::RecordSet.AliasTarget.
type RecordSet_AliasTarget struct {
	DNSName              any `json:"DNSName,omitempty"`
	EvaluateTargetHealth any `json:"EvaluateTargetHealth,omitempty"`
	HostedZoneId         any `json:"HostedZoneId,omitempty"`
}

// RecordSet_CidrRoutingConfig represents AWS::Route53::RecordSet.CidrRoutingConfig.
type RecordSet_CidrRoutingConfig struct {
	CollectionId any `json:"CollectionId,omitempty"`
	LocationName any `json:"LocationName,omitempty"`
}

// RecordSet_Coordinates represents AWS::Route53::RecordSet.Coordinates.
type RecordSet_Coordinates struct {
	Latitude  any `json:"Latitude,omitempty"`
	Longitude any `json:"Longitude,omitempty"`
}

// RecordSet_GeoLocation represents AWS::Route53::RecordSet.GeoLocation.
type RecordSet_GeoLocation struct {
	ContinentCode   any `json:"ContinentCode,omitempty"`
	CountryCode     any `json:"CountryCode,omitempty"`
	SubdivisionCode any `json:"SubdivisionCode,omitempty"`
}

// RecordSet_GeoProximityLocation represents AWS::Route53::RecordSet.GeoProximityLocation.
type RecordSet_GeoProximityLocation struct {
	AWSRegion      any                         `json:"AWSRegion,omitempty"`
	Bias           any                         `json:"Bias,omitempty"`
	Coordinates    *RecordSetGroup_Coordinates `json:"Coordinates,omitempty"`
	LocalZoneGroup any                         `json:"LocalZoneGroup,omitempty"`
}
