// Package amzn2_greengrass_cfn contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package amzn2_greengrass_cfn

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// CoreName - Greengrass Core name to be created. A "Thing" with be created with _Core appe...
var CoreName = Param("CoreName")

var InstanceType = Param("InstanceType")

var LatestAmiId = Param("LatestAmiId")

// SecurityAccessCIDR - CIDR block to limit inbound access for only SSH
var SecurityAccessCIDR = Param("SecurityAccessCIDR")

// myKeyPair - Amazon EC2 Key Pair for accessing Greengrass Core instance
var myKeyPair = Param("myKeyPair")
