// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package servicecatalogappregistry

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Application represents AWS::ServiceCatalogAppRegistry::Application.

type Application struct {
	// Attributes for Fn::GetAtt
	ApplicationName     wetwire.AttrRef `json:"-"`
	ApplicationTagKey   wetwire.AttrRef `json:"-"`
	ApplicationTagValue wetwire.AttrRef `json:"-"`
	Arn                 wetwire.AttrRef `json:"-"`
	Id                  wetwire.AttrRef `json:"-"`

	// Properties
	Description any            `json:"Description,omitempty"`
	Name        any            `json:"Name,omitempty"`
	Tags        map[string]any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Application) ResourceType() string {
	return "AWS::ServiceCatalogAppRegistry::Application"
}
