// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cloudtrail

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Channel represents AWS::CloudTrail::Channel.

type Channel struct {
	// Attributes for Fn::GetAtt
	ChannelArn wetwire.AttrRef `json:"-"`

	// Properties
	Destinations []Channel_Destination `json:"Destinations,omitempty"`
	Name         any                   `json:"Name,omitempty"`
	Source       any                   `json:"Source,omitempty"`
	Tags         []any                 `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Channel) ResourceType() string {
	return "AWS::CloudTrail::Channel"
}
