// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package bedrockagentcore

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// WorkloadIdentity represents AWS::BedrockAgentCore::WorkloadIdentity.

type WorkloadIdentity struct {
	// Attributes for Fn::GetAtt
	CreatedTime         wetwire.AttrRef `json:"-"`
	LastUpdatedTime     wetwire.AttrRef `json:"-"`
	WorkloadIdentityArn wetwire.AttrRef `json:"-"`

	// Properties
	AllowedResourceOauth2ReturnUrls []any `json:"AllowedResourceOauth2ReturnUrls,omitempty"`
	Name                            any   `json:"Name,omitempty"`
	Tags                            []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r WorkloadIdentity) ResourceType() string {
	return "AWS::BedrockAgentCore::WorkloadIdentity"
}
