// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package databrew

// Recipe represents AWS::DataBrew::Recipe.

type Recipe struct {

	// Properties
	Description any   `json:"Description,omitempty"`
	Name        any   `json:"Name,omitempty"`
	Steps       []any `json:"Steps,omitempty"`
	Tags        []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Recipe) ResourceType() string {
	return "AWS::DataBrew::Recipe"
}
