// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package elasticache

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// CacheCluster represents AWS::ElastiCache::CacheCluster.

type CacheCluster struct {
	// Attributes for Fn::GetAtt
	ConfigurationEndpoint_Address wetwire.AttrRef `json:"-"`
	ConfigurationEndpoint_Port    wetwire.AttrRef `json:"-"`
	RedisEndpoint_Address         wetwire.AttrRef `json:"-"`
	RedisEndpoint_Port            wetwire.AttrRef `json:"-"`

	// Properties
	AZMode                     any   `json:"AZMode,omitempty"`
	AutoMinorVersionUpgrade    any   `json:"AutoMinorVersionUpgrade,omitempty"`
	CacheNodeType              any   `json:"CacheNodeType,omitempty"`
	CacheParameterGroupName    any   `json:"CacheParameterGroupName,omitempty"`
	CacheSecurityGroupNames    []any `json:"CacheSecurityGroupNames,omitempty"`
	CacheSubnetGroupName       any   `json:"CacheSubnetGroupName,omitempty"`
	ClusterName                any   `json:"ClusterName,omitempty"`
	Engine                     any   `json:"Engine,omitempty"`
	EngineVersion              any   `json:"EngineVersion,omitempty"`
	IpDiscovery                any   `json:"IpDiscovery,omitempty"`
	LogDeliveryConfigurations  []any `json:"LogDeliveryConfigurations,omitempty"`
	NetworkType                any   `json:"NetworkType,omitempty"`
	NotificationTopicArn       any   `json:"NotificationTopicArn,omitempty"`
	NumCacheNodes              any   `json:"NumCacheNodes,omitempty"`
	Port                       any   `json:"Port,omitempty"`
	PreferredAvailabilityZone  any   `json:"PreferredAvailabilityZone,omitempty"`
	PreferredAvailabilityZones []any `json:"PreferredAvailabilityZones,omitempty"`
	PreferredMaintenanceWindow any   `json:"PreferredMaintenanceWindow,omitempty"`
	SnapshotArns               []any `json:"SnapshotArns,omitempty"`
	SnapshotName               any   `json:"SnapshotName,omitempty"`
	SnapshotRetentionLimit     any   `json:"SnapshotRetentionLimit,omitempty"`
	SnapshotWindow             any   `json:"SnapshotWindow,omitempty"`
	Tags                       []any `json:"Tags,omitempty"`
	TransitEncryptionEnabled   any   `json:"TransitEncryptionEnabled,omitempty"`
	VpcSecurityGroupIds        []any `json:"VpcSecurityGroupIds,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r CacheCluster) ResourceType() string {
	return "AWS::ElastiCache::CacheCluster"
}
