// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package elasticache

// CacheCluster_CloudWatchLogsDestinationDetails represents AWS::ElastiCache::CacheCluster.CloudWatchLogsDestinationDetails.
type CacheCluster_CloudWatchLogsDestinationDetails struct {
	LogGroup any `json:"LogGroup,omitempty"`
}

// CacheCluster_DestinationDetails represents AWS::ElastiCache::CacheCluster.DestinationDetails.
type CacheCluster_DestinationDetails struct {
	CloudWatchLogsDetails  *CacheCluster_CloudWatchLogsDestinationDetails  `json:"CloudWatchLogsDetails,omitempty"`
	KinesisFirehoseDetails *CacheCluster_KinesisFirehoseDestinationDetails `json:"KinesisFirehoseDetails,omitempty"`
}

// CacheCluster_KinesisFirehoseDestinationDetails represents AWS::ElastiCache::CacheCluster.KinesisFirehoseDestinationDetails.
type CacheCluster_KinesisFirehoseDestinationDetails struct {
	DeliveryStream any `json:"DeliveryStream,omitempty"`
}

// CacheCluster_LogDeliveryConfigurationRequest represents AWS::ElastiCache::CacheCluster.LogDeliveryConfigurationRequest.
type CacheCluster_LogDeliveryConfigurationRequest struct {
	DestinationDetails CacheCluster_DestinationDetails `json:"DestinationDetails,omitempty"`
	DestinationType    any                             `json:"DestinationType,omitempty"`
	LogFormat          any                             `json:"LogFormat,omitempty"`
	LogType            any                             `json:"LogType,omitempty"`
}
