// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package elasticache

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ParameterGroup represents AWS::ElastiCache::ParameterGroup.

type ParameterGroup struct {
	// Attributes for Fn::GetAtt
	CacheParameterGroupName wetwire.AttrRef `json:"-"`

	// Properties
	CacheParameterGroupFamily any            `json:"CacheParameterGroupFamily,omitempty"`
	Description               any            `json:"Description,omitempty"`
	Properties                map[string]any `json:"Properties,omitempty"`
	Tags                      []any          `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ParameterGroup) ResourceType() string {
	return "AWS::ElastiCache::ParameterGroup"
}
