// Package public_vpc contains CloudFormation resources.
// Parameters and Conditions
//
// Generated by wetwire-aws import.
package public_vpc

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
)

// DesiredCapacity - Number of EC2 instances to launch in your ECS cluster.
var DesiredCapacity = Parameter{
	Type: "Number",
	Description: "Number of EC2 instances to launch in your ECS cluster.",
	Default: "3",
}

// ECSAMI - AMI ID
var ECSAMI = Parameter{
	Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>",
	Description: "AMI ID",
	Default: "/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id",
}

// InstanceType - EC2 instance type
var InstanceType = Parameter{
	Type: "String",
	Description: "EC2 instance type",
	Default: "c4.xlarge",
	AllowedValues: []any{"t3.micro", "t3.small", "t3.medium", "t3.large", "t2.micro", "t2.small", "t2.medium", "t2.large", "m3.medium", "m3.large", "m3.xlarge", "m3.2xlarge", "m4.large", "m4.xlarge", "m4.2xlarge", "m4.4xlarge", "m4.10xlarge", "c4.large", "c4.xlarge", "c4.2xlarge", "c4.4xlarge", "c4.8xlarge", "c3.large", "c3.xlarge", "c3.2xlarge", "c3.4xlarge", "c3.8xlarge", "r3.large", "r3.xlarge", "r3.2xlarge", "r3.4xlarge", "r3.8xlarge", "i2.xlarge", "i2.2xlarge", "i2.4xlarge", "i2.8xlarge"},
	ConstraintDescription: "Please choose a valid instance type.",
}

// MaxSize - Maximum number of EC2 instances that can be launched in your ECS cluster.
var MaxSize = Parameter{
	Type: "Number",
	Description: "Maximum number of EC2 instances that can be launched in your ECS cluster.",
	Default: "6",
}
