// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package guardduty

// PublishingDestination_CFNDestinationProperties represents AWS::GuardDuty::PublishingDestination.CFNDestinationProperties.
type PublishingDestination_CFNDestinationProperties struct {
	DestinationArn any `json:"DestinationArn,omitempty"`
	KmsKeyArn      any `json:"KmsKeyArn,omitempty"`
}

// PublishingDestination_TagItem represents AWS::GuardDuty::PublishingDestination.TagItem.
type PublishingDestination_TagItem struct {
	Key   any `json:"Key,omitempty"`
	Value any `json:"Value,omitempty"`
}
