// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cognito

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// Terms represents AWS::Cognito::Terms.

type Terms struct {
	// Attributes for Fn::GetAtt
	TermsId wetwire.AttrRef `json:"-"`

	// Properties
	ClientId    any            `json:"ClientId,omitempty"`
	Enforcement any            `json:"Enforcement,omitempty"`
	Links       map[string]any `json:"Links,omitempty"`
	TermsName   any            `json:"TermsName,omitempty"`
	TermsSource any            `json:"TermsSource,omitempty"`
	UserPoolId  any            `json:"UserPoolId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r Terms) ResourceType() string {
	return "AWS::Cognito::Terms"
}
