// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package cognito

// UserPoolUser_AttributeType represents AWS::Cognito::UserPoolUser.AttributeType.
type UserPoolUser_AttributeType struct {
	Name  any `json:"Name,omitempty"`
	Value any `json:"Value,omitempty"`
}
