// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package iottwinmaker

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// ComponentType represents AWS::IoTTwinMaker::ComponentType.

type ComponentType struct {
	// Attributes for Fn::GetAtt
	Arn                  wetwire.AttrRef `json:"-"`
	CreationDateTime     wetwire.AttrRef `json:"-"`
	IsAbstract           wetwire.AttrRef `json:"-"`
	IsSchemaInitialized  wetwire.AttrRef `json:"-"`
	Status               wetwire.AttrRef `json:"-"`
	Status_Error         wetwire.AttrRef `json:"-"`
	Status_Error_Code    wetwire.AttrRef `json:"-"`
	Status_Error_Message wetwire.AttrRef `json:"-"`
	Status_State         wetwire.AttrRef `json:"-"`
	UpdateDateTime       wetwire.AttrRef `json:"-"`

	// Properties
	ComponentTypeId         any                                             `json:"ComponentTypeId,omitempty"`
	CompositeComponentTypes map[string]ComponentType_CompositeComponentType `json:"CompositeComponentTypes,omitempty"`
	Description             any                                             `json:"Description,omitempty"`
	ExtendsFrom             []any                                           `json:"ExtendsFrom,omitempty"`
	Functions               map[string]ComponentType_Function               `json:"Functions,omitempty"`
	IsSingleton             any                                             `json:"IsSingleton,omitempty"`
	PropertyDefinitions     map[string]ComponentType_PropertyDefinition     `json:"PropertyDefinitions,omitempty"`
	PropertyGroups          map[string]ComponentType_PropertyGroup          `json:"PropertyGroups,omitempty"`
	Tags                    map[string]any                                  `json:"Tags,omitempty"`
	WorkspaceId             any                                             `json:"WorkspaceId,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r ComponentType) ResourceType() string {
	return "AWS::IoTTwinMaker::ComponentType"
}
