// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package s3outposts

// Bucket_AbortIncompleteMultipartUpload represents AWS::S3Outposts::Bucket.AbortIncompleteMultipartUpload.
type Bucket_AbortIncompleteMultipartUpload struct {
	DaysAfterInitiation any `json:"DaysAfterInitiation,omitempty"`
}

// Bucket_Filter represents AWS::S3Outposts::Bucket.Filter.
type Bucket_Filter struct {
	AndOperator any `json:"AndOperator,omitempty"`
	Prefix      any `json:"Prefix,omitempty"`
	Tag         any `json:"Tag,omitempty"`
}

// Bucket_FilterAndOperator represents AWS::S3Outposts::Bucket.FilterAndOperator.
type Bucket_FilterAndOperator struct {
	Prefix any   `json:"Prefix,omitempty"`
	Tags   []any `json:"Tags,omitempty"`
}

// Bucket_FilterTag represents AWS::S3Outposts::Bucket.FilterTag.
type Bucket_FilterTag struct {
	Key   any `json:"Key,omitempty"`
	Value any `json:"Value,omitempty"`
}

// Bucket_LifecycleConfiguration represents AWS::S3Outposts::Bucket.LifecycleConfiguration.
type Bucket_LifecycleConfiguration struct {
	Rules []any `json:"Rules,omitempty"`
}

// Bucket_Rule represents AWS::S3Outposts::Bucket.Rule.
type Bucket_Rule struct {
	AbortIncompleteMultipartUpload any `json:"AbortIncompleteMultipartUpload,omitempty"`
	ExpirationDate                 any `json:"ExpirationDate,omitempty"`
	ExpirationInDays               any `json:"ExpirationInDays,omitempty"`
	Filter                         any `json:"Filter,omitempty"`
	Id                             any `json:"Id,omitempty"`
	Status                         any `json:"Status,omitempty"`
}
