// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package smsvoice

// Pool_MandatoryKeyword represents AWS::SMSVOICE::Pool.MandatoryKeyword.
type Pool_MandatoryKeyword struct {
	Message any `json:"Message,omitempty"`
}

// Pool_MandatoryKeywords represents AWS::SMSVOICE::Pool.MandatoryKeywords.
type Pool_MandatoryKeywords struct {
	HELP PhoneNumber_MandatoryKeyword `json:"HELP,omitempty"`
	STOP PhoneNumber_MandatoryKeyword `json:"STOP,omitempty"`
}

// Pool_OptionalKeyword represents AWS::SMSVOICE::Pool.OptionalKeyword.
type Pool_OptionalKeyword struct {
	Action  any `json:"Action,omitempty"`
	Keyword any `json:"Keyword,omitempty"`
	Message any `json:"Message,omitempty"`
}

// Pool_TwoWay represents AWS::SMSVOICE::Pool.TwoWay.
type Pool_TwoWay struct {
	ChannelArn  any `json:"ChannelArn,omitempty"`
	ChannelRole any `json:"ChannelRole,omitempty"`
	Enabled     any `json:"Enabled,omitempty"`
}
