// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T13:18:25-07:00

package lambda

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// CapacityProvider represents AWS::Lambda::CapacityProvider.

type CapacityProvider struct {
	// Attributes for Fn::GetAtt
	Arn   wetwire.AttrRef `json:"-"`
	State wetwire.AttrRef `json:"-"`

	// Properties
	CapacityProviderName          any                                                `json:"CapacityProviderName,omitempty"`
	CapacityProviderScalingConfig *CapacityProvider_CapacityProviderScalingConfig    `json:"CapacityProviderScalingConfig,omitempty"`
	InstanceRequirements          *CapacityProvider_InstanceRequirements             `json:"InstanceRequirements,omitempty"`
	KmsKeyArn                     any                                                `json:"KmsKeyArn,omitempty"`
	PermissionsConfig             CapacityProvider_CapacityProviderPermissionsConfig `json:"PermissionsConfig,omitempty"`
	Tags                          []any                                              `json:"Tags,omitempty"`
	VpcConfig                     CapacityProvider_CapacityProviderVpcConfig         `json:"VpcConfig,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r CapacityProvider) ResourceType() string {
	return "AWS::Lambda::CapacityProvider"
}
