// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-05T17:13:18-07:00

package workspaces

// ConnectionAlias_ConnectionAliasAssociation represents AWS::WorkSpaces::ConnectionAlias.ConnectionAliasAssociation.
type ConnectionAlias_ConnectionAliasAssociation struct {
	AssociatedAccountId  any `json:"AssociatedAccountId,omitempty"`
	AssociationStatus    any `json:"AssociationStatus,omitempty"`
	ConnectionIdentifier any `json:"ConnectionIdentifier,omitempty"`
	ResourceId           any `json:"ResourceId,omitempty"`
}
