// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-06T21:34:22-07:00

package networkmanager

import (
	wetwire "github.com/lex00/wetwire-aws-go"
)

// GlobalNetwork represents AWS::NetworkManager::GlobalNetwork.

type GlobalNetwork struct {
	// Attributes for Fn::GetAtt
	Arn wetwire.AttrRef `json:"-"`
	Id  wetwire.AttrRef `json:"-"`

	// Properties
	CreatedAt   any   `json:"CreatedAt,omitempty"`
	Description any   `json:"Description,omitempty"`
	State       any   `json:"State,omitempty"`
	Tags        []any `json:"Tags,omitempty"`
}

// ResourceType returns the CloudFormation resource type.
func (r GlobalNetwork) ResourceType() string {
	return "AWS::NetworkManager::GlobalNetwork"
}
