// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: cloudformation-schema-go/enums
// Generated: 2026-01-02T11:46:59-07:00

package imagebuilder

// BuildType represents valid values for BuildType.
type BuildType string

const (
	BuildTypeUserInitiated BuildType = "USER_INITIATED"
	BuildTypeScheduled     BuildType = "SCHEDULED"
	BuildTypeImport        BuildType = "IMPORT"
	BuildTypeImportIso     BuildType = "IMPORT_ISO"
)

// ComponentFormat represents valid values for ComponentFormat.
type ComponentFormat string

const (
	ComponentFormatShell ComponentFormat = "SHELL"
)

// ComponentStatus represents valid values for ComponentStatus.
type ComponentStatus string

const (
	ComponentStatusDeprecated ComponentStatus = "DEPRECATED"
	ComponentStatusDisabled   ComponentStatus = "DISABLED"
	ComponentStatusActive     ComponentStatus = "ACTIVE"
)

// ComponentType represents valid values for ComponentType.
type ComponentType string

const (
	ComponentTypeBuild ComponentType = "BUILD"
	ComponentTypeTest  ComponentType = "TEST"
)

// ContainerRepositoryService represents valid values for ContainerRepositoryService.
type ContainerRepositoryService string

const (
	ContainerRepositoryServiceEcr ContainerRepositoryService = "ECR"
)

// ContainerType represents valid values for ContainerType.
type ContainerType string

const (
	ContainerTypeDocker ContainerType = "DOCKER"
)

// DiskImageFormat represents valid values for DiskImageFormat.
type DiskImageFormat string

const (
	DiskImageFormatVmdk DiskImageFormat = "VMDK"
	DiskImageFormatRaw  DiskImageFormat = "RAW"
	DiskImageFormatVhd  DiskImageFormat = "VHD"
)

// EbsVolumeType represents valid values for EbsVolumeType.
type EbsVolumeType string

const (
	EbsVolumeTypeStandard EbsVolumeType = "standard"
	EbsVolumeTypeIo1      EbsVolumeType = "io1"
	EbsVolumeTypeIo2      EbsVolumeType = "io2"
	EbsVolumeTypeGp2      EbsVolumeType = "gp2"
	EbsVolumeTypeGp3      EbsVolumeType = "gp3"
	EbsVolumeTypeSc1      EbsVolumeType = "sc1"
	EbsVolumeTypeSt1      EbsVolumeType = "st1"
)

// ImageScanStatus represents valid values for ImageScanStatus.
type ImageScanStatus string

const (
	ImageScanStatusPending    ImageScanStatus = "PENDING"
	ImageScanStatusScanning   ImageScanStatus = "SCANNING"
	ImageScanStatusCollecting ImageScanStatus = "COLLECTING"
	ImageScanStatusCompleted  ImageScanStatus = "COMPLETED"
	ImageScanStatusAbandoned  ImageScanStatus = "ABANDONED"
	ImageScanStatusFailed     ImageScanStatus = "FAILED"
	ImageScanStatusTimedOut   ImageScanStatus = "TIMED_OUT"
)

// ImageSource represents valid values for ImageSource.
type ImageSource string

const (
	ImageSourceAmazonManaged  ImageSource = "AMAZON_MANAGED"
	ImageSourceAwsMarketplace ImageSource = "AWS_MARKETPLACE"
	ImageSourceImported       ImageSource = "IMPORTED"
	ImageSourceCustom         ImageSource = "CUSTOM"
)

// ImageStatus represents valid values for ImageStatus.
type ImageStatus string

const (
	ImageStatusPending      ImageStatus = "PENDING"
	ImageStatusCreating     ImageStatus = "CREATING"
	ImageStatusBuilding     ImageStatus = "BUILDING"
	ImageStatusTesting      ImageStatus = "TESTING"
	ImageStatusDistributing ImageStatus = "DISTRIBUTING"
	ImageStatusIntegrating  ImageStatus = "INTEGRATING"
	ImageStatusAvailable    ImageStatus = "AVAILABLE"
	ImageStatusCancelled    ImageStatus = "CANCELLED"
	ImageStatusFailed       ImageStatus = "FAILED"
	ImageStatusDeprecated   ImageStatus = "DEPRECATED"
	ImageStatusDeleted      ImageStatus = "DELETED"
	ImageStatusDisabled     ImageStatus = "DISABLED"
)

// ImageType represents valid values for ImageType.
type ImageType string

const (
	ImageTypeAmi    ImageType = "AMI"
	ImageTypeDocker ImageType = "DOCKER"
)

// LifecycleExecutionResourceActionName represents valid values for LifecycleExecutionResourceActionName.
type LifecycleExecutionResourceActionName string

const (
	LifecycleExecutionResourceActionNameAvailable LifecycleExecutionResourceActionName = "AVAILABLE"
	LifecycleExecutionResourceActionNameDelete    LifecycleExecutionResourceActionName = "DELETE"
	LifecycleExecutionResourceActionNameDeprecate LifecycleExecutionResourceActionName = "DEPRECATE"
	LifecycleExecutionResourceActionNameDisable   LifecycleExecutionResourceActionName = "DISABLE"
)

// LifecycleExecutionResourceStatus represents valid values for LifecycleExecutionResourceStatus.
type LifecycleExecutionResourceStatus string

const (
	LifecycleExecutionResourceStatusFailed     LifecycleExecutionResourceStatus = "FAILED"
	LifecycleExecutionResourceStatusInProgress LifecycleExecutionResourceStatus = "IN_PROGRESS"
	LifecycleExecutionResourceStatusSkipped    LifecycleExecutionResourceStatus = "SKIPPED"
	LifecycleExecutionResourceStatusSuccess    LifecycleExecutionResourceStatus = "SUCCESS"
)

// LifecycleExecutionStatus represents valid values for LifecycleExecutionStatus.
type LifecycleExecutionStatus string

const (
	LifecycleExecutionStatusInProgress LifecycleExecutionStatus = "IN_PROGRESS"
	LifecycleExecutionStatusCancelled  LifecycleExecutionStatus = "CANCELLED"
	LifecycleExecutionStatusCancelling LifecycleExecutionStatus = "CANCELLING"
	LifecycleExecutionStatusFailed     LifecycleExecutionStatus = "FAILED"
	LifecycleExecutionStatusSuccess    LifecycleExecutionStatus = "SUCCESS"
	LifecycleExecutionStatusPending    LifecycleExecutionStatus = "PENDING"
)

// LifecyclePolicyDetailActionType represents valid values for LifecyclePolicyDetailActionType.
type LifecyclePolicyDetailActionType string

const (
	LifecyclePolicyDetailActionTypeDelete    LifecyclePolicyDetailActionType = "DELETE"
	LifecyclePolicyDetailActionTypeDeprecate LifecyclePolicyDetailActionType = "DEPRECATE"
	LifecyclePolicyDetailActionTypeDisable   LifecyclePolicyDetailActionType = "DISABLE"
)

// LifecyclePolicyDetailFilterType represents valid values for LifecyclePolicyDetailFilterType.
type LifecyclePolicyDetailFilterType string

const (
	LifecyclePolicyDetailFilterTypeAge   LifecyclePolicyDetailFilterType = "AGE"
	LifecyclePolicyDetailFilterTypeCount LifecyclePolicyDetailFilterType = "COUNT"
)

// LifecyclePolicyResourceType represents valid values for LifecyclePolicyResourceType.
type LifecyclePolicyResourceType string

const (
	LifecyclePolicyResourceTypeAmiImage       LifecyclePolicyResourceType = "AMI_IMAGE"
	LifecyclePolicyResourceTypeContainerImage LifecyclePolicyResourceType = "CONTAINER_IMAGE"
)

// LifecyclePolicyStatus represents valid values for LifecyclePolicyStatus.
type LifecyclePolicyStatus string

const (
	LifecyclePolicyStatusDisabled LifecyclePolicyStatus = "DISABLED"
	LifecyclePolicyStatusEnabled  LifecyclePolicyStatus = "ENABLED"
)

// LifecyclePolicyTimeUnit represents valid values for LifecyclePolicyTimeUnit.
type LifecyclePolicyTimeUnit string

const (
	LifecyclePolicyTimeUnitDays   LifecyclePolicyTimeUnit = "DAYS"
	LifecyclePolicyTimeUnitWeeks  LifecyclePolicyTimeUnit = "WEEKS"
	LifecyclePolicyTimeUnitMonths LifecyclePolicyTimeUnit = "MONTHS"
	LifecyclePolicyTimeUnitYears  LifecyclePolicyTimeUnit = "YEARS"
)

// MarketplaceResourceType represents valid values for MarketplaceResourceType.
type MarketplaceResourceType string

const (
	MarketplaceResourceTypeComponentData     MarketplaceResourceType = "COMPONENT_DATA"
	MarketplaceResourceTypeComponentArtifact MarketplaceResourceType = "COMPONENT_ARTIFACT"
)

// OnWorkflowFailure represents valid values for OnWorkflowFailure.
type OnWorkflowFailure string

const (
	OnWorkflowFailureContinue OnWorkflowFailure = "CONTINUE"
	OnWorkflowFailureAbort    OnWorkflowFailure = "ABORT"
)

// Ownership represents valid values for Ownership.
type Ownership string

const (
	OwnershipSelf           Ownership = "Self"
	OwnershipShared         Ownership = "Shared"
	OwnershipAmazon         Ownership = "Amazon"
	OwnershipThirdparty     Ownership = "ThirdParty"
	OwnershipAwsmarketplace Ownership = "AWSMarketplace"
)

// PipelineExecutionStartCondition represents valid values for PipelineExecutionStartCondition.
type PipelineExecutionStartCondition string

const (
	PipelineExecutionStartConditionExpressionMatchOnly                          PipelineExecutionStartCondition = "EXPRESSION_MATCH_ONLY"
	PipelineExecutionStartConditionExpressionMatchAndDependencyUpdatesAvailable PipelineExecutionStartCondition = "EXPRESSION_MATCH_AND_DEPENDENCY_UPDATES_AVAILABLE"
)

// PipelineStatus represents valid values for PipelineStatus.
type PipelineStatus string

const (
	PipelineStatusDisabled PipelineStatus = "DISABLED"
	PipelineStatusEnabled  PipelineStatus = "ENABLED"
)

// Platform represents valid values for Platform.
type Platform string

const (
	PlatformWindows Platform = "Windows"
	PlatformLinux   Platform = "Linux"
	PlatformMacos   Platform = "macOS"
)

// ProductCodeType represents valid values for ProductCodeType.
type ProductCodeType string

const (
	ProductCodeTypeMarketplace ProductCodeType = "marketplace"
)

// ResourceStatus represents valid values for ResourceStatus.
type ResourceStatus string

const (
	ResourceStatusAvailable  ResourceStatus = "AVAILABLE"
	ResourceStatusDeleted    ResourceStatus = "DELETED"
	ResourceStatusDeprecated ResourceStatus = "DEPRECATED"
	ResourceStatusDisabled   ResourceStatus = "DISABLED"
)

// SsmParameterDataType represents valid values for SsmParameterDataType.
type SsmParameterDataType string

const (
	SsmParameterDataTypeText        SsmParameterDataType = "text"
	SsmParameterDataTypeAwsEc2Image SsmParameterDataType = "aws:ec2:image"
)

// TenancyType represents valid values for TenancyType.
type TenancyType string

const (
	TenancyTypeDefault   TenancyType = "default"
	TenancyTypeDedicated TenancyType = "dedicated"
	TenancyTypeHost      TenancyType = "host"
)

// WorkflowExecutionStatus represents valid values for WorkflowExecutionStatus.
type WorkflowExecutionStatus string

const (
	WorkflowExecutionStatusPending            WorkflowExecutionStatus = "PENDING"
	WorkflowExecutionStatusSkipped            WorkflowExecutionStatus = "SKIPPED"
	WorkflowExecutionStatusRunning            WorkflowExecutionStatus = "RUNNING"
	WorkflowExecutionStatusCompleted          WorkflowExecutionStatus = "COMPLETED"
	WorkflowExecutionStatusFailed             WorkflowExecutionStatus = "FAILED"
	WorkflowExecutionStatusRollbackInProgress WorkflowExecutionStatus = "ROLLBACK_IN_PROGRESS"
	WorkflowExecutionStatusRollbackCompleted  WorkflowExecutionStatus = "ROLLBACK_COMPLETED"
	WorkflowExecutionStatusCancelled          WorkflowExecutionStatus = "CANCELLED"
)

// WorkflowStatus represents valid values for WorkflowStatus.
type WorkflowStatus string

const (
	WorkflowStatusDeprecated WorkflowStatus = "DEPRECATED"
)

// WorkflowStepActionType represents valid values for WorkflowStepActionType.
type WorkflowStepActionType string

const (
	WorkflowStepActionTypeResume WorkflowStepActionType = "RESUME"
	WorkflowStepActionTypeStop   WorkflowStepActionType = "STOP"
)

// WorkflowStepExecutionRollbackStatus represents valid values for WorkflowStepExecutionRollbackStatus.
type WorkflowStepExecutionRollbackStatus string

const (
	WorkflowStepExecutionRollbackStatusRunning   WorkflowStepExecutionRollbackStatus = "RUNNING"
	WorkflowStepExecutionRollbackStatusCompleted WorkflowStepExecutionRollbackStatus = "COMPLETED"
	WorkflowStepExecutionRollbackStatusSkipped   WorkflowStepExecutionRollbackStatus = "SKIPPED"
	WorkflowStepExecutionRollbackStatusFailed    WorkflowStepExecutionRollbackStatus = "FAILED"
)

// WorkflowStepExecutionStatus represents valid values for WorkflowStepExecutionStatus.
type WorkflowStepExecutionStatus string

const (
	WorkflowStepExecutionStatusPending   WorkflowStepExecutionStatus = "PENDING"
	WorkflowStepExecutionStatusSkipped   WorkflowStepExecutionStatus = "SKIPPED"
	WorkflowStepExecutionStatusRunning   WorkflowStepExecutionStatus = "RUNNING"
	WorkflowStepExecutionStatusCompleted WorkflowStepExecutionStatus = "COMPLETED"
	WorkflowStepExecutionStatusFailed    WorkflowStepExecutionStatus = "FAILED"
	WorkflowStepExecutionStatusCancelled WorkflowStepExecutionStatus = "CANCELLED"
)

// WorkflowType represents valid values for WorkflowType.
type WorkflowType string

const (
	WorkflowTypeBuild        WorkflowType = "BUILD"
	WorkflowTypeTest         WorkflowType = "TEST"
	WorkflowTypeDistribution WorkflowType = "DISTRIBUTION"
)
