// Code generated by wetwire-aws codegen. DO NOT EDIT.
// Source: CloudFormation Resource Specification
// Generated: 2026-01-02T11:46:59-07:00

package imagebuilder

// Image_DeletionSettings represents AWS::ImageBuilder::Image.DeletionSettings.
type Image_DeletionSettings struct {
	ExecutionRole any `json:"ExecutionRole,omitempty"`
}

// Image_EcrConfiguration represents AWS::ImageBuilder::Image.EcrConfiguration.
type Image_EcrConfiguration struct {
	ContainerTags  []any `json:"ContainerTags,omitempty"`
	RepositoryName any   `json:"RepositoryName,omitempty"`
}

// Image_ImageLoggingConfiguration represents AWS::ImageBuilder::Image.ImageLoggingConfiguration.
type Image_ImageLoggingConfiguration struct {
	LogGroupName any `json:"LogGroupName,omitempty"`
}

// Image_ImagePipelineExecutionSettings represents AWS::ImageBuilder::Image.ImagePipelineExecutionSettings.
type Image_ImagePipelineExecutionSettings struct {
	DeploymentId any `json:"DeploymentId,omitempty"`
	OnUpdate     any `json:"OnUpdate,omitempty"`
}

// Image_ImageScanningConfiguration represents AWS::ImageBuilder::Image.ImageScanningConfiguration.
type Image_ImageScanningConfiguration struct {
	EcrConfiguration     *ImagePipeline_EcrConfiguration `json:"EcrConfiguration,omitempty"`
	ImageScanningEnabled any                             `json:"ImageScanningEnabled,omitempty"`
}

// Image_ImageTestsConfiguration represents AWS::ImageBuilder::Image.ImageTestsConfiguration.
type Image_ImageTestsConfiguration struct {
	ImageTestsEnabled any `json:"ImageTestsEnabled,omitempty"`
	TimeoutMinutes    any `json:"TimeoutMinutes,omitempty"`
}

// Image_LatestVersion represents AWS::ImageBuilder::Image.LatestVersion.
type Image_LatestVersion struct {
	Arn   any `json:"Arn,omitempty"`
	Major any `json:"Major,omitempty"`
	Minor any `json:"Minor,omitempty"`
	Patch any `json:"Patch,omitempty"`
}

// Image_WorkflowConfiguration represents AWS::ImageBuilder::Image.WorkflowConfiguration.
type Image_WorkflowConfiguration struct {
	OnFailure     any                               `json:"OnFailure,omitempty"`
	ParallelGroup any                               `json:"ParallelGroup,omitempty"`
	Parameters    []ImagePipeline_WorkflowParameter `json:"Parameters,omitempty"`
	WorkflowArn   any                               `json:"WorkflowArn,omitempty"`
}

// Image_WorkflowParameter represents AWS::ImageBuilder::Image.WorkflowParameter.
type Image_WorkflowParameter struct {
	Name  any   `json:"Name,omitempty"`
	Value []any `json:"Value,omitempty"`
}
