// Package template contains CloudFormation resources.
// Main resources
//
// Generated by wetwire-aws import.
package template

import (
	. "github.com/lex00/wetwire-aws-go/intrinsics"
	"github.com/lex00/wetwire-aws-go/resources/serverless"
)

var HelloWorldFunction = serverless.Function{
	CodeUri: "hello-world/",
	Events: Json{
	"HelloWorld": Json{
	"Properties": Json{
	"Method": "get",
	"Path": "/hello",
},
	"Type": "Api",
},
},
	Handler: "app.lambdaHandler",
	Runtime: "nodejs16.x",
}
