// Package template provides CloudFormation template building from discovered resources.
//
// This file contains CloudFormation service name mappings and type conversions.
package template

import "strings"

// cfResourceType converts Go type to CloudFormation type.
// e.g., "s3.Bucket" -> "AWS::S3::Bucket", "cloudfront.Distribution" -> "AWS::CloudFront::Distribution"
func cfResourceType(goType string) string {
	// Parse the Go type: "package.Type"
	parts := strings.SplitN(goType, ".", 2)
	if len(parts) != 2 {
		return ""
	}

	pkgName := parts[0]
	typeName := parts[1]

	// Map Go package names to CloudFormation service names
	serviceName := goPackageToCFService(pkgName)
	if serviceName == "" {
		return ""
	}

	return "AWS::" + serviceName + "::" + typeName
}

// goPackageToCFService maps Go package names to CloudFormation service names.
// This handles the case transformations needed for proper CloudFormation types.
func goPackageToCFService(pkg string) string {
	// Direct mappings for packages that don't follow simple title-casing
	directMap := map[string]string{
		"accessanalyzer":            "AccessAnalyzer",
		"acmpca":                    "ACMPCA",
		"aiops":                     "AIOps",
		"amazonmq":                  "AmazonMQ",
		"amplify":                   "Amplify",
		"amplifyuibuilder":          "AmplifyUIBuilder",
		"apigateway":                "ApiGateway",
		"apigatewayv2":              "ApiGatewayV2",
		"appconfig":                 "AppConfig",
		"appflow":                   "AppFlow",
		"appintegrations":           "AppIntegrations",
		"applicationautoscaling":    "ApplicationAutoScaling",
		"applicationinsights":       "ApplicationInsights",
		"applicationsignals":        "ApplicationSignals",
		"appmesh":                   "AppMesh",
		"apprunner":                 "AppRunner",
		"appstream":                 "AppStream",
		"appsync":                   "AppSync",
		"apptest":                   "AppTest",
		"aps":                       "APS",
		"arcregionswitch":           "ARCRegionSwitch",
		"arczonalshift":             "ARCZonalShift",
		"ask":                       "ASK",
		"athena":                    "Athena",
		"auditmanager":              "AuditManager",
		"autoscaling":               "AutoScaling",
		"autoscalingplans":          "AutoScalingPlans",
		"b2bi":                      "B2BI",
		"backup":                    "Backup",
		"backupgateway":             "BackupGateway",
		"batch":                     "Batch",
		"bcmdataexports":            "BCMDataExports",
		"bedrock":                   "Bedrock",
		"bedrockagentcore":          "BedrockAgentCore",
		"billing":                   "Billing",
		"billingconductor":          "BillingConductor",
		"budgets":                   "Budgets",
		"cases":                     "Cases",
		"cassandra":                 "Cassandra",
		"ce":                        "CE",
		"certificatemanager":        "CertificateManager",
		"chatbot":                   "Chatbot",
		"cleanrooms":                "CleanRooms",
		"cleanroomsml":              "CleanRoomsML",
		"cloud9":                    "Cloud9",
		"cloudformation":            "CloudFormation",
		"cloudfront":                "CloudFront",
		"cloudtrail":                "CloudTrail",
		"cloudwatch":                "CloudWatch",
		"codeartifact":              "CodeArtifact",
		"codebuild":                 "CodeBuild",
		"codecommit":                "CodeCommit",
		"codeconnections":           "CodeConnections",
		"codedeploy":                "CodeDeploy",
		"codeguruprofiler":          "CodeGuruProfiler",
		"codegurureviewer":          "CodeGuruReviewer",
		"codepipeline":              "CodePipeline",
		"codestar":                  "CodeStar",
		"codestarconnections":       "CodeStarConnections",
		"codestarnotifications":     "CodeStarNotifications",
		"cognito":                   "Cognito",
		"comprehend":                "Comprehend",
		"config":                    "Config",
		"connect":                   "Connect",
		"connectcampaigns":          "ConnectCampaigns",
		"connectcampaignsv2":        "ConnectCampaignsV2",
		"controltower":              "ControlTower",
		"cur":                       "CUR",
		"customerprofiles":          "CustomerProfiles",
		"databrew":                  "DataBrew",
		"datapipeline":              "DataPipeline",
		"datasync":                  "DataSync",
		"datazone":                  "DataZone",
		"dax":                       "DAX",
		"deadline":                  "Deadline",
		"detective":                 "Detective",
		"devopsagent":               "DevOpsAgent",
		"devopsguru":                "DevOpsGuru",
		"directoryservice":          "DirectoryService",
		"dlm":                       "DLM",
		"dms":                       "DMS",
		"docdb":                     "DocDB",
		"docdbelastic":              "DocDBElastic",
		"dsql":                      "DSQL",
		"dynamodb":                  "DynamoDB",
		"ec2":                       "EC2",
		"ecr":                       "ECR",
		"ecs":                       "ECS",
		"efs":                       "EFS",
		"eks":                       "EKS",
		"elasticache":               "ElastiCache",
		"elasticbeanstalk":          "ElasticBeanstalk",
		"elasticloadbalancing":      "ElasticLoadBalancing",
		"elasticloadbalancingv2":    "ElasticLoadBalancingV2",
		"elasticsearch":             "Elasticsearch",
		"emr":                       "EMR",
		"emrcontainers":             "EMRContainers",
		"emrserverless":             "EMRServerless",
		"entityresolution":          "EntityResolution",
		"events":                    "Events",
		"eventschemas":              "EventSchemas",
		"evidently":                 "Evidently",
		"evs":                       "EVS",
		"finspace":                  "FinSpace",
		"fis":                       "FIS",
		"fms":                       "FMS",
		"forecast":                  "Forecast",
		"frauddetector":             "FraudDetector",
		"fsx":                       "FSx",
		"gamelift":                  "GameLift",
		"globalaccelerator":         "GlobalAccelerator",
		"glue":                      "Glue",
		"grafana":                   "Grafana",
		"greengrass":                "Greengrass",
		"greengrassv2":              "GreengrassV2",
		"groundstation":             "GroundStation",
		"guardduty":                 "GuardDuty",
		"healthimaging":             "HealthImaging",
		"healthlake":                "HealthLake",
		"iam":                       "IAM",
		"identitystore":             "IdentityStore",
		"imagebuilder":              "ImageBuilder",
		"inspector":                 "Inspector",
		"inspectorv2":               "InspectorV2",
		"internetmonitor":           "InternetMonitor",
		"invoicing":                 "Invoicing",
		"iot":                       "IoT",
		"iotanalytics":              "IoTAnalytics",
		"iotcoredeviceadvisor":      "IoTCoreDeviceAdvisor",
		"iotevents":                 "IoTEvents",
		"iotfleetwise":              "IoTFleetWise",
		"iotsitewise":               "IoTSiteWise",
		"iotthingsgraph":            "IoTThingsGraph",
		"iottwinmaker":              "IoTTwinMaker",
		"iotwireless":               "IoTWireless",
		"ivs":                       "IVS",
		"ivschat":                   "IVSChat",
		"kafkaconnect":              "KafkaConnect",
		"kendra":                    "Kendra",
		"kendraranking":             "KendraRanking",
		"kinesis":                   "Kinesis",
		"kinesisanalytics":          "KinesisAnalytics",
		"kinesisanalyticsv2":        "KinesisAnalyticsV2",
		"kinesisfirehose":           "KinesisFirehose",
		"kinesisvideo":              "KinesisVideo",
		"kms":                       "KMS",
		"lakeformation":             "LakeFormation",
		"lambda":                    "Lambda",
		"launchwizard":              "LaunchWizard",
		"lex":                       "Lex",
		"licensemanager":            "LicenseManager",
		"lightsail":                 "Lightsail",
		"location":                  "Location",
		"logs":                      "Logs",
		"lookoutequipment":          "LookoutEquipment",
		"lookoutvision":             "LookoutVision",
		"m2":                        "M2",
		"macie":                     "Macie",
		"managedblockchain":         "ManagedBlockchain",
		"mediaconnect":              "MediaConnect",
		"mediaconvert":              "MediaConvert",
		"medialive":                 "MediaLive",
		"mediapackage":              "MediaPackage",
		"mediapackagev2":            "MediaPackageV2",
		"mediastore":                "MediaStore",
		"mediatailor":               "MediaTailor",
		"memorydb":                  "MemoryDB",
		"mpa":                       "MPA",
		"msk":                       "MSK",
		"mwaa":                      "MWAA",
		"neptune":                   "Neptune",
		"neptunegraph":              "NeptuneGraph",
		"networkfirewall":           "NetworkFirewall",
		"networkmanager":            "NetworkManager",
		"notifications":             "Notifications",
		"notificationscontacts":     "NotificationsContacts",
		"oam":                       "Oam",
		"observabilityadmin":        "ObservabilityAdmin",
		"odb":                       "ODB",
		"omics":                     "Omics",
		"opensearchserverless":      "OpenSearchServerless",
		"opensearchservice":         "OpenSearchService",
		"opsworks":                  "OpsWorks",
		"organizations":             "Organizations",
		"osis":                      "OSIS",
		"panorama":                  "Panorama",
		"paymentcryptography":       "PaymentCryptography",
		"pcaconnectorad":            "PCAConnectorAD",
		"pcaconnectorscep":          "PCAConnectorSCEP",
		"pcs":                       "PCS",
		"personalize":               "Personalize",
		"pinpoint":                  "Pinpoint",
		"pinpointemail":             "PinpointEmail",
		"pipes":                     "Pipes",
		"proton":                    "Proton",
		"qbusiness":                 "QBusiness",
		"qldb":                      "QLDB",
		"quicksight":                "QuickSight",
		"ram":                       "RAM",
		"rbin":                      "Rbin",
		"rds":                       "RDS",
		"redshift":                  "Redshift",
		"redshiftserverless":        "RedshiftServerless",
		"refactorspaces":            "RefactorSpaces",
		"rekognition":               "Rekognition",
		"resiliencehub":             "ResilienceHub",
		"resourceexplorer2":         "ResourceExplorer2",
		"resourcegroups":            "ResourceGroups",
		"robomaker":                 "RoboMaker",
		"rolesanywhere":             "RolesAnywhere",
		"route53":                   "Route53",
		"route53profiles":           "Route53Profiles",
		"route53recoverycontrol":    "Route53RecoveryControl",
		"route53recoveryreadiness":  "Route53RecoveryReadiness",
		"route53resolver":           "Route53Resolver",
		"rtbfabric":                 "RTBFabric",
		"rum":                       "RUM",
		"s3":                        "S3",
		"s3express":                 "S3Express",
		"s3objectlambda":            "S3ObjectLambda",
		"s3outposts":                "S3Outposts",
		"s3tables":                  "S3Tables",
		"s3vectors":                 "S3Vectors",
		"sagemaker":                 "SageMaker",
		"scheduler":                 "Scheduler",
		"sdb":                       "SDB",
		"secretsmanager":            "SecretsManager",
		"securityhub":               "SecurityHub",
		"securitylake":              "SecurityLake",
		"serverless":                "Serverless",
		"servicecatalog":            "ServiceCatalog",
		"servicecatalogappregistry": "ServiceCatalogAppRegistry",
		"servicediscovery":          "ServiceDiscovery",
		"ses":                       "SES",
		"shield":                    "Shield",
		"signer":                    "Signer",
		"simspaceweaver":            "SimSpaceWeaver",
		"smsvoice":                  "SMSVoice",
		"sns":                       "SNS",
		"sqs":                       "SQS",
		"ssm":                       "SSM",
		"ssmcontacts":               "SSMContacts",
		"ssmguiconnect":             "SSMGuiConnect",
		"ssmincidents":              "SSMIncidents",
		"ssmquicksetup":             "SSMQuickSetup",
		"sso":                       "SSO",
		"stepfunctions":             "StepFunctions",
		"supportapp":                "SupportApp",
		"synthetics":                "Synthetics",
		"systemsmanagersap":         "SystemsManagerSAP",
		"timestream":                "Timestream",
		"transfer":                  "Transfer",
		"verifiedpermissions":       "VerifiedPermissions",
		"voiceid":                   "VoiceID",
		"vpclattice":                "VpcLattice",
		"waf":                       "WAF",
		"wafregional":               "WAFRegional",
		"wafv2":                     "WAFv2",
		"wisdom":                    "Wisdom",
		"workspaces":                "WorkSpaces",
		"workspacesinstances":       "WorkSpacesInstances",
		"workspacesthinclient":      "WorkSpacesThinClient",
		"workspacesweb":             "WorkSpacesWeb",
		"xray":                      "XRay",
	}

	if service, ok := directMap[pkg]; ok {
		return service
	}
	return ""
}

// isSAMResourceType returns true if the Go type is a SAM resource.
func isSAMResourceType(goType string) bool {
	return len(goType) > 11 && goType[:11] == "serverless."
}
